# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2023 Telechips Inc.

dtb-tcc803x += tcc8030-lpd4321.dtb
dtb-tcc803x += tcc8031pe-lpd4321.dtb

dtb-telechips += $(addprefix tcc803x/, $(dtb-tcc803x))
