# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2023 Telechips Inc.

dtb-tcc807x += tcc8070-lpd4x322.dtb

dtb-tcc807x += tcc8070-subcore-lpd4x322.dtb

dtb-telechips += $(addprefix tcc807x/, $(dtb-tcc807x))
