# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2023 Telechips Inc.

include $(src)/telechips/tcc750x/Makefile
include $(src)/telechips/tcc803x/Makefile
include $(src)/telechips/tcc805x/Makefile
include $(src)/telechips/tcc807x/Makefile

dtb-$(CONFIG_ARCH_TELECHIPS) += $(addprefix telechips/, $(dtb-telechips))
