# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) Telechips Inc.

obj-y += init.o
obj-y += lowlevel_init.o
obj-y += soc.o

obj-$(CONFIG_OF_SYSTEM_SETUP) += fdt.o

obj-$(CONFIG_TCC805X)	+= tcc805x/
obj-$(CONFIG_TCC803X)	+= tcc803x/
