# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2023 Telechips Inc.

obj-$(CONFIG_ARM64) += lowlevel_init64.o
obj-y += fdt.o
obj-y += init.o
obj-y += reboot.o
obj-y += soc.o
obj-$(CONFIG_TCC_SECUREBOOT) += secureboot.o

obj-$(CONFIG_TCC750X) += tcc750x/
obj-$(CONFIG_TCC803X) += tcc803x/
obj-$(CONFIG_TCC805X) += tcc805x/
obj-$(CONFIG_TCC807X) += tcc807x/
