# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2023 Telechips Inc.

dtb-tcc805x += tcc8050-lpd4x322-sv0.1.dtb
dtb-tcc805x += tcc8050-lpd4x322-sv1.0.dtb
dtb-tcc805x += tcc8053-lpd4x322-sv0.1.dtb
dtb-tcc805x += tcc8053-lpd4x322-sv1.0.dtb
dtb-tcc805x += tcc8059-lpd4x321.dtb

dtb-tcc805x += tcc8050-subcore-lpd4x322-sv0.1.dtb
dtb-tcc805x += tcc8050-subcore-lpd4x322-sv1.0.dtb
dtb-tcc805x += tcc8053-subcore-lpd4x322-sv0.1.dtb
dtb-tcc805x += tcc8053-subcore-lpd4x322-sv1.0.dtb
dtb-tcc805x += tcc8059-subcore-lpd4x321.dtb

dtb-telechips += $(addprefix tcc805x/, $(dtb-tcc805x))
