// SPDX-License-Identifier: GPL-2.0-or-later OR MIT
/*
* Copyright (C) Telechips Inc.
*/
#include <linux/delay.h>

#include "dptx_v14.h"
#include "dptx_reg.h"
#include "dptx_dbg.h"

#define CHECK_REG_OFFSET(x) (((x) < (uint32_t)DP_MAX_OFFSET) ? (bool)true : (bool)false)

static const uint32_t dptx_sec_main_reg_offset_table[4] = {
	SEC_PHY_REG0303,
	SEC_PHY_REG0403,
	SEC_PHY_REG0503,
	SEC_PHY_REG0603
};

static const uint32_t dptx_sec_post_reg_offset_table[4] = {
	SEC_PHY_REG0304,
	SEC_PHY_REG0404,
	SEC_PHY_REG0504,
	SEC_PHY_REG0604
};

struct SEC_PHY_Reg_Data {
	uint8_t uclink_rate;
	uint32_t uireg_add;
	uint32_t uireg_val;
};

static struct SEC_PHY_Reg_Data stSEC_PHY_Link_Reg_Data[] = {
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0008, SEC_PHY_REG0008_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0008, SEC_PHY_REG0008_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0008, SEC_PHY_REG0008_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0008, SEC_PHY_REG0008_HBR3_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0009, SEC_PHY_REG0009_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG000A, SEC_PHY_REG000A_INIT},

	/* Samsung Guide 2023-12-20 */
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG000B, SEC_PHY_REG000B_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG000C, SEC_PHY_REG000C_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG000D, SEC_PHY_REG000D_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG000E, SEC_PHY_REG000E_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG000F, SEC_PHY_REG000F_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0010, SEC_PHY_REG0010_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0011, SEC_PHY_REG0011_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0012, SEC_PHY_REG0012_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0013, SEC_PHY_REG0013_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0014, SEC_PHY_REG0014_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0015, SEC_PHY_REG0015_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0016, SEC_PHY_REG0016_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0017, SEC_PHY_REG0017_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0018, SEC_PHY_REG0018_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0019, SEC_PHY_REG0019_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG001A, SEC_PHY_REG001A_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG001B, SEC_PHY_REG001B_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG001C, SEC_PHY_REG001C_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG001D, SEC_PHY_REG001D_INIT},

	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG001E, SEC_PHY_REG001E_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG001E, SEC_PHY_REG001E_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG001E, SEC_PHY_REG001E_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG001E, SEC_PHY_REG001E_HBR3_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG001F, SEC_PHY_REG001F_INIT},

	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0020, SEC_PHY_REG0020_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0020, SEC_PHY_REG0020_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0020, SEC_PHY_REG0020_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0020, SEC_PHY_REG0020_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0021, SEC_PHY_REG0021_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0021, SEC_PHY_REG0021_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0021, SEC_PHY_REG0021_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0021, SEC_PHY_REG0021_HBR3_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0022, SEC_PHY_REG0022_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0023, SEC_PHY_REG0023_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0024, SEC_PHY_REG0024_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0025, SEC_PHY_REG0025_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0025, SEC_PHY_REG0025_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0025, SEC_PHY_REG0025_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0025, SEC_PHY_REG0025_HBR3_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0026, SEC_PHY_REG0026_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0027, SEC_PHY_REG0027_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0027, SEC_PHY_REG0027_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0027, SEC_PHY_REG0027_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0027, SEC_PHY_REG0027_HBR3_INIT},

	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0028, SEC_PHY_REG0028_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0028, SEC_PHY_REG0028_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0028, SEC_PHY_REG0028_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0028, SEC_PHY_REG0028_HBR3_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0029, SEC_PHY_REG0029_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG002A, SEC_PHY_REG002A_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG002A, SEC_PHY_REG002A_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG002A, SEC_PHY_REG002A_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG002A, SEC_PHY_REG002A_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG002B, SEC_PHY_REG002B_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG002B, SEC_PHY_REG002B_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG002B, SEC_PHY_REG002B_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG002B, SEC_PHY_REG002B_HBR3_INIT},

	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG002C, SEC_PHY_REG002C_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG002C, SEC_PHY_REG002C_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG002C, SEC_PHY_REG002C_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG002C, SEC_PHY_REG002C_HBR3_INIT},

	/* Samsung Guide 2023-12-20 */
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG002D, SEC_PHY_REG002D_RESET},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG002D, SEC_PHY_REG002D_RESET},
	{(uint8_t)LINK_RATE_HBR2,  SEC_PHY_REG002D, SEC_PHY_REG002D_RESET},
	{(uint8_t)LINK_RATE_HBR3,  SEC_PHY_REG002D, SEC_PHY_REG002D_INIT},

	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG002E, SEC_PHY_REG002E_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG002E, SEC_PHY_REG002E_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG002E, SEC_PHY_REG002E_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG002E, SEC_PHY_REG002E_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG002F, SEC_PHY_REG002F_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG002F, SEC_PHY_REG002F_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG002F, SEC_PHY_REG002F_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG002F, SEC_PHY_REG002F_HBR3_INIT},

	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0030, SEC_PHY_REG0030_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0030, SEC_PHY_REG0030_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0030, SEC_PHY_REG0030_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0030, SEC_PHY_REG0030_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0031, SEC_PHY_REG0031_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0031, SEC_PHY_REG0031_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0031, SEC_PHY_REG0031_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0031, SEC_PHY_REG0031_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0032, SEC_PHY_REG0032_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0032, SEC_PHY_REG0032_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0032, SEC_PHY_REG0032_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0032, SEC_PHY_REG0032_HBR3_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0033, SEC_PHY_REG0033_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0034, SEC_PHY_REG0034_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0035, SEC_PHY_REG0035_INIT},

	/* Samsung Guide 2023-12-20 */
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0036, SEC_PHY_REG0036_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0037, SEC_PHY_REG0037_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0038, SEC_PHY_REG0038_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0039, SEC_PHY_REG0039_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG003A, SEC_PHY_REG003A_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG003B, SEC_PHY_REG003B_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG003C, SEC_PHY_REG003C_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG003D, SEC_PHY_REG003D_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG003E, SEC_PHY_REG003E_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG003F, SEC_PHY_REG003F_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0040, SEC_PHY_REG0040_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0041, SEC_PHY_REG0041_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0042, SEC_PHY_REG0042_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0043, SEC_PHY_REG0043_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0044, SEC_PHY_REG0044_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0045, SEC_PHY_REG0045_INIT},

	/* Samsung Guide 2023-12-20 */
	{(uint8_t)LINK_RATE_RBR, SEC_PHY_REG0046, SEC_PHY_REG0046_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR, SEC_PHY_REG0046, SEC_PHY_REG0046_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0046, SEC_PHY_REG0046_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0046, SEC_PHY_REG0046_HBR3_INIT},

	{(uint8_t)LINK_RATE_RBR, SEC_PHY_REG0047, SEC_PHY_REG0047_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR, SEC_PHY_REG0047, SEC_PHY_REG0047_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0047, SEC_PHY_REG0047_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0047, SEC_PHY_REG0047_HBR3_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0048, SEC_PHY_REG0048_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0049, SEC_PHY_REG0049_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG004A, SEC_PHY_REG004A_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG004B, SEC_PHY_REG004B_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG004C, SEC_PHY_REG004C_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG004D, SEC_PHY_REG004D_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG004E, SEC_PHY_REG004E_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG004E, SEC_PHY_REG004E_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG004E, SEC_PHY_REG004E_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG004E, SEC_PHY_REG004E_HBR3_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG004F, SEC_PHY_REG004F_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0050, SEC_PHY_REG0050_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0051, SEC_PHY_REG0051_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0051, SEC_PHY_REG0051_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0051, SEC_PHY_REG0051_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0051, SEC_PHY_REG0051_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0052, SEC_PHY_REG0052_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0052, SEC_PHY_REG0052_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0052, SEC_PHY_REG0052_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0052, SEC_PHY_REG0052_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0053, SEC_PHY_REG0053_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0053, SEC_PHY_REG0053_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0053, SEC_PHY_REG0053_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0053, SEC_PHY_REG0053_HBR3_INIT},

	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0054, SEC_PHY_REG0054_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0054, SEC_PHY_REG0054_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0054, SEC_PHY_REG0054_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0054, SEC_PHY_REG0054_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0055, SEC_PHY_REG0055_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0055, SEC_PHY_REG0055_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0055, SEC_PHY_REG0055_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0055, SEC_PHY_REG0055_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0056, SEC_PHY_REG0056_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0056, SEC_PHY_REG0056_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0056, SEC_PHY_REG0056_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0056, SEC_PHY_REG0056_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0057, SEC_PHY_REG0057_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0057, SEC_PHY_REG0057_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0057, SEC_PHY_REG0057_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0057, SEC_PHY_REG0057_HBR3_INIT},

	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0058, SEC_PHY_REG0058_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0058, SEC_PHY_REG0058_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0058, SEC_PHY_REG0058_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0058, SEC_PHY_REG0058_HBR3_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0059, SEC_PHY_REG0059_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG005A, SEC_PHY_REG005A_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG005A, SEC_PHY_REG005A_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG005A, SEC_PHY_REG005A_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG005A, SEC_PHY_REG005A_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG005B, SEC_PHY_REG005B_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG005B, SEC_PHY_REG005B_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG005B, SEC_PHY_REG005B_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG005B, SEC_PHY_REG005B_HBR3_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG005C, SEC_PHY_REG005C_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG005D, SEC_PHY_REG005D_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG005D, SEC_PHY_REG005D_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG005D, SEC_PHY_REG005D_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG005D, SEC_PHY_REG005D_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG005E, SEC_PHY_REG005E_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG005E, SEC_PHY_REG005E_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG005E, SEC_PHY_REG005E_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG005E, SEC_PHY_REG005E_HBR3_INIT},

	/* Samsung Guide 2023-12-20 */
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG005F, SEC_PHY_REG005F_RESET},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG005F, SEC_PHY_REG005F_RESET},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG005F, SEC_PHY_REG005F_RESET},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG005F, SEC_PHY_REG005F_HBR3_INIT},

	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0060, SEC_PHY_REG0060_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0060, SEC_PHY_REG0060_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0060, SEC_PHY_REG0060_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0060, SEC_PHY_REG0060_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0061, SEC_PHY_REG0061_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0061, SEC_PHY_REG0061_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0061, SEC_PHY_REG0061_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0061, SEC_PHY_REG0061_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0062, SEC_PHY_REG0062_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0062, SEC_PHY_REG0062_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0062, SEC_PHY_REG0062_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0062, SEC_PHY_REG0062_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0063, SEC_PHY_REG0063_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0063, SEC_PHY_REG0063_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0063, SEC_PHY_REG0063_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0063, SEC_PHY_REG0063_HBR3_INIT},

	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0064, SEC_PHY_REG0064_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0064, SEC_PHY_REG0064_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0064, SEC_PHY_REG0064_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0064, SEC_PHY_REG0064_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0065, SEC_PHY_REG0065_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0065, SEC_PHY_REG0065_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0065, SEC_PHY_REG0065_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0065, SEC_PHY_REG0065_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0066, SEC_PHY_REG0066_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0066, SEC_PHY_REG0066_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0066, SEC_PHY_REG0066_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0066, SEC_PHY_REG0066_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0067, SEC_PHY_REG0067_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0067, SEC_PHY_REG0067_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0067, SEC_PHY_REG0067_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0067, SEC_PHY_REG0067_HBR3_INIT},

	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0068, SEC_PHY_REG0068_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0068, SEC_PHY_REG0068_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0068, SEC_PHY_REG0068_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0068, SEC_PHY_REG0068_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0069, SEC_PHY_REG0069_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0069, SEC_PHY_REG0069_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0069, SEC_PHY_REG0069_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0069, SEC_PHY_REG0069_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG006A, SEC_PHY_REG006A_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG006A, SEC_PHY_REG006A_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG006A, SEC_PHY_REG006A_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG006A, SEC_PHY_REG006A_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG006B, SEC_PHY_REG006B_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG006B, SEC_PHY_REG006B_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG006B, SEC_PHY_REG006B_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG006B, SEC_PHY_REG006B_HBR3_INIT},

	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG006C, SEC_PHY_REG006C_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG006C, SEC_PHY_REG006C_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG006C, SEC_PHY_REG006C_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG006C, SEC_PHY_REG006C_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG006D, SEC_PHY_REG006D_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG006D, SEC_PHY_REG006D_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG006D, SEC_PHY_REG006D_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG006D, SEC_PHY_REG006D_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG006E, SEC_PHY_REG006E_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG006E, SEC_PHY_REG006E_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG006E, SEC_PHY_REG006E_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG006E, SEC_PHY_REG006E_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG006F, SEC_PHY_REG006F_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG006F, SEC_PHY_REG006F_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG006F, SEC_PHY_REG006F_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG006F, SEC_PHY_REG006F_HBR3_INIT},

	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0070, SEC_PHY_REG0070_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0070, SEC_PHY_REG0070_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0070, SEC_PHY_REG0070_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0070, SEC_PHY_REG0070_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0071, SEC_PHY_REG0071_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0071, SEC_PHY_REG0071_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0071, SEC_PHY_REG0071_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0071, SEC_PHY_REG0071_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0072, SEC_PHY_REG0072_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0072, SEC_PHY_REG0072_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0072, SEC_PHY_REG0072_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0072, SEC_PHY_REG0072_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0073, SEC_PHY_REG0073_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0073, SEC_PHY_REG0073_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0073, SEC_PHY_REG0073_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0073, SEC_PHY_REG0073_HBR3_INIT},

	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0074, SEC_PHY_REG0074_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0074, SEC_PHY_REG0074_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0074, SEC_PHY_REG0074_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0074, SEC_PHY_REG0074_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0075, SEC_PHY_REG0075_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0075, SEC_PHY_REG0075_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0075, SEC_PHY_REG0075_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0075, SEC_PHY_REG0075_HBR3_INIT},

	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0076, SEC_PHY_REG0076_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0076, SEC_PHY_REG0076_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0076, SEC_PHY_REG0076_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0076, SEC_PHY_REG0076_HBR3_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0077, SEC_PHY_REG0077_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0078, SEC_PHY_REG0078_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0079, SEC_PHY_REG0079_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG007A, SEC_PHY_REG007A_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG007B, SEC_PHY_REG007B_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG007C, SEC_PHY_REG007C_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG007D, SEC_PHY_REG007D_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG007E, SEC_PHY_REG007E_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG007F, SEC_PHY_REG007F_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0080, SEC_PHY_REG0080_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG008A, SEC_PHY_REG008A_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG008B, SEC_PHY_REG008B_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG008C, SEC_PHY_REG008C_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG008D, SEC_PHY_REG008D_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG008E, SEC_PHY_REG008E_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG008F, SEC_PHY_REG008F_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0090, SEC_PHY_REG0090_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0091, SEC_PHY_REG0091_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0092, SEC_PHY_REG0092_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0093, SEC_PHY_REG0093_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG009A, SEC_PHY_REG009A_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG031F, SEC_PHY_REG031F_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0320, SEC_PHY_REG0320_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG041F, SEC_PHY_REG041F_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0420, SEC_PHY_REG0420_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG051F, SEC_PHY_REG051F_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0520, SEC_PHY_REG0520_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG061F, SEC_PHY_REG061F_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0620, SEC_PHY_REG0620_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG003C, SEC_PHY_REG003C_2nd_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0081, SEC_PHY_REG0081_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0082, SEC_PHY_REG0082_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0083, SEC_PHY_REG0083_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0084, SEC_PHY_REG0084_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0084, SEC_PHY_REG0084_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0084, SEC_PHY_REG0084_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0084, SEC_PHY_REG0084_HBR3_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0085, SEC_PHY_REG0085_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0087, SEC_PHY_REG0087_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0089, SEC_PHY_REG0089_INIT},

	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0095, SEC_PHY_REG0095_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0095, SEC_PHY_REG0095_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0095, SEC_PHY_REG0095_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0095, SEC_PHY_REG0095_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0097, SEC_PHY_REG0097_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0097, SEC_PHY_REG0097_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0097, SEC_PHY_REG0097_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0097, SEC_PHY_REG0097_HBR3_INIT},
	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0099, SEC_PHY_REG0099_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0099, SEC_PHY_REG0099_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0099, SEC_PHY_REG0099_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0099, SEC_PHY_REG0099_HBR3_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG009A, SEC_PHY_REG009A_2nd_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG009B, SEC_PHY_REG009B_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0200, SEC_PHY_REG0200_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0206, SEC_PHY_REG0206_INIT},
	{(uint8_t)LINK_RATE_MAX,  SEC_PHY_REG0207, SEC_PHY_REG0207_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0303, SEC_PHY_REG0303_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0307, SEC_PHY_REG0307_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG030A, SEC_PHY_REG030A_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG030B, SEC_PHY_REG030B_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG030C, SEC_PHY_REG030C_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG030D, SEC_PHY_REG030D_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG030E, SEC_PHY_REG030E_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0310, SEC_PHY_REG0310_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0311, SEC_PHY_REG0311_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0316, SEC_PHY_REG0316_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG031B, SEC_PHY_REG031B_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0403, SEC_PHY_REG0403_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0407, SEC_PHY_REG0407_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG040A, SEC_PHY_REG040A_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG040B, SEC_PHY_REG040B_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG040C, SEC_PHY_REG040C_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG040D, SEC_PHY_REG040D_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG040E, SEC_PHY_REG040E_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0410, SEC_PHY_REG0410_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0411, SEC_PHY_REG0411_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0416, SEC_PHY_REG0416_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG041B, SEC_PHY_REG041B_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0503, SEC_PHY_REG0503_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0507, SEC_PHY_REG0507_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG050A, SEC_PHY_REG050A_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG050B, SEC_PHY_REG050B_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG050C, SEC_PHY_REG050C_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG050D, SEC_PHY_REG050D_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG050E, SEC_PHY_REG050E_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0510, SEC_PHY_REG0510_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0511, SEC_PHY_REG0511_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0516, SEC_PHY_REG0516_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG051B, SEC_PHY_REG051B_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0603, SEC_PHY_REG0603_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0607, SEC_PHY_REG0607_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG060A, SEC_PHY_REG060A_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG060B, SEC_PHY_REG060B_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG060C, SEC_PHY_REG060C_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG060D, SEC_PHY_REG060D_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG060E, SEC_PHY_REG060E_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0610, SEC_PHY_REG0610_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0611, SEC_PHY_REG0611_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0616, SEC_PHY_REG0616_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG061B, SEC_PHY_REG061B_INIT},

	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0099, SEC_PHY_REG0099_RBR_SC_EN},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0099, SEC_PHY_REG0099_HBR_SC_EN},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0099, SEC_PHY_REG0099_HBR2_SC_EN},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0099, SEC_PHY_REG0099_HBR3_SC_EN},

	{(uint8_t)LINK_RATE_RBR,  SEC_PHY_REG0097, SEC_PHY_REG0097_RBR_INIT},
	{(uint8_t)LINK_RATE_HBR,  SEC_PHY_REG0097, SEC_PHY_REG0097_HBR_INIT},
	{(uint8_t)LINK_RATE_HBR2, SEC_PHY_REG0097, SEC_PHY_REG0097_HBR2_INIT},
	{(uint8_t)LINK_RATE_HBR3, SEC_PHY_REG0097, SEC_PHY_REG0097_HBR3_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG_MAX, SEC_PHY_REG_DTAT_0_RST}
};

static struct SEC_PHY_Reg_Data stSEC_PHY_Aux_Reg_Data[] = {
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0113, SEC_PHY_REG0113_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0114, SEC_PHY_REG0114_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0115, SEC_PHY_REG0115_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0116, SEC_PHY_REG0116_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0117, SEC_PHY_REG0117_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0118, SEC_PHY_REG0118_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG011A, SEC_PHY_REG011A_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG011B, SEC_PHY_REG011B_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG011C, SEC_PHY_REG011C_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG011D, SEC_PHY_REG011D_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG011E, SEC_PHY_REG011E_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG011F, SEC_PHY_REG011F_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG010D, SEC_PHY_REG010D_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0110, SEC_PHY_REG0110_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG010F, SEC_PHY_REG010F_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0102, SEC_PHY_REG0102_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0103, SEC_PHY_REG0103_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG011F, SEC_PHY_REG011F_2nd_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0104, SEC_PHY_REG0104_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0120, SEC_PHY_REG0120_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_DELAY_USEC_REG, 1000},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0103, SEC_PHY_REG0103_2nd_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_DELAY_USEC_REG, 100},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0104, SEC_PHY_REG0104_2nd_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_DELAY_USEC_REG, 100},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0102, SEC_PHY_REG0102_2nd_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_DELAY_USEC_REG, 10},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG010F, SEC_PHY_REG010F_2nd_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_DELAY_USEC_REG, 10},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0104, SEC_PHY_REG0104_3rd_INIT},

	{(uint8_t)LINK_RATE_MAX, SEC_PHY_DELAY_USEC_REG, 100},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0123, SEC_PHY_REG0123_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG_MAX, SEC_PHY_REG_DTAT_0_RST}
};

static struct SEC_PHY_Reg_Data stSEC_PHY_SB_Reg_Data[] = {
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0103, SEC_PHY_REG0103_3rd_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0104, SEC_PHY_REG0104_4th_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0102, SEC_PHY_REG0102_3rd_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG010F, SEC_PHY_REG010F_3rd_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0104, SEC_PHY_REG0104_4th_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0123, SEC_PHY_REG0123_2nd_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG0108, SEC_PHY_REG0108_INIT},
	{(uint8_t)LINK_RATE_MAX, SEC_PHY_REG_MAX, SEC_PHY_REG_DTAT_0_RST}
};

static void dptx_reset_sec_phy(struct Dptx_Params *pstDptx)
{
	uint32_t reg_wval;

	if (pstDptx->ePhy_Dev == PHY_DEVICE_SEC) {
		reg_wval = ((uint32_t)PHY_CLK_DIV_DISABLE | (uint32_t)LC_REF_RO_PLL);
		(void)Dptx_Cfg_Set_PHY_Cfg(pstDptx, reg_wval);

		reg_wval = ((uint32_t)CFG_LANE_RESET | (uint32_t)CFG_CMN_RESET
			  | (uint32_t)CFG_INT_RESET);
		(void)Dptx_Cfg_SoftReset(pstDptx, reg_wval);

		reg_wval |= (uint32_t)CFG_DP_PHY_APB_RESET;
		(void)Dptx_Cfg_SoftReset(pstDptx, reg_wval);
		udelay(1);

		reg_wval &= ~(uint32_t)CFG_DP_PHY_APB_RESET;
		(void)Dptx_Cfg_SoftReset(pstDptx, reg_wval);
	}
}

static int32_t dptx_sec_check_phy_ssc_reg_value(uint8_t link_rate, uint32_t reg_addr,
						uint32_t *reg_val)
{
	int32_t ret = DPTX_RETURN_NO_ERROR;
	uint32_t reg_overrid_val = 0u;

	if (reg_val == NULL) {
		ret = -DPTX_RETURN_EINVAL;
		dptx_err("reg_val is NULL");
	} else {
		reg_overrid_val = *reg_val;
		/* HBR3 ------------------------------------------------------*/
		if (link_rate == (uint8_t)LINK_RATE_HBR3) {
			if (reg_addr == (uint32_t)SEC_PHY_REG0030) {
				/* To disable spread spectrum clocking, set lcpll_ssc_en to 0 */
				reg_overrid_val &= ~((uint32_t)1u << 0);
			}
			if (reg_addr == (uint32_t)SEC_PHY_REG0031) {
				/* To disable spread spectrum clocking, set lcpll_ssc_fm_deviation to 0x20 */
				reg_overrid_val = SEC_PHY_REG0031_RESET;
			}
			if (reg_addr == (uint32_t)SEC_PHY_REG0032) {
				/* To disable spread spectrum clocking, set lcpll_ssc_fm_freq to 0xC */
				reg_overrid_val = SEC_PHY_REG0032_HBR3_SSC_DIS;
			}
		} else {
			/* link rate below HBR3 --------------------------------------*/
			if (reg_addr == (uint32_t)SEC_PHY_REG0074) {
				/* To disable spread spectrum clocking, set ropll_ssc_en to 0 */
				reg_overrid_val &= ~((uint32_t)1u << 0);
			}
			if (reg_addr == (uint32_t)SEC_PHY_REG0075) {
				/* To disable spread spectrum clocking, set ropll_ssc_fm_deviation to 0x20 */
				reg_overrid_val = SEC_PHY_REG0075_RESET;
			}
			if (reg_addr == (uint32_t)SEC_PHY_REG0076) {
				/* To disable spread spectrum clocking, set ropll_ssc_fm_freq to 0xc */
				reg_overrid_val = SEC_PHY_REG0076_RESET;
			}
		}
		/* Common ----------------------------------------------------*/
		if (reg_addr == (uint32_t)SEC_PHY_REG0099) {
			if (reg_overrid_val == (uint32_t)SEC_PHY_REG0099_RBR_SC_EN) {
				/* RBR, HBR and HBR2 are same value */
				reg_overrid_val = (uint32_t)SEC_PHY_REG0099_RBR_SSC_DIS;
			}
			if (reg_overrid_val == (uint32_t)SEC_PHY_REG0099_HBR3_SC_EN) {
				reg_overrid_val = (uint32_t)SEC_PHY_REG0099_HBR3_SSC_DIS;
			}
		}
		if (reg_addr == (uint32_t)SEC_PHY_REG0047) {
			/* To disable spread spectrum clocking, set ropll_ssc_en to 0 */
			reg_overrid_val &= ~((uint32_t)1u << 0);
		}
		*reg_val = reg_overrid_val;
	}
	return ret;
}

int32_t Dptx_Sec_PHY_Init(struct Dptx_Params *pstDptx, uint8_t ucLinkRate, uint8_t ucLanes)
{
	bool bOffsetInRange, bPll_Ready, bPhy_Ready;
	uint8_t uclink_rate;
	int32_t iRetVal = DPTX_RETURN_NO_ERROR;
	uint32_t uiElements, uiPhy_Cfg;
	uint32_t uiReg_Addr, uiReg_Offset, uiReg_W_data;
	const struct SEC_PHY_Reg_Data *pstLink_Reg_Data;
	const struct SEC_PHY_Reg_Data *pstAux_Reg_Data;
	const struct SEC_PHY_Reg_Data *pstSB_Reg_Data;

	if (pstDptx->ePhy_Dev != PHY_DEVICE_SEC) {
		dptx_dbg("It's valid for SEC Phy only.. phy type = %d", pstDptx->ePhy_Dev);

		iRetVal = DPTX_RETURN_NO_ERROR;
	} else {
		dptx_reset_sec_phy(pstDptx);

		bOffsetInRange = CHECK_REG_OFFSET(pstDptx->uiSEC_PHY_Reg_Offset);
		if (!bOffsetInRange) {
			dptx_err("Invalid reg offset as 0x%x", pstDptx->uiRegBank_RegAddr_Offset);

			iRetVal = DPTX_RETURN_EINVAL;
		}

		if (iRetVal == DPTX_RETURN_NO_ERROR) {
			dptx_info("Init SEC Phy with Max rate(%u) = %s",
						ucLinkRate,
						(ucLinkRate == (uint8_t)DPTX_PHYIF_CTRL_RATE_RBR) ? "RBR" :
						(ucLinkRate == (uint8_t)DPTX_PHYIF_CTRL_RATE_HBR) ? "HBR" :
						(ucLinkRate == (uint8_t)DPTX_PHYIF_CTRL_RATE_HBR2) ? "HBR2" : "HBR3");

			uiReg_Offset = pstDptx->uiSEC_PHY_Reg_Offset;

			pstLink_Reg_Data = stSEC_PHY_Link_Reg_Data;

			/* Set LC (cascade) or RO PLL */
			uiPhy_Cfg = (ucLinkRate == (uint8_t)DPTX_PHYIF_CTRL_RATE_HBR3) ?
				    (uint32_t)((uint32_t)PHY_CLK_DIV_DISABLE | RO_REF_RO_PLL) :
				    (uint32_t)((uint32_t)PHY_CLK_DIV_DISABLE | LC_REF_RO_PLL);
			iRetVal = Dptx_Cfg_Set_PHY_Cfg(pstDptx, uiPhy_Cfg);

			for (uiElements = 0; (pstLink_Reg_Data[uiElements].uireg_add != (uint32_t)SEC_PHY_REG_MAX); uiElements++) {

				uclink_rate = pstLink_Reg_Data[uiElements].uclink_rate;

				if ((uclink_rate != (uint8_t)LINK_RATE_MAX) && (uclink_rate != ucLinkRate)) {
					/*For KCS */
					continue;
				}

				if (pstLink_Reg_Data[uiElements].uireg_add == (uint32_t)SEC_PHY_DELAY_USEC_REG) {
					udelay(pstLink_Reg_Data[uiElements].uireg_val);
					continue;
				}

				//dptx_info("Reg[0x%x] = 0x%x", pstLink_Reg_Data[uiElements].uireg_add, pstLink_Reg_Data[uiElements].uireg_val);

				uiReg_W_data = pstLink_Reg_Data[uiElements].uireg_val;
				uiReg_Addr = pstLink_Reg_Data[uiElements].uireg_add;

				if (DPTX_RETURN_ERROR(dptx_sec_check_phy_ssc_reg_value(ucLinkRate,
										       uiReg_Addr, &uiReg_W_data))) {
					break;
				}
				Dptx_Reg_Writel(pstDptx, (uiReg_Offset + uiReg_Addr), uiReg_W_data);
			}

			/* enable PHY_BIAS and PHY_BGR */
			uiPhy_Cfg |= (uint32_t)((uint32_t)CFG_BIAS_EN | CFG_BGR_EN);
			iRetVal = Dptx_Cfg_Set_PHY_Cfg(pstDptx, uiPhy_Cfg);
			udelay(10);

			pstAux_Reg_Data = stSEC_PHY_Aux_Reg_Data;

			for (uiElements = 0; (pstAux_Reg_Data[uiElements].uireg_add != (uint32_t)SEC_PHY_REG_MAX); uiElements++) {

				uclink_rate = pstAux_Reg_Data[uiElements].uclink_rate;

				if ((uclink_rate != (uint8_t)LINK_RATE_MAX) && (uclink_rate != ucLinkRate)) {
					/*For KCS */
					continue;
				}

				if (pstAux_Reg_Data[uiElements].uireg_add == (uint32_t)SEC_PHY_DELAY_USEC_REG) {
					udelay(pstAux_Reg_Data[uiElements].uireg_val);
					continue;
				}

		//		dptx_info("Reg[0x%x] = 0x%x", pstAux_Reg_Data[uiElements].uireg_add, pstAux_Reg_Data[uiElements].uireg_val);

				uiReg_W_data = pstAux_Reg_Data[uiElements].uireg_val;
				uiReg_Addr = pstAux_Reg_Data[uiElements].uireg_add;

				Dptx_Reg_Writel(pstDptx, (uiReg_Offset + uiReg_Addr), uiReg_W_data);
			}

			/* release PHY_INIT_reset */
			(void)Dptx_Cfg_SoftReset(pstDptx, (uint32_t)(CFG_LANE_RESET | CFG_CMN_RESET | CFG_DP_MB_RESET));
			udelay(10);

			/* enable PHY_PLL */
			uiPhy_Cfg |= (uint32_t)CFG_PLL_EN;
			iRetVal = Dptx_Cfg_Set_PHY_Cfg(pstDptx, uiPhy_Cfg);
			udelay(10);

			/* release PHY_CMN reset */
			(void)Dptx_Cfg_SoftReset(pstDptx, (uint32_t)(CFG_LANE_RESET | CFG_DP_MB_RESET));

			/* wait o_pll_lock_done and o_pll_clk_rdy */
			iRetVal = Dptx_Cfg_Check_PHY_Pll(pstDptx, &bPll_Ready);
		}

		if (iRetVal == DPTX_RETURN_NO_ERROR) {
			udelay(10);

			/* release PHY_lane_reset */
			(void)Dptx_Cfg_SoftReset(pstDptx, (uint32_t)CFG_DP_MB_RESET);

			/* wait o_phy_rdy */
			iRetVal = Dptx_Cfg_Check_PHY_Ready(pstDptx, &bPhy_Ready);
		}

		if (iRetVal == DPTX_RETURN_NO_ERROR) {
			pstSB_Reg_Data = stSEC_PHY_SB_Reg_Data;

			for (uiElements = 0; (pstSB_Reg_Data[uiElements].uireg_add != (uint32_t)SEC_PHY_REG_MAX); uiElements++) {

				uclink_rate = pstSB_Reg_Data[uiElements].uclink_rate;

				if ((uclink_rate != (uint8_t)LINK_RATE_MAX) && (uclink_rate != ucLinkRate)) {
					/*For KCS */
					continue;
				}

				if (pstSB_Reg_Data[uiElements].uireg_add == (uint32_t)SEC_PHY_DELAY_USEC_REG) {
					udelay(pstSB_Reg_Data[uiElements].uireg_val);
		//			dptx_info(" 0x%x : %u", pstSB_Reg_Data[uiElements].uireg_add, pstSB_Reg_Data[uiElements].uireg_val);
					continue;
				}

		//		dptx_info("Reg[0x%x] = 0x%x", pstSB_Reg_Data[uiElements].uireg_add, pstSB_Reg_Data[uiElements].uireg_val);

				uiReg_W_data = pstSB_Reg_Data[uiElements].uireg_val;
				uiReg_Addr = pstSB_Reg_Data[uiElements].uireg_add;

				if (pstSB_Reg_Data[uiElements].uireg_add == (uint32_t)SEC_PHY_REG0108) {
					uiReg_W_data &= ~((uint32_t)3u << 4);
					uiReg_W_data |= ((pstDptx->hw_config.aux_hysteresis & 0x3u) << 4);
				}

				Dptx_Reg_Writel(pstDptx, (uiReg_Offset + uiReg_Addr), uiReg_W_data);
			}

			iRetVal = Dptx_Cfg_Check_Sec_PHY_SB_Ready(pstDptx, &bPhy_Ready);
		}

		if (iRetVal == DPTX_RETURN_NO_ERROR) {

			iRetVal = Dptx_Sec_Set_NumOfLanes(pstDptx, ucLanes);

			for (uiElements = 0; uiElements < ucLanes; uiElements++) {
				(void)dptx_sec_set_phy_sigan_quality(pstDptx, uiElements, ucLinkRate,
						 VOLTAGE_SWING_LEVEL_0, PRE_EMPHASIS_LEVEL_0);
			}
		}
	}

	return iRetVal;
}

int32_t Dptx_Sec_Set_NumOfLanes(struct Dptx_Params *pstDptx, uint8_t ucLanes)
{
	bool bOffsetInRange;
	uint32_t uiReg_Addr, uiReg_Offset, uiReg_W_data;
	int32_t iRetVal = DPTX_RETURN_NO_ERROR;
	bool internal_ok = (bool)true;

	if (pstDptx->ePhy_Dev != PHY_DEVICE_SEC) {
		dptx_dbg("Nothing to do not for Samsung PHY");
		internal_ok = (bool)false;
	}

	if (internal_ok) {
		bOffsetInRange = CHECK_REG_OFFSET(pstDptx->uiSEC_PHY_Reg_Offset);
		if (!bOffsetInRange) {
			dptx_err("Invalid reg offset as 0x%x", pstDptx->uiRegBank_RegAddr_Offset);
			iRetVal = DPTX_RETURN_EINVAL;
			internal_ok = (bool)false;
		}
	}

	if (internal_ok) {
		uiReg_Offset = pstDptx->uiSEC_PHY_Reg_Offset;
		uiReg_Addr = (uint32_t)SEC_PHY_REG0207;

		switch (ucLanes) {
		case 1u:
			uiReg_W_data = 0x01U;
			break;
		case 2u:
			uiReg_W_data = 0x03U;
			break;
		case 4u:
			uiReg_W_data = 0x0FU;
			break;
		default:
			dptx_err("Invalid Num of lanes as 0x%x", ucLanes);
			iRetVal = DPTX_RETURN_EINVAL;
			internal_ok = (bool)false;
			break;
		}
	}

	if (internal_ok) {
		Dptx_Reg_Writel(pstDptx, (uiReg_Offset + uiReg_Addr), uiReg_W_data);
	}
	return iRetVal;
}

uint32_t dptx_sec_get_main_equalization(struct Dptx_Params *dptx_params, uint8_t lane_idx)
{
	uint32_t reg_offset, reg_addr;
	uint32_t reg_val = 0u;

	if (dptx_params->ePhy_Dev != PHY_DEVICE_SEC) {
		dptx_debug("Nothing to do not for Samsung PHY");
	} else {
		if (lane_idx > (uint8_t)PHY_LANE_3) {
			dptx_err("Invalid lane idx as %u", lane_idx);
		} else {
			if (!CHECK_REG_OFFSET(dptx_params->uiSEC_PHY_Reg_Offset)) {
				dptx_err("Invalid reg addr as 0x%x",
				     dptx_params->uiRegBank_RegAddr_Offset);
			} else if (!CHECK_REG_OFFSET(dptx_sec_main_reg_offset_table[lane_idx])) {
				dptx_err("Invalid reg offset as 0x%x",
				     dptx_sec_main_reg_offset_table[lane_idx]);
			} else {
				reg_addr = dptx_params->uiSEC_PHY_Reg_Offset;
				reg_offset = dptx_sec_main_reg_offset_table[lane_idx];

				reg_val = Dptx_Reg_Readl(dptx_params, (reg_addr +  reg_offset));
				reg_val &= 0x1Fu;
			}
		}
	}
	return reg_val;
}

int32_t dptx_sec_set_main_equalization(struct Dptx_Params *dptx_params, uint32_t lane_idx, uint32_t eq_val)
{
	uint32_t reg_offset, reg_addr, reg_val;
	int32_t ret = DPTX_RETURN_NO_ERROR;

	if (dptx_params->ePhy_Dev != PHY_DEVICE_SEC) {
		dptx_debug("Nothing to do not for Samsung PHY");
	} else {
		if (eq_val > 13u) {  /* 0 to 14 */
			dptx_err("Invalid VSW as %u", eq_val);
			ret = -DPTX_RETURN_EINVAL;
		}
		if (lane_idx > (uint8_t)PHY_LANE_3) {
			dptx_err("Invalid lane idx as %u", lane_idx);
			ret = -DPTX_RETURN_EINVAL;
		}
		if (DPTX_RETURN_SUCCESS(ret)) {
			if (!CHECK_REG_OFFSET(dptx_params->uiSEC_PHY_Reg_Offset)) {
				dptx_err("Invalid reg addr as 0x%x",
				     dptx_params->uiSEC_PHY_Reg_Offset);

				ret = -DPTX_RETURN_EINVAL;
			} else if (!CHECK_REG_OFFSET(dptx_sec_main_reg_offset_table[lane_idx])) {
				dptx_err("Invalid reg offset as 0x%x",
				     dptx_sec_main_reg_offset_table[lane_idx]);

				ret = -DPTX_RETURN_EINVAL;
			} else {
				reg_addr = dptx_params->uiSEC_PHY_Reg_Offset;
				reg_offset = dptx_sec_main_reg_offset_table[lane_idx];

				reg_val = (uint32_t)1u << 5; /* enable overrid */
				reg_val |= (eq_val & 0x1Fu);

				Dptx_Reg_Writel(dptx_params, (reg_addr +  reg_offset), reg_val);
			}
		}
	}
	return ret;
}

uint32_t dptx_sec_get_post_equalization(struct Dptx_Params *dptx_params, uint8_t lane_idx)
{
	uint32_t reg_offset, reg_addr;
	uint32_t reg_val = 0u;

	if (dptx_params->ePhy_Dev != PHY_DEVICE_SEC) {
		dptx_debug("Nothing to do not for Samsung PHY");
	} else {
		if (lane_idx > (uint8_t)3u) {
			dptx_err("Invalid lane idx as %u", lane_idx);
		} else {
			if (!CHECK_REG_OFFSET(dptx_params->uiSEC_PHY_Reg_Offset)) {
				dptx_err("Invalid reg offset as 0x%x",
				     dptx_params->uiRegBank_RegAddr_Offset);
			} else if (!CHECK_REG_OFFSET(dptx_sec_post_reg_offset_table[lane_idx])) {
				dptx_err("Invalid reg offset as 0x%x",
				     dptx_sec_post_reg_offset_table[lane_idx]);
			} else {
				reg_addr = dptx_params->uiSEC_PHY_Reg_Offset;
				reg_offset = dptx_sec_post_reg_offset_table[lane_idx];

				reg_val = Dptx_Reg_Readl(dptx_params, (reg_addr +  reg_offset));
				reg_val &= 0xFu;
			}
		}
	}
	return reg_val;
}

int32_t dptx_sec_set_post_equalization(struct Dptx_Params *dptx_params, uint32_t lane_idx, uint32_t eq_val)
{
	int32_t ret = DPTX_RETURN_NO_ERROR;
	uint32_t reg_offset, reg_addr, reg_val;

	if (dptx_params->ePhy_Dev != PHY_DEVICE_SEC) {
		dptx_debug("Nothing to do not for Samsung PHY");
	} else {
		if (eq_val > 15u) { /* 0 to 14 */
			dptx_err("Invalid VSW as %u", eq_val);
			ret = -DPTX_RETURN_EINVAL;
		}
		if (lane_idx > (uint32_t)PHY_LANE_3) {
			dptx_err("Invalid lane idx as %u", lane_idx);
			ret = -DPTX_RETURN_EINVAL;
		}
		if (DPTX_RETURN_SUCCESS(ret)) {
			if (!CHECK_REG_OFFSET(dptx_params->uiSEC_PHY_Reg_Offset)) {
				dptx_err("Invalid reg addr as 0x%x",
					dptx_params->uiRegBank_RegAddr_Offset);

				ret = -DPTX_RETURN_EINVAL;
			} else if (!CHECK_REG_OFFSET(dptx_sec_post_reg_offset_table[lane_idx])) {
				dptx_err("Invalid reg offset as 0x%x",
					dptx_sec_post_reg_offset_table[lane_idx]);

				ret = -DPTX_RETURN_EINVAL;
			} else {
				reg_addr = dptx_params->uiSEC_PHY_Reg_Offset;
				reg_offset = dptx_sec_post_reg_offset_table[lane_idx];

				reg_val = (uint32_t)1u << 4; /* enable overrid */
				reg_val |= (eq_val & 0xFu);

				Dptx_Reg_Writel(dptx_params, (reg_addr +  reg_offset), reg_val);
			}
		}
	}
	return ret;
}

int32_t dptx_sec_set_phy_sigan_quality(struct Dptx_Params *dev_param,
				       uint32_t lane_idx,
				       uint8_t link_rate,
				       enum PHY_VOLTAGE_SWING_LEVEL voltage_swing,
				       enum PHY_PRE_EMPHASIS_LEVEL pre_emphasis)
{
	int32_t ret = DPTX_RETURN_NO_ERROR;
	uint32_t linear_idx;

	if (dev_param->ePhy_Dev != PHY_DEVICE_SEC) {
		dptx_debug("Nothing to do not for Samsung PHY");
	} else {
		if (voltage_swing >= VOLTAGE_SWING_LEVEL_MAX) {
			dptx_err("Invalid VSW as %u", voltage_swing);
			ret = -DPTX_RETURN_EINVAL;
		}
		if (pre_emphasis >= PRE_EMPHASIS_LEVEL_MAX) {
			dptx_err("Invalid Pre-emp as %u", pre_emphasis);
			ret = -DPTX_RETURN_EINVAL;
		}
		if (lane_idx > (uint32_t)PHY_LANE_3) {
			dptx_err("Invalid lane idx as %u", lane_idx);
			ret = -DPTX_RETURN_EINVAL;
		}
		if (link_rate > (uint8_t)LINK_RATE_HBR3) {
			dptx_err("Invalid link rate as %u", link_rate);
			ret = -DPTX_RETURN_EINVAL;
		}
		if (DPTX_RETURN_SUCCESS(ret)) {
			linear_idx = ((uint32_t)voltage_swing * 4u) + (uint32_t)pre_emphasis;

			if ((linear_idx == 7u) || (linear_idx == 10u) ||
			    (linear_idx == 11u) || (linear_idx == 13u) ||
			    (linear_idx == 14u) || (linear_idx == 15u) ||
			    (linear_idx >= 16u)) {
				/**
				 * These values represent combinations of Voltage Swing (VSW)
				 * and Pre-Emphasis (PRE) that are invalid according to
				 * DisplayPor specifications.
				 *
				 * The array layout represents the following combinations:
				 *
				 * - VSW 0 PRE 0, VSW 0 PRE 1, ..., VSW 0 PRE 3
				 * - VSW 1 PRE 0, VSW 1 PRE 1, ..., VSW 1 PRE 3
				 * - ...
				 * - VSW 3 PRE 0, VSW 3 PRE 1, ..., VSW 3 PRE 3
				 *
				 * The loop index sequentially maps to these combinations.
				 * Invalid EQ configurations are as follows:
				 * - Index 7  (VSW 1 PRE 3)
				 * - Index 10 (VSW 2 PRE 2)
				 * - Index 11 (VSW 2 PRE 3)
				 * - Index 13 (VSW 3 PRE 1)
				 * - Index 14 (VSW 3 PRE 2)
				 * - Index 15 (VSW 3 PRE 3)
				 */
				dptx_err("Not allowed voltage swing %u level and pre-emphsis %u level", voltage_swing, pre_emphasis);
				ret = -DPTX_RETURN_EINVAL;
			}
		}
		if (DPTX_RETURN_SUCCESS(ret)) {
			ret = dptx_sec_set_main_equalization(dev_param, lane_idx,
					dev_param->hw_config.phy_eq[link_rate].main_eq[linear_idx]);
		}
		if (DPTX_RETURN_SUCCESS(ret)) {
			ret = dptx_sec_set_post_equalization(dev_param, lane_idx,
					dev_param->hw_config.phy_eq[link_rate].post_eq[linear_idx]);
		}
	}
	return ret;
}

