# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) Telechips Inc.

ccflags-y := \
	 -I$(srctree)/$(src) \
	 -I$(srctree)/$(src)/include

obj-y += \
	dptx_api.o \
	dptx_v14.o \
	dptx_reg.o \
	dptx_aux.o \
	dptx_vidin.o \
	dptx_core.o \
	dptx_intr.o \
	dptx_link.o \
	dptx_edid.o \
	dptx_extension.o \
	dptx_protect.o \
	dptx_clk.o \
	dptx_cfg.o \
	dptx_sec_phy.o \
	dptx_drm_dp_addition.o
