obj-y += can_test.o
obj-y += can.o
obj-y += can_drv.o
obj-y += can_msg.o
obj-y += can_par.o
obj-y += can_porting.o
obj-y += can_test.o
obj-y += can_gpio.o
obj-y += can_interrupt.o
obj-y += can_clock.o
obj-y += can_reset.o

CFLAGS_can_test.o += -Wno-int-to-pointer-cast -Wno-unused-function -Wno-unused-variable
CFLAGS_can_msg.o += -Wno-int-to-pointer-cast
CFLAGS_can_drv.o += -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast
CFLAGS_can_porting.o += -Wno-int-to-pointer-cast
