# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) Telechips Inc.

ccflags-y +=						\
	-I$(srctree)/board/telechips/common/		\
	-I$(srctree)/$(src)/earlycam/include		\
	-I$(srctree)/$(src)/earlycam/include/dev

obj-$(CONFIG_EARLYCAMERA_SOLUTION)	+= earlycamera_starter.o
obj-$(CONFIG_EARLYCAMERA_SOLUTION)	+= earlycam/

