// SPDX-License-Identifier: (GPL-2.0-or-later OR MIT)
/*
 * Copyright (C) Telechips Inc.
 */

#ifndef CKC_REG_H
#define CKC_REG_H

#include "ckc_iomap.h"
#include "ckc_offset.h"
#include "ckc_flags.h"

/*
 * Clock index for device tree.
 * These values used for clock-indices in clock device node.
 * The index number MUST BE match with Kernel & U-Boot
 */
#define DECLARE_CLK_ID(base, offset, index) (U32(base) + U32(offset) + U32(index))

/* Oscillator index */
/* Unsed SMU CKC Address can be used for oscillator ID */
#define OSC_XIN			DECLARE_CLK_ID(TCC_SMU_CCU_BASE, 0xFF000UL, 0x000UL)
#define OSC_XTIN		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, 0xFF000UL, 0x001UL)


/* PLL index */
#define PLL_0			DECLARE_CLK_ID(TCC_SMU_CCU_BASE, SMU_CCU_PLLPMS, 0x00UL)
#define PLL_1			DECLARE_CLK_ID(TCC_SMU_CCU_BASE, SMU_CCU_PLLPMS, 0x04UL)
#define PLL_2			DECLARE_CLK_ID(TCC_SMU_CCU_BASE, SMU_CCU_PLLPMS, 0x08UL)
#define PLL_3			DECLARE_CLK_ID(TCC_SMU_CCU_BASE, SMU_CCU_PLLPMS, 0x0CUL)


#define PLL_CA65_0		DECLARE_CLK_ID(TCC_CA65_CCU_BASE, CPU_CCU_PLLPMS, 0x00UL)
#define PLL_CA65_1		DECLARE_CLK_ID(TCC_CA65_CCU_BASE, CPU_CCU_PLLPMS, 0x10UL)
#define PLL_CA65_2		DECLARE_CLK_ID(TCC_CA65_CCU_BASE, CPU_CCU_PLLPMS, 0x20UL)
#define PLL_CA65_3		DECLARE_CLK_ID(TCC_CA65_CCU_BASE, CPU_CCU_PLLPMS, 0x30UL)

#define PLL_MEM_PHY_0		DECLARE_CLK_ID(TCC_MEM_PHY0_PLL_BASE, MEM_PHY_PLLPMS, 0x0UL)
#define PLL_MEM_PHY_1		DECLARE_CLK_ID(TCC_MEM_PHY1_PLL_BASE, MEM_PHY_PLLPMS, 0x0UL)

/* Divider index */
#define OSC_XIN_DIV		DECLARE_CLK_ID(TCC_SMU_CCU_BASE,  SMU_CCU_CLKDIVC1, 0x1UL)
#define OSC_XTIN_DIV		DECLARE_CLK_ID(TCC_SMU_CCU_BASE,  SMU_CCU_CLKDIVC1, 0x0UL)

#define PLL_0_DIV		DECLARE_CLK_ID(TCC_SMU_CCU_BASE,  SMU_CCU_CLKDIVC0, 0x2UL)
#define PLL_1_DIV		DECLARE_CLK_ID(TCC_SMU_CCU_BASE,  SMU_CCU_CLKDIVC0, 0x1UL)
#define PLL_2_DIV		DECLARE_CLK_ID(TCC_SMU_CCU_BASE,  SMU_CCU_CLKDIVC0, 0x0UL)
#define PLL_3_DIV		DECLARE_CLK_ID(TCC_SMU_CCU_BASE,  SMU_CCU_CLKDIVC1, 0x3UL)

#define PLL_CA65_0_DIV		DECLARE_CLK_ID(TCC_CA65_CCU_BASE, CPU_CCU_CLKDIV, 0x00UL)
#define PLL_CA65_1_DIV		DECLARE_CLK_ID(TCC_CA65_CCU_BASE, CPU_CCU_CLKDIV, 0x10UL)
#define PLL_CA65_2_DIV		DECLARE_CLK_ID(TCC_CA65_CCU_BASE, CPU_CCU_CLKDIV, 0x20UL)
#define PLL_CA65_3_DIV		DECLARE_CLK_ID(TCC_CA65_CCU_BASE, CPU_CCU_CLKDIV, 0x30UL)



/* CLKCTRL channel index */
#define FBUS_SMU		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, SMU_CCU_CLKCTRL, 0x000UL)
#define FBUS_CPU		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, SMU_CCU_CLKCTRL, 0x004UL)
#define FBUS_CM7_0		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, SMU_CCU_CLKCTRL, 0x008UL)
#define FBUS_CM7_1		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, SMU_CCU_CLKCTRL, 0x00CUL)
#define FBUS_CM7_2		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, SMU_CCU_CLKCTRL, 0x010UL)
#define FBUS_MEM		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, SMU_CCU_CLKCTRL, 0x014UL)
#define FBUS_HSIO		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, SMU_CCU_CLKCTRL, 0x018UL)
#define FBUS_EPP		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, SMU_CCU_CLKCTRL, 0x01CUL)
#define FBUS_NET		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, SMU_CCU_CLKCTRL, 0x020UL)
#define FBUS_IO			DECLARE_CLK_ID(TCC_SMU_CCU_BASE, SMU_CCU_CLKCTRL, 0x024UL)
#define FBUS_HSM		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, SMU_CCU_CLKCTRL, 0x028UL)
#define FBUS_PCIe		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, SMU_CCU_CLKCTRL, 0x02CUL)
#define PERI_SDMMC		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, SMU_CCU_CLKCTRL, 0x030UL)

#define FBUS_CA65_0		DECLARE_CLK_ID(TCC_CA65_CCU_BASE, CPU_CCU_CLKCTRL, 0x00UL)
#define FBUS_CA65_1		DECLARE_CLK_ID(TCC_CA65_CCU_BASE, CPU_CCU_CLKCTRL, 0x04UL)
#define FBUS_CA65_2		DECLARE_CLK_ID(TCC_CA65_CCU_BASE, CPU_CCU_CLKCTRL, 0x08UL)
#define FBUS_DSU		DECLARE_CLK_ID(TCC_CA65_CCU_BASE, CPU_CCU_CLKCTRL, 0x0CUL)
#define FBUS_CA65_PCLK		DECLARE_CLK_ID(TCC_CA65_CCU_BASE, CPU_CCU_CLKCTRL, 0x10UL)

/* Peripheral Clocks */
/* PCLK***CTRL register : starts from 0x4B100000 + 0x300*/
#define PERI_BASE_OFFSET	(SMU_CCU_PCLKCTRL + 0x0UL)

#define PERI_SM_TCX0		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x00UL)
#define PERI_SM_TCT0		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x04UL)
#define PERI_SM_TCZ0		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x08UL)
#define PERI_SM_TCX1		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x0CUL)
#define PERI_SM_TCT1		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x10UL)
#define PERI_SM_TCZ1		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x14UL)
#define PERI_SM_GTC		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x18UL)
#define PERI_HSIO_GMAC0_PCLK	DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x1CUL)
#define PERI_HSIO_GMAC0_TS	DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x20UL)
#define PERI_HSIO_GMAC1_PCLK	DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x24UL)
#define PERI_HSIO_GMAC1_TS	DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x28UL)
#define PERI_IO_GPSB0		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x2CUL)
#define PERI_IO_GPSB1		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x30UL)
#define PERI_IO_GPSB2		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x34UL)
#define PERI_IO_GPSB3		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x38UL)
#define PERI_IO_GPSB4		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x3CUL)
#define PERI_IO_GPSB5		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x40UL)
#define PERI_IO_I2C0		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x44UL)
#define PERI_IO_I2C1		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x48UL)
#define PERI_IO_I2C2		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x4CUL)
#define PERI_IO_I2C3		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x50UL)
#define PERI_IO_I2C4		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x54UL)
#define PERI_IO_UART0		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x58UL)
#define PERI_IO_UART1		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x5CUL)
#define PERI_IO_UART2		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x60UL)
#define PERI_IO_UART3		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x64UL)
#define PERI_IO_CAN0		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x68UL)
#define PERI_IO_CAN1		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x6CUL)
#define PERI_IO_CAN2		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x70UL)
#define PERI_IO_CAN3		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x74UL)
#define PERI_IO_ADC		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x78UL)
#define PERI_IO_PDM		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x7CUL)
#define PERI_IO_ICTC0		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x80UL)
#define PERI_IO_ICTC1		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x84UL)
#define PERI_IO_ICTC2		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x88UL)
#define PERI_NET_GMAC0_PCLK	DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x8CUL)
#define PERI_NET_GMAC1_PCLK	DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x90UL)
#define PERI_NET_TS		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x94UL)
#define PERI_NET_LPA		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x98UL)
#define PERI_MEM_SFMC0		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0x9CUL)
#define PERI_MEM_SFMC1		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0xA0UL)
#define PERI_MEM_SFMC0_1600	DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0xA4UL)
#define PERI_MEM_SFMC1_1600	DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0xA8UL)
#define PERI_PCIe_PHY_CR	DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0xACUL)
#define PERI_HSM		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0xB0UL)
#define PERI_OUT0		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0xB4UL)
#define PERI_OUT1		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0xB8UL)
#define PERI_OUT2		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0xBCUL)
#define PERI_OUT3		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0xC0UL)
#define PERI_OUT4		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0xC4UL)
#define PERI_OUT5		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0xC8UL)
#define PERI_OUT6		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0xCCUL)
#define PERI_OUT7		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0xD0UL)
#define PERI_OUT8		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0xD4UL)
#define PERI_OUT9		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0xD8UL)
#define PERI_OUT10		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0xDCUL)
#define PERI_OUT11		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0xE0UL)
#define PERI_OUT12		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0xE4UL)
#define PERI_OUT13		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0xE8UL)
#define PERI_OUT14		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0xECUL)
#define PERI_OUT15		DECLARE_CLK_ID(TCC_SMU_CCU_BASE, PERI_BASE_OFFSET, 0xF0UL)




/* Use this macro to find register address for each SWRESET & CLKEN ID */
#define	CKC_SWRST_CLKEN_ID(A) (A/32UL)

/* SMU CLKMASK	Register (0x1E00028C) */
#define SMU_START		0UL
#define SMU_CLK_RST_EN		CKC_SWRST_CLKEN_ID(SMU_START)
#define SMU_GPIO		SMU_START
#define SMU_TRNG		(SMU_START + 1UL)
#define SMU_TIMER0		(SMU_START + 2UL)
#define SMU_TIMER1		(SMU_START + 3UL)
#define SMU_GTC			(SMU_START + 4UL)
#define SMU_RESERVE5		(SMU_START + 5UL)
#define SMU_RESERVE6		(SMU_START + 6UL)
#define SMU_RESERVE7		(SMU_START + 7UL)
#define SMU_RESERVE8		(SMU_START + 8UL)
#define SMU_RESERVE9		(SMU_START + 9UL)
#define SMU_RESERVE10		(SMU_START + 10UL)
#define SMU_RESERVE11		(SMU_START + 11UL)
#define SMU_RESERVE12		(SMU_START + 12UL)
#define SMU_RESERVE13		(SMU_START + 13UL)
#define SMU_RESERVE14		(SMU_START + 14UL)
#define SMU_RESERVE15		(SMU_START + 15UL)
#define SMU_RESERVE16		(SMU_START + 16UL)
#define SMU_RESERVE17		(SMU_START + 17UL)
#define SMU_RESERVE18		(SMU_START + 18UL)
#define SMU_RESERVE19		(SMU_START + 19UL)
#define SMU_RESERVE20		(SMU_START + 20UL)
#define SMU_RESERVE21		(SMU_START + 21UL)
#define SMU_RESERVE22		(SMU_START + 22UL)
#define SMU_RESERVE23		(SMU_START + 23UL)
#define SMU_RESERVE24		(SMU_START + 24UL)
#define SMU_RESERVE25		(SMU_START + 25UL)
#define SMU_RESERVE26		(SMU_START + 26UL)
#define SMU_RESERVE27		(SMU_START + 27UL)
#define SMU_RESERVE28		(SMU_START + 28UL)
#define SMU_RESERVE29		(SMU_START + 29UL)
#define SMU_RESERVE30		(SMU_START + 30UL)
#define SMU_RESERVE31		(SMU_START + 31UL)
#define SMU_END			(SMU_START + 31UL)


/* HSIO BUS CLKEN   Register (0x17400000) */
/* HSIO BUS SWRESET Register (0x17400004) */
#define HSIO_START		(SMU_END + 1UL)
#define HSIO_CLK_RST_EN		CKC_SWRST_CLKEN_ID(HSIO_START)
#define HSIO_EMMC_CORE		HSIO_START
#define HSIO_EMMC_IOMUX		(HSIO_START + 1UL)
#define HSIO_USB		(HSIO_START + 2UL)
#define HSIO_GMAC0		(HSIO_START + 3UL) /* For CLKMASK */
#define HSIO_GMAC1		(HSIO_START + 4UL) /* For CLKMASK */
#define HSIO_GMAC0_DELAY	(HSIO_START + 3UL) /* For SWRESET */
#define HSIO_GMAC0_SAFETY	(HSIO_START + 4UL) /* For SWRESET */
#define HSIO_GMAC0_CORE		(HSIO_START + 5UL)
#define HSIO_GMAC1_DELAY	(HSIO_START + 6UL)
#define HSIO_GMAC1_SAFETY	(HSIO_START + 7UL)
#define HSIO_GNAC1_CORE		(HSIO_START + 8UL)
#define HSIO_TS_DEC_GMAC	(HSIO_START + 9UL)
#define HSIO_TS_ENC_GMAC0	(HSIO_START + 10UL)
#define HSIO_TS_ENC_GMAC1	(HSIO_START + 11UL)
#define HSIO_RESERVE12		(HSIO_START + 12UL)
#define HSIO_RESERVE13		(HSIO_START + 13UL)
#define HSIO_RESERVE14		(HSIO_START + 14UL)
#define HSIO_RESERVE15		(HSIO_START + 15UL)
#define HSIO_RESERVE16		(HSIO_START + 16UL)
#define HSIO_RESERVE17		(HSIO_START + 17UL)
#define HSIO_RESERVE18		(HSIO_START + 18UL)
#define HSIO_RESERVE19		(HSIO_START + 19UL)
#define HSIO_RESERVE20		(HSIO_START + 20UL)
#define HSIO_RESERVE21		(HSIO_START + 21UL)
#define HSIO_RESERVE22		(HSIO_START + 22UL)
#define HSIO_RESERVE23		(HSIO_START + 23UL)
#define HSIO_RESERVE24		(HSIO_START + 24UL)
#define HSIO_RESERVE25		(HSIO_START + 25UL)
#define HSIO_RESERVE26		(HSIO_START + 26UL)
#define HSIO_RESERVE27		(HSIO_START + 27UL)
#define HSIO_RESERVE28		(HSIO_START + 28UL)
#define HSIO_RESERVE29		(HSIO_START + 29UL)
#define HSIO_RESERVE30		(HSIO_START + 30UL)
#define HSIO_RESERVE31		(HSIO_START + 31UL)
#define HSIO_END		(HSIO_START + 31UL)






/* PCIe BUS SWRESET   Register (0x16004000) */
#define PCIe_START		(HSIO_END + 1UL)
#define PCIe_CLK_RST_EN		CKC_SWRST_CLKEN_ID(PCIe_START)
#define PCIe_PCIe		PCIe_START
#define PCIe_MMU		(PCIe_START + 1UL)
#define PCIe_MMU_CFG		(PCIe_START + 2UL)
#define PCIe_MMU_CTRL_STS	(PCIe_START + 3UL)
#define PCIe_RESERVE4		(PCIe_START + 4UL)
#define PCIe_RESERVE5		(PCIe_START + 5UL)
#define PCIe_RESERVE6		(PCIe_START + 6UL)
#define PCIe_RESERVE7		(PCIe_START + 7UL)
#define PCIe_RESERVE8		(PCIe_START + 8UL)
#define PCIe_RESERVE9		(PCIe_START + 9UL)
#define PCIe_RESERVE10		(PCIe_START + 10UL)
#define PCIe_RESERVE11		(PCIe_START + 11UL)
#define PCIe_RESERVE12		(PCIe_START + 12UL)
#define PCIe_RESERVE13		(PCIe_START + 13UL)
#define PCIe_RESERVE14		(PCIe_START + 14UL)
#define PCIe_RESERVE15		(PCIe_START + 15UL)
#define PCIe_RESERVE16		(PCIe_START + 16UL)
#define PCIe_RESERVE17		(PCIe_START + 17UL)
#define PCIe_RESERVE18		(PCIe_START + 18UL)
#define PCIe_RESERVE19		(PCIe_START + 19UL)
#define PCIe_RESERVE20		(PCIe_START + 20UL)
#define PCIe_RESERVE21		(PCIe_START + 21UL)
#define PCIe_RESERVE22		(PCIe_START + 22UL)
#define PCIe_RESERVE23		(PCIe_START + 23UL)
#define PCIe_RESERVE24		(PCIe_START + 24UL)
#define PCIe_RESERVE25		(PCIe_START + 25UL)
#define PCIe_RESERVE26		(PCIe_START + 26UL)
#define PCIe_RESERVE27		(PCIe_START + 27UL)
#define PCIe_RESERVE28		(PCIe_START + 28UL)
#define PCIe_RESERVE29		(PCIe_START + 29UL)
#define PCIe_RESERVE30		(PCIe_START + 30UL)
#define PCIe_RESERVE31		(PCIe_START + 31UL)
#define PCIe_END		(PCIe_START + 31UL)





/* IO BUS CLKMASK0 Register (0x4AE00000) */
/* IO BUS SWRESET0 Register (0x4AE00008) */
#define IO0_START		(PCIe_END + 1UL)
#define IO0_CLK_RST_EN		CKC_SWRST_CLKEN_ID(IO0_START)
#define IO_CAN			IO0_START
#define IO_CAN0			(IO0_START + 1UL)
#define IO_CAN1			(IO0_START + 2UL)
#define IO_CAN2			(IO0_START + 3UL)
#define IO_CAN3			(IO0_START + 4UL)
#define IO_CAN_CFG		(IO0_START + 5UL)
#define IO_GPSB			(IO0_START + 6UL)
#define IO_GPSB0		(IO0_START + 7UL)
#define IO_GPSB1		(IO0_START + 8UL)
#define IO_GPSB2		(IO0_START + 9UL)
#define IO_GPSB3		(IO0_START + 10UL)
#define IO_GPSB4		(IO0_START + 11UL)
#define IO_GPSB5		(IO0_START + 12UL)
#define IO_GPSB_SAFE		(IO0_START + 13UL)
#define IO_GPSB_CFG		(IO0_START + 14UL)
#define IO_ADC			(IO0_START + 15UL)
#define IO_PDM			(IO0_START + 16UL)
#define IO_ICTC			(IO0_START + 17UL)
#define IO_ICTC0		(IO0_START + 18UL)
#define IO_ICTC1		(IO0_START + 19UL)
#define IO_ICTC2		(IO0_START + 20UL)
#define IO0_RESERVE21		(IO0_START + 21UL)
#define IO0_RESERVE22		(IO0_START + 22UL)
#define IO0_RESERVE23		(IO0_START + 23UL)
#define IO0_RESERVE24		(IO0_START + 24UL)
#define IO0_RESERVE25		(IO0_START + 25UL)
#define IO0_RESERVE26		(IO0_START + 26UL)
#define IO0_RESERVE27		(IO0_START + 27UL)
#define IO0_RESERVE28		(IO0_START + 28UL)
#define IO0_RESERVE29		(IO0_START + 29UL)
#define IO0_RESERVE30		(IO0_START + 30UL)
#define IO0_RESERVE31		(IO0_START + 31UL)
#define IO0_END			(IO0_START + 31UL)





/* IO BUS CLKMASK1 Register (0x4AE00004) */
/* IO BUS SWRESET1 Register (0x4AE0000C) */
#define IO1_START		(IO0_END + 1UL)
#define IO1_CLK_RST_EN		CKC_SWRST_CLKEN_ID(IO1_START)
#define IO_UART			IO1_START
#define IO_UART0		(IO1_START + 1UL)
#define IO_UART1		(IO1_START + 2UL)
#define IO_UART2		(IO1_START + 3UL)
#define IO_UART3		(IO1_START + 4UL)
#define IO_UART_DMA0		(IO1_START + 5UL)
#define IO_UART_DMA1		(IO1_START + 6UL)
#define IO_UART_DMA2		(IO1_START + 7UL)
#define IO_UART_DMA3		(IO1_START + 8UL)
#define IO_UART_CFG		(IO1_START + 9UL)
#define IO_I2C			(IO1_START + 10UL)
#define IO_I2C0			(IO1_START + 11UL)
#define IO_I2C1			(IO1_START + 12UL)
#define IO_I2C2			(IO1_START + 13UL)
#define IO_I2C3			(IO1_START + 14UL)
#define IO_I2C4			(IO1_START + 15UL)
#define IO_I2C_CFG		(IO1_START + 16UL)
#define IO1_RESERVE17		(IO1_START + 17UL)
#define IO1_RESERVE18		(IO1_START + 18UL)
#define IO1_RESERVE19		(IO1_START + 19UL)
#define IO1_RESERVE20		(IO1_START + 20UL)
#define IO1_RESERVE21		(IO1_START + 21UL)
#define IO1_RESERVE22		(IO1_START + 22UL)
#define IO1_RESERVE23		(IO1_START + 23UL)
#define IO1_RESERVE24		(IO1_START + 24UL)
#define IO1_RESERVE25		(IO1_START + 25UL)
#define IO1_RESERVE26		(IO1_START + 26UL)
#define IO1_RESERVE27		(IO1_START + 27UL)
#define IO1_RESERVE28		(IO1_START + 28UL)
#define IO1_RESERVE29		(IO1_START + 29UL)
#define IO1_RESERVE30		(IO1_START + 30UL)
#define IO1_RESERVE31		(IO1_START + 31UL)
#define IO1_END			(IO1_START + 31UL)


/* PLL source clock (Not support CLK_F_GET_SRC_CLK yet..) */
#define PLL_SRC_XIN			0UL

/* Source clock flags for CLK_F_GET_SRC_CLK */
/* SMU BUS SEL */
#define SMU_CLKCTRL_SEL_PLL0		0UL
#define SMU_CLKCTRL_SEL_PLL1		1UL
#define SMU_CLKCTRL_SEL_PLL2		2UL
#define SMU_CLKCTRL_SEL_PLL3		3UL

#define SMU_CLKCTRL_SEL_XIN		5UL

#define SMU_CLKCTRL_SEL_PLL0DIV		6UL
#define SMU_CLKCTRL_SEL_PLL1DIV		7UL
#define SMU_CLKCTRL_SEL_PLL2DIV		8UL
#define SMU_CLKCTRL_SEL_PLL3DIV		9UL
#define SMU_CLKCTRL_SEL_XINDIV		10UL

/* CPU BUS SEL */
#define CPU_CLKCTRL_SEL_XIN		0UL
#define CPU_CLKCTRL_SEL_PLL		1UL
#define CPU_CLKCTRL_SEL_PLLDIV		2UL
#define CPU_CLKCTRL_SEL_EXTCLK		3UL

/* SMU Peripheral SEL */
#define SMU_PCLKCTRL_SEL_PLL0		0UL
#define SMU_PCLKCTRL_SEL_PLL1		1UL
#define SMU_PCLKCTRL_SEL_PLL2		2UL
#define SMU_PCLKCTRL_SEL_PLL3		3UL

#define SMU_PCLKCTRL_SEL_XIN		5UL
#define SMU_PCLKCTRL_SEL_XTIN		6UL

#define SMU_PCLKCTRL_SEL_PLL0DIV	9UL
#define SMU_PCLKCTRL_SEL_PLL1DIV	10UL
#define SMU_PCLKCTRL_SEL_PLL2DIV	11UL
#define SMU_PCLKCTRL_SEL_PLL3DIV	12UL

#define SMU_PCLKCTRL_SEL_XINDIV		13UL
#define SMU_PCLKCTRL_SEL_XTINDIV	14UL

#define SMU_PCLKCTRL_SEL_EXTCLK0	16UL
#define SMU_PCLKCTRL_SEL_EXTCLK1	17UL
#define SMU_PCLKCTRL_SEL_EXTCLK2	18UL
#define SMU_PCLKCTRL_SEL_EXTCLK3	19UL
#define SMU_PCLKCTRL_SEL_EXTCLK4	20UL
#define SMU_PCLKCTRL_SEL_EXTCLK5	21UL
#define SMU_PCLKCTRL_SEL_EXTCLK6	22UL
#define SMU_PCLKCTRL_SEL_EXTCLK7	23UL
#define SMU_PCLKCTRL_SEL_EXTCLK8	24UL
#define SMU_PCLKCTRL_SEL_EXTCLK9	25UL
#define SMU_PCLKCTRL_SEL_EXTCLK10	26UL
#define SMU_PCLKCTRL_SEL_EXTCLK11	27UL
#define SMU_PCLKCTRL_SEL_EXTCLK12	28UL
#define SMU_PCLKCTRL_SEL_EXTCLK13	29UL
#define SMU_PCLKCTRL_SEL_EXTCLK14	30UL
#define SMU_PCLKCTRL_SEL_EXTCLK15	31UL

#endif
