# Modified by Telechips Inc. (date: 2020-06)

obj-$(CONFIG_FIRMWARE)		+= firmware-uclass.o
obj-$(CONFIG_$(SPL_)ARM_PSCI_FW)	+= psci.o
obj-$(CONFIG_TI_SCI_PROTOCOL)	+= ti_sci.o
obj-$(CONFIG_SANDBOX)		+= firmware-sandbox.o
obj-$(CONFIG_ZYNQMP_FIRMWARE)	+= firmware-zynqmp.o
obj-$(CONFIG_TCC_SC_FIRMWARE)	+= tcc_sc_fw.o
