# SPDX-License-Identifier: GPL-2.0+
#
# Makefile for the U-Boot SOC specific device drivers.

# Modified by Telechips Inc. (date: 2020-05)

obj-$(CONFIG_SOC_TI) += ti/
obj-$(CONFIG_ARCH_TELECHIPS) += telechips/
