# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) Telechips Inc.

ccflags-y +=					\
	-I$(srctree)/$(src)/../include		\
	-I$(srctree)/$(src)/../../../video/tcc

obj-y +=			\
	earlycamera_main.o	\
	switch.o		\
	camera.o		\
	lcdc.o			\
	timer_irq.o		\
	cam_ipc.o
