/* SPDX-License-Identifier: (GPL-2.0-or-later OR MIT) */
/*
 * Copyright (C) 2023 Telechips Inc.
 */

#ifndef DT_TCC807X_CLKS_H
#define DT_TCC807X_CLKS_H

#include <asm/arch-tcc807x/ckc_flags.h>

/*
 * Clock index for device tree.
 * These values used for clock-indices in clock device node.
 * The index number MUST BE match with Kernel & U-Boot
 */

#define DECLARE_CLK_ID(base, offset, index) ((base) + (offset) + (index))

/* BASE Address */
/* Part 2. System */
#define SMU_CKC			0x14000000UL


/* Part 3. GPU */
#define GPU_CKC			0x10E00000UL
#define GPU_CFG			0x10E10000UL
#define G2D_CKC			0x1A000000UL
#define G2D_CFG			0x1A010000UL


/* Part 4. MEMORY */
#define MEM_PHY0_CKC		0x13040000UL
#define MEM_PHY1_CKC		0x13050000UL
#define MEM_PHY2_CKC		0x13140000UL
#define MEM_PHY3_CKC		0x13150000UL

#define MEM_CFG			0x13200000UL
#define MEM_CKC			0x13240000UL


/* Part 5. IO */
#define IO_CFG			0x16051000UL
#define IO_STR_CFG		0x16494000UL


/* Part 6. HSIO */
#define HSIO_CFG		0x11DA0000UL


/* Part 7. DISPLAY */
#define DDI_CFG			0x12380000UL
#define DP_CKC			0x124C0000UL


/* Part 8. VIDEO */
#define VIDEO_CFG		0x15100000UL
#define VIDEO_CKC		0x15280000UL


/* Part 9. AUDIO */
#define AUDIO_CCU		0x19600000UL


/* Part 10. CPU */
#define CPU_CFG			0x17000000UL
//#define CPU_MP_CFG		0x17100000UL
#define CPU_MP_CORE4_CCU	0x17110000UL
#define CPU_MP_CORE0_CCU	0x17120000UL
#define CPU_MP_DSU_CCU		0x17130000UL
#define CPU_MP_CORE5_CCU	0x17140000UL
#define CPU_MP_CORE6_CCU	0x17150000UL
#define CPU_MP_CORE7_CCU	0x17160000UL
#define CPU_MP_CORE1_CCU	0x17170000UL
#define CPU_MP_CORE2_CCU	0x17180000UL
#define CPU_MP_CORE3_CCU	0x17190000UL
//#define CPU_SP_CFG		0x17200000UL
#define CPU_SP_CORE0_CCU	0x17210000UL
#define CPU_SP_DSU_CCU		0x17220000UL
#define CPU_SP_CORE1_CCU	0x17230000UL

/* Part 16. CAMERA */
#define CAMERA_CKC		0x1C000000UL
#define CAMERA_CFG		0x1C004000UL


/* Part 17. NPU */
#define NPU_CKC			0x1F000000UL
#define NPU_CFG			0x1F010000UL


/*
 * CKC Register Offsets
 */
/* Part 2. System */
#define SMU_CLKCTRL	0x000UL
#define SMU_PLLPMS	0x080UL
#define SMU_PLLCON	0x100UL
#define SMU_PLLMON	0x180UL
#define SMU_CLKDIVC0	0x200UL
#define SMU_CLKDIVC1	0x204UL
#define SMU_SWRESET	0x284UL
#define SMU_SWRSTDIS	0x288UL
#define SMU_PCLKCTRL	0x400UL


/* Part 2. GPU */
#define GPU_CLKCTRL	0x000UL
#define GPU_PLLPMS	0x008UL
#define GPU_PLLCON	0x00CUL
#define GPU_PLLMON	0x010UL
#define GPU_CLKDIVC	0x018UL

#define GPU_CLKMASK	0x000UL
#define GPU_SWRESET	0x004UL


/* Part 4. MEMORY */
#define MEM_PHY_PLLPMS	0x000UL
#define MEM_PHY_PLLCON	0x004UL
#define MEM_PHY_PLLMON	0x008UL

#define MEM_CLKCTRL	0x000UL
#define MEM_PLLPMS	0x010UL
#define MEM_PLLCON	0x014UL
#define MEM_PLLMON	0x018UL
#define MEM_CLKDIVC	0x030UL


/* Part 5. IO */
#define IO_HCLKEN	0x000UL
#define IO_HRSTEN	0x00CUL
#define IO_PCLKEN	0x018UL

#define IO_HCLKEN_STR	0x000UL
#define IO_HRSTEN_STR	0x004UL


/* Part 6. HSIO */
#define HSIO_HCLKMASK	0x000UL
#define HSIO_SWRESET	0x004UL


/* Part 7. DISPLAY */
#define DDI_CLKEN	0x000UL
#define DDI_SWRESET	0x004UL

#define DP_CLKCTRL	0x000UL
#define DP_PLLPMS	0x010UL
#define DP_PLLCON	0x014UL
#define DP_PLLMON	0x018UL
#define DP_CLKDIVC	0x01CUL


/* Part 8. VIDEO */
#define VIDEO_ACLKMASK	0x000UL
#define VIDEO_SWRESET	0x004UL

#define VIDEO_CLKCTRL	0x000UL
#define VIDEO_PLLPMS	0x010UL
#define VIDEO_PLLCON	0x014UL
#define VIDEO_PLLMON	0x018UL
#define VIDEO_CLKDIVC	0x030UL


/* Part 9. AUDIO */
#define AUDIO_PLLPMS	0x000UL
#define AUDIO_PLLCON	0x004UL
#define AUDIO_PLLMON	0x008UL
#define AUDIO_CLKDIVC	0x020UL
#define AUDIO_CLKCTRL	0x024UL
#define AUDIO_CLKMASK	0x028UL
#define AUDIO_SWRESET	0x030UL
#define AUDIO_PCLKCTRL	0x038UL


/* Part 10. CPU */
#define CPU_ACLKMASK	0x000UL
#define CPU_SWRESET	0x004UL
#define CPU_SWRSTDIS	0x008UL

#define CPU_CLKCTRL	0x000UL
#define CPU_PLLPMS	0x008UL
#define CPU_PLLCON	0x00CUL
#define CPU_PLLMON	0x010UL
#define CPU_CLKDIVC	0x014UL


/* Part 16. CAMERA */
#define CAM_SWRESET	0x000UL
#define CAM_CLKMASK	0x008UL

#define CAM_CLKCTRL	0x000UL
#define CAM_PLLPMS	0x010UL
#define CAM_PLLCON	0x014UL
#define CAM_PLLMON	0x018UL
#define CAM_CLKDIVC	0x01CUL


/* Part 17. NPU */
#define NPU_CLKMASK	0x000UL
#define NPU_SWRESET	0x004UL

#define NPU_CLKCTRL	0x000UL
#define NPU_PLLPMS	0x008UL
#define NPU_PLLCON	0x00CUL
#define NPU_PLLMON	0x010UL
#define NPU_CLKDIVC	0x018UL

/* Oscillator index */
/* Unsed SMU CKC Address can be used for oscillator ID */
#define OSC_XIN			DECLARE_CLK_ID(SMU_CKC, 0xFF000UL, 0x000UL)
#define OSC_XTIN		DECLARE_CLK_ID(SMU_CKC, 0xFF000UL, 0x001UL)


/* PLL index */
#define PLL_0			DECLARE_CLK_ID(SMU_CKC, SMU_PLLPMS, 0x00UL)
#define PLL_1			DECLARE_CLK_ID(SMU_CKC, SMU_PLLPMS, 0x04UL)
#define PLL_2			DECLARE_CLK_ID(SMU_CKC, SMU_PLLPMS, 0x08UL)
#define PLL_3			DECLARE_CLK_ID(SMU_CKC, SMU_PLLPMS, 0x0CUL)
#define PLL_4			DECLARE_CLK_ID(SMU_CKC, SMU_PLLPMS, 0x10UL)

#define PLL_GPU			DECLARE_CLK_ID(GPU_CKC, GPU_PLLPMS, 0x00UL)
#define PLL_G2D			DECLARE_CLK_ID(G2D_CKC, GPU_PLLPMS, 0x00UL)

#define PLL_MEMPHY_0		DECLARE_CLK_ID(MEM_PHY0_CKC, MEM_PHY_PLLPMS, 0x0UL)
#define PLL_MEMPHY_1		DECLARE_CLK_ID(MEM_PHY1_CKC, MEM_PHY_PLLPMS, 0x0UL)
#define PLL_MEMPHY_2		DECLARE_CLK_ID(MEM_PHY2_CKC, MEM_PHY_PLLPMS, 0x0UL)
#define PLL_MEMPHY_3		DECLARE_CLK_ID(MEM_PHY3_CKC, MEM_PHY_PLLPMS, 0x0UL)

#define PLL_MEM_0		DECLARE_CLK_ID(MEM_CKC, MEM_PLLPMS, 0x00UL)
#define PLL_MEM_1		DECLARE_CLK_ID(MEM_CKC, MEM_PLLPMS, 0x10UL)

#define PLL_DP			DECLARE_CLK_ID(DP_CKC, DP_PLLPMS, 0x00UL)

#define PLL_VIDEO_0		DECLARE_CLK_ID(VIDEO_CKC, VIDEO_PLLPMS, 0x00UL)
#define PLL_VIDEO_1		DECLARE_CLK_ID(VIDEO_CKC, VIDEO_PLLPMS, 0x10UL)

#define PLL_AUDIO_0		DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PLLPMS, 0x00UL)
#define PLL_AUDIO_1		DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PLLPMS, 0x10UL)

#define PLL_MP_CA55_0		DECLARE_CLK_ID(CPU_MP_CORE0_CCU, CPU_PLLPMS, 0x00UL)
#define PLL_MP_CA55_1		DECLARE_CLK_ID(CPU_MP_CORE1_CCU, CPU_PLLPMS, 0x00UL)
#define PLL_MP_CA55_2		DECLARE_CLK_ID(CPU_MP_CORE2_CCU, CPU_PLLPMS, 0x00UL)
#define PLL_MP_CA55_3		DECLARE_CLK_ID(CPU_MP_CORE3_CCU, CPU_PLLPMS, 0x00UL)
#define PLL_MP_CA76_0		DECLARE_CLK_ID(CPU_MP_CORE4_CCU, CPU_PLLPMS, 0x00UL)
#define PLL_MP_CA76_1		DECLARE_CLK_ID(CPU_MP_CORE5_CCU, CPU_PLLPMS, 0x00UL)
#define PLL_MP_CA76_2		DECLARE_CLK_ID(CPU_MP_CORE6_CCU, CPU_PLLPMS, 0x00UL)
#define PLL_MP_CA76_3		DECLARE_CLK_ID(CPU_MP_CORE7_CCU, CPU_PLLPMS, 0x00UL)
#define PLL_MP_DSU		DECLARE_CLK_ID(CPU_MP_DSU_CCU,   CPU_PLLPMS, 0x00UL)

#define PLL_SP_CA55_0		DECLARE_CLK_ID(CPU_SP_CORE0_CCU, CPU_PLLPMS, 0x00UL)
#define PLL_SP_CA55_1		DECLARE_CLK_ID(CPU_SP_CORE1_CCU, CPU_PLLPMS, 0x00UL)
#define PLL_SP_DSU		DECLARE_CLK_ID(CPU_SP_DSU_CCU,   CPU_PLLPMS, 0x00UL)

#define PLL_CAM			DECLARE_CLK_ID(CAMERA_CKC, CAM_PLLPMS, 0x00UL)

#define PLL_NPU			DECLARE_CLK_ID(NPU_CKC, NPU_PLLPMS, 0x00UL)


/* Divider index */
#define PLL_0_DIV		DECLARE_CLK_ID(SMU_CKC,  SMU_CLKDIVC0, 0x3UL)
#define PLL_1_DIV		DECLARE_CLK_ID(SMU_CKC,  SMU_CLKDIVC0, 0x2UL)
#define PLL_2_DIV		DECLARE_CLK_ID(SMU_CKC,  SMU_CLKDIVC0, 0x1UL)
#define PLL_3_DIV		DECLARE_CLK_ID(SMU_CKC,  SMU_CLKDIVC0, 0x0UL)
#define PLL_4_DIV		DECLARE_CLK_ID(SMU_CKC,  SMU_CLKDIVC1, 0x3UL)
#define OSC_XIN_DIV		DECLARE_CLK_ID(SMU_CKC,  SMU_CLKDIVC1, 0x1UL)
#define OSC_XTIN_DIV		DECLARE_CLK_ID(SMU_CKC,  SMU_CLKDIVC1, 0x0UL)

#define PLL_GPU_DIV		DECLARE_CLK_ID(GPU_CKC, GPU_CLKDIVC, 0x00UL)
#define PLL_G2D_DIV		DECLARE_CLK_ID(G2D_CKC, GPU_CLKDIVC, 0x00UL)

#define PLL_MEM_0_DIV_0		DECLARE_CLK_ID(MEM_CKC, MEM_CLKDIVC, 0x0UL)
#define PLL_MEM_0_DIV_1		DECLARE_CLK_ID(MEM_CKC, MEM_CLKDIVC, 0x1UL)
#define PLL_MEM_1_DIV_0		DECLARE_CLK_ID(MEM_CKC, MEM_CLKDIVC, 0x2UL)
#define PLL_MEM_1_DIV_1		DECLARE_CLK_ID(MEM_CKC, MEM_CLKDIVC, 0x3UL)

#define PLL_DP_DIV_0		DECLARE_CLK_ID(DP_CKC,  DP_CLKDIVC, 0x0UL)
#define PLL_DP_DIV_1		DECLARE_CLK_ID(DP_CKC,  DP_CLKDIVC, 0x4UL)
#define PLL_DP_DIV_2		DECLARE_CLK_ID(DP_CKC,  DP_CLKDIVC, 0x8UL)

#define PLL_VIDEO_0_DIV_0	DECLARE_CLK_ID(VIDEO_CKC,  VIDEO_CLKDIVC, 0x0UL)
#define PLL_VIDEO_0_DIV_1	DECLARE_CLK_ID(VIDEO_CKC,  VIDEO_CLKDIVC, 0x1UL)
#define PLL_VIDEO_1_DIV_0	DECLARE_CLK_ID(VIDEO_CKC,  VIDEO_CLKDIVC, 0x2UL)
#define PLL_VIDEO_1_DIV_1	DECLARE_CLK_ID(VIDEO_CKC,  VIDEO_CLKDIVC, 0x3UL)

#define PLL_AUDIO_0_DIV		DECLARE_CLK_ID(AUDIO_CCU,  AUDIO_CLKDIVC, 0x3UL)
#define PLL_AUDIO_1_DIV		DECLARE_CLK_ID(AUDIO_CCU,  AUDIO_CLKDIVC, 0x2UL)
#define OSC_AUDIO_XIN_DIV	DECLARE_CLK_ID(AUDIO_CCU,  AUDIO_CLKDIVC, 0x1UL)

#define PLL_MP_CA55_0_DIV	DECLARE_CLK_ID(CPU_MP_CORE0_CCU, CPU_CLKDIVC, 0x0UL)
#define PLL_MP_CA55_1_DIV	DECLARE_CLK_ID(CPU_MP_CORE1_CCU, CPU_CLKDIVC, 0x0UL)
#define PLL_MP_CA55_2_DIV	DECLARE_CLK_ID(CPU_MP_CORE2_CCU, CPU_CLKDIVC, 0x0UL)
#define PLL_MP_CA55_3_DIV	DECLARE_CLK_ID(CPU_MP_CORE3_CCU, CPU_CLKDIVC, 0x0UL)
#define PLL_MP_CA76_0_DIV	DECLARE_CLK_ID(CPU_MP_CORE4_CCU, CPU_CLKDIVC, 0x0UL)
#define PLL_MP_CA76_1_DIV	DECLARE_CLK_ID(CPU_MP_CORE5_CCU, CPU_CLKDIVC, 0x0UL)
#define PLL_MP_CA76_2_DIV	DECLARE_CLK_ID(CPU_MP_CORE6_CCU, CPU_CLKDIVC, 0x0UL)
#define PLL_MP_CA76_3_DIV	DECLARE_CLK_ID(CPU_MP_CORE7_CCU, CPU_CLKDIVC, 0x0UL)
#define PLL_MP_DSU_DIV_0	DECLARE_CLK_ID(CPU_MP_DSU_CCU,   CPU_CLKDIVC, 0x0UL)
#define PLL_MP_DSU_DIV_1	DECLARE_CLK_ID(CPU_MP_DSU_CCU,   CPU_CLKDIVC, 0x1UL)

#define PLL_SP_CA55_0_DIV	DECLARE_CLK_ID(CPU_SP_CORE0_CCU, CPU_CLKDIVC, 0x0UL)
#define PLL_SP_CA55_1_DIV	DECLARE_CLK_ID(CPU_SP_CORE1_CCU, CPU_CLKDIVC, 0x0UL)
#define PLL_SP_DSU_DIV_0	DECLARE_CLK_ID(CPU_SP_DSU_CCU,   CPU_CLKDIVC, 0x0UL)
#define PLL_SP_DSU_DIV_1	DECLARE_CLK_ID(CPU_SP_DSU_CCU,   CPU_CLKDIVC, 0x1UL)

#define PLL_CAM_DIV_0		DECLARE_CLK_ID(CAMERA_CKC, CAM_CLKDIVC, 0x00UL)
#define PLL_CAM_DIV_1		DECLARE_CLK_ID(CAMERA_CKC, CAM_CLKDIVC, 0x04UL)
#define PLL_CAM_DIV_2		DECLARE_CLK_ID(CAMERA_CKC, CAM_CLKDIVC, 0x08UL)
#define PLL_CAM_DIV_3		DECLARE_CLK_ID(CAMERA_CKC, CAM_CLKDIVC, 0x0CUL)
#define PLL_CAM_DIV_4		DECLARE_CLK_ID(CAMERA_CKC, CAM_CLKDIVC, 0x14UL)

#define PLL_NPU_DIV		DECLARE_CLK_ID(NPU_CKC, NPU_CLKDIVC, 0x0UL)

/* CLKCTRL channel index */
#define FBUS_CPU		DECLARE_CLK_ID(SMU_CKC, SMU_CLKCTRL, 0x008UL)
#define FBUS_TAW		DECLARE_CLK_ID(SMU_CKC, SMU_CLKCTRL, 0x00CUL)
#define FBUS_HSIO		DECLARE_CLK_ID(SMU_CKC, SMU_CLKCTRL, 0x018UL)
#define FBUS_SMU		DECLARE_CLK_ID(SMU_CKC, SMU_CLKCTRL, 0x01CUL)
#define FBUS_DDI		DECLARE_CLK_ID(SMU_CKC, SMU_CLKCTRL, 0x024UL)
#define FBUS_IO			DECLARE_CLK_ID(SMU_CKC, SMU_CLKCTRL, 0x02CUL)
#define FBUS_HSM		DECLARE_CLK_ID(SMU_CKC, SMU_CLKCTRL, 0x040UL)
#define FBUS_PCIe0		DECLARE_CLK_ID(SMU_CKC, SMU_CLKCTRL, 0x044UL)
#define FBUS_PCIe1		DECLARE_CLK_ID(SMU_CKC, SMU_CLKCTRL, 0x048UL)

#define FBUS_GPU		DECLARE_CLK_ID(GPU_CKC, GPU_CLKCTRL, 0x0UL)
#define FBUS_G2D		DECLARE_CLK_ID(G2D_CKC, GPU_CLKCTRL, 0x0UL)

#define FBUS_MEM		DECLARE_CLK_ID(MEM_CKC, MEM_CLKCTRL, 0x000UL)
#define FBUS_MEM_SMMU		DECLARE_CLK_ID(MEM_CKC, MEM_CLKCTRL, 0x004UL)
#define FBUS_MEM_LPDDR		DECLARE_CLK_ID(MEM_CKC, MEM_CLKCTRL, 0x00CUL)

#define FBUS_DDI_AXI		DECLARE_CLK_ID(DP_CKC, DP_CLKCTRL, 0x0UL)
#define FBUS_DDI_AUX		DECLARE_CLK_ID(DP_CKC, DP_CLKCTRL, 0x4UL)
#define FBUS_DDI_APB		DECLARE_CLK_ID(DP_CKC, DP_CLKCTRL, 0x8UL)

#define FBUS_VBUS		DECLARE_CLK_ID(VIDEO_CKC, VIDEO_CLKCTRL, 0x0UL)
#define FBUS_CODA		DECLARE_CLK_ID(VIDEO_CKC, VIDEO_CLKCTRL, 0x4UL)
#define FBUS_CHEVCDEC		DECLARE_CLK_ID(VIDEO_CKC, VIDEO_CLKCTRL, 0x8UL)
#define FBUS_BHEVCDEC		DECLARE_CLK_ID(VIDEO_CKC, VIDEO_CLKCTRL, 0xCUL)
#define FBUS_CHEVCENC		DECLARE_CLK_ID(VIDEO_CKC, VIDEO_CLKCTRL, 0x34UL)
#define FBUS_BHEVCENC		DECLARE_CLK_ID(VIDEO_CKC, VIDEO_CLKCTRL, 0x38UL)

#define FBUS_AUDIO		DECLARE_CLK_ID(AUDIO_CCU, AUDIO_CLKCTRL, 0x0UL)

#define FBUS_MP_CA55_0		DECLARE_CLK_ID(CPU_MP_CORE0_CCU, CPU_CLKCTRL, 0x0UL)
#define FBUS_MP_CA55_1		DECLARE_CLK_ID(CPU_MP_CORE1_CCU, CPU_CLKCTRL, 0x0UL)
#define FBUS_MP_CA55_2		DECLARE_CLK_ID(CPU_MP_CORE2_CCU, CPU_CLKCTRL, 0x0UL)
#define FBUS_MP_CA55_3		DECLARE_CLK_ID(CPU_MP_CORE3_CCU, CPU_CLKCTRL, 0x0UL)
#define FBUS_MP_CA76_0		DECLARE_CLK_ID(CPU_MP_CORE4_CCU, CPU_CLKCTRL, 0x0UL)
#define FBUS_MP_CA76_1		DECLARE_CLK_ID(CPU_MP_CORE5_CCU, CPU_CLKCTRL, 0x0UL)
#define FBUS_MP_CA76_2		DECLARE_CLK_ID(CPU_MP_CORE6_CCU, CPU_CLKCTRL, 0x0UL)
#define FBUS_MP_CA76_3		DECLARE_CLK_ID(CPU_MP_CORE7_CCU, CPU_CLKCTRL, 0x0UL)
#define FBUS_MP_DSU		DECLARE_CLK_ID(CPU_MP_DSU_CCU,   CPU_CLKCTRL, 0x0UL)
#define FBUS_MP_DSU_PCLK	DECLARE_CLK_ID(CPU_MP_DSU_CCU,   CPU_CLKCTRL, 0x4UL)

#define FBUS_SP_CA55_0		DECLARE_CLK_ID(CPU_SP_CORE0_CCU, CPU_CLKCTRL, 0x0UL)
#define FBUS_SP_CA55_1		DECLARE_CLK_ID(CPU_SP_CORE1_CCU, CPU_CLKCTRL, 0x0UL)
#define FBUS_SP_DSU		DECLARE_CLK_ID(CPU_SP_DSU_CCU,   CPU_CLKCTRL, 0x0UL)
#define FBUS_SP_DSU_PCLK	DECLARE_CLK_ID(CPU_SP_DSU_CCU,   CPU_CLKCTRL, 0x4UL)

#define FBUS_CAM_APB		DECLARE_CLK_ID(CAMERA_CKC, CAM_CLKCTRL, 0x00UL)
#define FBUS_CAM_AXI		DECLARE_CLK_ID(CAMERA_CKC, CAM_CLKCTRL, 0x04UL)
#define FBUS_CAM_SYS		DECLARE_CLK_ID(CAMERA_CKC, CAM_CLKCTRL, 0x08UL)
#define FBUS_CAM_PIX		DECLARE_CLK_ID(CAMERA_CKC, CAM_CLKCTRL, 0x0CUL)
#define PERI_CAM_I2C		DECLARE_CLK_ID(CAMERA_CKC, CAM_CLKCTRL, 0x2CUL)

#define FBUS_NPU		DECLARE_CLK_ID(NPU_CKC, NPU_CLKCTRL, 0x0UL)


/* Peripheral Clocks */
/* PCLK***CTRL register : starts from 0x14000000 + 0x400*/
#define PERI_SMU_BASE_OFFSET    (SMU_PCLKCTRL + 0x000UL)
#define PERI_DDI_BASE_OFFSET    (SMU_PCLKCTRL + 0x100UL)
#define PERI_HSIO_BASE_OFFSET   (SMU_PCLKCTRL + 0x200UL)
#define PERI_IO_BASE_OFFSET     (SMU_PCLKCTRL + 0x300UL)
#define PERI_CPU_BASE_OFFSET    (SMU_PCLKCTRL + 0x500UL)
#define PERI_EXT_BASE_OFFSET    (SMU_PCLKCTRL + 0x600UL)
#define PERI_SSS_BASE_OFFSET    (SMU_PCLKCTRL + 0x700UL)

/* SMU Peri. */
#define PERI_TCT		DECLARE_CLK_ID(SMU_CKC, PERI_SMU_BASE_OFFSET, 0x004UL)
#define PERI_TCZ		DECLARE_CLK_ID(SMU_CKC, PERI_SMU_BASE_OFFSET, 0x008UL)

/* DDIB Peri. */
#define PERI_LCDTIMER		DECLARE_CLK_ID(SMU_CKC, PERI_DDI_BASE_OFFSET, 0x000UL)
#define PERI_LCD0		DECLARE_CLK_ID(SMU_CKC, PERI_DDI_BASE_OFFSET, 0x004UL)
#define PERI_LCD1		DECLARE_CLK_ID(SMU_CKC, PERI_DDI_BASE_OFFSET, 0x008UL)
#define PERI_LCD2		DECLARE_CLK_ID(SMU_CKC, PERI_DDI_BASE_OFFSET, 0x00CUL)
#define PERI_LCD3		DECLARE_CLK_ID(SMU_CKC, PERI_DDI_BASE_OFFSET, 0x010UL)
#define PERI_LCD4		DECLARE_CLK_ID(SMU_CKC, PERI_DDI_BASE_OFFSET, 0x014UL)

/* HSB Peri. */
#define PERI_GMAC		DECLARE_CLK_ID(SMU_CKC, PERI_HSIO_BASE_OFFSET, 0x000UL)
#define PERI_GMAC_PTP		DECLARE_CLK_ID(SMU_CKC, PERI_HSIO_BASE_OFFSET, 0x004UL)
#define PERI_PCIE0_PHY_CR_CLK	DECLARE_CLK_ID(SMU_CKC, PERI_HSIO_BASE_OFFSET, 0x010UL)
#define PERI_PCIE1_PHY_CR_CLK	DECLARE_CLK_ID(SMU_CKC, PERI_HSIO_BASE_OFFSET, 0x01CUL)

/* IOB Peri. */
#define PERI_RMT		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x000UL)
#define PERI_RESERVE01		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x004UL)
#define PERI_SDMMC1		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x008UL)
#define PERI_SDMMC2		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x00CUL)
#define PERI_CAN0		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x010UL)
#define PERI_CAN1		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x014UL)
#define PERI_CAN2		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x018UL)
#define PERI_CAN3		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x01CUL)
#define PERI_CAN4		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x020UL)
#define PERI_CAN5		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x024UL)
#define PERI_CAN6		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x028UL)
#define PERI_PDM		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x02CUL)
#define PERI_CAN7		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x030UL)
#define PERI_CAN8		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x034UL)
#define PERI_I2C0		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x038UL)
#define PERI_I2C1		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x03CUL)
#define PERI_I2C2		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x040UL)
#define PERI_I2C3		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x044UL)
#define PERI_UART0		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x048UL)
#define PERI_UART1		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x04CUL)
#define PERI_UART2		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x050UL)
#define PERI_UART3		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x054UL)
#define PERI_CAN9		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x058UL)
#define PERI_CAN10		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x05CUL)
#define PERI_CAN11		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x060UL)
#define PERI_TS_RX0		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x064UL)
#define PERI_GPSB0		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x068UL)
#define PERI_GPSB1		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x06CUL)
#define PERI_GPSB2		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x070UL)
#define PERI_GPSB3		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x074UL)
#define PERI_GPSB4		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x078UL)
#define PERI_GPSB5		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x07CUL)
#define PERI_UART4		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x080UL)
#define PERI_TS_RX1		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x084UL)
#define PERI_ADC		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x088UL)
#define PERI_RESERVE35		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x08CUL)
#define PERI_RESERVE36		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x090UL)
#define PERI_RESERVE37		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x094UL)
#define PERI_RESERVE38		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x098UL)
#define PERI_RESERVE39		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x09CUL)
#define PERI_IC_TC		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x0A0UL)
#define PERI_RESERVE41		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x0A4UL)
#define PERI_RESERVE42		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x0A8UL)
#define PERI_RESERVE43		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x0ACUL)
#define PERI_RESERVE44		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x0B0UL)
#define PERI_RESERVE45		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x0B4UL)
#define PERI_RESERVE46		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x0B8UL)
#define PERI_RESERVE47		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x0BCUL)
#define PERI_RESERVE48		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x0C0UL)
#define PERI_RESERVE49		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x0C4UL)
#define PERI_UART5		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x0C8UL)
#define PERI_UART6		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x0CCUL)
#define PERI_UART7		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x0D0UL)
#define PERI_UART8		DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x0D4UL)

/* CB Peri. */
#define PERI_CB_WDT		DECLARE_CLK_ID(SMU_CKC, PERI_CPU_BASE_OFFSET, 0x000UL)

/* External Peri. */
#define PERI_OUT0		DECLARE_CLK_ID(SMU_CKC, PERI_EXT_BASE_OFFSET, 0x000UL)
#define PERI_OUT1		DECLARE_CLK_ID(SMU_CKC, PERI_EXT_BASE_OFFSET, 0x004UL)
#define PERI_OUT2		DECLARE_CLK_ID(SMU_CKC, PERI_EXT_BASE_OFFSET, 0x008UL)
#define PERI_OUT3		DECLARE_CLK_ID(SMU_CKC, PERI_EXT_BASE_OFFSET, 0x00CUL)
#define PERI_OUT4		DECLARE_CLK_ID(SMU_CKC, PERI_EXT_BASE_OFFSET, 0x010UL)
#define PERI_OUT5		DECLARE_CLK_ID(SMU_CKC, PERI_EXT_BASE_OFFSET, 0x014UL)

/* HSMB Peri. */
#define PERI_HSMB		DECLARE_CLK_ID(SMU_CKC, PERI_SSS_BASE_OFFSET, 0x000UL)


/* Audio Sub-System Peri */
/* PCLK_CFG_xxx register : starts from 0x19600000 + 0x38*/

#define PERI_AUDIO_MAIC0_DAIF	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x000UL)
#define PERI_AUDIO_MAIC0_FILTER	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x004UL)
#define PERI_AUDIO_MAIC0_SPDIF	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x008UL)
#define PERI_AUDIO_MAIC1_DAIF	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x00CUL)
#define PERI_AUDIO_MAIC1_FILTER	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x010UL)
#define PERI_AUDIO_MAIC1_SPDIF	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x014UL)
#define PERI_AUDIO_MAIC2_DAIF	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x018UL)
#define PERI_AUDIO_MAIC2_FILTER	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x01CUL)
#define PERI_AUDIO_MAIC2_SPDIF	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x020UL)
#define PERI_AUDIO_MAIC3_DAIF	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x024UL)
#define PERI_AUDIO_MAIC3_FILTER	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x028UL)
#define PERI_AUDIO_MAIC3_SPDIF	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x02CUL)
#define PERI_AUDIO_MAIC4_DAIF	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x030UL)
#define PERI_AUDIO_MAIC4_FILTER	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x034UL)
#define PERI_AUDIO_MAIC4_SPDIF	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x038UL)
#define PERI_AUDIO_MAIC5_DAIF	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x03CUL)
#define PERI_AUDIO_MAIC5_FILTER	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x040UL)
#define PERI_AUDIO_MAIC5_SPDIF	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x044UL)
#define PERI_AUDIO_MAIC6_DAIF	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x048UL)
#define PERI_AUDIO_MAIC6_FILTER	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x04CUL)
#define PERI_AUDIO_MAIC6_SPDIF	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x050UL)
#define PERI_AUDIO_MAIC7_DAIF	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x054UL)
#define PERI_AUDIO_MAIC7_FILTER	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x058UL)
#define PERI_AUDIO_MAIC7_SPDIF	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x05CUL)
#define PERI_AUDIO_MASRC_AUX0	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x060UL)
#define PERI_AUDIO_MASRC_AUX1	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x064UL)
#define PERI_AUDIO_MASRC_AUX2	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x068UL)
#define PERI_AUDIO_MASRC_AUX3	DECLARE_CLK_ID(AUDIO_CCU, AUDIO_PCLKCTRL, 0x06CUL)



/* Use this macro to find register address for each SWRESET & CLKEN ID */
#define CKC_SWRST_CLKEN_ID(A)	((A)/32UL)

/* CLKEN / SWRESET */
#define SMUBUS_START		0UL
#define SMUBUS_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(SMUBUS_START)
#define SMUBUS_CPU_MP		SMUBUS_START
#define SMUBUS_CPU_SP		(SMUBUS_START + 1UL)
#define SMUBUS_CPU_SUB		(SMUBUS_START + 2UL)
#define SMUBUS_RESERVE3		(SMUBUS_START + 3UL)
#define SMUBUS_RESERVE4		(SMUBUS_START + 4UL)
#define	SMUBUS_VPU		(SMUBUS_START + 5UL)
#define SMUBUS_HSIO		(SMUBUS_START + 6UL)
#define SMUBUS_RESERVE7		(SMUBUS_START + 7UL)
#define SMUBUS_3D		(SMUBUS_START + 8UL)
#define SMUBUS_DDI		(SMUBUS_START + 9UL)
#define SMUBUS_2D		(SMUBUS_START + 10UL)
#define SMUBUS_IO		(SMUBUS_START + 11UL)
#define SMUBUS_RESERVE12	(SMUBUS_START + 12UL)
#define SMUBUS_RESERVE13	(SMUBUS_START + 13UL)
#define SMUBUS_RESERVE14	(SMUBUS_START + 14UL)
#define SMUBUS_RESERVE15	(SMUBUS_START + 15UL)
#define SMUBUS_RESERVE16	(SMUBUS_START + 16UL)
#define SMUBUS_PCIe		(SMUBUS_START + 17UL)
#define SMUBUS_RESERVE18	(SMUBUS_START + 18UL)
#define SMUBUS_RESERVE19	(SMUBUS_START + 19UL)
#define SMUBUS_RESERVE20	(SMUBUS_START + 20UL)
#define SMUBUS_RESERVE21	(SMUBUS_START + 21UL)
#define SMUBUS_RESERVE22	(SMUBUS_START + 22UL)
#define SMUBUS_USB30		(SMUBUS_START + 23UL)
#define SMUBUS_RESERVE24	(SMUBUS_START + 24UL)
#define SMUBUS_AUDIO		(SMUBUS_START + 25UL)
#define SMUBUS_NPU		(SMUBUS_START + 26UL)
#define SMUBUS_RTC		(SMUBUS_START + 27UL)
#define SMUBUS_RESERVE28	(SMUBUS_START + 28UL)
#define SMUBUS_RESERVE29	(SMUBUS_START + 29UL)
#define SMUBUS_RESERVE30	(SMUBUS_START + 30UL)
#define SMUBUS_RESERVE31	(SMUBUS_START + 31UL)
#define SMUBUS_END		(SMUBUS_START + 31UL)





#define CPUMP_START		(SMUBUS_END + 1UL)
#define CPUMP_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(CPUMP_START)
#define CPUMP_X2X		CPUMP_START
#define CPUMP_H2H		(CPUMP_START + 1UL)
#define CPUMP_APBIF		(CPUMP_START + 2UL)
#define CPUMP_CFGR		(CPUMP_START + 3UL)
#define CPUMP_RESERVE4		(CPUMP_START + 4UL)
#define CPUMP_DSU		(CPUMP_START + 5UL)
#define CPUMP_CA55CKC		(CPUMP_START + 6UL)
#define CPUMP_CA76CKC		(CPUMP_START + 7UL)
#define CPUMP_APBDBG		(CPUMP_START + 8UL)
#define CPUMP_GIGPPI		(CPUMP_START + 9UL)
#define CPUMP_CORE0RST		(CPUMP_START + 10UL)
#define CPUMP_CORE1RST		(CPUMP_START + 11UL)
#define CPUMP_CORE4RST		(CPUMP_START + 12UL)
#define CPUMP_CORE5RST		(CPUMP_START + 13UL)
#define CPUMP_CORE6RST		(CPUMP_START + 14UL)
#define CPUMP_CORE7RST		(CPUMP_START + 15UL)
#define CPUMP_CPUPOR0		(CPUMP_START + 16UL)
#define CPUMP_CPUPOR1		(CPUMP_START + 17UL)
#define CPUMP_CPUPOR4		(CPUMP_START + 18UL)
#define CPUMP_CPUPOR5		(CPUMP_START + 19UL)
#define CPUMP_CPUPOR6		(CPUMP_START + 20UL)
#define CPUMP_CPUPOR7		(CPUMP_START + 21UL)
#define CPUMP_DBG		(CPUMP_START + 22UL)
#define CPUMP_ATB		(CPUMP_START + 23UL)
#define CPUMP_PERIPH		(CPUMP_START + 24UL)
#define CPUMP_GICP		(CPUMP_START + 25UL)
#define CPUMP_SPOR		(CPUMP_START + 26UL)
#define CPUMP_SRESET		(CPUMP_START + 27UL)
#define CPUMP_CORE2RST		(CPUMP_START + 28UL)
#define CPUMP_CORE3RST		(CPUMP_START + 29UL)
#define CPUMP_CPUPOR2		(CPUMP_START + 30UL)
#define CPUMP_CPUPOR3		(CPUMP_START + 31UL)
#define CPUMP_END		(CPUMP_START + 31UL)






#define CPUSP_START		(CPUMP_END + 1UL)
#define CPUSP_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(CPUSP_START)
#define CPUSP_X2X		CPUSP_START
#define CPUSP_H2H		(CPUSP_START + 1UL)
#define CPUSP_APBIF		(CPUSP_START + 2UL)
#define CPUSP_CFGR		(CPUSP_START + 3UL)
#define CPUSP_RESERVE4		(CPUSP_START + 4UL)
#define CPUSP_DSU		(CPUSP_START + 5UL)
#define CPUSP_CORE0CKC		(CPUSP_START + 6UL)
#define CPUSP_CORE1CKC		(CPUSP_START + 7UL)
#define CPUSP_APBDBG		(CPUSP_START + 8UL)
#define CPUSP_GIGPPI		(CPUSP_START + 9UL)
#define CPUSP_CORE0RST		(CPUSP_START + 10UL)
#define CPUSP_CORE1RST		(CPUSP_START + 11UL)
#define CPUSP_RESERVE12		(CPUSP_START + 12UL)
#define CPUSP_RESERVE13		(CPUSP_START + 13UL)
#define CPUSP_RESERVE14		(CPUSP_START + 14UL)
#define CPUSP_RESERVE15		(CPUSP_START + 15UL)
#define CPUSP_CPUPOR0		(CPUSP_START + 16UL)
#define CPUSP_CPUPOR1		(CPUSP_START + 17UL)
#define CPUSP_RESERVE18		(CPUSP_START + 18UL)
#define CPUSP_RESERVE19		(CPUSP_START + 19UL)
#define CPUSP_RESERVE20		(CPUSP_START + 20UL)
#define CPUSP_RESERVE21		(CPUSP_START + 21UL)
#define CPUSP_DBG		(CPUSP_START + 22UL)
#define CPUSP_ATB		(CPUSP_START + 23UL)
#define CPUSP_PERIPH		(CPUSP_START + 24UL)
#define CPUSP_GICP		(CPUSP_START + 25UL)
#define CPUSP_SPOR		(CPUSP_START + 26UL)
#define CPUSP_SRESET		(CPUSP_START + 27UL)
#define CPUSP_FUNNEL		(CPUSP_START + 28UL)
#define CPUSP_RESERVE29		(CPUSP_START + 29UL)
#define CPUSP_RESERVE30		(CPUSP_START + 30UL)
#define CPUSP_RESERVE31		(CPUSP_START + 31UL)
#define CPUSP_END		(CPUSP_START + 31UL)






#define CPUBUS_START		(CPUSP_END + 1UL)
#define CPUBUS_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(CPUBUS_START)
#define CPUBUS_WDT0		CPUBUS_START
#define CPUBUS_WDT1		(CPUBUS_START + 1UL)
#define CPUBUS_WDT2		(CPUBUS_START + 2UL)
#define CPUBUS_WDT3		(CPUBUS_START + 3UL)
#define CPUBUS_WDT4		(CPUBUS_START + 4UL)
#define CPUBUS_WDT8		(CPUBUS_START + 5UL)
#define CPUBUS_CBUSCFG		(CPUBUS_START + 6UL)
#define CPUBUS_MB2DAP		(CPUBUS_START + 7UL)
#define CPUBUS_DAP		(CPUBUS_START + 8UL)
#define CPUBUS_DAPCFG		(CPUBUS_START + 9UL)
#define CPUBUS_DAP2MB		(CPUBUS_START + 10UL)
#define CPUBUS_MB2CB		(CPUBUS_START + 11UL)
#define CPUBUS_AHBMUX		(CPUBUS_START + 12UL)
#define CPUBUS_APBIF		(CPUBUS_START + 13UL)
#define CPUBUS_MPH2H		(CPUBUS_START + 14UL)
#define CPUBUS_MP		(CPUBUS_START + 15UL)
#define CPUBUS_SPH2H		(CPUBUS_START + 16UL)
#define CPUBUS_SP		(CPUBUS_START + 17UL)
#define CPUBUS_WDT9		(CPUBUS_START + 18UL)
#define CPUBUS_GIC0		(CPUBUS_START + 19UL)
#define CPUBUS_MBOX		(CPUBUS_START + 20UL)
#define CPUBUS_RESERVE21	(CPUBUS_START + 21UL)
#define CPUBUS_WDT5		(CPUBUS_START + 22UL)
#define CPUBUS_WDT6		(CPUBUS_START + 23UL)
#define CPUBUS_WDT7		(CPUBUS_START + 24UL)
#define CPUBUS_RESERVE25	(CPUBUS_START + 25UL)
#define CPUBUS_SJTAG		(CPUBUS_START + 26UL)
#define CPUBUS_HSSTP		(CPUBUS_START + 27UL)
#define CPUBUS_GIC1		(CPUBUS_START + 28UL)
#define CPUBUS_MPPOR		(CPUBUS_START + 29UL)
#define CPUBUS_SPPOR		(CPUBUS_START + 30UL)
#define CPUBUS_CBP		(CPUBUS_START + 31UL)
#define CPUBUS_END		(CPUBUS_START + 31UL)





/* IOBUS has 4 register for swreset & clken. (HCLKEN0-2 + HCLKEN_STR) */
#define IOBUS0_START		(CPUBUS_END + 1UL)
#define IOBUS0_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(IOBUS0_START)
#define IOBUS_IC_TC		IOBUS0_START
#define IOBUS_CAN_DMA		(IOBUS0_START + 1UL)   // When can DMA is in used, should be set 1
#define IOBUS_GPSB3		(IOBUS0_START + 2UL)
#define IOBUS_CAN_DMA_4		(IOBUS0_START + 3UL)
#define IOBUS_CAN_DMA_3		(IOBUS0_START + 4UL)
#define IOBUS_CAN_DMA_2		(IOBUS0_START + 5UL)
#define IOBUS_CAN_DMA_1		(IOBUS0_START + 6UL)
#define IOBUS_DMA_G0		(IOBUS0_START + 7UL)
#define IOBUS_DMA_G1		(IOBUS0_START + 8UL)
#define IOBUS_DMA_G2		(IOBUS0_START + 9UL)
#define IOBUS_DMA		(IOBUS0_START + 10UL)	// When DMA is in used, should be set 1
#define IOBUS_CAN_DMA_0		(IOBUS0_START + 11UL)
#define IOBUS_PDM		(IOBUS0_START + 12UL)
#define IOBUS_CAN_CFG		(IOBUS0_START + 13UL)
#define IOBUS_I2C_S2		(IOBUS0_START + 14UL)
#define IOBUS_CAN_11		(IOBUS0_START + 15UL)
#define IOBUS_CAN_10		(IOBUS0_START + 16UL)
#define IOBUS_CAN_9		(IOBUS0_START + 17UL)
#define IOBUS_CAN_8		(IOBUS0_START + 18UL)
#define IOBUS_CAN_7		(IOBUS0_START + 19UL)
#define IOBUS_PRT		(IOBUS0_START + 20UL)
#define IOBUS_CAN_6		(IOBUS0_START + 21UL)
#define IOBUS_CAN_5		(IOBUS0_START + 22UL)
#define IOBUS_CAN_4		(IOBUS0_START + 23UL)
#define IOBUS_CAN_3		(IOBUS0_START + 24UL)
#define IOBUS_CAN_2		(IOBUS0_START + 25UL)
#define IOBUS_CAN_1		(IOBUS0_START + 26UL)
#define IOBUS_CAN_0		(IOBUS0_START + 27UL)
#define IOBUS_CAN		(IOBUS0_START + 28UL)	// When can is in used should be set 1
#define IOBUS_I2C_M0		(IOBUS0_START + 29UL)
#define IOBUS_I2C_M1		(IOBUS0_START + 30UL)
#define IOBUS_I2C_M2		(IOBUS0_START + 31UL)
#define IOBUS0_END		(IOBUS0_START + 31UL)






#define IOBUS1_START		(IOBUS0_END + 1UL)
#define IOBUS1_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(IOBUS1_START)
#define IOBUS_I2C_M3		IOBUS1_START
#define IOBUS_I2C_S0		(IOBUS1_START + 1UL)
#define IOBUS_I2C_S1		(IOBUS1_START + 2UL)
#define IOBUS_I2C_G0		(IOBUS1_START + 3UL)	// When I2C is in used,
#define IOBUS_I2C_G1		(IOBUS1_START + 4UL)	// I2C0 & I2C1 should be set 1
#define IOBUS1_RESERVE5		(IOBUS1_START + 5UL)
#define IOBUS1_RESERVE6		(IOBUS1_START + 6UL)
#define IOBUS1_RESERVE7		(IOBUS1_START + 7UL)
#define IOBUS1_RESERVE8		(IOBUS1_START + 8UL)
#define IOBUS1_RESERVE9		(IOBUS1_START + 9UL)
#define IOBUS1_RESERVE10	(IOBUS1_START + 10UL)
#define IOBUS1_RESERVE11	(IOBUS1_START + 11UL)
#define IOBUS1_RESERVE12	(IOBUS1_START + 12UL)
#define IOBUS1_RESERVE13	(IOBUS1_START + 13UL)
#define IOBUS1_RESERVE14	(IOBUS1_START + 14UL)
#define IOBUS_TSIF_1		(IOBUS1_START + 15UL)
#define IOBUS_CAN_DMA_5		(IOBUS1_START + 16UL)
#define IOBUS_GPSB_G0		(IOBUS1_START + 17UL)	// When GPSB is in used should be set 1
#define IOBUS_ADC		(IOBUS1_START + 18UL)
#define IOBUS_GPSB0		(IOBUS1_START + 19UL)
#define IOBUS_GPSB1		(IOBUS1_START + 20UL)
#define IOBUS_GPSB2		(IOBUS1_START + 21UL)
#define IOBUS_GPSB4		(IOBUS1_START + 22UL)
#define IOBUS_GPSB5		(IOBUS1_START + 23UL)
#define IOBUS1_RESERVE24	(IOBUS1_START + 24UL)
#define IOBUS_GPSB_G1		(IOBUS1_START + 25UL)	// When GPSB is in used should be set 1
#define IOBUS_TSIF_0		(IOBUS1_START + 26UL)
#define IOBUS_I2C_S3		(IOBUS1_START + 27UL)
#define IOBUS_I2C_M4		(IOBUS1_START + 28UL)
#define IOBUS_I2C_M5		(IOBUS1_START + 29UL)
#define IOBUS_I2C_M6		(IOBUS1_START + 30UL)
#define IOBUS_I2C_M7		(IOBUS1_START + 31UL)
#define IOBUS1_END		(IOBUS1_START + 31UL)






#define IOBUS2_START		(IOBUS1_END + 1UL)
#define IOBUS2_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(IOBUS2_START)
#define IOBUS_UART0		IOBUS2_START
#define IOBUS_UART1		(IOBUS2_START + 1UL)
#define IOBUS_UART2		(IOBUS2_START + 2UL)
#define IOBUS_UART3		(IOBUS2_START + 3UL)
#define IOBUS_UART4		(IOBUS2_START + 4UL)
#define IOBUS_UART5		(IOBUS2_START + 5UL)
#define IOBUS_UART6		(IOBUS2_START + 6UL)
#define IOBUS_UART7		(IOBUS2_START + 7UL)
#define IOBUS_UART8		(IOBUS2_START + 8UL)
#define IOBUS2_RESERVE9		(IOBUS2_START + 9UL)
#define IOBUS2_RESERVE10	(IOBUS2_START + 10UL)
#define IOBUS2_RESERVE11	(IOBUS2_START + 11UL)
#define IOBUS2_RESERVE12	(IOBUS2_START + 12UL)
#define IOBUS2_RESERVE13	(IOBUS2_START + 13UL)
#define IOBUS2_RESERVE14	(IOBUS2_START + 14UL)
#define IOBUS2_RESERVE15	(IOBUS2_START + 15UL)
#define IOBUS_UDMA0		(IOBUS2_START + 16UL)
#define IOBUS_UDMA1		(IOBUS2_START + 17UL)
#define IOBUS_UDMA2		(IOBUS2_START + 18UL)
#define IOBUS_UDMA3		(IOBUS2_START + 19UL)
#define IOBUS_UART_G0		(IOBUS2_START + 20UL)	// When UART is used, should be set 1
#define IOBUS_UART_G1		(IOBUS2_START + 21UL)	// When UART is used, should be set 1
#define IOBUS_UDMA4		(IOBUS2_START + 22UL)
#define IOBUS_UDMA5		(IOBUS2_START + 23UL)
#define IOBUS_UDMA6		(IOBUS2_START + 24UL)
#define IOBUS_UDMA7		(IOBUS2_START + 25UL)	// When GPSB is in used should be set 1
#define IOBUS_UDMA8		(IOBUS2_START + 26UL)
#define IOBUS2_RESERVE27	(IOBUS2_START + 27UL)
#define IOBUS2_RESERVE28	(IOBUS2_START + 28UL)
#define IOBUS2_RESERVE29	(IOBUS2_START + 29UL)
#define IOBUS2_RESERVE30	(IOBUS2_START + 30UL)
#define IOBUS2_RESERVE31	(IOBUS2_START + 31UL)
#define IOBUS2_END		(IOBUS2_START + 31UL)






#define IOBUS_STRG_START	(IOBUS2_END + 1UL)
#define IOBUS_STRG_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(IOBUS_STRG_START)
#define IOBUS_DMA_G3		IOBUS_STRG_START
#define IOBUS_STRG_RESERVE1	(IOBUS_STRG_START + 1UL)
#define IOBUS_STRG_RESERVE2	(IOBUS_STRG_START + 2UL)
#define IOBUS_SDMMC1		(IOBUS_STRG_START + 3UL)
#define IOBUS_SDMMC2		(IOBUS_STRG_START + 4UL)
#define IOBUS_SDMMC		(IOBUS_STRG_START + 5UL)// When SDMMC is used, should be set 1
#define IOBUS_STRG_RESERVE6	(IOBUS_STRG_START + 6UL)
#define IOBUS_STRG_RESERVE7	(IOBUS_STRG_START + 7UL)
#define IOBUS_STRG_RESERVE8	(IOBUS_STRG_START + 8UL)
#define IOBUS_STRG_RESERVE9	(IOBUS_STRG_START + 9UL)
#define IOBUS_RTC		(IOBUS_STRG_START + 10UL)
#define IOBUS_STRG_RESERVE11	(IOBUS_STRG_START + 11UL)
#define IOBUS_STRG_RESERVE12	(IOBUS_STRG_START + 12UL)
#define IOBUS_STRG_RESERVE13	(IOBUS_STRG_START + 13UL)
#define IOBUS_STRG_RESERVE14	(IOBUS_STRG_START + 14UL)
#define IOBUS_STRG_RESERVE15	(IOBUS_STRG_START + 15UL)
#define IOBUS_STRG_RESERVE16	(IOBUS_STRG_START + 16UL)
#define IOBUS_STRG_RESERVE17	(IOBUS_STRG_START + 17UL)
#define IOBUS_STRG_RESERVE18	(IOBUS_STRG_START + 18UL)
#define IOBUS_STRG_RESERVE19	(IOBUS_STRG_START + 19UL)
#define IOBUS_STRG_RESERVE20	(IOBUS_STRG_START + 20UL)
#define IOBUS_STRG_RESERVE21	(IOBUS_STRG_START + 21UL)
#define IOBUS_STRG_RESERVE22	(IOBUS_STRG_START + 22UL)
#define IOBUS_STRG_RESERVE23	(IOBUS_STRG_START + 23UL)
#define IOBUS_STRG_RESERVE24	(IOBUS_STRG_START + 24UL)
#define IOBUS_STRG_RESERVE25	(IOBUS_STRG_START + 25UL)
#define IOBUS_STRG_RESERVE26	(IOBUS_STRG_START + 26UL)
#define IOBUS_STRG_RESERVE27	(IOBUS_STRG_START + 27UL)
#define IOBUS_STRG_RESERVE28	(IOBUS_STRG_START + 28UL)
#define IOBUS_STRG_RESERVE29	(IOBUS_STRG_START + 29UL)
#define IOBUS_STRG_RESERVE30	(IOBUS_STRG_START + 30UL)
#define IOBUS_STRG_RESERVE31	(IOBUS_STRG_START + 31UL)
#define IOBUS_STRG_END		(IOBUS_STRG_START + 31UL)






#define DDIBUS_START		(IOBUS_STRG_END + 1UL)
#define DDIBUS_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(DDIBUS_START)
#define DDIBUS_VIOC		DDIBUS_START
#define DDIBUS_RESERVE1		(DDIBUS_START + 1UL)
#define DDIBUS_RESERVE2		(DDIBUS_START + 2UL)
#define DDIBUS_RESERVE3		(DDIBUS_START + 3UL)
#define DDIBUS_RESERVE4		(DDIBUS_START + 4UL)
#define DDIBUS_RESERVE5		(DDIBUS_START + 5UL)
#define DDIBUS_RESERVE6		(DDIBUS_START + 6UL)
#define DDIBUS_RESERVE7		(DDIBUS_START + 7UL)
#define DDIBUS_RESERVE8		(DDIBUS_START + 8UL)
#define DDIBUS_RESERVE9		(DDIBUS_START + 9UL)
#define DDIBUS_RESERVE10	(DDIBUS_START + 10UL)
#define DDIBUS_RESERVE11	(DDIBUS_START + 11UL)
#define DDIBUS_RESERVE12	(DDIBUS_START + 12UL)
#define DDIBUS_RESERVE13	(DDIBUS_START + 13UL)
#define DDIBUS_RESERVE14	(DDIBUS_START + 14UL)
#define DDIBUS_RESERVE15	(DDIBUS_START + 15UL)
#define DDIBUS_RESERVE16	(DDIBUS_START + 16UL)
#define DDIBUS_RESERVE17	(DDIBUS_START + 17UL)
#define DDIBUS_RESERVE18	(DDIBUS_START + 18UL)
#define DDIBUS_RESERVE19	(DDIBUS_START + 19UL)
#define DDIBUS_RESERVE20	(DDIBUS_START + 20UL)
#define DDIBUS_RESERVE21	(DDIBUS_START + 21UL)
#define DDIBUS_RESERVE22	(DDIBUS_START + 22UL)
#define DDIBUS_RESERVE23	(DDIBUS_START + 23UL)
#define DDIBUS_RESERVE24	(DDIBUS_START + 24UL)
#define DDIBUS_RESERVE25	(DDIBUS_START + 25UL)
#define DDIBUS_RESERVE26	(DDIBUS_START + 26UL)
#define DDIBUS_RESERVE27	(DDIBUS_START + 27UL)
#define DDIBUS_RESERVE28	(DDIBUS_START + 28UL)
#define DDIBUS_RESERVE29	(DDIBUS_START + 29UL)
#define DDIBUS_RESERVE30	(DDIBUS_START + 30UL)
#define DDIBUS_RESERVE31	(DDIBUS_START + 31UL)
#define DDIBUS_END		(DDIBUS_START + 31UL)






#define VIDEOBUS_START		(DDIBUS_END + 1UL)
#define VIDEOBUS_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(VIDEOBUS_START)
#define VIDEOBUS_JPEG		VIDEOBUS_START
#define VIDEOBUS_CODA_BUS	(VIDEOBUS_START + 1UL)
#define VIDEOBUS_CODA_CORE	(VIDEOBUS_START + 2UL)
#define VIDEOBUS_HEVC_BUS	(VIDEOBUS_START + 3UL)
#define VIDEOBUS_HEVC_CORE	(VIDEOBUS_START + 4UL)
#define VIDEOBUS_HEVC_ENCODER0	(VIDEOBUS_START + 5UL)
#define VIDEOBUS_HEVC_ENCODER1	(VIDEOBUS_START + 6UL)
#define VIDEOBUS_RESERVE7	(VIDEOBUS_START + 7UL)
#define VIDEOBUS_RESERVE8	(VIDEOBUS_START + 8UL)
#define VIDEOBUS_RESERVE9	(VIDEOBUS_START + 9UL)
#define VIDEOBUS_RESERVE10	(VIDEOBUS_START + 10UL)
#define VIDEOBUS_RESERVE11	(VIDEOBUS_START + 11UL)
#define VIDEOBUS_RESERVE12	(VIDEOBUS_START + 12UL)
#define VIDEOBUS_RESERVE13	(VIDEOBUS_START + 13UL)
#define VIDEOBUS_RESERVE14	(VIDEOBUS_START + 14UL)
#define VIDEOBUS_RESERVE15	(VIDEOBUS_START + 15UL)
#define VIDEOBUS_RESERVE16	(VIDEOBUS_START + 16UL)
#define VIDEOBUS_RESERVE17	(VIDEOBUS_START + 17UL)
#define VIDEOBUS_RESERVE18	(VIDEOBUS_START + 18UL)
#define VIDEOBUS_RESERVE19	(VIDEOBUS_START + 19UL)
#define VIDEOBUS_RESERVE20	(VIDEOBUS_START + 20UL)
#define VIDEOBUS_RESERVE21	(VIDEOBUS_START + 21UL)
#define VIDEOBUS_RESERVE22	(VIDEOBUS_START + 22UL)
#define VIDEOBUS_RESERVE23	(VIDEOBUS_START + 23UL)
#define VIDEOBUS_RESERVE24	(VIDEOBUS_START + 24UL)
#define VIDEOBUS_RESERVE25	(VIDEOBUS_START + 25UL)
#define VIDEOBUS_RESERVE26	(VIDEOBUS_START + 26UL)
#define VIDEOBUS_RESERVE27	(VIDEOBUS_START + 27UL)
#define VIDEOBUS_RESERVE28	(VIDEOBUS_START + 28UL)
#define VIDEOBUS_RESERVE29	(VIDEOBUS_START + 29UL)
#define VIDEOBUS_RESERVE30	(VIDEOBUS_START + 30UL)
#define VIDEOBUS_RESERVE31	(VIDEOBUS_START + 31UL)
#define VIDEOBUS_END		(VIDEOBUS_START + 31UL)






#define HSIOBUS_START		(VIDEOBUS_END + 1UL)
#define HSIOBUS_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(HSIOBUS_START)
#define HSIOBUS_USB30		HSIOBUS_START
#define HSIOBUS_RESERVE1	(HSIOBUS_START + 1UL)
#define HSIOBUS_GMAC		(HSIOBUS_START + 2UL)
#define HSIOBUS_RESERVE3	(HSIOBUS_START + 3UL)
#define HSIOBUS_RESERVE4	(HSIOBUS_START + 4UL)
#define HSIOBUS_RESERVE5	(HSIOBUS_START + 5UL)
#define HSIOBUS_USB20H		(HSIOBUS_START + 6UL)
#define HSIOBUS_RESERVE7	(HSIOBUS_START + 7UL)
#define HSIOBUS_RESERVE8	(HSIOBUS_START + 8UL)
#define HSIOBUS_RESERVE9	(HSIOBUS_START + 9UL)
#define HSIOBUS_RESERVE10	(HSIOBUS_START + 10UL)
#define HSIOBUS_RESERVE11	(HSIOBUS_START + 11UL)
#define HSIOBUS_RESERVE12	(HSIOBUS_START + 12UL)
#define HSIOBUS_RESERVE13	(HSIOBUS_START + 13UL)
#define HSIOBUS_RESERVE14	(HSIOBUS_START + 14UL)
#define HSIOBUS_RESERVE15	(HSIOBUS_START + 15UL)
#define HSIOBUS_RESERVE16	(HSIOBUS_START + 16UL)
#define HSIOBUS_RESERVE17	(HSIOBUS_START + 17UL)
#define HSIOBUS_CIPHER		(HSIOBUS_START + 18UL)
#define HSIOBUS_DWC_OTG		(HSIOBUS_START + 19UL)
#define HSIOBUS_RESERVE20	(HSIOBUS_START + 20UL)
#define HSIOBUS_SECURE_WRAP	(HSIOBUS_START + 21UL)
#define HSIOBUS_TRNG		(HSIOBUS_START + 22UL)
#define HSIOBUS_RESERVE23	(HSIOBUS_START + 23UL)
#define HSIOBUS_RESERVE24	(HSIOBUS_START + 24UL)
#define HSIOBUS_RESERVE25	(HSIOBUS_START + 25UL)
#define HSIOBUS_RESERVE26	(HSIOBUS_START + 26UL)
#define HSIOBUS_RESERVE27	(HSIOBUS_START + 27UL)
#define HSIOBUS_RESERVE28	(HSIOBUS_START + 28UL)
#define HSIOBUS_RESERVE29	(HSIOBUS_START + 29UL)
#define HSIOBUS_RESERVE30	(HSIOBUS_START + 30UL)
#define HSIOBUS_RESERVE31	(HSIOBUS_START + 31UL)
#define HSIOBUS_END		(HSIOBUS_START + 31UL)






#define AUDIOBUS0_START		(HSIOBUS_END + 1UL)
#define AUDIOBUS0_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(AUDIOBUS0_START)
#define AUDIOBUS_MAIC0_DMA	AUDIOBUS0_START
#define AUDIOBUS_MAIC0_DAIF	(AUDIOBUS0_START + 1UL)
#define AUDIOBUS_MAIC0_SPDIF	(AUDIOBUS0_START + 2UL)
#define AUDIOBUS_MAIC1_DMA	(AUDIOBUS0_START + 3UL)
#define AUDIOBUS_MAIC1_DAIF	(AUDIOBUS0_START + 4UL)
#define AUDIOBUS_MAIC1_SPDIF	(AUDIOBUS0_START + 5UL)
#define AUDIOBUS_MAIC2_DMA	(AUDIOBUS0_START + 6UL)
#define AUDIOBUS_MAIC2_DAIF	(AUDIOBUS0_START + 7UL)
#define AUDIOBUS_MAIC2_SPDIF	(AUDIOBUS0_START + 8UL)
#define AUDIOBUS_MAIC3_DMA	(AUDIOBUS0_START + 9UL)
#define AUDIOBUS_MAIC3_DAIF	(AUDIOBUS0_START + 10UL)
#define AUDIOBUS_MAIC3_SPDIF	(AUDIOBUS0_START + 11UL)
#define AUDIOBUS_MAIC4_DMA	(AUDIOBUS0_START + 12UL)
#define AUDIOBUS_MAIC4_DAIF	(AUDIOBUS0_START + 13UL)
#define AUDIOBUS_MAIC4_SPDIF	(AUDIOBUS0_START + 14UL)
#define AUDIOBUS_MAIC5_DMA	(AUDIOBUS0_START + 15UL)
#define AUDIOBUS_MAIC5_DAIF	(AUDIOBUS0_START + 16UL)
#define AUDIOBUS_MAIC5_SPDIF	(AUDIOBUS0_START + 17UL)
#define AUDIOBUS_MAIC6_DMA	(AUDIOBUS0_START + 18UL)
#define AUDIOBUS_MAIC6_DAIF	(AUDIOBUS0_START + 19UL)
#define AUDIOBUS_MAIC6_SPDIF	(AUDIOBUS0_START + 20UL)
#define AUDIOBUS_MAIC7_DMA	(AUDIOBUS0_START + 21UL)
#define AUDIOBUS_MAIC7_DAIF	(AUDIOBUS0_START + 22UL)
#define AUDIOBUS_MAIC7_SPDIF	(AUDIOBUS0_START + 23UL)
#define AUDIOBUS_MAVC_0 	(AUDIOBUS0_START + 24UL)
#define AUDIOBUS_MAVC_1 	(AUDIOBUS0_START + 25UL)
#define AUDIOBUS_MAVC_2 	(AUDIOBUS0_START + 26UL)
#define AUDIOBUS_MAVC_3 	(AUDIOBUS0_START + 27UL)
#define AUDIOBUS_MAVC_4 	(AUDIOBUS0_START + 28UL)
#define AUDIOBUS_MAVC_5 	(AUDIOBUS0_START + 29UL)
#define AUDIOBUS_MAVC_6 	(AUDIOBUS0_START + 30UL)
#define AUDIOBUS_MAVC_7 	(AUDIOBUS0_START + 31UL)
#define AUDIOBUS0_END		(AUDIOBUS0_START + 31UL)






#define AUDIOBUS1_START		(AUDIOBUS0_END + 1UL)
#define AUDIOBUS1_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(AUDIOBUS1_START)
#define AUDIOBUS_MARS_0		AUDIOBUS1_START
#define AUDIOBUS_MARS_1		(AUDIOBUS1_START + 1UL)
#define AUDIOBUS_MARS_2		(AUDIOBUS1_START + 2UL)
#define AUDIOBUS_MARS_3		(AUDIOBUS1_START + 3UL)
#define AUDIOBUS_MARS_4		(AUDIOBUS1_START + 4UL)
#define AUDIOBUS_MARS_5		(AUDIOBUS1_START + 5UL)
#define AUDIOBUS_MASM_0		(AUDIOBUS1_START + 6UL)
#define AUDIOBUS_MASM_1		(AUDIOBUS1_START + 7UL)
#define AUDIOBUS_MASM_2		(AUDIOBUS1_START + 8UL)
#define AUDIOBUS_MASM_3		(AUDIOBUS1_START + 9UL)
#define AUDIOBUS_MASM_4		(AUDIOBUS1_START + 10UL)
#define AUDIOBUS_MASRC_0	(AUDIOBUS1_START + 11UL)
#define AUDIOBUS_MASRC_1	(AUDIOBUS1_START + 12UL)
#define AUDIOBUS_MASRC_2	(AUDIOBUS1_START + 13UL)
#define AUDIOBUS_MASRC_3	(AUDIOBUS1_START + 14UL)
#define AUDIOBUS_MASRC_4	(AUDIOBUS1_START + 15UL)
#define AUDIOBUS_MASRC_5	(AUDIOBUS1_START + 16UL)
#define AUDIOBUS_MAFC_0		(AUDIOBUS1_START + 17UL)
#define AUDIOBUS_MAFC_1		(AUDIOBUS1_START + 18UL)
#define AUDIOBUS_MAFC_2		(AUDIOBUS1_START + 19UL)
#define AUDIOBUS_MAFC_3		(AUDIOBUS1_START + 20UL)
#define AUDIOBUS_CFG		(AUDIOBUS1_START + 21UL)
#define AUDIOBUS_SRAM		(AUDIOBUS1_START + 22UL)
#define AUDIOBUS_RESERVE23	(AUDIOBUS1_START + 23UL)
#define AUDIOBUS_RESERVE24 	(AUDIOBUS1_START + 24UL)
#define AUDIOBUS_RESERVE25 	(AUDIOBUS1_START + 25UL)
#define AUDIOBUS_RESERVE26 	(AUDIOBUS1_START + 26UL)
#define AUDIOBUS_RESERVE27 	(AUDIOBUS1_START + 27UL)
#define AUDIOBUS_RESERVE28 	(AUDIOBUS1_START + 28UL)
#define AUDIOBUS_RESERVE29 	(AUDIOBUS1_START + 29UL)
#define AUDIOBUS_RESERVE30 	(AUDIOBUS1_START + 30UL)
#define AUDIOBUS_RESERVE31 	(AUDIOBUS1_START + 31UL)
#define AUDIOBUS1_END		(AUDIOBUS1_START + 31UL)





/* CAMERA BUS SWRESET */
#define CAMBUS0_SWRST_START		(AUDIOBUS1_END + 1UL)
#define CAMBUS0_SWRST_EN		CKC_SWRST_CLKEN_ID(CAMBUS0_SWRST_START)
#define CAMBUS_MIPI0_SWRST		CAMBUS0_SWRST_START
#define CAMBUS_MIPI0_PHY_M_SWRST	(CAMBUS0_SWRST_START + 1UL)
#define CAMBUS_MIPI0_PHY_S_SWRST	(CAMBUS0_SWRST_START + 2UL)
#define CAMBUS_MIPI0_PHY_APB_SWRST	(CAMBUS0_SWRST_START + 3UL)
#define CAMBUS_MIPI0_CSI_SWRST		(CAMBUS0_SWRST_START + 4UL)
#define CAMBUS_MIPI0_GDP_PIX_SWRST	(CAMBUS0_SWRST_START + 5UL)
#define CAMBUS_MIPI0_GDP_APB_SWRST	(CAMBUS0_SWRST_START + 6UL)
#define CAMBUS_MIPI0_DSI_SWRST		(CAMBUS0_SWRST_START + 7UL)
#define CAMBUS_MIPI1_SWRST		(CAMBUS0_SWRST_START + 8UL)
#define CAMBUS_MIPI1_PHY_M_SWRST	(CAMBUS0_SWRST_START + 9UL)
#define CAMBUS_MIPI1_PHY_S_SWRST	(CAMBUS0_SWRST_START + 10UL)
#define CAMBUS_MIPI1_PHY_APB_SWRST	(CAMBUS0_SWRST_START + 11UL)
#define CAMBUS_MIPI1_CSI_SWRST		(CAMBUS0_SWRST_START + 12UL)
#define CAMBUS_MIPI1_GDP_PIX_SWRST	(CAMBUS0_SWRST_START + 13UL)
#define CAMBUS_MIPI1_GDP_APB_SWRST	(CAMBUS0_SWRST_START + 14UL)
#define CAMBUS_MIPI1_DSI_SWRST		(CAMBUS0_SWRST_START + 15UL)
#define CAMBUS_ISP_BUS_SWRST		(CAMBUS0_SWRST_START + 16UL)
#define CAMBUS_ISP_RISCV_SWRST		(CAMBUS0_SWRST_START + 17UL)
#define CAMBUS_ISP_PIX_SWRST		(CAMBUS0_SWRST_START + 18UL)
#define CAMBUS0_RESERVE19_SWRST		(CAMBUS0_SWRST_START + 19UL)
#define CAMBUS0_RESERVE20_SWRST		(CAMBUS0_SWRST_START + 20UL)
#define CAMBUS0_RESERVE21_SWRST		(CAMBUS0_SWRST_START + 21UL)
#define CAMBUS0_RESERVE22_SWRST		(CAMBUS0_SWRST_START + 22UL)
#define CAMBUS0_RESERVE23_SWRST		(CAMBUS0_SWRST_START + 23UL)
#define CAMBUS_RISYNC0_APB_SWRST	(CAMBUS0_SWRST_START + 24UL)
#define CAMBUS_RISYNC0_CORE_SWRST	(CAMBUS0_SWRST_START + 25UL)
#define CAMBUS_RISYNC1_APB_SWRST	(CAMBUS0_SWRST_START + 26UL)
#define CAMBUS_RISYNC1_CORE_SWRST	(CAMBUS0_SWRST_START + 27UL)
#define CAMBUS0_RESERVE28_SWRST		(CAMBUS0_SWRST_START + 28UL)
#define CAMBUS0_RESERVE29_SWRST		(CAMBUS0_SWRST_START + 29UL)
#define CAMBUS0_RESERVE30_SWRST		(CAMBUS0_SWRST_START + 30UL)
#define CAMBUS0_RESERVE31_SWRST		(CAMBUS0_SWRST_START + 31UL)
#define CAMBUS0_SWRST_END		(CAMBUS0_SWRST_START + 31UL)






#define CAMBUS1_SWRST_START		(CAMBUS0_SWRST_END + 1UL)
#define CAMBUS1_SWRST_EN		CKC_SWRST_CLKEN_ID(CAMBUS1_SWRST_START)
#define CAMBUS_CIED0_SWRST		CAMBUS1_SWRST_START
#define CAMBUS_CIED1_SWRST		(CAMBUS1_SWRST_START + 1UL)
#define CAMBUS_CIED2_SWRST		(CAMBUS1_SWRST_START + 2UL)
#define CAMBUS_CIED3_SWRST		(CAMBUS1_SWRST_START + 3UL)
#define CAMBUS_CIED4_SWRST		(CAMBUS1_SWRST_START + 4UL)
#define CAMBUS_CIED5_SWRST		(CAMBUS1_SWRST_START + 5UL)
#define CAMBUS_CIED6_SWRST		(CAMBUS1_SWRST_START + 6UL)
#define CAMBUS_CIED7_SWRST		(CAMBUS1_SWRST_START + 7UL)
#define CAMBUS_CIED8_SWRST		(CAMBUS1_SWRST_START + 8UL)
#define CAMBUS_CIED9_SWRST		(CAMBUS1_SWRST_START + 9UL)
#define CAMBUS_SVM_SWRST		(CAMBUS1_SWRST_START + 10UL)
#define CAMBUS_VIN_SWRST		(CAMBUS1_SWRST_START + 11UL)
#define CAMBUS_DEWARP_SWRST		(CAMBUS1_SWRST_START + 12UL)
#define CAMBUS_XBAR_SWRST		(CAMBUS1_SWRST_START + 13UL)
#define CAMBUS1_RESERVE14_SWRST		(CAMBUS1_SWRST_START + 14UL)
#define CAMBUS1_RESERVE15_SWRST		(CAMBUS1_SWRST_START + 15UL)
#define CAMBUS1_RESERVE16_SWRST		(CAMBUS1_SWRST_START + 16UL)
#define CAMBUS1_RESERVE17_SWRST		(CAMBUS1_SWRST_START + 17UL)
#define CAMBUS1_RESERVE18_SWRST		(CAMBUS1_SWRST_START + 18UL)
#define CAMBUS1_RESERVE19_SWRST		(CAMBUS1_SWRST_START + 19UL)
#define CAMBUS1_RESERVE20_SWRST		(CAMBUS1_SWRST_START + 20UL)
#define CAMBUS1_RESERVE21_SWRST		(CAMBUS1_SWRST_START + 21UL)
#define CAMBUS1_RESERVE22_SWRST		(CAMBUS1_SWRST_START + 22UL)
#define CAMBUS1_RESERVE23_SWRST		(CAMBUS1_SWRST_START + 23UL)
#define CAMBUS1_RESERVE24_SWRST		(CAMBUS1_SWRST_START + 24UL)
#define CAMBUS1_RESERVE25_SWRST		(CAMBUS1_SWRST_START + 25UL)
#define CAMBUS1_RESERVE26_SWRST		(CAMBUS1_SWRST_START + 26UL)
#define CAMBUS1_RESERVE27_SWRST		(CAMBUS1_SWRST_START + 27UL)
#define CAMBUS1_RESERVE28_SWRST		(CAMBUS1_SWRST_START + 28UL)
#define CAMBUS1_RESERVE29_SWRST		(CAMBUS1_SWRST_START + 29UL)
#define CAMBUS1_RESERVE30_SWRST		(CAMBUS1_SWRST_START + 30UL)
#define CAMBUS1_RESERVE31_SWRST		(CAMBUS1_SWRST_START + 31UL)
#define CAMBUS1_SWRST_END		(CAMBUS1_SWRST_START + 31UL)





/* CAMERA BUS CLKMASK */
#define CAMBUS0_CLKMASK_START		(CAMBUS1_SWRST_END + 1UL)
#define CAMBUS0_CLK_EN			CKC_SWRST_CLKEN_ID(CAMBUS0_CLKMASK_START)
#define CAMBUS_MIPI0_CLK_MASK		CAMBUS0_CLKMASK_START
#define CAMBUS_MIPI0_PHY_APB_MASK	(CAMBUS0_CLKMASK_START + 1UL)
#define CAMBUS_MIPI0_CSI_APB_MASK	(CAMBUS0_CLKMASK_START + 2UL)
#define CAMBUS_MIPI0_CSI_PIX_MASK	(CAMBUS0_CLKMASK_START + 3UL)
#define CAMBUS_MIPI0_GDP_APB_MASK	(CAMBUS0_CLKMASK_START + 4UL)
#define CAMBUS_MIPI0_GDP_PIX_MASK	(CAMBUS0_CLKMASK_START + 5UL)
#define CAMBUS_MIPI0_DSI_APB_MASK	(CAMBUS0_CLKMASK_START + 6UL)
#define CAMBUS_MIPI0_DSI_SYS_MASK	(CAMBUS0_CLKMASK_START + 7UL)
#define CAMBUS_MIPI1_CLK_MASK	        (CAMBUS0_CLKMASK_START + 8UL)
#define CAMBUS_MIPI1_PHY_APB_MASK	(CAMBUS0_CLKMASK_START + 9UL)
#define CAMBUS_MIPI1_CSI_APB_MASK	(CAMBUS0_CLKMASK_START + 10UL)
#define CAMBUS_MIPI1_CSI_PIX_MASK	(CAMBUS0_CLKMASK_START + 11UL)
#define CAMBUS_MIPI1_GDP_APB_MASK	(CAMBUS0_CLKMASK_START + 12UL)
#define CAMBUS_MIPI1_GDP_PIX_MASK	(CAMBUS0_CLKMASK_START + 13UL)
#define CAMBUS_MIPI1_DSI_APB_MASK	(CAMBUS0_CLKMASK_START + 14UL)
#define CAMBUS_MIPI1_DSI_SYS_MASK	(CAMBUS0_CLKMASK_START + 15UL)
#define CAMBUS_ISP_BUS_MASK		(CAMBUS0_CLKMASK_START + 16UL)
#define CAMBUS_ISP_APB_MASK		(CAMBUS0_CLKMASK_START + 17UL)
#define CAMBUS_ISP0_PIX_MASK		(CAMBUS0_CLKMASK_START + 18UL)
#define CAMBUS_ISP1_PIX_MASK		(CAMBUS0_CLKMASK_START + 19UL)
#define CAMBUS_ISP2_PIX_MASK		(CAMBUS0_CLKMASK_START + 20UL)
#define CAMBUS_ISP3_PIX_MASK		(CAMBUS0_CLKMASK_START + 21UL)
#define CAMBUS_RISYNC0_APB_MASK		(CAMBUS0_CLKMASK_START + 22UL)
#define CAMBUS_RISYNC0_PIX_MASK		(CAMBUS0_CLKMASK_START + 23UL)
#define CAMBUS_RISYNC1_APB_MASK 	(CAMBUS0_CLKMASK_START + 24UL)
#define CAMBUS_RISYNC1_PIX_MASK 	(CAMBUS0_CLKMASK_START + 25UL)
#define CAMBUS_VIN_APB_MASK	 	(CAMBUS0_CLKMASK_START + 26UL)
#define CAMBUS_VIN_AIX_MASK	 	(CAMBUS0_CLKMASK_START + 27UL)
#define CAMBUS_VIN_PIX0_MASK 		(CAMBUS0_CLKMASK_START + 28UL)
#define CAMBUS_VIN_PIX1_MASK 		(CAMBUS0_CLKMASK_START + 29UL)
#define CAMBUS_VIN_PIX2_MASK 		(CAMBUS0_CLKMASK_START + 30UL)
#define CAMBUS_VIN_PIX3_MASK		(CAMBUS0_CLKMASK_START + 31UL)
#define CAMBUS0_CLKMASK_END		(CAMBUS0_CLKMASK_START + 31UL)






#define CAMBUS1_CLKMASK_START		(CAMBUS0_CLKMASK_END + 1UL)
#define CAMBUS1_CLK_EN			CKC_SWRST_CLKEN_ID(CAMBUS1_CLKMASK_START)
#define CAMBUS_CIED0_APB_MASK		CAMBUS1_CLKMASK_START
#define CAMBUS_CIED0_PIX_MASK		(CAMBUS1_CLKMASK_START + 1UL)
#define CAMBUS_CIED1_APB_MASK		(CAMBUS1_CLKMASK_START + 2UL)
#define CAMBUS_CIED1_PIX_MASK		(CAMBUS1_CLKMASK_START + 3UL)
#define CAMBUS_CIED2_APB_MASK		(CAMBUS1_CLKMASK_START + 4UL)
#define CAMBUS_CIED2_PIX_MASK		(CAMBUS1_CLKMASK_START + 5UL)
#define CAMBUS_CIED3_APB_MASK		(CAMBUS1_CLKMASK_START + 6UL)
#define CAMBUS_CIED3_PIX_MASK		(CAMBUS1_CLKMASK_START + 7UL)
#define CAMBUS_CIED4_APB_MASK	        (CAMBUS1_CLKMASK_START + 8UL)
#define CAMBUS_CIED4_PIX_MASK		(CAMBUS1_CLKMASK_START + 9UL)
#define CAMBUS_CIED5_APB_MASK		(CAMBUS1_CLKMASK_START + 10UL)
#define CAMBUS_CIED5_PIX_MASK		(CAMBUS1_CLKMASK_START + 11UL)
#define CAMBUS_CIED6_APB_MASK		(CAMBUS1_CLKMASK_START + 12UL)
#define CAMBUS_CIED6_PIX_MASK		(CAMBUS1_CLKMASK_START + 13UL)
#define CAMBUS_CIED7_APB_MASK	        (CAMBUS1_CLKMASK_START + 14UL)
#define CAMBUS_CIED7_PIX_MASK	        (CAMBUS1_CLKMASK_START + 15UL)
#define CAMBUS_CIED8_APB_MASK	        (CAMBUS1_CLKMASK_START + 16UL)
#define CAMBUS_CIED8_PIX_MASK	        (CAMBUS1_CLKMASK_START + 17UL)
#define CAMBUS_CIED9_APB_MASK	        (CAMBUS1_CLKMASK_START + 18UL)
#define CAMBUS_CIED9_PIX_MASK	        (CAMBUS1_CLKMASK_START + 19UL)
#define CAMBUS_SVDM_CORE_MASK	        (CAMBUS1_CLKMASK_START + 20UL)
#define CAMBUS_SVDM_PIX0_MASK	        (CAMBUS1_CLKMASK_START + 21UL)
#define CAMBUS_SVDM_PIX1_MASK	        (CAMBUS1_CLKMASK_START + 22UL)
#define CAMBUS_SVDM_PIX2_MASK	        (CAMBUS1_CLKMASK_START + 23UL)
#define CAMBUS_SVDM_PIX3_MASK	        (CAMBUS1_CLKMASK_START + 24UL)
#define CAMBUS_SVDM_APB_MASK 	        (CAMBUS1_CLKMASK_START + 25UL)
#define CAMBUS_SVDM_AXI_MASK 	        (CAMBUS1_CLKMASK_START + 26UL)
#define CAMBUS_MDW_APB_MASK	        (CAMBUS1_CLKMASK_START + 27UL)
#define CAMBUS_MDW_AXI_MASK	        (CAMBUS1_CLKMASK_START + 28UL)
#define CAMBUS_X2X_SLV_APB_MASK	        (CAMBUS1_CLKMASK_START + 29UL)
#define CAMBUS_X2X_SLV_AXI_MASK	        (CAMBUS1_CLKMASK_START + 30UL)
#define CAMBUS1_RESERVE31_MASK 	        (CAMBUS1_CLKMASK_START + 31UL)
#define CAMBUS1_CLKAMSK_END	        (CAMBUS1_CLKMASK_START + 31UL)






#define NPUBUS_START		(CAMBUS1_CLKAMSK_END + 1UL)
#define NPUBUS_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(NPUBUS_START)
#define NPUBUS_X2X		NPUBUS_START
#define NPUBUS_RESERVE1		(NPUBUS_START + 1UL)
#define NPUBUS_RESERVE2		(NPUBUS_START + 2UL)
#define NPUBUS_RESERVE3		(NPUBUS_START + 3UL)
#define NPUBUS_H2H		(NPUBUS_START + 4UL)
#define NPUBUS_RESERVE5		(NPUBUS_START + 5UL)
#define NPUBUS_RESERVE6		(NPUBUS_START + 6UL)
#define NPUBUS_RESERVE7		(NPUBUS_START + 7UL)
#define NPUBUS_NPU		(NPUBUS_START + 8UL)
#define NPUBUS_RESERVE9		(NPUBUS_START + 9UL)
#define NPUBUS_RESERVE10	(NPUBUS_START + 10UL)
#define NPUBUS_RESERVE11	(NPUBUS_START + 11UL)
#define NPUBUS_SECURE		(NPUBUS_START + 12UL)
#define NPUBUS_RESERVE13	(NPUBUS_START + 13UL)
#define NPUBUS_RESERVE14	(NPUBUS_START + 14UL)
#define NPUBUS_RESERVE15	(NPUBUS_START + 15UL)
#define NPUBUS_RESERVE16	(NPUBUS_START + 16UL)
#define NPUBUS_RESERVE17	(NPUBUS_START + 17UL)
#define NPUBUS_RESERVE18	(NPUBUS_START + 18UL)
#define NPUBUS_RESERVE19	(NPUBUS_START + 19UL)
#define NPUBUS_RESERVE20	(NPUBUS_START + 20UL)
#define NPUBUS_RESERVE21	(NPUBUS_START + 21UL)
#define NPUBUS_RESERVE22	(NPUBUS_START + 22UL)
#define NPUBUS_RESERVE23	(NPUBUS_START + 23UL)
#define NPUBUS_RESERVE24 	(NPUBUS_START + 24UL)
#define NPUBUS_RESERVE25 	(NPUBUS_START + 25UL)
#define NPUBUS_RESERVE26 	(NPUBUS_START + 26UL)
#define NPUBUS_RESERVE27 	(NPUBUS_START + 27UL)
#define NPUBUS_RESERVE28 	(NPUBUS_START + 28UL)
#define NPUBUS_RESERVE29 	(NPUBUS_START + 29UL)
#define NPUBUS_RESERVE30 	(NPUBUS_START + 30UL)
#define NPUBUS_RESERVE31 	(NPUBUS_START + 31UL)
#define NPUBUS_END		(NPUBUS_START + 31UL)




#define GPUBUS_START		(NPUBUS_END + 1UL)
#define GPUBUS_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(GPUBUS_START)
#define GPUBUS_3D		GPUBUS_START
#define GPUBUS_3D_RECOVERY	(GPUBUS_START + 1UL)
#define GPUBUS_ADB		(GPUBUS_START + 2UL)
#define GPUBUS_RESERVE3		(GPUBUS_START + 3UL)
#define GPUBUS_RESERVE4		(GPUBUS_START + 4UL)
#define GPUBUS_RESERVE5		(GPUBUS_START + 5UL)
#define GPUBUS_RESERVE6		(GPUBUS_START + 6UL)
#define GPUBUS_RESERVE7		(GPUBUS_START + 7UL)
#define GPUBUS_RESERVE8		(GPUBUS_START + 8UL)
#define GPUBUS_RESERVE9		(GPUBUS_START + 9UL)
#define GPUBUS_RESERVE10	(GPUBUS_START + 10UL)
#define GPUBUS_RESERVE11	(GPUBUS_START + 11UL)
#define GPUBUS_RESERVE12	(GPUBUS_START + 12UL)
#define GPUBUS_RESERVE13	(GPUBUS_START + 13UL)
#define GPUBUS_RESERVE14	(GPUBUS_START + 14UL)
#define GPUBUS_RESERVE15	(GPUBUS_START + 15UL)
#define GPUBUS_RESERVE16	(GPUBUS_START + 16UL)
#define GPUBUS_RESERVE17	(GPUBUS_START + 17UL)
#define GPUBUS_RESERVE18	(GPUBUS_START + 18UL)
#define GPUBUS_RESERVE19	(GPUBUS_START + 19UL)
#define GPUBUS_RESERVE20	(GPUBUS_START + 20UL)
#define GPUBUS_RESERVE21	(GPUBUS_START + 21UL)
#define GPUBUS_RESERVE22	(GPUBUS_START + 22UL)
#define GPUBUS_RESERVE23	(GPUBUS_START + 23UL)
#define GPUBUS_RESERVE24 	(GPUBUS_START + 24UL)
#define GPUBUS_RESERVE25 	(GPUBUS_START + 25UL)
#define GPUBUS_RESERVE26 	(GPUBUS_START + 26UL)
#define GPUBUS_RESERVE27 	(GPUBUS_START + 27UL)
#define GPUBUS_RESERVE28 	(GPUBUS_START + 28UL)
#define GPUBUS_RESERVE29 	(GPUBUS_START + 29UL)
#define GPUBUS_RESERVE30 	(GPUBUS_START + 30UL)
#define GPUBUS_RESERVE31 	(GPUBUS_START + 31UL)
#define GPUBUS_END		(GPUBUS_START + 31UL)

#define IOPERI_START		(GPUBUS_END + 1UL)
#define IOPERI_CLK_EN		CKC_SWRST_CLKEN_ID(IOPERI_START)
#define IOPERI_RESERVE0		IOPERI_START
#define IOPERI_RESERVE1		(IOPERI_START + 1UL)
#define IOPERI_RESERVE2		(IOPERI_START + 2UL)
#define IOPERI_RESERVE3		(IOPERI_START + 3UL)
#define IOPERI_RESERVE4		(IOPERI_START + 4UL)
#define IOPERI_RESERVE5		(IOPERI_START + 5UL)
#define IOPERI_RESERVE6		(IOPERI_START + 6UL)
#define IOPERI_RESERVE7		(IOPERI_START + 7UL)
#define IOPERI_UART0		(IOPERI_START + 8UL)
#define IOPERI_UART1		(IOPERI_START + 9UL)
#define IOPERI_UART2		(IOPERI_START + 10UL)
#define IOPERI_UART3		(IOPERI_START + 11UL)
#define IOPERI_UART4		(IOPERI_START + 12UL)
#define IOPERI_UART5		(IOPERI_START + 13UL)
#define IOPERI_UART6		(IOPERI_START + 14UL)
#define IOPERI_UART7		(IOPERI_START + 15UL)
#define IOPERI_UART8		(IOPERI_START + 16UL)
#define IOPERI_RESERVE17	(IOPERI_START + 17UL)
#define IOPERI_RESERVE18	(IOPERI_START + 18UL)
#define IOPERI_RESERVE19	(IOPERI_START + 19UL)
#define IOPERI_RESERVE20	(IOPERI_START + 20UL)
#define IOPERI_RESERVE21	(IOPERI_START + 21UL)
#define IOPERI_RESERVE22	(IOPERI_START + 22UL)
#define IOPERI_RESERVE23	(IOPERI_START + 23UL)
#define IOPERI_I2C0 		(IOPERI_START + 24UL)
#define IOPERI_I2C1 		(IOPERI_START + 25UL)
#define IOPERI_I2C2 		(IOPERI_START + 26UL)
#define IOPERI_I2C3 		(IOPERI_START + 27UL)
#define IOPERI_I2C4 		(IOPERI_START + 28UL)
#define IOPERI_I2C5 		(IOPERI_START + 29UL)
#define IOPERI_I2C6 		(IOPERI_START + 30UL)
#define IOPERI_I2C7 		(IOPERI_START + 31UL)
#define IOPERI_END		(IOPERI_START + 31UL)


/* PLL source clock (Not support CLK_F_GET_SRC_CLK yet..) */
#define PLL_SRC_XIN	0UL

/* Source clock flags for CLK_F_GET_SRC_CLK */
/* SMU BUS SEL */
#define SMU_CLKCTRL_SEL_PLL0		0UL
#define SMU_CLKCTRL_SEL_PLL1		1UL
#define SMU_CLKCTRL_SEL_PLL2		2UL
#define SMU_CLKCTRL_SEL_PLL3		3UL
#define SMU_CLKCTRL_SEL_PLL4		4UL
#define SMU_CLKCTRL_SEL_XIN		5UL

#define SMU_CLKCTRL_SEL_PLL0DIV		7UL
#define SMU_CLKCTRL_SEL_PLL1DIV		8UL
#define SMU_CLKCTRL_SEL_PLL2DIV		9UL
#define SMU_CLKCTRL_SEL_PLL3DIV		10UL
#define SMU_CLKCTRL_SEL_PLL4DIV		11UL
#define SMU_CLKCTRL_SEL_XINDIV		12UL

#define SMU_CLKCTRL_SEL_EXTIN2		14UL
#define SMU_CLKCTRL_SEL_EXTIN3		15UL

/* CPU BUS SEL */
#define CPU_CLKCTRL_SEL_XIN		0UL
#define CPU_CLKCTRL_SEL_PLL		1UL
#define CPU_CLKCTRL_SEL_PLLDIV		2UL
#define CPU_CLKCTRL_SEL_EXTCLK		3UL

/* MEM BUS SEL */
#define MEM_CLKCTRL_SEL_XIN		0UL
#define MEM_CLKCTRL_SEL_PLL0		1UL
#define MEM_CLKCTRL_SEL_PLL1		2UL
#define MEM_CLKCTRL_SEL_PLL0_DIV0	3UL
#define MEM_CLKCTRL_SEL_PLL0_DIV1	4UL
#define MEM_CLKCTRL_SEL_PLL1_DIV0	5UL
#define MEM_CLKCTRL_SEL_PLL1_DIV1	6UL
#define MEM_CLKCTRL_SEL_XTIN		7UL
#define MEM_CLKCTRL_SEL_EXTCLK		0xFUL

/* GPU/G2D BUS SEL */
#define GPU_CLKCTRL_SEL_XIN		0UL
#define GPU_CLKCTRL_SEL_PLL		1UL
#define GPU_CLKCTRL_SEL_PLLDIV		2UL
#define GPU_CLKCTRL_SEL_EXTCLK		3UL

/* DISPLAY BUS SEL */
#define DDI_CLKCTRL_SEL_XIN		0UL
#define DDI_CLKCTRL_SEL_PLL		1UL
#define DDI_CLKCTRL_SEL_PLLDIV		2UL

/* VPU BUS SEL */
#define VPU_CLKCTRL_SEL_XIN		0UL
#define VPU_CLKCTRL_SEL_PLL0		1UL
#define VPU_CLKCTRL_SEL_PLL1		2UL
#define VPU_CLKCTRL_SEL_PLL0_DIV0	3UL
#define VPU_CLKCTRL_SEL_PLL0_DIV1	4UL
#define VPU_CLKCTRL_SEL_PLL1_DIV0	5UL
#define VPU_CLKCTRL_SEL_PLL1_DIV1	6UL
#define VPU_CLKCTRL_SEL_EXTCLK		7UL

/* AUDIO BUS SEL */
#define AUDIO_CLKCTRL_SEL_XIN		0UL
#define AUDIO_CLKCTRL_SEL_PLL0		1UL
#define AUDIO_CLKCTRL_SEL_PLL1		2UL
#define AUDIO_CLKCTRL_SEL_XIN_DIV	3UL
#define AUDIO_CLKCTRL_SEL_PLL0_DIV	4UL
#define AUDIO_CLKCTRL_SEL_PLL1_DIV	5UL

/* NPU BUS SEL */
#define NPU_CLKCTRL_SEL_XIN		0UL
#define NPU_CLKCTRL_SEL_PLL		1UL
#define NPU_CLKCTRL_SEL_PLLDIV		2UL
#define NPU_CLKCTRL_SEL_EXTCLK		3UL

/* CAM BUS SEL */
#define CAM_CLKCTRL_SEL_XIN		0UL
#define CAM_CLKCTRL_SEL_PLL		1UL
#define CAM_CLKCTRL_SEL_PLLDIV		2UL

/* SMU Peripheral SEL */
#define SMU_PCLKCTRL_SEL_PLL0		0UL
#define SMU_PCLKCTRL_SEL_PLL1		1UL
#define SMU_PCLKCTRL_SEL_PLL2		2UL
#define SMU_PCLKCTRL_SEL_PLL3		3UL
#define SMU_PCLKCTRL_SEL_PLL4		4UL
#define SMU_PCLKCTRL_SEL_XIN		5UL
#define SMU_PCLKCTRL_SEL_XTIN		6UL

#define SMU_PCLKCTRL_SEL_PLL0DIV	10UL
#define SMU_PCLKCTRL_SEL_PLL1DIV	11UL
#define SMU_PCLKCTRL_SEL_PLL2DIV	12UL
#define SMU_PCLKCTRL_SEL_PLL3DIV	13UL
#define SMU_PCLKCTRL_SEL_PLL4DIV	14UL

#define SMU_PCLKCTRL_SEL_PCI0PHY	18UL
#define SMU_PCLKCTRL_SEL_PCI1PHY	19UL

#define SMU_PCLKCTRL_SEL_XINDIV		23UL
#define SMU_PCLKCTRL_SEL_XTINDIV	24UL
#define SMU_PCLKCTRL_SEL_EXTCLK0	25UL
#define SMU_PCLKCTRL_SEL_EXTCLK1	26UL


/* AUDIO Peripheral SEL */
#define AUDIO_PCLKCTRL_SEL_PLL0		0UL
#define AUDIO_PCLKCTRL_SEL_PLL1		1UL

#define AUDIO_PCLKCTRL_SEL_XIN		5UL

#define AUDIO_PCLKCTRL_SEL_PLL0DIV	10UL
#define AUDIO_PCLKCTRL_SEL_PLL1DIV	11UL

#define AUDIO_PCLKCTRL_SEL_DP_PLL	21UL

#define AUDIO_PCLKCTRL_SEL_XINDIV	23UL

#define AUDIO_PCLKCTRL_SEL_EXTCLK0	25UL
#define AUDIO_PCLKCTRL_SEL_EXTCLK1	26UL

#endif
