/* SPDX-License-Identifier: (GPL-2.0-or-later OR MIT) */
/*
 * Copyright (C) 2023 Telechips Inc.
 */

#ifndef DT_TCC807X_CLKS_H
#define DT_TCC807X_CLKS_H

#include "telechips,clk-common.h"


/*
 * Clock index for device tree.
 * These values used for clock-indices in clock device node.
 * The index number MUST BE match with TF-A
 */



#define PLL_0			0UL
#define PLL_1			1UL
#define PLL_2			2UL
#define PLL_3			3UL
#define PLL_4			4UL
#define PLL_0_DIV		5UL
#define PLL_1_DIV		6UL
#define PLL_2_DIV		7UL
#define PLL_3_DIV		8UL
#define PLL_4_DIV		9UL
#define PLL_XIN			10UL
#define PLL_XTIN		11UL

#define PLL_DEDICATED		12UL

#define PLL_MP_CA76		13UL
#define PLL_MP_CA76_DIV		14UL
#define PLL_MP_CA55		15UL
#define PLL_MP_CA55_DIV		16UL
#define PLL_MP_DSU		17UL
#define PLL_MP_DSU_DIV_0	18UL
//#define PLL_MP_DSU_DIV_1	19UL

//#define PLL_SP_CA76		20UL
//#define PLL_SP_CA76_DIV	21UL
#define PLL_SP_CA55		22UL
#define PLL_SP_CA55_DIV		23UL
#define PLL_SP_DSU		24UL
#define PLL_SP_DSU_DIV_0	25UL
//#define PLL_SP_DSU_DIV_1	26UL

#define PLL_MEM_0		27UL
#define PLL_MEM_1		28UL
#define PLL_MEM_0_DIV_0		29UL
#define PLL_MEM_0_DIV_1		30UL
#define PLL_MEM_1_DIV_0		31UL
#define PLL_MEM_1_DIV_1		32UL
#define PLL_MEMPHY_0		33UL
#define PLL_MEMPHY_1		34UL
#define PLL_MEMPHY_2		35UL
#define PLL_MEMPHY_3		36UL

#define PLL_DDI			37UL
#define PLL_DDI_DIV_0		38UL
#define PLL_DDI_DIV_1		39UL
#define PLL_DDI_DIV_2		40UL

#define PLL_VIDEO_0		41UL
#define PLL_VIDEO_1		42UL
#define PLL_VIDEO_0_DIV_0	43UL
#define PLL_VIDEO_0_DIV_1	44UL
#define PLL_VIDEO_1_DIV_0	45UL
#define PLL_VIDEO_1_DIV_1	46UL

#define PLL_AUDIO_0		47UL
#define PLL_AUDIO_1		48UL
#define PLL_AUDIO_0_DIV		49UL
#define PLL_AUDIO_1_DIV		50UL

#define PLL_GPU			51UL
#define PLL_GPU_DIV	 	52UL

#define PLL_G2D			53UL
#define PLL_G2D_DIV 		54UL

#define PLL_CAM			55UL
#define PLL_CAM_DIV_0		56UL
#define PLL_CAM_DIV_1		57UL
#define PLL_CAM_DIV_2		58UL
#define PLL_CAM_DIV_3		59UL

#define PLL_NPU			60UL
#define PLL_NPU_DIV		61UL

#define PLL_MAX			62UL




/* CLKCTRL channel index */
#define FBUS_CPU			2UL
#define FBUS_TAW			3UL
#define FBUS_HSIO			6UL
#define FBUS_SMU			7UL
#define FBUS_DDI			9UL
#define FBUS_IO				11UL
#define FBUS_HSM			16UL
#define FBUS_PCIe0			17UL
#define FBUS_PCIe1			18UL

#define FBUS_DEDICATED_START		19UL

#define FBUS_DEDICATED_CPU_START	20UL
#define FBUS_MP_CA76			21UL
#define FBUS_MP_CA55			22UL
#define FBUS_MP_DSU_PCLK		23UL
#define FBUS_MP_DSU			24UL
#define FBUS_SP_CA55			25UL
#define FBUS_SP_DSU_PCLK		26UL
#define FBUS_SP_DSU			27UL
#define FBUS_DEDICATED_CPU_END		28UL

#define FBUS_DEDICATED_MEM_START	29UL
#define FBUS_MEM			30UL
#define FBUS_MEM_SMMU			31UL
#define FBUS_MEM_LPDDR			32UL
#define FBUS_DEDICATED_MEM_END		33UL

#define FBUS_DEDICATED_DDI_START	34UL
#define FBUS_DDI_AXI			35UL
#define FBUS_DDI_AUX			36UL
#define FBUS_DDI_APB			37UL
#define FBUS_DEDICATED_DDI_END		38UL

#define FBUS_DEDICATED_VPU_START	39UL
#define FBUS_VBUS			40UL
#define FBUS_CODA			41UL
#define FBUS_CHEVCDEC			42UL
#define FBUS_BHEVCDEC			43UL
#define FBUS_CHEVCENC			44UL
#define FBUS_BHEVCENC			45UL
#define FBUS_DEDICATED_VPU_END		46UL

#define FBUS_DEDICATED_AUDIO_START	47UL
#define FBUS_AUDIO			48UL
#define FBUS_DEDICATED_AUDIO_END	49UL

#define FBUS_DEDICATED_GPU_START	50UL
#define FBUS_GPU			51UL
#define FBUS_G2D			52UL
#define FBUS_DEDICATED_GPU_END		53UL

#define FBUS_DEDICATED_CAM_START	54UL
#define FBUS_CAM_APB			55UL
#define FBUS_CAM_AXI			56UL
#define FBUS_CAM_SYS			57UL
#define FBUS_CAM_PIX			58UL
#define FBUS_DEDICATED_CAM_END		59UL

#define FBUS_DEDICATED_NPU_START	60UL
#define FBUS_NPU			61UL
#define FBUS_DEDICATED_NPU_END		62UL

#define FBUS_DEDICATED_END		63UL

#define FBUS_MAX			64UL



#define DECLARE_PERI_ID(base, offset, index) ((base) + (offset) + ((index)*4U))

/* Peripheral Clocks */
/* PCLK***CTRL register : starts from 0x14000000 + 0x400*/
#define TCC_CKC_BASE 		0x14000000UL
#define CKC_PCLKCTRL		0x400UL

#define PERI_SMU_BASE		TCC_CKC_BASE
#define PERI_SMU_BASE_OFFSET	(CKC_PCLKCTRL + 0x0U)
#define PERI_DDIB_BASE_OFFSET	(CKC_PCLKCTRL + 0x100UL)
#define PERI_HSIOB_BASE_OFFSET	(CKC_PCLKCTRL + 0x200UL)
#define PERI_IOB_BASE_OFFSET	(CKC_PCLKCTRL + 0x300UL)
#define PERI_CPUB_BASE_OFFSET	(CKC_PCLKCTRL + 0x500UL)
#define PERI_EXT_BASE_OFFSET	(CKC_PCLKCTRL + 0x600UL)
#define PERI_HSMB_BASE_OFFSET	(CKC_PCLKCTRL + 0x700UL)

/* SMU Peri. */
#define PERI_TCX		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_SMU_BASE_OFFSET, 0UL)
#define PERI_TCT		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_SMU_BASE_OFFSET, 1UL)
#define PERI_TCZ		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_SMU_BASE_OFFSET, 2UL)

/* DDIB Peri. */
#define PERI_LCDTIMER		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_DDIB_BASE_OFFSET, 0UL)
#define PERI_LCD0		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_DDIB_BASE_OFFSET, 1UL)
#define PERI_LCD1		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_DDIB_BASE_OFFSET, 2UL)
#define PERI_LCD2		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_DDIB_BASE_OFFSET, 3UL)
#define PERI_LCD3		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_DDIB_BASE_OFFSET, 4UL)
#define PERI_LCD4		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_DDIB_BASE_OFFSET, 5UL)

/* HSB Peri. */
#define PERI_GMAC		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_HSIOB_BASE_OFFSET, 0UL)
#define PERI_GMAC_PTP		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_HSIOB_BASE_OFFSET, 1UL)
#define PERI_PCIE0_PHY_CR_CLK	DECLARE_PERI_ID(PERI_SMU_BASE, PERI_HSIOB_BASE_OFFSET, 4UL)
#define PERI_PCIE1_PHY_CR_CLK	DECLARE_PERI_ID(PERI_SMU_BASE, PERI_HSIOB_BASE_OFFSET, 7UL)

/* IOB Peri. */
#define PERI_RMT		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 0UL)
#define PERI_RESERVE1		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 1UL)
#define PERI_SDMMC1		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 2UL)
#define PERI_SDMMC2		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 3UL)
#define PERI_CAN0		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 4UL)
#define PERI_CAN1		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 5UL)
#define PERI_CAN2		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 6UL)
#define PERI_CAN3		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 7UL)
#define PERI_CAN4		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 8UL)
#define PERI_CAN5		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 9UL)
#define PERI_CAN6		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 10UL)
#define PERI_PDM		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 11UL)
#define PERI_CAN7		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 12UL)
#define PERI_CAN8		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 13UL)
#define PERI_I2C0		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 14UL)
#define PERI_I2C1		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 15UL)
#define PERI_I2C2		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 16UL)
#define PERI_I2C3		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 17UL)
#define PERI_UART0		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 18UL)
#define PERI_UART1		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 19UL)
#define PERI_UART2		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 20UL)
#define PERI_UART3		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 21UL)
#define PERI_CAN9		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 22UL)
#define PERI_CAN10		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 23UL)
#define PERI_CAN11		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 24UL)
#define PERI_TS_RX0		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 25UL)
#define PERI_GPSB0		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 26UL)
#define PERI_GPSB1		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 27UL)
#define PERI_GPSB2		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 28UL)
#define PERI_GPSB3		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 29UL)
#define PERI_GPSB4		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 30UL)
#define PERI_GPSB5		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 31UL)
#define PERI_UART4		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 32UL)
#define PERI_TS_RX1		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 33UL)
#define PERI_ADC		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 34UL)
#define PERI_RESERVE35		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 35UL)
#define PERI_RESERVE36		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 36UL)
#define PERI_RESERVE37		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 37UL)
#define PERI_RESERVE38		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 38UL)
#define PERI_RESERVE39		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 39UL)
#define PERI_IC_TC		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 40UL)
#define PERI_RESERVE41		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 41UL)
#define PERI_RESERVE42		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 42UL)
#define PERI_RESERVE43		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 43UL)
#define PERI_RESERVE44		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 44UL)
#define PERI_RESERVE45		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 45UL)
#define PERI_RESERVE46		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 46UL)
#define PERI_RESERVE47		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 47UL)
#define PERI_RESERVE48		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 48UL)
#define PERI_RESERVE49		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 49UL)
#define PERI_UART5		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 50UL)
#define PERI_UART6		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 51UL)
#define PERI_UART7		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 52UL)
#define PERI_UART8		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_IOB_BASE_OFFSET, 53UL)

/* CB Peri. */
#define PERI_CB_WDT		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_CPUB_BASE_OFFSET, 0UL)

/* External Peri. */
#define PERI_OUT0		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_EXT_BASE_OFFSET, 0UL)
#define PERI_OUT1		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_EXT_BASE_OFFSET, 1UL)
#define PERI_OUT2		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_EXT_BASE_OFFSET, 2UL)
#define PERI_OUT3		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_EXT_BASE_OFFSET, 3UL)
#define PERI_OUT4		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_EXT_BASE_OFFSET, 4UL)
#define PERI_OUT5		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_EXT_BASE_OFFSET, 5UL)

/* HSMB Peri. */
#define PERI_HSMB		DECLARE_PERI_ID(PERI_SMU_BASE, PERI_HSMB_BASE_OFFSET, 0UL)


/* Audio Sub-System Peri */
/* PCLK_CFG_xxx register : starts from 0x19600000 + 0x38*/
#define TCC_AUCIO_CKC_BASE	0x19600000UL
#define AUDIO_CKC_PCLKCTRL	0x038UL

#define PERI_AUDIO_BASE		TCC_AUDIO_CKC_BASE
#define PERI_AUDIO_BASE_OFFSET	(AUDIO_CKC_PCLKCTRL + 0x000UL)

#define PERI_AUDIO_MAIC0_DAIF	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 0UL)
#define PERI_AUDIO_MAIC0_FILTER	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 1UL)
#define PERI_AUDIO_MAIC0_SPDIF	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 2UL)
#define PERI_AUDIO_MAIC1_DAIF	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 3UL)
#define PERI_AUDIO_MAIC1_FILTER	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 4UL)
#define PERI_AUDIO_MAIC1_SPDIF	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 5UL)
#define PERI_AUDIO_MAIC2_DAIF	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 6UL)
#define PERI_AUDIO_MAIC2_FILTER	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 7UL)
#define PERI_AUDIO_MAIC2_SPDIF	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 8UL)
#define PERI_AUDIO_MAIC3_DAIF	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 9UL)
#define PERI_AUDIO_MAIC3_FILTER	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 10UL)
#define PERI_AUDIO_MAIC3_SPDIF	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 11UL)
#define PERI_AUDIO_MAIC4_DAIF	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 12UL)
#define PERI_AUDIO_MAIC4_FILTER	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 13UL)
#define PERI_AUDIO_MAIC4_SPDIF	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 14UL)
#define PERI_AUDIO_MAIC5_DAIF	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 15UL)
#define PERI_AUDIO_MAIC5_FILTER	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 16UL)
#define PERI_AUDIO_MAIC5_SPDIF	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 17UL)
#define PERI_AUDIO_MAIC6_DAIF	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 18UL)
#define PERI_AUDIO_MAIC6_FILTER	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 19UL)
#define PERI_AUDIO_MAIC6_SPDIF	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 20UL)
#define PERI_AUDIO_MAIC7_DAIF	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 21UL)
#define PERI_AUDIO_MAIC7_FILTER	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 22UL)
#define PERI_AUDIO_MAIC7_SPDIF	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 23UL)
#define PERI_AUDIO_MASRC_AUX0	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 24UL)
#define PERI_AUDIO_MASRC_AUX1	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 25UL)
#define PERI_AUDIO_MASRC_AUX2	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 26UL)
#define PERI_AUDIO_MASRC_AUX3	DECLARE_PERI_ID(PERI_AUDIO_BASE, PERI_AUDIO_BASE_OFFSET, 27UL)


/* Use this macro to find register address for each SWRESET & CLKEN ID */
#define CKC_SWRST_CLKEN_ID(A)	((A)/32UL)

/* CLKEN / SWRESET */
#define SMUBUS_START		0UL
#define SMUBUS_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(SMUBUS_START)
#define SMUBUS_CPU_MP		SMUBUS_START
#define SMUBUS_CPU_SP		(SMUBUS_START + 1UL)
#define SMUBUS_CPU_SUB		(SMUBUS_START + 2UL)
#define SMUBUS_RESERVE3		(SMUBUS_START + 3UL)
#define SMUBUS_MEM		(SMUBUS_START + 4UL)
#define	SMUBUS_VPU		(SMUBUS_START + 5UL)
#define SMUBUS_HSIO		(SMUBUS_START + 6UL)
#define SMUBUS_SMU		(SMUBUS_START + 7UL)
#define SMUBUS_3D		(SMUBUS_START + 8UL)
#define SMUBUS_DDI		(SMUBUS_START + 9UL)
#define SMUBUS_2D		(SMUBUS_START + 10UL)
#define SMUBUS_IO		(SMUBUS_START + 11UL)
#define SMUBUS_CODA		(SMUBUS_START + 12UL)
#define SMUBUS_CHEVCDEC		(SMUBUS_START + 13UL)
#define SMUBUS_RESERVE14	(SMUBUS_START + 14UL)
#define SMUBUS_BHEVCDEC		(SMUBUS_START + 15UL)
#define SMUBUS_RESERVE16	(SMUBUS_START + 16UL)
#define SMUBUS_PCIe		(SMUBUS_START + 17UL)
#define SMUBUS_RESERVE18	(SMUBUS_START + 18UL)
#define SMUBUS_STORAGE		(SMUBUS_START + 19UL)
#define SMUBUS_RESERVE20	(SMUBUS_START + 20UL)
#define SMUBUS_CHEVCENC		(SMUBUS_START + 21UL)
#define SMUBUS_BHEVCENC		(SMUBUS_START + 22UL)
#define SMUBUS_USB30		(SMUBUS_START + 23UL)
#define SMUBUS_RESERVE24	(SMUBUS_START + 24UL)
#define SMUBUS_AUDIO		(SMUBUS_START + 25UL)
#define SMUBUS_NPU		(SMUBUS_START + 26UL)
#define SMUBUS_RTC		(SMUBUS_START + 27UL)
#define SMUBUS_RESERVE28	(SMUBUS_START + 28UL)
#define SMUBUS_RESERVE29	(SMUBUS_START + 29UL)
#define SMUBUS_RESERVE30	(SMUBUS_START + 30UL)
#define SMUBUS_RESERVE31	(SMUBUS_START + 31UL)
#define SMUBUS_END		(SMUBUS_START + 31UL)





#define CPUMP_START		(SMUBUS_END + 1UL)
#define CPUMP_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(CPUMP_START)
#define CPUMP_X2X		CPUMP_START
#define CPUMP_H2H		(CPUMP_START + 1UL)
#define CPUMP_APBIF		(CPUMP_START + 2UL)
#define CPUMP_CFGR		(CPUMP_START + 3UL)
#define CPUMP_RESERVE4		(CPUMP_START + 4UL)
#define CPUMP_DSU		(CPUMP_START + 5UL)
#define CPUMP_CA55		(CPUMP_START + 6UL)
#define CPUMP_CA76		(CPUMP_START + 7UL)
#define CPUMP_APBDBG		(CPUMP_START + 8UL)
#define CPUMP_GIGPPI		(CPUMP_START + 9UL)
#define CPUMP_CORE0RST		(CPUMP_START + 10UL)
#define CPUMP_CORE1RST		(CPUMP_START + 11UL)
#define CPUMP_CORE2RST		(CPUMP_START + 12UL)
#define CPUMP_CORE3RST		(CPUMP_START + 13UL)
#define CPUMP_CORE4RST		(CPUMP_START + 14UL)
#define CPUMP_CORE5RST		(CPUMP_START + 15UL)
#define CPUMP_CPUPOR0		(CPUMP_START + 16UL)
#define CPUMP_CPUPOR1		(CPUMP_START + 17UL)
#define CPUMP_CPUPOR2		(CPUMP_START + 18UL)
#define CPUMP_CPUPOR3		(CPUMP_START + 19UL)
#define CPUMP_CPUPOR4		(CPUMP_START + 20UL)
#define CPUMP_CPUPOR5		(CPUMP_START + 21UL)
#define CPUMP_DBG		(CPUMP_START + 22UL)
#define CPUMP_ATB		(CPUMP_START + 23UL)
#define CPUMP_PERIPH		(CPUMP_START + 24UL)
#define CPUMP_GICP		(CPUMP_START + 25UL)
#define CPUMP_SPOR		(CPUMP_START + 26UL)
#define CPUMP_SRESET		(CPUMP_START + 27UL)
#define CPUMP_FUNNEL		(CPUMP_START + 28UL)
#define CPUMP_RESERVE29		(CPUMP_START + 29UL)
#define CPUMP_RESERVE30		(CPUMP_START + 30UL)
#define CPUMP_RESERVE31		(CPUMP_START + 31UL)
#define CPUMP_END		(CPUMP_START + 31UL)






#define CPUSP_START		(CPUMP_END + 1UL)
#define CPUSP_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(CPUSP_START)
#define CPUSP_X2X		CPUSP_START
#define CPUSP_H2H		(CPUSP_START + 1UL)
#define CPUSP_APBIF		(CPUSP_START + 2UL)
#define CPUSP_CFGR		(CPUSP_START + 3UL)
#define CPUSP_RESERVE4		(CPUSP_START + 4UL)
#define CPUSP_DSU		(CPUSP_START + 5UL)
#define CPUSP_CA55		(CPUSP_START + 6UL)
#define CPUSP_RESERVE7		(CPUSP_START + 7UL)
#define CPUSP_APBDBG		(CPUSP_START + 8UL)
#define CPUSP_GIGPPI		(CPUSP_START + 9UL)
#define CPUSP_CORE0RST		(CPUSP_START + 10UL)
#define CPUSP_CORE1RST		(CPUSP_START + 11UL)
#define CPUSP_RESERVE12		(CPUSP_START + 12UL)
#define CPUSP_RESERVE13		(CPUSP_START + 13UL)
#define CPUSP_RESERVE14		(CPUSP_START + 14UL)
#define CPUSP_RESERVE15		(CPUSP_START + 15UL)
#define CPUSP_CPUPOR0		(CPUSP_START + 16UL)
#define CPUSP_CPUPOR1		(CPUSP_START + 17UL)
#define CPUSP_RESERVE18		(CPUSP_START + 18UL)
#define CPUSP_RESERVE19		(CPUSP_START + 19UL)
#define CPUSP_RESERVE20		(CPUSP_START + 20UL)
#define CPUSP_RESERVE21		(CPUSP_START + 21UL)
#define CPUSP_DBG		(CPUSP_START + 22UL)
#define CPUSP_ATB		(CPUSP_START + 23UL)
#define CPUSP_PERIPH		(CPUSP_START + 24UL)
#define CPUSP_GICP		(CPUSP_START + 25UL)
#define CPUSP_SPOR		(CPUSP_START + 26UL)
#define CPUSP_SRESET		(CPUSP_START + 27UL)
#define CPUSP_FUNNEL		(CPUSP_START + 28UL)
#define CPUSP_RESERVE29		(CPUSP_START + 29UL)
#define CPUSP_RESERVE30		(CPUSP_START + 30UL)
#define CPUSP_RESERVE31		(CPUSP_START + 31UL)
#define CPUSP_END		(CPUSP_START + 31UL)






#define CPUBUS_START		(CPUSP_END + 1UL)
#define CPUBUS_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(CPUBUS_START)
#define CPUBUS_WDT0		CPUBUS_START
#define CPUBUS_WDT1		(CPUBUS_START + 1UL)
#define CPUBUS_WDT2		(CPUBUS_START + 2UL)
#define CPUBUS_WDT3		(CPUBUS_START + 3UL)
#define CPUBUS_WDT4		(CPUBUS_START + 4UL)
#define CPUBUS_RESERVE5		(CPUBUS_START + 5UL)
#define CPUBUS_CBUSCFG		(CPUBUS_START + 6UL)
#define CPUBUS_MB2DAP		(CPUBUS_START + 7UL)
#define CPUBUS_DAP		(CPUBUS_START + 8UL)
#define CPUBUS_DAPCFG		(CPUBUS_START + 9UL)
#define CPUBUS_DAP2MB		(CPUBUS_START + 10UL)
#define CPUBUS_MB2CB		(CPUBUS_START + 11UL)
#define CPUBUS_AHBMUX		(CPUBUS_START + 12UL)
#define CPUBUS_APBIF		(CPUBUS_START + 13UL)
#define CPUBUS_MPH2H		(CPUBUS_START + 14UL)
#define CPUBUS_MP		(CPUBUS_START + 15UL)
#define CPUBUS_SPH2H		(CPUBUS_START + 16UL)
#define CPUBUS_SP		(CPUBUS_START + 17UL)
#define CPUBUS_RESERVE18	(CPUBUS_START + 18UL)
#define CPUBUS_GIC0		(CPUBUS_START + 19UL)
#define CPUBUS_MBOX		(CPUBUS_START + 20UL)
#define CPUBUS_RESERVE21	(CPUBUS_START + 21UL)
#define CPUBUS_WDT5		(CPUBUS_START + 22UL)
#define CPUBUS_WDT6		(CPUBUS_START + 23UL)
#define CPUBUS_WDT7		(CPUBUS_START + 24UL)
#define CPUBUS_RESERVE25	(CPUBUS_START + 25UL)
#define CPUBUS_SJTAG		(CPUBUS_START + 26UL)
#define CPUBUS_HSSTP		(CPUBUS_START + 27UL)
#define CPUBUS_GIC1		(CPUBUS_START + 28UL)
#define CPUBUS_MPPOR		(CPUBUS_START + 29UL)
#define CPUBUS_SPPOR		(CPUBUS_START + 30UL)
#define CPUBUS_CBP		(CPUBUS_START + 31UL)
#define CPUBUS_END		(CPUBUS_START + 31UL)





/* IOBUS has 4 register for swreset & clken. (HCLKEN0-2 + HCLKEN_STR) */
#define IOBUS0_START		(CPUBUS_END + 1UL)
#define IOBUS0_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(IOBUS0_START)
#define IOBUS_IC_TC		IOBUS0_START
#define IOBUS_CAN_DMA		(IOBUS0_START + 1UL)   // When can DMA is in used, should be set 1
#define IOBUS_GPSB3		(IOBUS0_START + 2UL)
#define IOBUS_CAN_DMA_4		(IOBUS0_START + 3UL)
#define IOBUS_CAN_DMA_3		(IOBUS0_START + 4UL)
#define IOBUS_CAN_DMA_2		(IOBUS0_START + 5UL)
#define IOBUS_CAN_DMA_1		(IOBUS0_START + 6UL)
#define IOBUS_DMA_G0		(IOBUS0_START + 7UL)
#define IOBUS_DMA_G1		(IOBUS0_START + 8UL)
#define IOBUS_DMA_G2		(IOBUS0_START + 9UL)
#define IOBUS_DMA		(IOBUS0_START + 10UL)	// When DMA is in used, should be set 1
#define IOBUS_CAN_DMA_0		(IOBUS0_START + 11UL)
#define IOBUS_PDM		(IOBUS0_START + 12UL)
#define IOBUS_CAN_CFG		(IOBUS0_START + 13UL)
#define IOBUS_I2C_S2		(IOBUS0_START + 14UL)
#define IOBUS_CAN_11		(IOBUS0_START + 15UL)
#define IOBUS_CAN_10		(IOBUS0_START + 16UL)
#define IOBUS_CAN_9		(IOBUS0_START + 17UL)
#define IOBUS_CAN_8		(IOBUS0_START + 18UL)
#define IOBUS_CAN_7		(IOBUS0_START + 19UL)
#define IOBUS_PRT		(IOBUS0_START + 20UL)
#define IOBUS_CAN_6		(IOBUS0_START + 21UL)
#define IOBUS_CAN_5		(IOBUS0_START + 22UL)
#define IOBUS_CAN_4		(IOBUS0_START + 23UL)
#define IOBUS_CAN_3		(IOBUS0_START + 24UL)
#define IOBUS_CAN_2		(IOBUS0_START + 25UL)
#define IOBUS_CAN_1		(IOBUS0_START + 26UL)
#define IOBUS_CAN_0		(IOBUS0_START + 27UL)
#define IOBUS_CAN		(IOBUS0_START + 28UL)	// When can is in used should be set 1
#define IOBUS_I2C_M0		(IOBUS0_START + 29UL)
#define IOBUS_I2C_M1		(IOBUS0_START + 30UL)
#define IOBUS_I2C_M2		(IOBUS0_START + 31UL)
#define IOBUS0_END		(IOBUS0_START + 31UL)





#define IOBUS1_START		(IOBUS0_END + 1UL)
#define IOBUS1_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(IOBUS1_START)
#define IOBUS_I2C_M3		IOBUS1_START
#define IOBUS_I2C_S0		(IOBUS1_START + 1UL)
#define IOBUS_I2C_S1		(IOBUS1_START + 2UL)
#define IOBUS_I2C_G0		(IOBUS1_START + 3UL)	// When I2C is in used,
#define IOBUS_I2C_G1		(IOBUS1_START + 4UL)	// I2C0 & I2C1 should be set 1
#define IOBUS1_RESERVE5		(IOBUS1_START + 5UL)
#define IOBUS1_RESERVE6		(IOBUS1_START + 6UL)
#define IOBUS1_RESERVE7		(IOBUS1_START + 7UL)
#define IOBUS1_RESERVE8		(IOBUS1_START + 8UL)
#define IOBUS1_RESERVE9		(IOBUS1_START + 9UL)
#define IOBUS1_RESERVE10	(IOBUS1_START + 10UL)
#define IOBUS1_RESERVE11	(IOBUS1_START + 11UL)
#define IOBUS1_RESERVE12	(IOBUS1_START + 12UL)
#define IOBUS1_RESERVE13	(IOBUS1_START + 13UL)
#define IOBUS1_RESERVE14	(IOBUS1_START + 14UL)
#define IOBUS_TSIF_1		(IOBUS1_START + 15UL)
#define IOBUS_CAN_DMA_5		(IOBUS1_START + 16UL)
#define IOBUS_GPSB_G0		(IOBUS1_START + 17UL)	// When GPSB is in used should be set 1
#define IOBUS_ADC		(IOBUS1_START + 18UL)
#define IOBUS_GPSB0		(IOBUS1_START + 19UL)
#define IOBUS_GPSB1		(IOBUS1_START + 20UL)
#define IOBUS_GPSB2		(IOBUS1_START + 21UL)
#define IOBUS_GPSB4		(IOBUS1_START + 22UL)
#define IOBUS_GPSB5		(IOBUS1_START + 23UL)
#define IOBUS1_RESERVE24	(IOBUS1_START + 24UL)
#define IOBUS_GPSB_G1		(IOBUS1_START + 25UL)	// When GPSB is in used should be set 1
#define IOBUS_TSIF_0		(IOBUS1_START + 26UL)
#define IOBUS_I2C_S3		(IOBUS1_START + 27UL)
#define IOBUS_I2C_M4		(IOBUS1_START + 28UL)
#define IOBUS_I2C_M5		(IOBUS1_START + 29UL)
#define IOBUS_I2C_M6		(IOBUS1_START + 30UL)
#define IOBUS_I2C_M7		(IOBUS1_START + 31UL)
#define IOBUS1_END		(IOBUS1_START + 31UL)






#define IOBUS2_START		(IOBUS1_END + 1UL)
#define IOBUS2_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(IOBUS2_START)
#define IOBUS_UART0		IOBUS2_START
#define IOBUS_UART1		(IOBUS2_START + 1UL)
#define IOBUS_UART2		(IOBUS2_START + 2UL)
#define IOBUS_UART3		(IOBUS2_START + 3UL)
#define IOBUS_UART4		(IOBUS2_START + 4UL)
#define IOBUS_UART5		(IOBUS2_START + 5UL)
#define IOBUS_UART6		(IOBUS2_START + 6UL)
#define IOBUS_UART7		(IOBUS2_START + 7UL)
#define IOBUS_UART8		(IOBUS2_START + 8UL)
#define IOBUS2_RESERVE9		(IOBUS2_START + 9UL)
#define IOBUS2_RESERVE10	(IOBUS2_START + 10UL)
#define IOBUS2_RESERVE11	(IOBUS2_START + 11UL)
#define IOBUS2_RESERVE12	(IOBUS2_START + 12UL)
#define IOBUS2_RESERVE13	(IOBUS2_START + 13UL)
#define IOBUS2_RESERVE14	(IOBUS2_START + 14UL)
#define IOBUS2_RESERVE15	(IOBUS2_START + 15UL)
#define IOBUS_UDMA0		(IOBUS2_START + 16UL)
#define IOBUS_UDMA1		(IOBUS2_START + 17UL)
#define IOBUS_UDMA2		(IOBUS2_START + 18UL)
#define IOBUS_UDMA3		(IOBUS2_START + 19UL)
#define IOBUS_UART_G0		(IOBUS2_START + 20UL)	// When UART is used, should be set 1
#define IOBUS_UART_G1		(IOBUS2_START + 21UL)	// When UART is used, should be set 1
#define IOBUS_UDMA4		(IOBUS2_START + 22UL)
#define IOBUS_UDMA5		(IOBUS2_START + 23UL)
#define IOBUS_UDMA6		(IOBUS2_START + 24UL)
#define IOBUS_UDMA7		(IOBUS2_START + 25UL)	// When GPSB is in used should be set 1
#define IOBUS_UDMA8		(IOBUS2_START + 26UL)
#define IOBUS2_RESERVE27	(IOBUS2_START + 27UL)
#define IOBUS2_RESERVE28	(IOBUS2_START + 28UL)
#define IOBUS2_RESERVE29	(IOBUS2_START + 29UL)
#define IOBUS2_RESERVE30	(IOBUS2_START + 30UL)
#define IOBUS2_RESERVE31	(IOBUS2_START + 31UL)
#define IOBUS2_END		(IOBUS2_START + 31UL)






#define IOBUS_STRG_START	(IOBUS2_END + 1UL)
#define IOBUS_STRG_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(IOBUS_STRG_START)
#define IOBUS_DMA_G3		IOBUS_STRG_START
#define IOBUS_STRG_RESERVE1	(IOBUS_STRG_START + 1UL)
#define IOBUS_STRG_RESERVE2	(IOBUS_STRG_START + 2UL)
#define IOBUS_SDMMC1		(IOBUS_STRG_START + 3UL)
#define IOBUS_SDMMC2		(IOBUS_STRG_START + 4UL)
#define IOBUS_SDMMC		(IOBUS_STRG_START + 5UL)// When SDMMC is used, should be set 1
#define IOBUS_STRG_RESERVE6	(IOBUS_STRG_START + 6UL)
#define IOBUS_STRG_RESERVE7	(IOBUS_STRG_START + 7UL)
#define IOBUS_STRG_RESERVE8	(IOBUS_STRG_START + 8UL)
#define IOBUS_STRG_RESERVE9	(IOBUS_STRG_START + 9UL)
#define IOBUS_RTC		(IOBUS_STRG_START + 10UL)
#define IOBUS_STRG_RESERVE11	(IOBUS_STRG_START + 11UL)
#define IOBUS_STRG_RESERVE12	(IOBUS_STRG_START + 12UL)
#define IOBUS_STRG_RESERVE13	(IOBUS_STRG_START + 13UL)
#define IOBUS_STRG_RESERVE14	(IOBUS_STRG_START + 14UL)
#define IOBUS_STRG_RESERVE15	(IOBUS_STRG_START + 15UL)
#define IOBUS_STRG_RESERVE16	(IOBUS_STRG_START + 16UL)
#define IOBUS_STRG_RESERVE17	(IOBUS_STRG_START + 17UL)
#define IOBUS_STRG_RESERVE18	(IOBUS_STRG_START + 18UL)
#define IOBUS_STRG_RESERVE19	(IOBUS_STRG_START + 19UL)
#define IOBUS_STRG_RESERVE20	(IOBUS_STRG_START + 20UL)
#define IOBUS_STRG_RESERVE21	(IOBUS_STRG_START + 21UL)
#define IOBUS_STRG_RESERVE22	(IOBUS_STRG_START + 22UL)
#define IOBUS_STRG_RESERVE23	(IOBUS_STRG_START + 23UL)
#define IOBUS_STRG_RESERVE24	(IOBUS_STRG_START + 24UL)
#define IOBUS_STRG_RESERVE25	(IOBUS_STRG_START + 25UL)
#define IOBUS_STRG_RESERVE26	(IOBUS_STRG_START + 26UL)
#define IOBUS_STRG_RESERVE27	(IOBUS_STRG_START + 27UL)
#define IOBUS_STRG_RESERVE28	(IOBUS_STRG_START + 28UL)
#define IOBUS_STRG_RESERVE29	(IOBUS_STRG_START + 29UL)
#define IOBUS_STRG_RESERVE30	(IOBUS_STRG_START + 30UL)
#define IOBUS_STRG_RESERVE31	(IOBUS_STRG_START + 31UL)
#define IOBUS_STRG_END		(IOBUS_STRG_START + 31UL)






#define DDIBUS_START		(IOBUS_STRG_END + 1UL)
#define DDIBUS_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(DDIBUS_START)
#define DDIBUS_VIOC		DDIBUS_START
#define DDIBUS_RESERVE1		(DDIBUS_START + 1UL)
#define DDIBUS_RESERVE2		(DDIBUS_START + 2UL)
#define DDIBUS_RESERVE3		(DDIBUS_START + 3UL)
#define DDIBUS_RESERVE4		(DDIBUS_START + 4UL)
#define DDIBUS_RESERVE5		(DDIBUS_START + 5UL)
#define DDIBUS_RESERVE6		(DDIBUS_START + 6UL)
#define DDIBUS_RESERVE7		(DDIBUS_START + 7UL)
#define DDIBUS_RESERVE8		(DDIBUS_START + 8UL)
#define DDIBUS_RESERVE9		(DDIBUS_START + 9UL)
#define DDIBUS_RESERVE10	(DDIBUS_START + 10UL)
#define DDIBUS_RESERVE11	(DDIBUS_START + 11UL)
#define DDIBUS_RESERVE12	(DDIBUS_START + 12UL)
#define DDIBUS_RESERVE13	(DDIBUS_START + 13UL)
#define DDIBUS_RESERVE14	(DDIBUS_START + 14UL)
#define DDIBUS_RESERVE15	(DDIBUS_START + 15UL)
#define DDIBUS_RESERVE16	(DDIBUS_START + 16UL)
#define DDIBUS_RESERVE17	(DDIBUS_START + 17UL)
#define DDIBUS_RESERVE18	(DDIBUS_START + 18UL)
#define DDIBUS_RESERVE19	(DDIBUS_START + 19UL)
#define DDIBUS_RESERVE20	(DDIBUS_START + 20UL)
#define DDIBUS_RESERVE21	(DDIBUS_START + 21UL)
#define DDIBUS_RESERVE22	(DDIBUS_START + 22UL)
#define DDIBUS_RESERVE23	(DDIBUS_START + 23UL)
#define DDIBUS_RESERVE24	(DDIBUS_START + 24UL)
#define DDIBUS_RESERVE25	(DDIBUS_START + 25UL)
#define DDIBUS_RESERVE26	(DDIBUS_START + 26UL)
#define DDIBUS_RESERVE27	(DDIBUS_START + 27UL)
#define DDIBUS_RESERVE28	(DDIBUS_START + 28UL)
#define DDIBUS_RESERVE29	(DDIBUS_START + 29UL)
#define DDIBUS_RESERVE30	(DDIBUS_START + 30UL)
#define DDIBUS_RESERVE31	(DDIBUS_START + 31UL)
#define DDIBUS_END		(DDIBUS_START + 31UL)






#define VIDEOBUS_START		(DDIBUS_END + 1UL)
#define VIDEOBUS_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(VIDEOBUS_START)
#define VIDEOBUS_JPEG		VIDEOBUS_START
#define VIDEOBUS_CODA_BUS	(VIDEOBUS_START + 1UL)
#define VIDEOBUS_CODA_CORE	(VIDEOBUS_START + 2UL)
#define VIDEOBUS_HEVC_BUS	(VIDEOBUS_START + 3UL)
#define VIDEOBUS_HEVC_CORE	(VIDEOBUS_START + 4UL)
#define VIDEOBUS_HEVC_ENCODER	(VIDEOBUS_START + 5UL)
#define VIDEOBUS_RESERVE6	(VIDEOBUS_START + 6UL)
#define VIDEOBUS_RESERVE7	(VIDEOBUS_START + 7UL)
#define VIDEOBUS_RESERVE8	(VIDEOBUS_START + 8UL)
#define VIDEOBUS_RESERVE9	(VIDEOBUS_START + 9UL)
#define VIDEOBUS_RESERVE10	(VIDEOBUS_START + 10UL)
#define VIDEOBUS_RESERVE11	(VIDEOBUS_START + 11UL)
#define VIDEOBUS_RESERVE12	(VIDEOBUS_START + 12UL)
#define VIDEOBUS_RESERVE13	(VIDEOBUS_START + 13UL)
#define VIDEOBUS_RESERVE14	(VIDEOBUS_START + 14UL)
#define VIDEOBUS_RESERVE15	(VIDEOBUS_START + 15UL)
#define VIDEOBUS_RESERVE16	(VIDEOBUS_START + 16UL)
#define VIDEOBUS_RESERVE17	(VIDEOBUS_START + 17UL)
#define VIDEOBUS_RESERVE18	(VIDEOBUS_START + 18UL)
#define VIDEOBUS_RESERVE19	(VIDEOBUS_START + 19UL)
#define VIDEOBUS_RESERVE20	(VIDEOBUS_START + 20UL)
#define VIDEOBUS_RESERVE21	(VIDEOBUS_START + 21UL)
#define VIDEOBUS_RESERVE22	(VIDEOBUS_START + 22UL)
#define VIDEOBUS_RESERVE23	(VIDEOBUS_START + 23UL)
#define VIDEOBUS_RESERVE24	(VIDEOBUS_START + 24UL)
#define VIDEOBUS_RESERVE25	(VIDEOBUS_START + 25UL)
#define VIDEOBUS_RESERVE26	(VIDEOBUS_START + 26UL)
#define VIDEOBUS_RESERVE27	(VIDEOBUS_START + 27UL)
#define VIDEOBUS_RESERVE28	(VIDEOBUS_START + 28UL)
#define VIDEOBUS_RESERVE29	(VIDEOBUS_START + 29UL)
#define VIDEOBUS_RESERVE30	(VIDEOBUS_START + 30UL)
#define VIDEOBUS_RESERVE31	(VIDEOBUS_START + 31UL)
#define VIDEOBUS_END		(VIDEOBUS_START + 31UL)






#define HSIOBUS_START		(VIDEOBUS_END + 1UL)
#define HSIOBUS_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(HSIOBUS_START)
#define HSIOBUS_USB30		HSIOBUS_START
#define HSIOBUS_RESERVE1	(HSIOBUS_START + 1UL)
#define HSIOBUS_GMAC		(HSIOBUS_START + 2UL)
#define HSIOBUS_RESERVE3	(HSIOBUS_START + 3UL)
#define HSIOBUS_RESERVE4	(HSIOBUS_START + 4UL)
#define HSIOBUS_RESERVE5	(HSIOBUS_START + 5UL)
#define HSIOBUS_USB20H		(HSIOBUS_START + 6UL)
#define HSIOBUS_RESERVE7	(HSIOBUS_START + 7UL)
#define HSIOBUS_RESERVE8	(HSIOBUS_START + 8UL)
#define HSIOBUS_RESERVE9	(HSIOBUS_START + 9UL)
#define HSIOBUS_RESERVE10	(HSIOBUS_START + 10UL)
#define HSIOBUS_RESERVE11	(HSIOBUS_START + 11UL)
#define HSIOBUS_RESERVE12	(HSIOBUS_START + 12UL)
#define HSIOBUS_RESERVE13	(HSIOBUS_START + 13UL)
#define HSIOBUS_RESERVE14	(HSIOBUS_START + 14UL)
#define HSIOBUS_RESERVE15	(HSIOBUS_START + 15UL)
#define HSIOBUS_RESERVE16	(HSIOBUS_START + 16UL)
#define HSIOBUS_RESERVE17	(HSIOBUS_START + 17UL)
#define HSIOBUS_CIPHER		(HSIOBUS_START + 18UL)
#define HSIOBUS_DWC_OTG		(HSIOBUS_START + 19UL)
#define HSIOBUS_RESERVE20	(HSIOBUS_START + 20UL)
#define HSIOBUS_SECURE_WRAP	(HSIOBUS_START + 21UL)
#define HSIOBUS_TRNG		(HSIOBUS_START + 22UL)
#define HSIOBUS_RESERVE23	(HSIOBUS_START + 23UL)
#define HSIOBUS_RESERVE24	(HSIOBUS_START + 24UL)
#define HSIOBUS_RESERVE25	(HSIOBUS_START + 25UL)
#define HSIOBUS_RESERVE26	(HSIOBUS_START + 26UL)
#define HSIOBUS_RESERVE27	(HSIOBUS_START + 27UL)
#define HSIOBUS_RESERVE28	(HSIOBUS_START + 28UL)
#define HSIOBUS_RESERVE29	(HSIOBUS_START + 29UL)
#define HSIOBUS_RESERVE30	(HSIOBUS_START + 30UL)
#define HSIOBUS_RESERVE31	(HSIOBUS_START + 31UL)
#define HSIOBUS_END		(HSIOBUS_START + 31UL)






#define AUDIOBUS0_START		(HSIOBUS_END + 1UL)
#define AUDIOBUS0_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(AUDIOBUS0_START)
#define AUDIOBUS_MAIC0_DMA	AUDIOBUS0_START
#define AUDIOBUS_MAIC0_DAIF	(AUDIOBUS0_START + 1UL)
#define AUDIOBUS_MAIC0_SPDIF	(AUDIOBUS0_START + 2UL)
#define AUDIOBUS_MAIC1_DMA	(AUDIOBUS0_START + 3UL)
#define AUDIOBUS_MAIC1_DAIF	(AUDIOBUS0_START + 4UL)
#define AUDIOBUS_MAIC1_SPDIF	(AUDIOBUS0_START + 5UL)
#define AUDIOBUS_MAIC2_DMA	(AUDIOBUS0_START + 6UL)
#define AUDIOBUS_MAIC2_DAIF	(AUDIOBUS0_START + 7UL)
#define AUDIOBUS_MAIC2_SPDIF	(AUDIOBUS0_START + 8UL)
#define AUDIOBUS_MAIC3_DMA	(AUDIOBUS0_START + 9UL)
#define AUDIOBUS_MAIC3_DAIF	(AUDIOBUS0_START + 10UL)
#define AUDIOBUS_MAIC3_SPDIF	(AUDIOBUS0_START + 11UL)
#define AUDIOBUS_MAIC4_DMA	(AUDIOBUS0_START + 12UL)
#define AUDIOBUS_MAIC4_DAIF	(AUDIOBUS0_START + 13UL)
#define AUDIOBUS_MAIC4_SPDIF	(AUDIOBUS0_START + 14UL)
#define AUDIOBUS_MAIC5_DMA	(AUDIOBUS0_START + 15UL)
#define AUDIOBUS_MAIC5_DAIF	(AUDIOBUS0_START + 16UL)
#define AUDIOBUS_MAIC5_SPDIF	(AUDIOBUS0_START + 17UL)
#define AUDIOBUS_MAIC6_DMA	(AUDIOBUS0_START + 18UL)
#define AUDIOBUS_MAIC6_DAIF	(AUDIOBUS0_START + 19UL)
#define AUDIOBUS_MAIC6_SPDIF	(AUDIOBUS0_START + 20UL)
#define AUDIOBUS_MAIC7_DMA	(AUDIOBUS0_START + 21UL)
#define AUDIOBUS_MAIC7_DAIF	(AUDIOBUS0_START + 22UL)
#define AUDIOBUS_MAIC7_SPDIF	(AUDIOBUS0_START + 23UL)
#define AUDIOBUS_MAVC_0 	(AUDIOBUS0_START + 24UL)
#define AUDIOBUS_MAVC_1 	(AUDIOBUS0_START + 25UL)
#define AUDIOBUS_MAVC_2 	(AUDIOBUS0_START + 26UL)
#define AUDIOBUS_MAVC_3 	(AUDIOBUS0_START + 27UL)
#define AUDIOBUS_MAVC_4 	(AUDIOBUS0_START + 28UL)
#define AUDIOBUS_MAVC_5 	(AUDIOBUS0_START + 29UL)
#define AUDIOBUS_MAVC_6 	(AUDIOBUS0_START + 30UL)
#define AUDIOBUS_MAVC_7 	(AUDIOBUS0_START + 31UL)
#define AUDIOBUS0_END		(AUDIOBUS0_START + 31UL)






#define AUDIOBUS1_START		(AUDIOBUS0_END + 1UL)
#define AUDIOBUS1_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(AUDIOBUS1_START)
#define AUDIOBUS_MARS_0		AUDIOBUS1_START
#define AUDIOBUS_MARS_1		(AUDIOBUS1_START + 1UL)
#define AUDIOBUS_MARS_2		(AUDIOBUS1_START + 2UL)
#define AUDIOBUS_MARS_3		(AUDIOBUS1_START + 3UL)
#define AUDIOBUS_MARS_4		(AUDIOBUS1_START + 4UL)
#define AUDIOBUS_MARS_5		(AUDIOBUS1_START + 5UL)
#define AUDIOBUS_MASM_0		(AUDIOBUS1_START + 6UL)
#define AUDIOBUS_MASM_1		(AUDIOBUS1_START + 7UL)
#define AUDIOBUS_MASM_2		(AUDIOBUS1_START + 8UL)
#define AUDIOBUS_MASM_3		(AUDIOBUS1_START + 9UL)
#define AUDIOBUS_MASM_4		(AUDIOBUS1_START + 10UL)
#define AUDIOBUS_MASRC_0	(AUDIOBUS1_START + 11UL)
#define AUDIOBUS_MASRC_1	(AUDIOBUS1_START + 12UL)
#define AUDIOBUS_MASRC_2	(AUDIOBUS1_START + 13UL)
#define AUDIOBUS_MASRC_3	(AUDIOBUS1_START + 14UL)
#define AUDIOBUS_MASRC_4	(AUDIOBUS1_START + 15UL)
#define AUDIOBUS_MASRC_5	(AUDIOBUS1_START + 16UL)
#define AUDIOBUS_MAFC_0		(AUDIOBUS1_START + 17UL)
#define AUDIOBUS_MAFC_1		(AUDIOBUS1_START + 18UL)
#define AUDIOBUS_MAFC_2		(AUDIOBUS1_START + 19UL)
#define AUDIOBUS_MAFC_3		(AUDIOBUS1_START + 20UL)
#define AUDIOBUS_CFG		(AUDIOBUS1_START + 21UL)
#define AUDIOBUS_SRAM		(AUDIOBUS1_START + 22UL)
#define AUDIOBUS_RESERVE23	(AUDIOBUS1_START + 23UL)
#define AUDIOBUS_RESERVE24 	(AUDIOBUS1_START + 24UL)
#define AUDIOBUS_RESERVE25 	(AUDIOBUS1_START + 25UL)
#define AUDIOBUS_RESERVE26 	(AUDIOBUS1_START + 26UL)
#define AUDIOBUS_RESERVE27 	(AUDIOBUS1_START + 27UL)
#define AUDIOBUS_RESERVE28 	(AUDIOBUS1_START + 28UL)
#define AUDIOBUS_RESERVE29 	(AUDIOBUS1_START + 29UL)
#define AUDIOBUS_RESERVE30 	(AUDIOBUS1_START + 30UL)
#define AUDIOBUS_RESERVE31 	(AUDIOBUS1_START + 31UL)
#define AUDIOBUS1_END		(AUDIOBUS1_START + 31UL)





/* CAMERA BUS SWRESET */
#define CAMBUS0_SWRST_START		(AUDIOBUS1_END + 1UL)
#define CAMBUS0_SWRST_EN		CKC_SWRST_CLKEN_ID(CAMBUS0_SWRST_START)
#define CAMBUS_MIPI0_SWRST		CAMBUS0_SWRST_START
#define CAMBUS_MIPI0_PHY_M_SWRST	(CAMBUS0_SWRST_START + 1UL)
#define CAMBUS_MIPI0_PHY_S_SWRST	(CAMBUS0_SWRST_START + 2UL)
#define CAMBUS_MIPI0_PHY_APB_SWRST	(CAMBUS0_SWRST_START + 3UL)
#define CAMBUS_MIPI0_CSI_SWRST		(CAMBUS0_SWRST_START + 4UL)
#define CAMBUS_MIPI0_GDP_PIX_SWRST	(CAMBUS0_SWRST_START + 5UL)
#define CAMBUS_MIPI0_GDP_APB_SWRST	(CAMBUS0_SWRST_START + 6UL)
#define CAMBUS_MIPI0_DSI_SWRST		(CAMBUS0_SWRST_START + 7UL)
#define CAMBUS_MIPI1_SWRST		(CAMBUS0_SWRST_START + 8UL)
#define CAMBUS_MIPI1_PHY_M_SWRST	(CAMBUS0_SWRST_START + 9UL)
#define CAMBUS_MIPI1_PHY_S_SWRST	(CAMBUS0_SWRST_START + 10UL)
#define CAMBUS_MIPI1_PHY_APB_SWRST	(CAMBUS0_SWRST_START + 11UL)
#define CAMBUS_MIPI1_CSI_SWRST		(CAMBUS0_SWRST_START + 12UL)
#define CAMBUS_MIPI1_GDP_PIX_SWRST	(CAMBUS0_SWRST_START + 13UL)
#define CAMBUS_MIPI1_GDP_APB_SWRST	(CAMBUS0_SWRST_START + 14UL)
#define CAMBUS_MIPI1_DSI_SWRST		(CAMBUS0_SWRST_START + 15UL)
#define CAMBUS_ISP_BUS_SWRST		(CAMBUS0_SWRST_START + 16UL)
#define CAMBUS_ISP_RISCV_SWRST		(CAMBUS0_SWRST_START + 17UL)
#define CAMBUS_ISP_PIX_SWRST		(CAMBUS0_SWRST_START + 18UL)
#define CAMBUS0_RESERVE19_SWRST		(CAMBUS0_SWRST_START + 19UL)
#define CAMBUS0_RESERVE20_SWRST		(CAMBUS0_SWRST_START + 20UL)
#define CAMBUS0_RESERVE21_SWRST		(CAMBUS0_SWRST_START + 21UL)
#define CAMBUS0_RESERVE22_SWRST		(CAMBUS0_SWRST_START + 22UL)
#define CAMBUS0_RESERVE23_SWRST		(CAMBUS0_SWRST_START + 23UL)
#define CAMBUS_RISYNC0_APB_SWRST	(CAMBUS0_SWRST_START + 24UL)
#define CAMBUS_RISYNC0_CORE_SWRST	(CAMBUS0_SWRST_START + 25UL)
#define CAMBUS_RISYNC1_APB_SWRST	(CAMBUS0_SWRST_START + 26UL)
#define CAMBUS_RISYNC1_CORE_SWRST	(CAMBUS0_SWRST_START + 27UL)
#define CAMBUS0_RESERVE28_SWRST		(CAMBUS0_SWRST_START + 28UL)
#define CAMBUS0_RESERVE29_SWRST		(CAMBUS0_SWRST_START + 29UL)
#define CAMBUS0_RESERVE30_SWRST		(CAMBUS0_SWRST_START + 30UL)
#define CAMBUS0_RESERVE31_SWRST		(CAMBUS0_SWRST_START + 31UL)
#define CAMBUS0_SWRST_END		(CAMBUS0_SWRST_START + 31UL)






#define CAMBUS1_SWRST_START		(CAMBUS0_SWRST_END + 1UL)
#define CAMBUS1_SWRST_EN		CKC_SWRST_CLKEN_ID(CAMBUS1_SWRST_START)
#define CAMBUS_CIED0_SWRST		CAMBUS1_SWRST_START
#define CAMBUS_CIED1_SWRST		(CAMBUS1_SWRST_START + 1UL)
#define CAMBUS_CIED2_SWRST		(CAMBUS1_SWRST_START + 2UL)
#define CAMBUS_CIED3_SWRST		(CAMBUS1_SWRST_START + 3UL)
#define CAMBUS_CIED4_SWRST		(CAMBUS1_SWRST_START + 4UL)
#define CAMBUS_CIED5_SWRST		(CAMBUS1_SWRST_START + 5UL)
#define CAMBUS_CIED6_SWRST		(CAMBUS1_SWRST_START + 6UL)
#define CAMBUS_CIED7_SWRST		(CAMBUS1_SWRST_START + 7UL)
#define CAMBUS_CIED8_SWRST		(CAMBUS1_SWRST_START + 8UL)
#define CAMBUS_CIED9_SWRST		(CAMBUS1_SWRST_START + 9UL)
#define CAMBUS_SVM_SWRST		(CAMBUS1_SWRST_START + 10UL)
#define CAMBUS_VIN_SWRST		(CAMBUS1_SWRST_START + 11UL)
#define CAMBUS_DEWARP_SWRST		(CAMBUS1_SWRST_START + 12UL)
#define CAMBUS_XBAR_SWRST		(CAMBUS1_SWRST_START + 13UL)
#define CAMBUS1_RESERVE14_SWRST		(CAMBUS1_SWRST_START + 14UL)
#define CAMBUS1_RESERVE15_SWRST		(CAMBUS1_SWRST_START + 15UL)
#define CAMBUS1_RESERVE16_SWRST		(CAMBUS1_SWRST_START + 16UL)
#define CAMBUS1_RESERVE17_SWRST		(CAMBUS1_SWRST_START + 17UL)
#define CAMBUS1_RESERVE18_SWRST		(CAMBUS1_SWRST_START + 18UL)
#define CAMBUS1_RESERVE19_SWRST		(CAMBUS1_SWRST_START + 19UL)
#define CAMBUS1_RESERVE20_SWRST		(CAMBUS1_SWRST_START + 20UL)
#define CAMBUS1_RESERVE21_SWRST		(CAMBUS1_SWRST_START + 21UL)
#define CAMBUS1_RESERVE22_SWRST		(CAMBUS1_SWRST_START + 22UL)
#define CAMBUS1_RESERVE23_SWRST		(CAMBUS1_SWRST_START + 23UL)
#define CAMBUS1_RESERVE24_SWRST		(CAMBUS1_SWRST_START + 24UL)
#define CAMBUS1_RESERVE25_SWRST		(CAMBUS1_SWRST_START + 25UL)
#define CAMBUS1_RESERVE26_SWRST		(CAMBUS1_SWRST_START + 26UL)
#define CAMBUS1_RESERVE27_SWRST		(CAMBUS1_SWRST_START + 27UL)
#define CAMBUS1_RESERVE28_SWRST		(CAMBUS1_SWRST_START + 28UL)
#define CAMBUS1_RESERVE29_SWRST		(CAMBUS1_SWRST_START + 29UL)
#define CAMBUS1_RESERVE30_SWRST		(CAMBUS1_SWRST_START + 30UL)
#define CAMBUS1_RESERVE31_SWRST		(CAMBUS1_SWRST_START + 31UL)
#define CAMBUS1_SWRST_END		(CAMBUS1_SWRST_START + 31UL)





/* CAMERA BUS CLKMASK */
#define CAMBUS0_CLKMASK_START		(CAMBUS1_SWRST_END + 1UL)
#define CAMBUS0_CLK_EN			CKC_SWRST_CLKEN_ID(CAMBUS0_CLKMASK_START)
#define CAMBUS_MIPI0_CLK_MASK		CAMBUS0_CLKMASK_START
#define CAMBUS_MIPI0_PHY_APB_MASK	(CAMBUS0_CLKMASK_START + 1UL)
#define CAMBUS_MIPI0_CSI_APB_MASK	(CAMBUS0_CLKMASK_START + 2UL)
#define CAMBUS_MIPI0_CSI_PIX_MASK	(CAMBUS0_CLKMASK_START + 3UL)
#define CAMBUS_MIPI0_GDP_APB_MASK	(CAMBUS0_CLKMASK_START + 4UL)
#define CAMBUS_MIPI0_GDP_PIX_MASK	(CAMBUS0_CLKMASK_START + 5UL)
#define CAMBUS_MIPI0_DSI_APB_MASK	(CAMBUS0_CLKMASK_START + 6UL)
#define CAMBUS_MIPI0_DSI_SYS_MASK	(CAMBUS0_CLKMASK_START + 7UL)
#define CAMBUS_MIPI1_CLK_MASK	        (CAMBUS0_CLKMASK_START + 8UL)
#define CAMBUS_MIPI1_PHY_APB_MASK	(CAMBUS0_CLKMASK_START + 9UL)
#define CAMBUS_MIPI1_CSI_APB_MASK	(CAMBUS0_CLKMASK_START + 10UL)
#define CAMBUS_MIPI1_CSI_PIX_MASK	(CAMBUS0_CLKMASK_START + 11UL)
#define CAMBUS_MIPI1_GDP_APB_MASK	(CAMBUS0_CLKMASK_START + 12UL)
#define CAMBUS_MIPI1_GDP_PIX_MASK	(CAMBUS0_CLKMASK_START + 13UL)
#define CAMBUS_MIPI1_DSI_APB_MASK	(CAMBUS0_CLKMASK_START + 14UL)
#define CAMBUS_MIPI1_DSI_SYS_MASK	(CAMBUS0_CLKMASK_START + 15UL)
#define CAMBUS_ISP_BUS_MASK		(CAMBUS0_CLKMASK_START + 16UL)
#define CAMBUS_ISP_APB_MASK		(CAMBUS0_CLKMASK_START + 17UL)
#define CAMBUS_ISP0_PIX_MASK		(CAMBUS0_CLKMASK_START + 18UL)
#define CAMBUS_ISP1_PIX_MASK		(CAMBUS0_CLKMASK_START + 19UL)
#define CAMBUS_ISP2_PIX_MASK		(CAMBUS0_CLKMASK_START + 20UL)
#define CAMBUS_ISP3_PIX_MASK		(CAMBUS0_CLKMASK_START + 21UL)
#define CAMBUS_RISYNC0_APB_MASK		(CAMBUS0_CLKMASK_START + 22UL)
#define CAMBUS_RISYNC0_PIX_MASK		(CAMBUS0_CLKMASK_START + 23UL)
#define CAMBUS_RISYNC1_APB_MASK 	(CAMBUS0_CLKMASK_START + 24UL)
#define CAMBUS_RISYNC1_PIX_MASK 	(CAMBUS0_CLKMASK_START + 25UL)
#define CAMBUS_VIN_APB_MASK	 	(CAMBUS0_CLKMASK_START + 26UL)
#define CAMBUS_VIN_AIX_MASK	 	(CAMBUS0_CLKMASK_START + 27UL)
#define CAMBUS_VIN_PIX0_MASK 		(CAMBUS0_CLKMASK_START + 28UL)
#define CAMBUS_VIN_PIX1_MASK 		(CAMBUS0_CLKMASK_START + 29UL)
#define CAMBUS_VIN_PIX2_MASK 		(CAMBUS0_CLKMASK_START + 30UL)
#define CAMBUS_VIN_PIX3_MASK		(CAMBUS0_CLKMASK_START + 31UL)
#define CAMBUS0_CLKMASK_END		(CAMBUS0_CLKMASK_START + 31UL)






#define CAMBUS1_CLKMASK_START		(CAMBUS0_CLKMASK_END + 1UL)
#define CAMBUS1_CLK_EN			CKC_SWRST_CLKEN_ID(CAMBUS1_CLKMASK_START)
#define CAMBUS_CIED0_APB_MASK		CAMBUS1_CLKMASK_START
#define CAMBUS_CIED0_PIX_MASK		(CAMBUS1_CLKMASK_START + 1UL)
#define CAMBUS_CIED1_APB_MASK		(CAMBUS1_CLKMASK_START + 2UL)
#define CAMBUS_CIED1_PIX_MASK		(CAMBUS1_CLKMASK_START + 3UL)
#define CAMBUS_CIED2_APB_MASK		(CAMBUS1_CLKMASK_START + 4UL)
#define CAMBUS_CIED2_PIX_MASK		(CAMBUS1_CLKMASK_START + 5UL)
#define CAMBUS_CIED3_APB_MASK		(CAMBUS1_CLKMASK_START + 6UL)
#define CAMBUS_CIED3_PIX_MASK		(CAMBUS1_CLKMASK_START + 7UL)
#define CAMBUS_CIED4_APB_MASK	        (CAMBUS1_CLKMASK_START + 8UL)
#define CAMBUS_CIED4_PIX_MASK		(CAMBUS1_CLKMASK_START + 9UL)
#define CAMBUS_CIED5_APB_MASK		(CAMBUS1_CLKMASK_START + 10UL)
#define CAMBUS_CIED5_PIX_MASK		(CAMBUS1_CLKMASK_START + 11UL)
#define CAMBUS_CIED6_APB_MASK		(CAMBUS1_CLKMASK_START + 12UL)
#define CAMBUS_CIED6_PIX_MASK		(CAMBUS1_CLKMASK_START + 13UL)
#define CAMBUS_CIED7_APB_MASK	        (CAMBUS1_CLKMASK_START + 14UL)
#define CAMBUS_CIED7_PIX_MASK	        (CAMBUS1_CLKMASK_START + 15UL)
#define CAMBUS_CIED8_APB_MASK	        (CAMBUS1_CLKMASK_START + 16UL)
#define CAMBUS_CIED8_PIX_MASK	        (CAMBUS1_CLKMASK_START + 17UL)
#define CAMBUS_CIED9_APB_MASK	        (CAMBUS1_CLKMASK_START + 18UL)
#define CAMBUS_CIED9_PIX_MASK	        (CAMBUS1_CLKMASK_START + 19UL)
#define CAMBUS_SVDM_CORE_MASK	        (CAMBUS1_CLKMASK_START + 20UL)
#define CAMBUS_SVDM_PIX0_MASK	        (CAMBUS1_CLKMASK_START + 21UL)
#define CAMBUS_SVDM_PIX1_MASK	        (CAMBUS1_CLKMASK_START + 22UL)
#define CAMBUS_SVDM_PIX2_MASK	        (CAMBUS1_CLKMASK_START + 23UL)
#define CAMBUS_SVDM_PIX3_MASK	        (CAMBUS1_CLKMASK_START + 24UL)
#define CAMBUS_SVDM_APB_MASK 	        (CAMBUS1_CLKMASK_START + 25UL)
#define CAMBUS_SVDM_AXI_MASK 	        (CAMBUS1_CLKMASK_START + 26UL)
#define CAMBUS_MDW_APB_MASK	        (CAMBUS1_CLKMASK_START + 27UL)
#define CAMBUS_MDW_AXI_MASK	        (CAMBUS1_CLKMASK_START + 28UL)
#define CAMBUS_X2X_SLV_APB_MASK	        (CAMBUS1_CLKMASK_START + 29UL)
#define CAMBUS_X2X_SLV_AXI_MASK	        (CAMBUS1_CLKMASK_START + 30UL)
#define CAMBUS1_RESERVE31_MASK 	        (CAMBUS1_CLKMASK_START + 31UL)
#define CAMBUS1_CLKAMSK_END	        (CAMBUS1_CLKMASK_START + 31UL)






#define NPUBUS_START		(CAMBUS1_CLKAMSK_END + 1UL)
#define NPUBUS_CLK_SWRST_EN	CKC_SWRST_CLKEN_ID(NPUBUS_START)
#define NPUBUS_X2X		NPUBUS_START
#define NPUBUS_RESERVE1		(NPUBUS_START + 1UL)
#define NPUBUS_RESERVE2		(NPUBUS_START + 2UL)
#define NPUBUS_RESERVE3		(NPUBUS_START + 3UL)
#define NPUBUS_H2H		(NPUBUS_START + 4UL)
#define NPUBUS_RESERVE5		(NPUBUS_START + 5UL)
#define NPUBUS_RESERVE6		(NPUBUS_START + 6UL)
#define NPUBUS_RESERVE7		(NPUBUS_START + 7UL)
#define NPUBUS_NPU		(NPUBUS_START + 8UL)
#define NPUBUS_RESERVE9		(NPUBUS_START + 9UL)
#define NPUBUS_RESERVE10	(NPUBUS_START + 10UL)
#define NPUBUS_RESERVE11	(NPUBUS_START + 11UL)
#define NPUBUS_SECURE		(NPUBUS_START + 12UL)
#define NPUBUS_RESERVE13	(NPUBUS_START + 13UL)
#define NPUBUS_RESERVE14	(NPUBUS_START + 14UL)
#define NPUBUS_RESERVE15	(NPUBUS_START + 15UL)
#define NPUBUS_RESERVE16	(NPUBUS_START + 16UL)
#define NPUBUS_RESERVE17	(NPUBUS_START + 17UL)
#define NPUBUS_RESERVE18	(NPUBUS_START + 18UL)
#define NPUBUS_RESERVE19	(NPUBUS_START + 19UL)
#define NPUBUS_RESERVE20	(NPUBUS_START + 20UL)
#define NPUBUS_RESERVE21	(NPUBUS_START + 21UL)
#define NPUBUS_RESERVE22	(NPUBUS_START + 22UL)
#define NPUBUS_RESERVE23	(NPUBUS_START + 23UL)
#define NPUBUS_RESERVE24 	(NPUBUS_START + 24UL)
#define NPUBUS_RESERVE25 	(NPUBUS_START + 25UL)
#define NPUBUS_RESERVE26 	(NPUBUS_START + 26UL)
#define NPUBUS_RESERVE27 	(NPUBUS_START + 27UL)
#define NPUBUS_RESERVE28 	(NPUBUS_START + 28UL)
#define NPUBUS_RESERVE29 	(NPUBUS_START + 29UL)
#define NPUBUS_RESERVE30 	(NPUBUS_START + 30UL)
#define NPUBUS_RESERVE31 	(NPUBUS_START + 31UL)
#define NPUBUS_END		(NPUBUS_START + 31UL)


/* PLL source clock (Not support CLK_F_GET_SRC_CLK yet..) */
#define PLL_SRC_XIN	0UL

/* Source clock flags for CLK_F_GET_SRC_CLK */
/* SMU BUS SEL */
#define SMU_CLKCTRL_SEL_PLL0		0UL
#define SMU_CLKCTRL_SEL_PLL1		1UL
#define SMU_CLKCTRL_SEL_PLL2		2UL
#define SMU_CLKCTRL_SEL_PLL3		3UL
#define SMU_CLKCTRL_SEL_PLL4		4UL
#define SMU_CLKCTRL_SEL_XIN		5UL

#define SMU_CLKCTRL_SEL_PLL0DIV		7UL
#define SMU_CLKCTRL_SEL_PLL1DIV		8UL
#define SMU_CLKCTRL_SEL_PLL2DIV		9UL
#define SMU_CLKCTRL_SEL_PLL3DIV		10UL
#define SMU_CLKCTRL_SEL_PLL4DIV		11UL
#define SMU_CLKCTRL_SEL_XINDIV		12UL

#define SMU_CLKCTRL_SEL_EXTIN2		14UL
#define SMU_CLKCTRL_SEL_EXTIN3		15UL

/* CPU BUS SEL */
#define CPU_CLKCTRL_SEL_XIN		0UL
#define CPU_CLKCTRL_SEL_PLL		1UL
#define CPU_CLKCTRL_SEL_PLLDIV		2UL
#define CPU_CLKCTRL_SEL_EXTCLK		3UL

/* MEM BUS SEL */
#define MEM_CLKCTRL_SEL_XIN		0UL
#define MEM_CLKCTRL_SEL_PLL0		1UL
#define MEM_CLKCTRL_SEL_PLL1		2UL
#define MEM_CLKCTRL_SEL_PLL0_DIV0	3UL
#define MEM_CLKCTRL_SEL_PLL0_DIV1	4UL
#define MEM_CLKCTRL_SEL_PLL1_DIV0	5UL
#define MEM_CLKCTRL_SEL_PLL1_DIV1	6UL
#define MEM_CLKCTRL_SEL_XTIN		7UL
#define MEM_CLKCTRL_SEL_EXTCLK		0xFUL

/* GPU/G2D BUS SEL */
#define GPU_CLKCTRL_SEL_XIN		0UL
#define GPU_CLKCTRL_SEL_PLL		1UL
#define GPU_CLKCTRL_SEL_PLLDIV		2UL
#define GPU_CLKCTRL_SEL_EXTCLK		3UL

/* DISPLAY BUS SEL */
#define DDI_CLKCTRL_SEL_XIN		0UL
#define DDI_CLKCTRL_SEL_PLL		1UL
#define DDI_CLKCTRL_SEL_PLLDIV		2UL

/* VPU BUS SEL */
#define VPU_CLKCTRL_SEL_XIN		0UL
#define VPU_CLKCTRL_SEL_PLL0		1UL
#define VPU_CLKCTRL_SEL_PLL1		2UL
#define VPU_CLKCTRL_SEL_PLL0_DIV0	3UL
#define VPU_CLKCTRL_SEL_PLL0_DIV1	4UL
#define VPU_CLKCTRL_SEL_PLL1_DIV0	5UL
#define VPU_CLKCTRL_SEL_PLL1_DIV1	6UL
#define VPU_CLKCTRL_SEL_EXTCLK		7UL

/* AUDIO BUS SEL */
#define AUDIO_CLKCTRL_SEL_XIN		0UL
#define AUDIO_CLKCTRL_SEL_PLL0		1UL
#define AUDIO_CLKCTRL_SEL_PLL1		2UL
#define AUDIO_CLKCTRL_SEL_XIN_DIV	3UL
#define AUDIO_CLKCTRL_SEL_PLL0_DIV	4UL
#define AUDIO_CLKCTRL_SEL_PLL1_DIV	5UL

/* NPU BUS SEL */
#define NPU_CLKCTRL_SEL_XIN		0UL
#define NPU_CLKCTRL_SEL_PLL		1UL
#define NPU_CLKCTRL_SEL_PLLDIV		2UL
#define NPU_CLKCTRL_SEL_EXTCLK		3UL

/* CAM BUS SEL */
#define CAM_CLKCTRL_SEL_XIN		0UL
#define CAM_CLKCTRL_SEL_PLL		1UL
#define CAM_CLKCTRL_SEL_PLLDIV		2UL

/* SMU Peripheral SEL */
#define SMU_PCLKCTRL_SEL_PLL0		0UL
#define SMU_PCLKCTRL_SEL_PLL1		1UL
#define SMU_PCLKCTRL_SEL_PLL2		2UL
#define SMU_PCLKCTRL_SEL_PLL3		3UL
#define SMU_PCLKCTRL_SEL_PLL4		4UL
#define SMU_PCLKCTRL_SEL_XIN		5UL
#define SMU_PCLKCTRL_SEL_XTIN		6UL

#define SMU_PCLKCTRL_SEL_PLL0DIV	10UL
#define SMU_PCLKCTRL_SEL_PLL1DIV	11UL
#define SMU_PCLKCTRL_SEL_PLL2DIV	12UL
#define SMU_PCLKCTRL_SEL_PLL3DIV	13UL
#define SMU_PCLKCTRL_SEL_PLL4DIV	14UL

#define SMU_PCLKCTRL_SEL_PCI0PHY	18UL
#define SMU_PCLKCTRL_SEL_PCI1PHY	19UL

#define SMU_PCLKCTRL_SEL_XINDIV		23UL
#define SMU_PCLKCTRL_SEL_XTINDIV	24UL
#define SMU_PCLKCTRL_SEL_EXTCLK0	25UL
#define SMU_PCLKCTRL_SEL_EXTCLK1	26UL


/* AUDIO Peripheral SEL */
#define AUDIO_PCLKCTRL_SEL_PLL0		0UL
#define AUDIO_PCLKCTRL_SEL_PLL1		1UL

#define AUDIO_PCLKCTRL_SEL_XIN		5UL

#define AUDIO_PCLKCTRL_SEL_PLL0DIV	10UL
#define AUDIO_PCLKCTRL_SEL_PLL1DIV	11UL

#define AUDIO_PCLKCTRL_SEL_DP_PLL	21UL

#define AUDIO_PCLKCTRL_SEL_XINDIV	23UL

#define AUDIO_PCLKCTRL_SEL_EXTCLK0	25UL
#define AUDIO_PCLKCTRL_SEL_EXTCLK1	26UL

#endif
