/* SPDX-License-Identifier: (GPL-2.0-or-later OR MIT) */
/*
 * Copyright (C) 2023 Telechips Inc.
 */

#ifndef DT_TCC750X_CLKS_H
#define DT_TCC750X_CLKS_H

#include <asm/arch-tcc750x/ckc_iomap.h>
#include <asm/arch-tcc750x/ckc_offset.h>
#include <asm/arch-tcc750x/ckc_flags.h>

/*
 * Clock index for device tree.
 * These values used for clock-indices in clock device node.
 * The index number MUST BE match with Kernel & U-Boot
 */
#define DECLARE_CLK_ID(base, offset, index) ((base) + (offset) + (index))

/* Oscillator index */
/* Unsed SMU CKC Address can be used for oscillator ID */
#define OSC_XIN			DECLARE_CLK_ID(TCC_CKC_BASE, 0xFF000UL, 0x000UL)


/* PLL index */
#define PLL_0			DECLARE_CLK_ID(TCC_CKC_BASE, CKC_PLLPMS, 0x00UL)
#define PLL_1			DECLARE_CLK_ID(TCC_CKC_BASE, CKC_PLLPMS, 0x04UL)
#define PLL_2			DECLARE_CLK_ID(TCC_CKC_BASE, CKC_PLLPMS, 0x08UL)
#define PLL_3			DECLARE_CLK_ID(TCC_CKC_BASE, CKC_PLLPMS, 0x0CUL)
#define PLL_4			DECLARE_CLK_ID(TCC_CKC_BASE, CKC_PLLPMS, 0x10UL)


#define PLL_CA53		DECLARE_CLK_ID(TCC_CPU_CKC_BASE, CPU_CKC_PLLPMS, 0x0UL)

#define PLL_MEM_PHY_0		DECLARE_CLK_ID(TCC_OMC_PHY0_PLL_BASE, MEM_PHY_PLLPMS, 0x0UL)
#define PLL_MEM_PHY_1		DECLARE_CLK_ID(TCC_OMC_PHY1_PLL_BASE, MEM_PHY_PLLPMS, 0x0UL)

#define PLL_CAM			DECLARE_CLK_ID(TCC_CAM_CKC_BASE, CAM_CKC_PLLPMS, 0x0UL)

#define PLL_NPU_0		DECLARE_CLK_ID(TCC_NPU_CKC_BASE, NPU_CKC_PLLPMS, 0x00UL)
#define PLL_NPU_1		DECLARE_CLK_ID(TCC_NPU_CKC_BASE, NPU_CKC_PLLPMS, 0x24UL)

#define PLL_VIDEO_0		DECLARE_CLK_ID(TCC_VIDIO_CKC_BASE, VIDEO_CKC_PLLPMS, 0x00UL)
#define PLL_VIDEO_1		DECLARE_CLK_ID(TCC_VIDIO_CKC_BASE, VIDEO_CKC_PLLPMS, 0x10UL)


/* Divider index */
#define OSC_XIN_DIV             DECLARE_CLK_ID(TCC_CKC_BASE,  CKC_CLKDIVC1, 0x1UL)

#define PLL_0_DIV		DECLARE_CLK_ID(TCC_CKC_BASE,  CKC_CLKDIVC0, 0x3UL)
#define PLL_1_DIV		DECLARE_CLK_ID(TCC_CKC_BASE,  CKC_CLKDIVC0, 0x2UL)
#define PLL_2_DIV		DECLARE_CLK_ID(TCC_CKC_BASE,  CKC_CLKDIVC0, 0x1UL)
#define PLL_3_DIV		DECLARE_CLK_ID(TCC_CKC_BASE,  CKC_CLKDIVC0, 0x0UL)
#define PLL_4_DIV		DECLARE_CLK_ID(TCC_CKC_BASE,  CKC_CLKDIVC1, 0x3UL)

#define PLL_CA53_DIV		DECLARE_CLK_ID(TCC_CPU_CKC_BASE,  CPU_CKC_CLKDIV, 0x0UL)

#define PLL_CAM_DIV_0		DECLARE_CLK_ID(TCC_CAM_CKC_BASE,  CAM_CKC_CLKDIV, 0x0UL)
#define PLL_CAM_DIV_1		DECLARE_CLK_ID(TCC_CAM_CKC_BASE,  CAM_CKC_CLKDIV, 0x4UL)
#define PLL_CAM_DIV_2		DECLARE_CLK_ID(TCC_CAM_CKC_BASE,  CAM_CKC_CLKDIV, 0x8UL)
#define PLL_CAM_DIV_3		DECLARE_CLK_ID(TCC_CAM_CKC_BASE,  CAM_CKC_CLKDIV, 0xCUL)

#define PLL_NPU_0_DIV_0		DECLARE_CLK_ID(TCC_NPU_CKC_BASE,  NPU_CKC_CLKDIV, (0x00UL+0x0UL))
#define PLL_NPU_1_DIV_0		DECLARE_CLK_ID(TCC_NPU_CKC_BASE,  NPU_CKC_CLKDIV, (0x00UL+0x1UL))
#define PLL_NPU_0_DIV_1		DECLARE_CLK_ID(TCC_NPU_CKC_BASE,  NPU_CKC_CLKDIV, (0x04UL+0x0UL))
#define PLL_NPU_1_DIV_1		DECLARE_CLK_ID(TCC_NPU_CKC_BASE,  NPU_CKC_CLKDIV, (0x04UL+0x1UL))
#define PLL_NPU_0_DIV_2		DECLARE_CLK_ID(TCC_NPU_CKC_BASE,  NPU_CKC_CLKDIV, (0x08UL+0x0UL))
#define PLL_NPU_1_DIV_2		DECLARE_CLK_ID(TCC_NPU_CKC_BASE,  NPU_CKC_CLKDIV, (0x08UL+0x1UL))
#define PLL_NPU_0_DIV_3		DECLARE_CLK_ID(TCC_NPU_CKC_BASE,  NPU_CKC_CLKDIV, (0x0CUL+0x0UL))
#define PLL_NPU_1_DIV_3		DECLARE_CLK_ID(TCC_NPU_CKC_BASE,  NPU_CKC_CLKDIV, (0x0CUL+0x1UL))
#define PLL_NPU_0_DIV_4		DECLARE_CLK_ID(TCC_NPU_CKC_BASE,  NPU_CKC_CLKDIV, (0x10UL+0x0UL))
#define PLL_NPU_1_DIV_4		DECLARE_CLK_ID(TCC_NPU_CKC_BASE,  NPU_CKC_CLKDIV, (0x10UL+0x1UL))
#define PLL_NPU_0_DIV_5		DECLARE_CLK_ID(TCC_NPU_CKC_BASE,  NPU_CKC_CLKDIV, (0x14UL+0x0UL))
#define PLL_NPU_1_DIV_5		DECLARE_CLK_ID(TCC_NPU_CKC_BASE,  NPU_CKC_CLKDIV, (0x14UL+0x1UL))
#define PLL_NPU_0_DIV_6		DECLARE_CLK_ID(TCC_NPU_CKC_BASE,  NPU_CKC_CLKDIV, (0x18UL+0x0UL))
#define PLL_NPU_1_DIV_6		DECLARE_CLK_ID(TCC_NPU_CKC_BASE,  NPU_CKC_CLKDIV, (0x18UL+0x1UL))

#define PLL_VIDEO_0_DIV_0	DECLARE_CLK_ID(TCC_VIDIO_CKC_BASE,  VIDEO_CKC_CLKDIV, 0x0UL)
#define PLL_VIDEO_0_DIV_1	DECLARE_CLK_ID(TCC_VIDIO_CKC_BASE,  VIDEO_CKC_CLKDIV, 0x1UL)
#define PLL_VIDEO_1_DIV_0	DECLARE_CLK_ID(TCC_VIDIO_CKC_BASE,  VIDEO_CKC_CLKDIV, 0x2UL)


/* CLKCTRL channel index */
#define FBUS_CPUBUS		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x000UL)
#define FBUS_OIC		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x004UL)
#define FBUS_OMC_ACLK		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x008UL)		// OMC Subsystem
#define FBUS_PCIe		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x00CUL)
#define FBUS_CAM		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x010UL)
#define FBUS_DDI		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x014UL)
#define FBUS_GMAC		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x018UL)
#define FBUS_OIC_CR		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x01CUL)
#define FBUS_IMEM		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x020UL)		// Internal Memroy
#define FBUS_HSM		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x024UL)
#define FBUS_CBC		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x028UL)
#define FBUS_DMA		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x02CUL)
#define FBUS_SFMC		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x030UL)
#define FBUS_SDMMC		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x034UL)
#define FBUS_CAN		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x038UL)
#define FBUS_UART		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x03CUL)
#define FBUS_GPSB		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x040UL)
#define FBUS_I2C		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x044UL)
#define FBUS_SYS		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x048UL)
#define FBUS_PMU		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x04CUL)
#define FBUS_MEMCFG		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x050UL)
#define FBUS_OTP		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x054UL)
#define FBUS_TZCFG		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x058UL)
#define FBUS_OMC_PCLK		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x05CUL)
#define FBUS_SIL		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x060UL)
#define FBUS_LIDAR_PROC		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x064UL)
#define FBUS_LIDAR_CTRL		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x068UL)
#define FBUS_OIC_PCDV		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x06CUL)
#define FBUS_OIC_SAFE_DAP	DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x070UL)
#define FBUS_OIC_NPU0		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x074UL)
#define FBUS_OIC_NPU1		DECLARE_CLK_ID(TCC_CKC_BASE, CKC_CLKCTRL, 0x078UL)

#define FBUS_CA53		DECLARE_CLK_ID(TCC_CPU_CKC_BASE, CAM_CKC_CLKCTRL, 0x0UL)

#define FBUS_CAM_AXI		DECLARE_CLK_ID(TCC_CAM_CKC_BASE, CAM_CKC_CLKCTRL, 0x0UL)
#define FBUS_CAM_PIX		DECLARE_CLK_ID(TCC_CAM_CKC_BASE, CAM_CKC_CLKCTRL, 0x4UL)
#define FBUS_CAM_APB		DECLARE_CLK_ID(TCC_CAM_CKC_BASE, CAM_CKC_CLKCTRL, 0x8UL)
#define FBUS_CAM_PERI		DECLARE_CLK_ID(TCC_CAM_CKC_BASE, CAM_CKC_CLKCTRL, 0xCUL)

#define FBUS_NPU_0_ACLK		DECLARE_CLK_ID(TCC_NPU_CKC_BASE, NPU_CKC_CLKCTRL, 0x000UL)
#define FBUS_NPU_PCLK		DECLARE_CLK_ID(TCC_NPU_CKC_BASE, NPU_CKC_CLKCTRL, 0x004UL)
#define FBUS_NPU_0_CCLK		DECLARE_CLK_ID(TCC_NPU_CKC_BASE, NPU_CKC_CLKCTRL, 0x008UL)
#define FBUS_NPU_0_CPUCLK	DECLARE_CLK_ID(TCC_NPU_CKC_BASE, NPU_CKC_CLKCTRL, 0x00CUL)
#define FBUS_NPU_1_ACLK		DECLARE_CLK_ID(TCC_NPU_CKC_BASE, NPU_CKC_CLKCTRL, 0x028UL)
#define FBUS_NPU_1_CCLK		DECLARE_CLK_ID(TCC_NPU_CKC_BASE, NPU_CKC_CLKCTRL, 0x02CUL)
#define FBUS_NPU_1_CPUCLK	DECLARE_CLK_ID(TCC_NPU_CKC_BASE, NPU_CKC_CLKCTRL, 0x030UL)

#define FBUS_VBUS		DECLARE_CLK_ID(TCC_VIDIO_CKC_BASE, VIDEO_CKC_CLKCTRL, 0x00UL)
#define FBUS_CHEVCENC		DECLARE_CLK_ID(TCC_VIDIO_CKC_BASE, VIDEO_CKC_CLKCTRL, 0x04UL)
#define FBUS_BHEVCENC		DECLARE_CLK_ID(TCC_VIDIO_CKC_BASE, VIDEO_CKC_CLKCTRL, 0x08UL)


/* Peripheral Clocks */
/* PCLK***CTRL register : starts from 0x1E000000 + 0x400*/
#define PERI_SYS_BASE_OFFSET	(CKC_PCLKCTRL + 0x0UL)

#define PERI_CPU_WDT_TIMER	DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x00UL)
#define PERI_TCX		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x04UL)
#define PERI_TCT		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x08UL)
#define PERI_TCZ		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x0CUL)
#define PERI_PCIe		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x10UL)
#define PERI_GMAC0		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x14UL)
#define PERI_GMAC1		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x18UL)
#define PERI_SFMC		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x1CUL)
#define PERI_SDMMC		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x20UL)
#define PERI_CAN0		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x24UL)
#define PERI_CAN1		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x28UL)
#define PERI_UART0		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x2CUL)
#define PERI_UART1		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x30UL)
#define PERI_UART2		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x34UL)
#define PERI_GPSB0		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x38UL)
#define PERI_GPSB1		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x3CUL)
#define PERI_GPSB2		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x40UL)
#define PERI_GPSB3		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x44UL)
#define PERI_GPSB4		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x48UL)
#define PERI_I2C0		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x4CUL)
#define PERI_I2C1		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x50UL)
#define PERI_I2C2		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x54UL)
#define PERI_DISP_TIMER		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x58UL)
#define PERI_DISP		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x5CUL)
#define PERI_DISP_TVM		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x60UL)
#define PERI_OUT0		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x64UL)
#define PERI_OUT1		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x68UL)
#define PERI_OUT2		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x6CUL)
#define PERI_OUT3		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x70UL)
#define PERI_OUT4		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x74UL)
#define PERI_OUT5		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x78UL)
#define PERI_OUT6		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x7CUL)
#define PERI_OUT7		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x80UL)
#define PERI_HSMB		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x84UL)
#define PERI_SPAD		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x88UL)
#define PERI_VCSEL		DECLARE_CLK_ID(TCC_CKC_BASE, PERI_SYS_BASE_OFFSET, 0x8CUL)



/* Use this macro to find register address for each SWRESET & CLKEN ID */
#define	CKC_SWRST_CLKEN_ID(A) (A/32UL)

/* Register BSWRESET0 	(0x1E000284) */
/* Register BCLKMASK0 	(0x1E000290) */
/* Register RSTDIS0 	(0x1E0002A4) */
#define SYSBUS0_START		0UL
#define SYSBUS0_CLK_RST_EN	CKC_SWRST_CLKEN_ID(SYSBUS0_START)
#define SYSBUS_CPU		SYSBUS0_START
#define SYSBUS_OIC		(SYSBUS0_START + 1UL)
#define SYSBUS_OMC_ACLK		(SYSBUS0_START + 2UL)
#define SYSBUS_PCIe		(SYSBUS0_START + 3UL)
#define SYSBUS_CAM		(SYSBUS0_START + 4UL)
#define SYSBUS_DDI		(SYSBUS0_START + 5UL)
#define SYSBUS_GMAC		(SYSBUS0_START + 6UL)
#define SYSBUS_OIC_CR		(SYSBUS0_START + 7UL)
#define SYSBUS_IMEM		(SYSBUS0_START + 8UL)
#define SYSBUS_HSM_ACLK		(SYSBUS0_START + 9UL)
#define SYSBUS_HSM_HCLK		(SYSBUS0_START + 10UL)
#define SYSBUS_CBC		(SYSBUS0_START + 11UL)
#define SYSBUS_DMA0		(SYSBUS0_START + 12UL)
#define SYSBUS_DMA1		(SYSBUS0_START + 13UL)
#define SYSBUS_DMA2		(SYSBUS0_START + 14UL)
#define SYSBUS_DMA3		(SYSBUS0_START + 15UL)
#define SYSBUS_DMA4		(SYSBUS0_START + 16UL)
#define SYSBUS_DMA_SLAVE	(SYSBUS0_START + 17UL)
#define SYSBUS_SFMC		(SYSBUS0_START + 18UL)
#define SYSBUS_SDMMC		(SYSBUS0_START + 19UL)
#define SYSBUS_SDMMC_SLAVE	(SYSBUS0_START + 20UL)
#define SYSBUS_CAN0		(SYSBUS0_START + 21UL)
#define SYSBUS_CAN1		(SYSBUS0_START + 22UL)
#define SYSBUS_CAN_CFG		(SYSBUS0_START + 23UL)
#define SYSBUS_CAN_SLAVE	(SYSBUS0_START + 24UL)
#define SYSBUS_UART0		(SYSBUS0_START + 25UL)
#define SYSBUS_UART1		(SYSBUS0_START + 26UL)
#define SYSBUS_UART2		(SYSBUS0_START + 27UL)
#define SYSBUS_UART_CFG		(SYSBUS0_START + 28UL)
#define SYSBUS_UART_SLAVE	(SYSBUS0_START + 29UL)
#define SYSBUS_GPSB0		(SYSBUS0_START + 30UL)
#define SYSBUS_GPSB1		(SYSBUS0_START + 31UL)
#define SYSBUS0_END		(SYSBUS0_START + 31UL)


/* Register BSWRESET1 	(0x1E000288) */
/* Register BCLKMASK1	(0x1E000294) */
/* Register RSTDIS1 	(0x1E0002A8) */
#define SYSBUS1_START		(SYSBUS0_END + 1UL)
#define SYSBUS1_CLK_RST_EN	CKC_SWRST_CLKEN_ID(SYSBUS1_START)
#define SYSBUS_GPSB2		SYSBUS1_START
#define SYSBUS_GPSB3		(SYSBUS1_START + 1UL)
#define SYSBUS_GPSB4		(SYSBUS1_START + 2UL)
#define SYSBUS_GPSB_CFG		(SYSBUS1_START + 3UL)
#define SYSBUS_GPSB_SM		(SYSBUS1_START + 4UL)
#define SYSBUS_GPSB_SLAVE	(SYSBUS1_START + 5UL)
#define SYSBUS_I2C0		(SYSBUS1_START + 6UL)
#define SYSBUS_I2C1		(SYSBUS1_START + 7UL)
#define SYSBUS_I2C2		(SYSBUS1_START + 8UL)
#define SYSBUS_I2CS0		(SYSBUS1_START + 9UL)
#define SYSBUS_I2CS1		(SYSBUS1_START + 10UL)
#define SYSBUS_I2CS2		(SYSBUS1_START + 11UL)
#define SYSBUS_I2C_CFG		(SYSBUS1_START + 12UL)
#define SYSBUS_I2C_SLAVE	(SYSBUS1_START + 13UL)
#define SYSBUS_TC		(SYSBUS1_START + 14UL)
#define SYSBUS_GPIO		(SYSBUS1_START + 15UL)
#define SYSBUS_TSENSOR		(SYSBUS1_START + 16UL)
#define SYSBUS_PMU		(SYSBUS1_START + 17UL)
#define SYSBUS_MEMCFG		(SYSBUS1_START + 18UL)
#define SYSBUS_OTP		(SYSBUS1_START + 19UL)
#define SYSBUS_TZCFG		(SYSBUS1_START + 20UL)
#define SYSBUS_OMC_PCLK		(SYSBUS1_START + 21UL)
#define SYSBUS_SYS		(SYSBUS1_START + 22UL)
#define SYSBUS_GPSB_HSM		(SYSBUS1_START + 23UL)
#define SYSBUS_SIL		(SYSBUS1_START + 24UL)
#define SYSBUS_SIL_SLAVE	(SYSBUS1_START + 25UL)
#define SYSBUS_LIDAR_PROC	(SYSBUS1_START + 26UL)
#define SYSBUS_LIDAR_PROC_SLAVE	(SYSBUS1_START + 27UL)
#define SYSBUS_LIDAR_CTRL_SLAVE	(SYSBUS1_START + 28UL)
#define SYSBUS_NPU		(SYSBUS1_START + 29UL)
#define SYSBUS_SAFE		(SYSBUS1_START + 30UL)
#define SYSBUS_VBUS		(SYSBUS1_START + 31UL)
#define SYSBUS1_END		(SYSBUS1_START + 31UL)


/* Register BSWRESET2 	(0x1E00028C) */
/* Register BCLKMASK2	(0x1E00029C) */
/* Register RSTDIS1 	(0x1E0002AC) */
#define SYSBUS2_START		(SYSBUS1_END + 1UL)
#define SYSBUS2_CLK_RST_EN	CKC_SWRST_CLKEN_ID(SYSBUS2_START)
#define SYSBUS_OIC_PCDV		SYSBUS2_START
#define SYSBUS_SAFE_DAP		(SYSBUS2_START + 1UL)
#define SYSBUS_NPU0		(SYSBUS2_START + 2UL)
#define SYSBUS_NPU1		(SYSBUS2_START + 3UL)
#define SYSBUS2_RESERVE4	(SYSBUS2_START + 4UL)
#define SYSBUS2_RESERVE5	(SYSBUS2_START + 5UL)
#define SYSBUS2_RESERVE6	(SYSBUS2_START + 6UL)
#define SYSBUS2_RESERVE7	(SYSBUS2_START + 7UL)
#define SYSBUS2_RESERVE8	(SYSBUS2_START + 8UL)
#define SYSBUS2_RESERVE9	(SYSBUS2_START + 9UL)
#define SYSBUS2_RESERVE10	(SYSBUS2_START + 10UL)
#define SYSBUS2_RESERVE11	(SYSBUS2_START + 11UL)
#define SYSBUS2_RESERVE12	(SYSBUS2_START + 12UL)
#define SYSBUS2_RESERVE13	(SYSBUS2_START + 13UL)
#define SYSBUS2_RESERVE14	(SYSBUS2_START + 14UL)
#define SYSBUS2_RESERVE15	(SYSBUS2_START + 15UL)
#define SYSBUS2_RESERVE16	(SYSBUS2_START + 16UL)
#define SYSBUS2_RESERVE17	(SYSBUS2_START + 17UL)
#define SYSBUS2_RESERVE18	(SYSBUS2_START + 18UL)
#define SYSBUS2_RESERVE19	(SYSBUS2_START + 19UL)
#define SYSBUS2_RESERVE20	(SYSBUS2_START + 20UL)
#define SYSBUS2_RESERVE21	(SYSBUS2_START + 21UL)
#define SYSBUS2_RESERVE22	(SYSBUS2_START + 22UL)
#define SYSBUS2_RESERVE23	(SYSBUS2_START + 23UL)
#define SYSBUS2_RESERVE24	(SYSBUS2_START + 24UL)
#define SYSBUS2_RESERVE25	(SYSBUS2_START + 25UL)
#define SYSBUS2_RESERVE26	(SYSBUS2_START + 26UL)
#define SYSBUS2_RESERVE27	(SYSBUS2_START + 27UL)
#define SYSBUS2_RESERVE28	(SYSBUS2_START + 28UL)
#define SYSBUS2_RESERVE29	(SYSBUS2_START + 29UL)
#define SYSBUS2_RESERVE30	(SYSBUS2_START + 30UL)
#define SYSBUS2_RESERVE31	(SYSBUS2_START + 31UL)
#define SYSBUS2_END		(SYSBUS2_START + 31UL)




/* PSWRESET0 Register (0x1E00029C) */
#define SYSPERI0_START		(SYSBUS2_END + 1UL)
#define SYSPERI0_CLK_RST_EN	CKC_SWRST_CLKEN_ID(SYSPERI0_START)
#define SYSPERI_WDT		SYSPERI0_START
#define SYSPERI_TCX		(SYSPERI0_START + 1UL)
#define SYSPERI_TCT		(SYSPERI0_START + 2UL)
#define SYSPERI_TCZ		(SYSPERI0_START + 3UL)
#define SYSPERI_PCIe		(SYSPERI0_START + 4UL)
#define SYSPERI_GMAC0		(SYSPERI0_START + 5UL)
#define SYSPERI_GMAC1		(SYSPERI0_START + 6UL)
#define SYSPERI_SFMC		(SYSPERI0_START + 7UL)
#define SYSPERI_SDMMC		(SYSPERI0_START + 8UL)
#define SYSPERI_CAN0		(SYSPERI0_START + 9UL)
#define SYSPERI_CAN1		(SYSPERI0_START + 10UL)
#define SYSPERI_UART0		(SYSPERI0_START + 11UL)
#define SYSPERI_UART1		(SYSPERI0_START + 12UL)
#define SYSPERI_UART2		(SYSPERI0_START + 13UL)
#define SYSPERI_GPSB0		(SYSPERI0_START + 14UL)
#define SYSPERI_GPSB1		(SYSPERI0_START + 15UL)
#define SYSPERI_GPSB2		(SYSPERI0_START + 16UL)
#define SYSPERI_GPSB3		(SYSPERI0_START + 17UL)
#define SYSPERI_GPSB4		(SYSPERI0_START + 18UL)
#define SYSPERI_I2C0		(SYSPERI0_START + 19UL)
#define SYSPERI_I2C1		(SYSPERI0_START + 20UL)
#define SYSPERI_I2C2		(SYSPERI0_START + 21UL)
#define SYSPERI_DISP0		(SYSPERI0_START + 22UL)
#define SYSPERI_DISP1		(SYSPERI0_START + 23UL)
#define SYSPERI_DISP2		(SYSPERI0_START + 24UL)
#define SYSPERI_OUT0		(SYSPERI0_START + 25UL)
#define SYSPERI_OUT1		(SYSPERI0_START + 26UL)
#define SYSPERI_OUT2		(SYSPERI0_START + 27UL)
#define SYSPERI_OUT3		(SYSPERI0_START + 28UL)
#define SYSPERI_OUT4		(SYSPERI0_START + 29UL)
#define SYSPERI_OUT5		(SYSPERI0_START + 30UL)
#define SYSPERI_OUT6		(SYSPERI0_START + 31UL)
#define SYSPERI0_END		(SYSPERI0_START + 31UL)




/* PSWRESET1 Register (0x1E000298) */
#define SYSPERI1_START		(SYSPERI0_END + 1UL)
#define SYSPERI1_CLK_RST_EN	CKC_SWRST_CLKEN_ID(SYSPERI1_START)
#define SYSPERI_OUT7		SYSPERI1_START
#define SYSPERI_HSMB		(SYSPERI1_START + 1UL)
#define SYSPERI1_RESERVE2	(SYSPERI1_START + 2UL)
#define SYSPERI1_RESERVE3	(SYSPERI1_START + 3UL)
#define SYSPERI1_RESERVE4	(SYSPERI1_START + 4UL)
#define SYSPERI1_RESERVE5	(SYSPERI1_START + 5UL)
#define SYSPERI1_RESERVE6	(SYSPERI1_START + 6UL)
#define SYSPERI1_RESERVE7	(SYSPERI1_START + 7UL)
#define SYSPERI1_RESERVE8	(SYSPERI1_START + 8UL)
#define SYSPERI1_RESERVE9	(SYSPERI1_START + 9UL)
#define SYSPERI1_RESERVE10	(SYSPERI1_START + 10UL)
#define SYSPERI1_RESERVE11	(SYSPERI1_START + 11UL)
#define SYSPERI1_RESERVE12	(SYSPERI1_START + 12UL)
#define SYSPERI1_RESERVE13	(SYSPERI1_START + 13UL)
#define SYSPERI1_RESERVE14	(SYSPERI1_START + 14UL)
#define SYSPERI1_RESERVE15	(SYSPERI1_START + 15UL)
#define SYSPERI1_RESERVE16	(SYSPERI1_START + 16UL)
#define SYSPERI1_RESERVE17	(SYSPERI1_START + 17UL)
#define SYSPERI1_RESERVE18	(SYSPERI1_START + 18UL)
#define SYSPERI1_RESERVE19	(SYSPERI1_START + 19UL)
#define SYSPERI1_RESERVE20	(SYSPERI1_START + 20UL)
#define SYSPERI1_RESERVE21	(SYSPERI1_START + 21UL)
#define SYSPERI1_RESERVE22	(SYSPERI1_START + 22UL)
#define SYSPERI1_RESERVE23	(SYSPERI1_START + 23UL)
#define SYSPERI1_RESERVE24	(SYSPERI1_START + 24UL)
#define SYSPERI1_RESERVE25	(SYSPERI1_START + 25UL)
#define SYSPERI1_RESERVE26	(SYSPERI1_START + 26UL)
#define SYSPERI1_RESERVE27	(SYSPERI1_START + 27UL)
#define SYSPERI1_RESERVE28	(SYSPERI1_START + 28UL)
#define SYSPERI1_RESERVE29	(SYSPERI1_START + 29UL)
#define SYSPERI1_RESERVE30	(SYSPERI1_START + 30UL)
#define SYSPERI1_RESERVE31	(SYSPERI1_START + 31UL)
#define SYSPERI1_END		(SYSPERI1_START + 31UL)


/* CA53 CLKMASK Register (0x10100000) */
/* CA53 SWRESET Register (0x10100004) */
/* CA53 RSTDIS  Register (0x10100008) */
#define CA53_START		(SYSPERI1_END + 1UL)
#define CA53_CLK_RST_EN		CKC_SWRST_CLKEN_ID(CA53_START)
#define CA53_X2X		CA53_START
#define CA53_H2H		(CA53_START + 1UL)
#define CA53_APBIF		(CA53_START + 2UL)
#define CA53_CFGR		(CA53_START + 3UL)
#define CA53_RESERVE4		(CA53_START + 4UL)
#define CA53_CKC		(CA53_START + 5UL)
#define CA53_CLKEN		(CA53_START + 6UL)
#define CA53_DBG		(CA53_START + 7UL)
#define CA53_ETC		(CA53_START + 8UL)
#define CA53_EVT		(CA53_START + 9UL)
#define CA53_CNT		(CA53_START + 10UL)
#define CA53_L2RST		(CA53_START + 11UL)
#define CA53_CORE0RST		(CA53_START + 12UL)
#define CA53_CORE1RST		(CA53_START + 13UL)
#define CA53_CORE2RST		(CA53_START + 14UL)
#define CA53_CORE3RST		(CA53_START + 15UL)
#define CA53_CA53POR0		(CA53_START + 16UL)
#define CA53_CA53POR1		(CA53_START + 17UL)
#define CA53_CA53POR2		(CA53_START + 18UL)
#define CA53_CA53POR3		(CA53_START + 19UL)
#define CA53_APBDBG		(CA53_START + 20UL)
#define CA53_ATB		(CA53_START + 21UL)
#define CA53_RESERVE22		(CA53_START + 22UL)
#define CA53_RESERVE23		(CA53_START + 23UL)
#define CA53_RESERVE24		(CA53_START + 24UL)
#define CA53_RESERVE25		(CA53_START + 25UL)
#define CA53_RESERVE26		(CA53_START + 26UL)
#define CA53_RESERVE27		(CA53_START + 27UL)
#define CA53_RESERVE28		(CA53_START + 28UL)
#define CA53_RESERVE29		(CA53_START + 29UL)
#define CA53_RESERVE30		(CA53_START + 30UL)
#define CA53_RESERVE31		(CA53_START + 31UL)
#define CA53_END		(CA53_START + 31UL)


/* CPU BUS ACLKMASK Register (0x10000000) */
/* CPU BUS SWRESETN Register (0x10000004) */
/* CPU BUS RSTDIS   Register (0x10000008) */
#define CPUBUS_START		(CA53_END + 1UL)
#define CPUBUS_CLK_RST_EN	CKC_SWRST_CLKEN_ID(CPUBUS_START)
#define CPUBUS_RESERVE0		CPUBUS_START
#define CPUBUS_RESERVE1		(CPUBUS_START + 1UL)
#define CPUBUS_RESERVE2		(CPUBUS_START + 2UL)
#define CPUBUS_RESERVE3		(CPUBUS_START + 3UL)
#define CPUBUS_WDT0		(CPUBUS_START + 4UL)
#define CPUBUS_RESERVE5		(CPUBUS_START + 5UL)
#define CPUBUS_CBUSCFG		(CPUBUS_START + 6UL)
#define CPUBUS_MB2DAP		(CPUBUS_START + 7UL)
#define CPUBUS_DAP		(CPUBUS_START + 8UL)
#define CPUBUS_DAPCFG		(CPUBUS_START + 9UL)
#define CPUBUS_DAP2MB		(CPUBUS_START + 10UL)
#define CPUBUS_MB2CB		(CPUBUS_START + 11UL)
#define CPUBUS_AHBMUX		(CPUBUS_START + 12UL)
#define CPUBUS_APBIF		(CPUBUS_START + 13UL)
#define CPUBUS_RESERVE14	(CPUBUS_START + 14UL)
#define CPUBUS_GIC_X2X		(CPUBUS_START + 15UL)
#define CPUBUS_CA53H2H		(CPUBUS_START + 16UL)
#define CPUBUS_CA53		(CPUBUS_START + 17UL)
#define CPUBUS_RESERVE18	(CPUBUS_START + 18UL)
#define CPUBUS_RESERVE19	(CPUBUS_START + 19UL)
#define CPUBUS_MBOX		(CPUBUS_START + 20UL)
#define CPUBUS_RESERVE21	(CPUBUS_START + 21UL)
#define CPUBUS_WDT1		(CPUBUS_START + 22UL)
#define CPUBUS_WDT2		(CPUBUS_START + 23UL)
#define CPUBUS_WDT3		(CPUBUS_START + 24UL)
#define CPUBUS_DAPNIC		(CPUBUS_START + 25UL)
#define CPUBUS_RESERVE26	(CPUBUS_START + 26UL)
#define CPUBUS_RESERVE27	(CPUBUS_START + 27UL)
#define CPUBUS_GIC		(CPUBUS_START + 28UL)
#define CPUBUS_RESERVE29	(CPUBUS_START + 29UL)
#define CPUBUS_APPOR		(CPUBUS_START + 30UL)
#define CPUBUS_RESERVE31	(CPUBUS_START + 31UL)
#define CPUBUS_END		(CPUBUS_START + 31UL)



/* DDI BUS CLKEN   Register (0x17400000) */
/* DDI BUS SWRESET Register (0x17400004) */
#define DDIBUS_START		(CPUBUS_END + 1UL)
#define DDIBUS_CLK_RST_EN	CKC_SWRST_CLKEN_ID(DDIBUS_START)
#define DDIBUS_VIOC		DDIBUS_START
#define DDIBUS_RESERVE1		(DDIBUS_START + 1UL)
#define DDIBUS_RESERVE2		(DDIBUS_START + 2UL)
#define DDIBUS_RESERVE3		(DDIBUS_START + 3UL)
#define DDIBUS_RESERVE4		(DDIBUS_START + 4UL)
#define DDIBUS_RESERVE5		(DDIBUS_START + 5UL)
#define DDIBUS_RESERVE6		(DDIBUS_START + 6UL)
#define DDIBUS_RESERVE7		(DDIBUS_START + 7UL)
#define DDIBUS_RESERVE8		(DDIBUS_START + 8UL)
#define DDIBUS_RESERVE9		(DDIBUS_START + 9UL)
#define DDIBUS_RESERVE10	(DDIBUS_START + 10UL)
#define DDIBUS_RESERVE11	(DDIBUS_START + 11UL)
#define DDIBUS_RESERVE12	(DDIBUS_START + 12UL)
#define DDIBUS_RESERVE13	(DDIBUS_START + 13UL)
#define DDIBUS_RESERVE14	(DDIBUS_START + 14UL)
#define DDIBUS_RESERVE15	(DDIBUS_START + 15UL)
#define DDIBUS_RESERVE16	(DDIBUS_START + 16UL)
#define DDIBUS_RESERVE17	(DDIBUS_START + 17UL)
#define DDIBUS_RESERVE18	(DDIBUS_START + 18UL)
#define DDIBUS_RESERVE19	(DDIBUS_START + 19UL)
#define DDIBUS_RESERVE20	(DDIBUS_START + 20UL)
#define DDIBUS_RESERVE21	(DDIBUS_START + 21UL)
#define DDIBUS_RESERVE22	(DDIBUS_START + 22UL)
#define DDIBUS_RESERVE23	(DDIBUS_START + 23UL)
#define DDIBUS_RESERVE24	(DDIBUS_START + 24UL)
#define DDIBUS_RESERVE25	(DDIBUS_START + 25UL)
#define DDIBUS_RESERVE26	(DDIBUS_START + 26UL)
#define DDIBUS_RESERVE27	(DDIBUS_START + 27UL)
#define DDIBUS_RESERVE28	(DDIBUS_START + 28UL)
#define DDIBUS_RESERVE29	(DDIBUS_START + 29UL)
#define DDIBUS_RESERVE30	(DDIBUS_START + 30UL)
#define DDIBUS_RESERVE31	(DDIBUS_START + 31UL)
#define DDIBUS_END		(DDIBUS_START + 31UL)




/* CAM BUS SWRESET   Register (0x16004000) */
#define CAMBUS0_START		(DDIBUS_END + 1UL)
#define CAMBUS_RST_EN		CKC_SWRST_CLKEN_ID(CAMBUS0_START)
#define CAMBUS0_RESERVE0	CAMBUS_START
#define CAMBUS0_RESERVE1	(CAMBUS0_START + 1UL)
#define CAMBUS_MPMR		(CAMBUS0_START + 2UL)
#define CAMBUS_MPSR		(CAMBUS0_START + 3UL)
#define CAMBUS_MCS		(CAMBUS0_START + 4UL)
#define CAMBUS_MDS		(CAMBUS0_START + 5UL)
#define CAMBUS0_RESERVE6	(CAMBUS0_START + 6UL)
#define CAMBUS0_RESERVE7	(CAMBUS0_START + 7UL)
#define CAMBUS_IBS		(CAMBUS0_START + 8UL)
#define CAMBUS_IRS		(CAMBUS0_START + 9UL)
#define CAMBUS_IPS		(CAMBUS0_START + 10UL)
#define CAMBUS_IP2S		(CAMBUS0_START + 11UL)
#define CAMBUS_R0AS		(CAMBUS0_START + 12UL)
#define CAMBUS_R0CS		(CAMBUS0_START + 13UL)
#define CAMBUS_R2AS		(CAMBUS0_START + 14UL)
#define CAMBUS_R2CS		(CAMBUS0_START + 15UL)
#define CAMBUS_C0S		(CAMBUS0_START + 16UL)
#define CAMBUS_C1S		(CAMBUS0_START + 17UL)
#define CAMBUS_C2S		(CAMBUS0_START + 18UL)
#define CAMBUS_C3S		(CAMBUS0_START + 19UL)
#define CAMBUS_C4S		(CAMBUS0_START + 20UL)
#define CAMBUS_C5S		(CAMBUS0_START + 21UL)
#define CAMBUS0_RESERVE22	(CAMBUS0_START + 22UL)
#define CAMBUS0_RESERVE23	(CAMBUS0_START + 23UL)
#define CAMBUS_OS		(CAMBUS0_START + 24UL)
#define CAMBUS_VS		(CAMBUS0_START + 25UL)
#define CAMBUS_MS		(CAMBUS0_START + 26UL)
#define CAMBUS_XS		(CAMBUS0_START + 27UL)
#define CAMBUS_I2C		(CAMBUS0_START + 28UL)
#define CAMBUS0_RESERVE29	(CAMBUS0_START + 29UL)
#define CAMBUS0_RESERVE30	(CAMBUS0_START + 30UL)
#define CAMBUS0_RESERVE31	(CAMBUS0_START + 31UL)
#define CAMBUS0_END		(CAMBUS0_START + 31UL)




/* CAM BUS CLKEN   Register (0x16004004) */
#define CAMBUS1_START		(CAMBUS0_END + 1UL)
#define CAMBUS_CLK_EN		CKC_SWRST_CLKEN_ID(CAMBUS1_START)
#define CAMBUS_MPSM		CAMBUS_START
#define CAMBUS_MPMM		(CAMBUS1_START + 1UL)
#define CAMBUS_MCAM		(CAMBUS1_START + 2UL)
#define CAMBUS_MCPM		(CAMBUS1_START + 3UL)
#define CAMBUS_MCXM		(CAMBUS1_START + 4UL)
#define CAMBUS_MDAM		(CAMBUS1_START + 5UL)
#define CAMBUS_MDPM		(CAMBUS1_START + 6UL)
#define CAMBUS1_RESERVE7	(CAMBUS1_START + 7UL)
#define CAMBUS_IXM		(CAMBUS1_START + 8UL)
#define CAMBUS_IPM		(CAMBUS1_START + 9UL)
#define CAMBUS_I0PM		(CAMBUS1_START + 10UL)
#define CAMBUS_I1PM		(CAMBUS1_START + 11UL)
#define CAMBUS_I2PM		(CAMBUS1_START + 12UL)
#define CAMBUS_I3PM		(CAMBUS1_START + 13UL)
#define CAMBUS_R0AM		(CAMBUS1_START + 14UL)
#define CAMBUS_R0PM		(CAMBUS1_START + 15UL)
#define CAMBUS_R2AM		(CAMBUS1_START + 16UL)
#define CAMBUS_R2PM		(CAMBUS1_START + 17UL)
#define CAMBUS_C0CM		(CAMBUS1_START + 18UL)
#define CAMBUS_C1CM		(CAMBUS1_START + 19UL)
#define CAMBUS_C2CM		(CAMBUS1_START + 20UL)
#define CAMBUS_C3CM		(CAMBUS1_START + 21UL)
#define CAMBUS_C4CM		(CAMBUS1_START + 22UL)
#define CAMBUS_C5CM		(CAMBUS1_START + 23UL)
#define CAMBUS_OCM		(CAMBUS1_START + 24UL)
#define CAMBUS_OP0M		(CAMBUS1_START + 25UL)
#define CAMBUS_OP1M		(CAMBUS1_START + 26UL)
#define CAMBUS_VBM		(CAMBUS1_START + 27UL)
#define CAMBUS_VP0M		(CAMBUS1_START + 28UL)
#define CAMBUS_VP1M		(CAMBUS1_START + 29UL)
#define CAMBUS_MCM		(CAMBUS1_START + 30UL)
#define CAMBUS_XCM		(CAMBUS1_START + 31UL)
#define CAMBUS1_END		(CAMBUS1_START + 31UL)



/* NPU BUS SWRESET Register (0x11100020) */
#define NPUBUS0_START		(CAMBUS1_END + 1UL)
#define NPUBUS_RST_EN		CKC_SWRST_CLKEN_ID(NPUBUS0_START)
#define NPUBUS_NPU0_ACLK_RST	NPUBUS0_START
#define NPUBUS_NPU_PCLK_RST	(NPUBUS0_START + 1UL)
#define NPUBUS_NPU0_CCLK_RST	(NPUBUS0_START + 2UL)
#define NPUBUS_NPU0_CPUCLK_RST	(NPUBUS0_START + 3UL)
#define NPUBUS_NPU1_ACLK_RST	(NPUBUS0_START + 4UL)
#define NPUBUS_NPU1_CCLK_RST	(NPUBUS0_START + 5UL)
#define NPUBUS_NPU1_CPUCLK_RST	(NPUBUS0_START + 6UL)
#define NPUBUS0_RESERVE7	(NPUBUS0_START + 7UL)
#define NPUBUS0_RESERVE8	(NPUBUS0_START + 8UL)
#define NPUBUS0_RESERVE9	(NPUBUS0_START + 9UL)
#define NPUBUS0_RESERVE10	(NPUBUS0_START + 10UL)
#define NPUBUS0_RESERVE11	(NPUBUS0_START + 11UL)
#define NPUBUS0_RESERVE12	(NPUBUS0_START + 12UL)
#define NPUBUS0_RESERVE13	(NPUBUS0_START + 13UL)
#define NPUBUS0_RESERVE14	(NPUBUS0_START + 14UL)
#define NPUBUS0_RESERVE15	(NPUBUS0_START + 15UL)
#define NPUBUS0_RESERVE16	(NPUBUS0_START + 16UL)
#define NPUBUS0_RESERVE17	(NPUBUS0_START + 17UL)
#define NPUBUS0_RESERVE18	(NPUBUS0_START + 18UL)
#define NPUBUS0_RESERVE19	(NPUBUS0_START + 19UL)
#define NPUBUS0_RESERVE20	(NPUBUS0_START + 20UL)
#define NPUBUS0_RESERVE21	(NPUBUS0_START + 21UL)
#define NPUBUS0_RESERVE22	(NPUBUS0_START + 22UL)
#define NPUBUS0_RESERVE23	(NPUBUS0_START + 23UL)
#define NPUBUS0_RESERVE24	(NPUBUS0_START + 24UL)
#define NPUBUS0_RESERVE25	(NPUBUS0_START + 25UL)
#define NPUBUS0_RESERVE26	(NPUBUS0_START + 26UL)
#define NPUBUS0_RESERVE27	(NPUBUS0_START + 27UL)
#define NPUBUS0_RESERVE28	(NPUBUS0_START + 28UL)
#define NPUBUS0_RESERVE29	(NPUBUS0_START + 29UL)
#define NPUBUS0_RESERVE30	(NPUBUS0_START + 30UL)
#define NPUBUS0_RESERVE31	(NPUBUS0_START + 31UL)
#define NPUBUS0_END		(NPUBUS0_START + 31UL)


/* NPU BUS SWRESET Register (0x11100024) */
#define NPUBUS1_START		(NPUBUS0_END + 1UL)
#define NPUBUS_CLK_EN		CKC_SWRST_CLKEN_ID(NPUBUS1_START)
#define NPUBUS_NPU0_ACLK_EN	NPUBUS1_START
#define NPUBUS_NPU_PCLK_EN	(NPUBUS1_START + 1UL)
#define NPUBUS_NPU0_CCLK_EN	(NPUBUS1_START + 2UL)
#define NPUBUS_NPU0_CPUCLK_EN	(NPUBUS1_START + 3UL)
#define NPUBUS_NPU0_CCLK_DIV2_EN	(NPUBUS1_START + 4UL)
#define NPUBUS_NPU1_ACLK_EN	(NPUBUS1_START + 5UL)
#define NPUBUS_NPU1_CCLK_EN	(NPUBUS1_START + 6UL)
#define NPUBUS_NPU1_CPUCLK_EN	(NPUBUS1_START + 7UL)
#define NPUBUS_NPU1_CCLK_DIV2_EN	(NPUBUS1_START + 8UL)
#define NPUBUS1_RESERVE9	(NPUBUS1_START + 9UL)
#define NPUBUS1_RESERVE10	(NPUBUS1_START + 10UL)
#define NPUBUS1_RESERVE11	(NPUBUS1_START + 11UL)
#define NPUBUS1_RESERVE12	(NPUBUS1_START + 12UL)
#define NPUBUS1_RESERVE13	(NPUBUS1_START + 13UL)
#define NPUBUS1_RESERVE14	(NPUBUS1_START + 14UL)
#define NPUBUS1_RESERVE15	(NPUBUS1_START + 15UL)
#define NPUBUS1_RESERVE16	(NPUBUS1_START + 16UL)
#define NPUBUS1_RESERVE17	(NPUBUS1_START + 17UL)
#define NPUBUS1_RESERVE18	(NPUBUS1_START + 18UL)
#define NPUBUS1_RESERVE19	(NPUBUS1_START + 19UL)
#define NPUBUS1_RESERVE20	(NPUBUS1_START + 20UL)
#define NPUBUS1_RESERVE21	(NPUBUS1_START + 21UL)
#define NPUBUS1_RESERVE22	(NPUBUS1_START + 22UL)
#define NPUBUS1_RESERVE23	(NPUBUS1_START + 23UL)
#define NPUBUS1_RESERVE24	(NPUBUS1_START + 24UL)
#define NPUBUS1_RESERVE25	(NPUBUS1_START + 25UL)
#define NPUBUS1_RESERVE26	(NPUBUS1_START + 26UL)
#define NPUBUS1_RESERVE27	(NPUBUS1_START + 27UL)
#define NPUBUS1_RESERVE28	(NPUBUS1_START + 28UL)
#define NPUBUS1_RESERVE29	(NPUBUS1_START + 29UL)
#define NPUBUS1_RESERVE30	(NPUBUS1_START + 30UL)
#define NPUBUS1_RESERVE31	(NPUBUS1_START + 31UL)
#define NPUBUS1_END		(NPUBUS1_START + 31UL)

/* NPU BUS SWRESET Register (0x11100024) */
#define VIDEOBUS_START		(NPUBUS1_END + 1UL)
#define VIDEOBUS_RST_EN		CKC_SWRST_CLKEN_ID(VIDEOBUS_START)
#define VIDEOBUS_HEVCENC	VIDEOBUS_START
#define VIDEOBUS_RESERVE1	(VIDEOBUS_START + 1UL)
#define VIDEOBUS_RESERVE2	(VIDEOBUS_START + 2UL)
#define VIDEOBUS_RESERVE3	(VIDEOBUS_START + 3UL)
#define VIDEOBUS_RESERVE4	(VIDEOBUS_START + 4UL)
#define VIDEOBUS_RESERVE5	(VIDEOBUS_START + 5UL)
#define VIDEOBUS_RESERVE6	(VIDEOBUS_START + 6UL)
#define VIDEOBUS_RESERVE7	(VIDEOBUS_START + 7UL)
#define VIDEOBUS_RESERVE8	(VIDEOBUS_START + 8UL)
#define VIDEOBUS_RESERVE9	(VIDEOBUS_START + 9UL)
#define VIDEOBUS_RESERVE10	(VIDEOBUS_START + 10UL)
#define VIDEOBUS_RESERVE11	(VIDEOBUS_START + 11UL)
#define VIDEOBUS_RESERVE12	(VIDEOBUS_START + 12UL)
#define VIDEOBUS_RESERVE13	(VIDEOBUS_START + 13UL)
#define VIDEOBUS_RESERVE14	(VIDEOBUS_START + 14UL)
#define VIDEOBUS_RESERVE15	(VIDEOBUS_START + 15UL)
#define VIDEOBUS_RESERVE16	(VIDEOBUS_START + 16UL)
#define VIDEOBUS_RESERVE17	(VIDEOBUS_START + 17UL)
#define VIDEOBUS_RESERVE18	(VIDEOBUS_START + 18UL)
#define VIDEOBUS_RESERVE19	(VIDEOBUS_START + 19UL)
#define VIDEOBUS_RESERVE20	(VIDEOBUS_START + 20UL)
#define VIDEOBUS_RESERVE21	(VIDEOBUS_START + 21UL)
#define VIDEOBUS_RESERVE22	(VIDEOBUS_START + 22UL)
#define VIDEOBUS_RESERVE23	(VIDEOBUS_START + 23UL)
#define VIDEOBUS_RESERVE24	(VIDEOBUS_START + 24UL)
#define VIDEOBUS_RESERVE25	(VIDEOBUS_START + 25UL)
#define VIDEOBUS_RESERVE26	(VIDEOBUS_START + 26UL)
#define VIDEOBUS_RESERVE27	(VIDEOBUS_START + 27UL)
#define VIDEOBUS_RESERVE28	(VIDEOBUS_START + 28UL)
#define VIDEOBUS_RESERVE29	(VIDEOBUS_START + 29UL)
#define VIDEOBUS_RESERVE30	(VIDEOBUS_START + 30UL)
#define VIDEOBUS_RESERVE31	(VIDEOBUS_START + 31UL)
#define VIDEOBUS_END		(VIDEOBUS_START + 31UL)

/* PLL source clock (Not support CLK_F_GET_SRC_CLK yet) */
#define PLL_SRC_XIN			0UL

/* Source clock flags for CLK_F_GET_SRC_CLK */
/* SYSTEM BUS SEL */
#define SYS_CLKCTRL_SEL_PLL0		0UL
#define SYS_CLKCTRL_SEL_PLL1		1UL
#define SYS_CLKCTRL_SEL_PLL2		2UL
#define SYS_CLKCTRL_SEL_PLL3		3UL
#define SYS_CLKCTRL_SEL_PLL4		4UL
#define SYS_CLKCTRL_SEL_XIN		5UL
#define SYS_CLKCTRL_SEL_EXTIN0		6UL
#define SYS_CLKCTRL_SEL_PLL0DIV		7UL
#define SYS_CLKCTRL_SEL_PLL1DIV		8UL
#define SYS_CLKCTRL_SEL_PLL2DIV		9UL
#define SYS_CLKCTRL_SEL_PLL3DIV		10UL
#define SYS_CLKCTRL_SEL_PLL4DIV		11UL
#define SYS_CLKCTRL_SEL_XINDIV		12UL
#define SYS_CLKCTRL_SEL_EXTIN1		13UL
#define SYS_CLKCTRL_SEL_EXTIN2		14UL
#define SYS_CLKCTRL_SEL_EXTIN3		15UL

/* Peripheral SEL */
#define PCLKCTRL_SEL_PLL0		0UL
#define PCLKCTRL_SEL_PLL1		1UL
#define PCLKCTRL_SEL_PLL2		2UL
#define PCLKCTRL_SEL_PLL3		3UL
#define PCLKCTRL_SEL_PLL4		4UL
#define PCLKCTRL_SEL_XIN		5UL
#define PCLKCTRL_SEL_PLL0DIV		10UL
#define PCLKCTRL_SEL_PLL1DIV		11UL
#define PCLKCTRL_SEL_PLL2DIV		12UL
#define PCLKCTRL_SEL_PLL3DIV		13UL
#define PCLKCTRL_SEL_PLL4DIV		14UL
#define PCLKCTRL_SEL_PCIPHY_CLKOUT	18UL
#define PCLKCTRL_SEL_XINDIV		23UL
#define PCLKCTRL_SEL_EXTCLK0		25UL
#define PCLKCTRL_SEL_EXTCLK1		26UL

/* CPU BUS SEL */
#define CPU_CLKCTRL_SEL_XIN		0UL
#define CPU_CLKCTRL_SEL_PLL		1UL
#define CPU_CLKCTRL_SEL_PLLDIV		2UL
#define CPU_CLKCTRL_SEL_EXTCLK		3UL

/* NPU BUS SEL */
#define NPU_CLKCTRL_SEL_XIN		0UL
#define NPU_CLKCTRL_SEL_PLL0		1UL
#define NPU_CLKCTRL_SEL_PLL1		2UL
#define NPU_CLKCTRL_SEL_PLL0DIV		3UL
#define NPU_CLKCTRL_SEL_PLL1DIV		4UL

/* VIDEO BUS SEL */
#define VIDEO_CLKCTRL_SEL_XIN		0UL
#define VIDEO_CLKCTRL_SEL_PLL0		1UL
#define VIDEO_CLKCTRL_SEL_PLL1		2UL
#define VIDEO_CLKCTRL_SEL_PLL0DIV0	3UL
#define VIDEO_CLKCTRL_SEL_PLL0DIV1	4UL
#define VIDEO_CLKCTRL_SEL_PLL1DIV0	5UL
#define VIDEO_CLKCTRL_SEL_PLL1DIV1	6UL
#define VIDEO_CLKCTRL_SEL_EXTCLK	7UL

/* CAM BUS SEL */
#define CAM_CLKCTRL_SEL_XIN		0UL
#define CAM_CLKCTRL_SEL_PLL		1UL
#define CAM_CLKCTRL_SEL_PLLDIV		2UL


#endif
