/* SPDX-License-Identifier: (GPL-2.0-or-later OR MIT) */
/*
 * Copyright (C) 2023 Telechips Inc.
 */

#ifndef DT_TCC805X_CLKS_H
#define DT_TCC805X_CLKS_H

#include <asm/arch-tcc805x/ckc_flags.h>

/*
 * Clock index for device tree.
 * These values used for clock-indices in clock device node.
 * The index number MUST BE match with Kernel & U-Boot
 */

#define DECLARE_CLK_ID(base, offset, index) ((base) + (offset) + (index))

/* BASE Address */
/* Part 2. System */
#define SMU_CKC                 0x14000000UL


/* Part 3. GPU */
#define GPU_CKC                 0x10000000UL
#define GPU_CFG                 0x10010000UL
#define G2D_CKC                 0x1A000000UL
#define G2D_CFG                 0x1A010000UL


/* Part 4. MEMORY */
#define MEM_PHY0_CKC            0x13340000UL
#define MEM_PHY1_CKC            0x13350000UL
#define MEM_PHY2_CKC            0x13440000UL
#define MEM_PHY3_CKC            0x13450000UL

#define MEM_CFG                 0x13500000UL
#define MEM_CKC                 0x13540000UL


/* Part 5. IO */
#define IO_CFG                  0x16051000UL
#define IO_STR_CFG              0x16494000UL


/* Part 6. HSIO */
#define HSIO_CFG                0x11DA0000UL


/* Part 7. DISPLAY */
#define DDI_CFG                 0x12380000UL
#define DP_CKC                  0x124C0000UL
#define MIPI_CKC                0x1BC00000UL


/* Part 8. VIDEO */
#define VIDEO_CFG               0x15100000UL
#define VIDEO_CKC               0x15280000UL


/* Part 10. CPU */
#define CPU_CFG	                0x17000000UL
#define CA72_CFG		0x17100000UL
#define CA72_CCU		0x17110000UL
#define CA53_CFG		0x17200000UL
#define CA53_CCU		0x17210000UL


/*
 * CKC Register Offsets
 */
/* Part 2. System */
#define SMU_CLKCTRL     0x000UL
#define SMU_PLLPMS      0x080UL
#define SMU_PLLCON      0x100UL
#define SMU_PLLMON      0x180UL
#define SMU_CLKDIVC0    0x200UL
#define SMU_CLKDIVC1    0x204UL
#define SMU_SWRESET     0x284UL
#define SMU_SWRSTDIS    0x288UL
#define SMU_PCLKCTRL    0x400UL


/* Part 2. GPU */
#define GPU_CLKCTRL     0x000UL
#define GPU_PLLPMS	0x008UL
#define GPU_PLLCON	0x00CUL
#define GPU_PLLMON	0x010UL
#define GPU_CLKDIVC	0x014UL

#define GPU_CLKMASK     0x000UL
#define GPU_SWRESET     0x004UL


/* Part 4. MEMORY */
#define MEM_PHY_PLLPMS	0x000UL

#define MEM_CLKCTRL	0x000UL
#define MEM_PLLPMS	0x010UL
#define MEM_PLLCON	0x014UL
#define MEM_PLLMON	0x018UL
#define MEM_CLKDIVC	0x030UL


/* Part 5. IO */
#define IO_HCLKEN       0x000UL
#define IO_HRSTEN       0x00CUL
#define IO_PCLKEN       0x018UL


/* Part 6. HSIO */
#define HSIO_HCLKMASK   0x000UL
#define HSIO_SWRESET    0x004UL


/* Part 7. DISPLAY */
#define DDI_CLKEN       0x000UL
#define DDI_SWRESET     0x004UL

#define DP_CLKCTRL      0x000UL
#define DP_PLLPMS       0x010UL
#define DP_PLLCON       0x014UL
#define DP_PLLMON       0x018UL
#define DP_CLKDIVC      0x01CUL

#define MIPI_CLKCTRL    0x000UL
#define MIPI_PLLPMS     0x008UL
#define MIPI_PLLCON     0x00CUL
#define MIPI_PLLMON     0x010UL
#define MIPI_CLKDIVC    0x014UL


/* Part 8. VIDEO */
#define VIDEO_ACLKMASK  0x000UL
#define VIDEO_SWRESET   0x004UL

#define VIDEO_CLKCTRL   0x000UL
#define VIDEO_PLLPMS    0x010UL
#define VIDEO_PLLCON    0x014UL
#define VIDEO_PLLMON    0x018UL
#define VIDEO_CLKDIVC   0x030UL


/* Part 10. CPU */
#define CPU_ACLKMASK    0x000UL
#define CPU_SWRESET     0x004UL
#define CPU_SWRSTDIS    0x008UL

#define CPU_CLKCTRL     0x000UL
#define CPU_PLLPMS      0x008UL
#define CPU_PLLCON      0x00CUL
#define CPU_PLLMON      0x010UL
#define CPU_CLKDIVC     0x014UL


/* Oscillator index */
/* Unsed SMU CKC Address can be used for oscillator ID */
#define OSC_XIN			DECLARE_CLK_ID(SMU_CKC, 0xFF000UL, 0x000UL)
#define OSC_XTIN		DECLARE_CLK_ID(SMU_CKC, 0xFF000UL, 0x001UL)


/* PLL index */
#define PLL_0			DECLARE_CLK_ID(SMU_CKC, SMU_PLLPMS, 0x00UL)
#define PLL_1			DECLARE_CLK_ID(SMU_CKC, SMU_PLLPMS, 0x04UL)
#define PLL_2			DECLARE_CLK_ID(SMU_CKC, SMU_PLLPMS, 0x08UL)
#define PLL_3			DECLARE_CLK_ID(SMU_CKC, SMU_PLLPMS, 0x0CUL)
#define PLL_4			DECLARE_CLK_ID(SMU_CKC, SMU_PLLPMS, 0x10UL)

#define PLL_GPU                 DECLARE_CLK_ID(GPU_CKC, GPU_PLLPMS, 0x00UL)
#define PLL_G2D                 DECLARE_CLK_ID(G2D_CKC, GPU_PLLPMS, 0x00UL)

#define PLL_MEM_PHY_0		DECLARE_CLK_ID(MEM_PHY0_CKC, MEM_PHY_PLLPMS, 0x0UL)
#define PLL_MEM_PHY_1		DECLARE_CLK_ID(MEM_PHY1_CKC, MEM_PHY_PLLPMS, 0x0UL)
#define PLL_MEM_PHY_2		DECLARE_CLK_ID(MEM_PHY2_CKC, MEM_PHY_PLLPMS, 0x0UL)
#define PLL_MEM_PHY_3		DECLARE_CLK_ID(MEM_PHY3_CKC, MEM_PHY_PLLPMS, 0x0UL)

#define PLL_MEM                 DECLARE_CLK_ID(MEM_CKC, MEM_PLLPMS, 0x00UL)

#define PLL_DP                  DECLARE_CLK_ID(DP_CKC, DP_PLLPMS, 0x00UL)
#define PLL_MIPI                DECLARE_CLK_ID(MIPI_CKC, MIPI_PLLPMS, 0x00UL)

#define PLL_VIDEO_0             DECLARE_CLK_ID(VIDEO_CKC, VIDEO_PLLPMS, 0x00UL)
#define PLL_VIDEO_1             DECLARE_CLK_ID(VIDEO_CKC, VIDEO_PLLPMS, 0x10UL)

#define PLL_CA72                DECLARE_CLK_ID(CA72_CCU, CPU_PLLPMS, 0x00UL)
#define PLL_CA53                DECLARE_CLK_ID(CA53_CCU, CPU_PLLPMS, 0x00UL)

/* Divider index */
#define PLL_0_DIV		DECLARE_CLK_ID(SMU_CKC,  SMU_CLKDIVC0, 0x3UL)
#define PLL_1_DIV		DECLARE_CLK_ID(SMU_CKC,  SMU_CLKDIVC0, 0x2UL)
#define PLL_2_DIV		DECLARE_CLK_ID(SMU_CKC,  SMU_CLKDIVC0, 0x1UL)
#define PLL_3_DIV		DECLARE_CLK_ID(SMU_CKC,  SMU_CLKDIVC0, 0x0UL)
#define PLL_4_DIV		DECLARE_CLK_ID(SMU_CKC,  SMU_CLKDIVC1, 0x3UL)
#define OSC_XIN_DIV             DECLARE_CLK_ID(SMU_CKC,  SMU_CLKDIVC1, 0x1UL)
#define OSC_XTIN_DIV            DECLARE_CLK_ID(SMU_CKC,  SMU_CLKDIVC1, 0x0UL)

#define PLL_GPU_DIV             DECLARE_CLK_ID(GPU_CKC, GPU_CLKDIVC, 0x00UL)
#define PLL_G2D_DIV             DECLARE_CLK_ID(G2D_CKC, GPU_CLKDIVC, 0x00UL)

#define PLL_MEM_DIV_0           DECLARE_CLK_ID(MEM_CKC, MEM_CLKDIVC, 0x0UL)
#define PLL_MEM_DIV_1           DECLARE_CLK_ID(MEM_CKC, MEM_CLKDIVC, 0x1UL)
#define PLL_MEM_DIV_2           DECLARE_CLK_ID(MEM_CKC, MEM_CLKDIVC, 0x2UL)
#define PLL_MEM_DIV_3           DECLARE_CLK_ID(MEM_CKC, MEM_CLKDIVC, 0x3UL)

#define PLL_DP_DIV_0		DECLARE_CLK_ID(DP_CKC,  DP_CLKDIVC, 0x0UL)
#define PLL_DP_DIV_1		DECLARE_CLK_ID(DP_CKC,  DP_CLKDIVC, 0x4UL)
#define PLL_DP_DIV_2		DECLARE_CLK_ID(DP_CKC,  DP_CLKDIVC, 0x8UL)

#define PLL_MIPI_DIV		DECLARE_CLK_ID(MIPI_CKC,  MIPI_CLKDIVC, 0x0UL)

#define PLL_VIDEO_0_DIV_0	DECLARE_CLK_ID(VIDEO_CKC,  VIDEO_CLKDIVC, 0x0UL)
#define PLL_VIDEO_0_DIV_1	DECLARE_CLK_ID(VIDEO_CKC,  VIDEO_CLKDIVC, 0x1UL)
#define PLL_VIDEO_1_DIV_0	DECLARE_CLK_ID(VIDEO_CKC,  VIDEO_CLKDIVC, 0x2UL)
#define PLL_VIDEO_1_DIV_1	DECLARE_CLK_ID(VIDEO_CKC,  VIDEO_CLKDIVC, 0x3UL)

#define PLL_CA72_DIV            DECLARE_CLK_ID(CA72_CCU, CPU_CLKDIVC, 0x00UL)
#define PLL_CA53_DIV            DECLARE_CLK_ID(CA53_CCU, CPU_CLKDIVC, 0x00UL)

/* CLKCTRL channel index */
#define FBUS_CPUBUS             DECLARE_CLK_ID(SMU_CKC, SMU_CLKCTRL, 0x008UL)		// OMC Subsystem
#define FBUS_CMBUS              DECLARE_CLK_ID(SMU_CKC, SMU_CLKCTRL, 0x00CUL)
#define FBUS_HSIO               DECLARE_CLK_ID(SMU_CKC, SMU_CLKCTRL, 0x018UL)
#define FBUS_SMU                DECLARE_CLK_ID(SMU_CKC, SMU_CLKCTRL, 0x01CUL)
#define FBUS_DDI                DECLARE_CLK_ID(SMU_CKC, SMU_CLKCTRL, 0x024UL)
#define FBUS_IO                 DECLARE_CLK_ID(SMU_CKC, SMU_CLKCTRL, 0x02CUL)
#define FBUS_HSM                DECLARE_CLK_ID(SMU_CKC, SMU_CLKCTRL, 0x040UL)
#define FBUS_PCIe0              DECLARE_CLK_ID(SMU_CKC, SMU_CLKCTRL, 0x044UL)
#define FBUS_PCIe1              DECLARE_CLK_ID(SMU_CKC, SMU_CLKCTRL, 0x048UL)

#define FBUS_GPU		DECLARE_CLK_ID(GPU_CKC, GPU_CLKCTRL, 0x0UL)
#define FBUS_G2D		DECLARE_CLK_ID(G2D_CKC, GPU_CLKCTRL, 0x0UL)

#define FBUS_MEM		DECLARE_CLK_ID(MEM_CKC, MEM_CLKCTRL, 0x0UL)
#define FBUS_MEM_SUB		DECLARE_CLK_ID(MEM_CKC, MEM_CLKCTRL, 0x4UL)
#define FBUS_MEM_PHY_USER	DECLARE_CLK_ID(MEM_CKC, MEM_CLKCTRL, 0x8UL)
#define FBUS_MEM_PHY_PERI	DECLARE_CLK_ID(MEM_CKC, MEM_CLKCTRL, 0xCUL)

#define FBUS_DP_AXI		DECLARE_CLK_ID(DP_CKC, DP_CLKCTRL, 0x0UL)
#define FBUS_DP_AUX		DECLARE_CLK_ID(DP_CKC, DP_CLKCTRL, 0x4UL)
#define FBUS_DP_APB		DECLARE_CLK_ID(DP_CKC, DP_CLKCTRL, 0x8UL)

#define FBUS_MIPI		DECLARE_CLK_ID(MIPI_CKC, MIPI_CLKCTRL, 0x0UL)
#define FBUS_MIPI_PIXEL		DECLARE_CLK_ID(MIPI_CKC, MIPI_CLKCTRL, 0x4UL)

#define FBUS_VBUS		DECLARE_CLK_ID(VIDEO_CKC, VIDEO_CLKCTRL, 0x0UL)
#define FBUS_CODA		DECLARE_CLK_ID(VIDEO_CKC, VIDEO_CLKCTRL, 0x4UL)
#define FBUS_CHEVCDEC		DECLARE_CLK_ID(VIDEO_CKC, VIDEO_CLKCTRL, 0x8UL)
#define FBUS_BHEVCDEC		DECLARE_CLK_ID(VIDEO_CKC, VIDEO_CLKCTRL, 0xCUL)
#define FBUS_CHEVCENC		DECLARE_CLK_ID(VIDEO_CKC, VIDEO_CLKCTRL, 0x34UL)
#define FBUS_BHEVCENC		DECLARE_CLK_ID(VIDEO_CKC, VIDEO_CLKCTRL, 0x38UL)

#define FBUS_CA72		DECLARE_CLK_ID(CA72_CCU, CPU_CLKCTRL, 0x0UL)
#define FBUS_CA53		DECLARE_CLK_ID(CA53_CCU, CPU_CLKCTRL, 0x0UL)




/* Peripheral Clocks */
/* PCLK***CTRL register : starts from 0x14000000 + 0x400*/
#define PERI_SMU_BASE_OFFSET    (SMU_PCLKCTRL + 0x000UL)
#define PERI_DDI_BASE_OFFSET    (SMU_PCLKCTRL + 0x100UL)
#define PERI_HSIO_BASE_OFFSET   (SMU_PCLKCTRL + 0x200UL)
#define PERI_IO_BASE_OFFSET     (SMU_PCLKCTRL + 0x300UL)
#define PERI_CM_BASE_OFFSET     (SMU_PCLKCTRL + 0x400UL)
#define PERI_CPU_BASE_OFFSET    (SMU_PCLKCTRL + 0x500UL)
#define PERI_EXT_BASE_OFFSET    (SMU_PCLKCTRL + 0x600UL)
#define PERI_SSS_BASE_OFFSET    (SMU_PCLKCTRL + 0x700UL)

#define PERI_TCT                DECLARE_CLK_ID(SMU_CKC, PERI_SMU_BASE_OFFSET, 0x04UL)
#define PERI_TCZ                DECLARE_CLK_ID(SMU_CKC, PERI_SMU_BASE_OFFSET, 0x08UL)

#define PERI_LCDTIMER           DECLARE_CLK_ID(SMU_CKC, PERI_DDI_BASE_OFFSET, 0x00UL)
#define PERI_LCD0               DECLARE_CLK_ID(SMU_CKC, PERI_DDI_BASE_OFFSET, 0x04UL)
#define PERI_LCD1               DECLARE_CLK_ID(SMU_CKC, PERI_DDI_BASE_OFFSET, 0x08UL)
#define PERI_LCD2               DECLARE_CLK_ID(SMU_CKC, PERI_DDI_BASE_OFFSET, 0x0CUL)
#define PERI_LCD3               DECLARE_CLK_ID(SMU_CKC, PERI_DDI_BASE_OFFSET, 0x18UL)

#define PERI_GMAC               DECLARE_CLK_ID(SMU_CKC, PERI_HSIO_BASE_OFFSET, 0x00UL)
#define PERI_GMAC_PTP           DECLARE_CLK_ID(SMU_CKC, PERI_HSIO_BASE_OFFSET, 0x04UL)
#define PERI_PCIE0_PHY_CR_CLK   DECLARE_CLK_ID(SMU_CKC, PERI_HSIO_BASE_OFFSET, 0x10UL)

#define PERI_RMT                DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x00UL)
#define PERI_GPSB3              DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x04UL)
#define PERI_SDMMC1             DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x08UL)
#define PERI_SDMMC2             DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x0CUL)
#define PERI_MDAI0              DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x14UL)
#define PERI_MFLT0_DAI          DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x18UL)
#define PERI_MSPDIF0            DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x1CUL)
#define PERI_SRCH0_CORE         DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x20UL)
#define PERI_SRCH0_FILTER       DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x24UL)
#define PERI_SRCH0_SPDIF        DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x28UL)
#define PERI_PDM                DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x2CUL)
#define PERI_TSADC              DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x34UL)
#define PERI_I2C0               DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x38UL)
#define PERI_I2C1               DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x3CUL)
#define PERI_I2C2               DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x40UL)
#define PERI_I2C3               DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x44UL)
#define PERI_UART0              DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x48UL)
#define PERI_UART1              DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x4CUL)
#define PERI_UART2              DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x50UL)
#define PERI_UART3              DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x54UL)
#define PERI_MDAI1              DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x58UL)
#define PERI_MFLT1_DAI          DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x5CUL)
#define PERI_MSPDIF1            DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x60UL)
#define PERI_MDAI2              DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x64UL)
#define PERI_GPSB0              DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x68UL)
#define PERI_GPSB1              DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x6CUL)
#define PERI_GPSB2              DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x70UL)
#define PERI_GPSBMS0            DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x74UL)
#define PERI_GPSBMS1            DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x78UL)
#define PERI_GPSBMS2            DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x7CUL)
#define PERI_UART4              DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x80UL)
#define PERI_AUX0_INPUT         DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x84UL)
#define PERI_AUX1_INPUT         DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x88UL)
#define PERI_MFLT2_DAI          DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x90UL)
#define PERI_AUX0_OUTPUT        DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x94UL)
#define PERI_AUX1_OUTPUT        DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x98UL)
#define PERI_MSPDIF2            DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0x9CUL)
#define PERI_IC_TC              DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0xA0UL)
#define PERI_SRCH1_CORE         DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0xA4UL)
#define PERI_SRCH1_FILTER       DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0xA8UL)
#define PERI_SRCH1_SPDIF        DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0xACUL)
#define PERI_SRCH2_CORE         DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0xB0UL)
#define PERI_SRCH2_FILTER       DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0xB4UL)
#define PERI_SRCH2_SPDIF        DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0xB8UL)
#define PERI_SRCH3_CORE         DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0xBCUL)
#define PERI_SRCH3_FILTER       DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0xC0UL)
#define PERI_SRCH3_SPDIF        DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0xC4UL)
#define PERI_UART5              DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0xC8UL)
#define PERI_UART6              DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0xCCUL)
#define PERI_UART7              DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0xD0UL)
#define PERI_UART8              DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0xD4UL)
#define PERI_MDAI3              DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0xD8UL)
#define PERI_MFLT3_DAI          DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0xDCUL)
#define PERI_MSPDIF3            DECLARE_CLK_ID(SMU_CKC, PERI_IO_BASE_OFFSET, 0xE0UL)

#define PERI_TSRX0              DECLARE_CLK_ID(SMU_CKC, PERI_CM_BASE_OFFSET, 0x00UL)
#define PERI_TSRX1              DECLARE_CLK_ID(SMU_CKC, PERI_CM_BASE_OFFSET, 0x04UL)
#define PERI_TSRX2              DECLARE_CLK_ID(SMU_CKC, PERI_CM_BASE_OFFSET, 0x08UL)
#define PERI_TSRX3              DECLARE_CLK_ID(SMU_CKC, PERI_CM_BASE_OFFSET, 0x0CUL)
#define PERI_TSRX4              DECLARE_CLK_ID(SMU_CKC, PERI_CM_BASE_OFFSET, 0x10UL)
#define PERI_TSRX5              DECLARE_CLK_ID(SMU_CKC, PERI_CM_BASE_OFFSET, 0x14UL)
#define PERI_TSRX6              DECLARE_CLK_ID(SMU_CKC, PERI_CM_BASE_OFFSET, 0x18UL)
#define PERI_TSRX7              DECLARE_CLK_ID(SMU_CKC, PERI_CM_BASE_OFFSET, 0x1CUL)
#define PERI_TSRX8              DECLARE_CLK_ID(SMU_CKC, PERI_CM_BASE_OFFSET, 0x20UL)

#define PERI_CB_WDT             DECLARE_CLK_ID(SMU_CKC, PERI_CPU_BASE_OFFSET, 0x00UL)

#define PERI_OUT0              DECLARE_CLK_ID(SMU_CKC, PERI_EXT_BASE_OFFSET, 0x00UL)
#define PERI_OUT1              DECLARE_CLK_ID(SMU_CKC, PERI_EXT_BASE_OFFSET, 0x04UL)
#define PERI_OUT2              DECLARE_CLK_ID(SMU_CKC, PERI_EXT_BASE_OFFSET, 0x08UL)
#define PERI_OUT3              DECLARE_CLK_ID(SMU_CKC, PERI_EXT_BASE_OFFSET, 0x0CUL)
#define PERI_OUT4              DECLARE_CLK_ID(SMU_CKC, PERI_EXT_BASE_OFFSET, 0x10UL)
#define PERI_OUT5              DECLARE_CLK_ID(SMU_CKC, PERI_EXT_BASE_OFFSET, 0x14UL)

#define PERI_HSMB              DECLARE_CLK_ID(SMU_CKC, PERI_SSS_BASE_OFFSET, 0x00UL)

/* Use this macro to find register address for each SWRESET & CLKEN ID */
#define	CKC_SWRST_CLKEN_ID(A) ((A)/32UL)

/* Register SWRESET 	(0x14000284) */
/* Register SWRSTDIS 	(0x14000288) */
#define SMUBUS_START            0UL
#define SMUBUS_CLK_RST_EN       CKC_SWRST_CLKEN_ID(SMUBUS_START)
#define SMUBUS_CA72             SMUBUS_START
#define SMUBUS_CA53             (SMUBUS_START + 1UL)
#define SMUBUS_CPU_SUB          (SMUBUS_START + 2UL)
#define SMUBUS_CM_SUB           (SMUBUS_START + 3UL)
#define SMUBUS_MEM              (SMUBUS_START + 4UL)
#define SMUBUS_VPU              (SMUBUS_START + 5UL)
#define SMUBUS_HSIO             (SMUBUS_START + 6UL)
#define SMUBUS_SMU              (SMUBUS_START + 7UL)
#define SMUBUS_3D               (SMUBUS_START + 8UL)
#define SMUBUS_DDI              (SMUBUS_START + 9UL)
#define SMUBUS_2D               (SMUBUS_START + 10UL)
#define SMUBUS_IO               (SMUBUS_START + 11UL)
#define SMUBUS_CODA             (SMUBUS_START + 12UL)
#define SMUBUS_CHEVCDEC         (SMUBUS_START + 13UL)
#define SMUBUS_RESERVE14        (SMUBUS_START + 14UL)
#define SMUBUS_BHEVCDEC	        (SMUBUS_START + 15UL)
#define SMUBUS_RESERVE16        (SMUBUS_START + 16UL)
#define SMUBUS_PCIe             (SMUBUS_START + 17UL)
#define SMUBUS_RESERVE18        (SMUBUS_START + 18UL)
#define SMUBUS_RESERVE19        (SMUBUS_START + 19UL)
#define SMUBUS_RESERVE20        (SMUBUS_START + 20UL)
#define SMUBUS_CHEVCENC         (SMUBUS_START + 21UL)
#define SMUBUS_BHEVCENC         (SMUBUS_START + 22UL)
#define SMUBUS_USB30            (SMUBUS_START + 23UL)
#define SMUBUS_RESERVE24        (SMUBUS_START + 24UL)
#define SMUBUS_RESERVE25        (SMUBUS_START + 25UL)
#define SMUBUS_RESERVE26        (SMUBUS_START + 26UL)
#define SMUBUS_RESERVE27        (SMUBUS_START + 27UL)
#define SMUBUS_RESERVE28        (SMUBUS_START + 28UL)
#define SMUBUS_RESERVE29        (SMUBUS_START + 29UL)
#define SMUBUS_RESERVE30        (SMUBUS_START + 30UL)
#define SMUBUS_RESERVE31        (SMUBUS_START + 31UL)
#define SMUBUS_END              (SMUBUS_START + 31UL)


/* Register CLKMASK 	(0x10010000) */
/* Register SWRESET	(0x10010004) */
#define GPUBUS_START            (SMUBUS_END + 1UL)
#define GPUBUS_CLK_RST_EN       CKC_SWRST_CLKEN_ID(GPUBUS_START)
#define GPUBUS_3D               GPUBUS_START
#define GPUBUS_RESERVE1         (GPUBUS_START + 1UL)
#define GPUBUS_ADB              (GPUBUS_START + 2UL)
#define GPUBUS_RESERVE3         (GPUBUS_START + 3UL)
#define GPUBUS_RESERVE4         (GPUBUS_START + 4UL)
#define GPUBUS_RESERVE5         (GPUBUS_START + 5UL)
#define GPUBUS_RESERVE6         (GPUBUS_START + 6UL)
#define GPUBUS_RESERVE7         (GPUBUS_START + 7UL)
#define GPUBUS_RESERVE8         (GPUBUS_START + 8UL)
#define GPUBUS_RESERVE9         (GPUBUS_START + 9UL)
#define GPUBUS_RESERVE10        (GPUBUS_START + 10UL)
#define GPUBUS_RESERVE11        (GPUBUS_START + 11UL)
#define GPUBUS_RESERVE12        (GPUBUS_START + 12UL)
#define GPUBUS_RESERVE13        (GPUBUS_START + 13UL)
#define GPUBUS_RESERVE14        (GPUBUS_START + 14UL)
#define GPUBUS_RESERVE15        (GPUBUS_START + 15UL)
#define GPUBUS_RESERVE16        (GPUBUS_START + 16UL)
#define GPUBUS_RESERVE17        (GPUBUS_START + 17UL)
#define GPUBUS_RESERVE18        (GPUBUS_START + 18UL)
#define GPUBUS_RESERVE19        (GPUBUS_START + 19UL)
#define GPUBUS_RESERVE20        (GPUBUS_START + 20UL)
#define GPUBUS_RESERVE21        (GPUBUS_START + 21UL)
#define GPUBUS_RESERVE22        (GPUBUS_START + 22UL)
#define GPUBUS_RESERVE23        (GPUBUS_START + 23UL)
#define GPUBUS_RESERVE24        (GPUBUS_START + 24UL)
#define GPUBUS_RESERVE25        (GPUBUS_START + 25UL)
#define GPUBUS_RESERVE26        (GPUBUS_START + 26UL)
#define GPUBUS_RESERVE27        (GPUBUS_START + 27UL)
#define GPUBUS_RESERVE28        (GPUBUS_START + 28UL)
#define GPUBUS_RESERVE29        (GPUBUS_START + 29UL)
#define GPUBUS_RESERVE30        (GPUBUS_START + 30UL)
#define GPUBUS_RESERVE31        (GPUBUS_START + 31UL)
#define GPUBUS_END              (GPUBUS_START + 31UL)




/* HCLKEN0 Register (0x16051000) */
/* HRSTEN0 Register (0x1605100C) */
#define IOBUS0_START            (GPUBUS_END + 1UL)
#define IOBUS0_CLK_RST_EN       CKC_SWRST_CLKEN_ID(IOBUS0_START)
#define IOBUS_IC_TC             IOBUS0_START
#define IOBUS_RESERVE1          (IOBUS0_START + 1UL)
#define IOBUS_GPSB6             (IOBUS0_START + 2UL)
#define IOBUS_RESERVE3          (IOBUS0_START + 3UL)
#define IOBUS_RESERVE4          (IOBUS0_START + 4UL)
#define IOBUS_PL080             (IOBUS0_START + 5UL)
#define IOBUS_ASRC              (IOBUS0_START + 6UL)
#define IOBUS_DMA0              (IOBUS0_START + 7UL)
#define IOBUS_DMA1              (IOBUS0_START + 8UL)
#define IOBUS_DMA2              (IOBUS0_START + 9UL)
#define IOBUS_DMA               (IOBUS0_START + 10UL)
#define IOBUS_RESERVE11         (IOBUS0_START + 11UL)
#define IOBUS_PWM               (IOBUS0_START + 12UL)
#define IOBUS_RESERVE13         (IOBUS0_START + 13UL)
#define IOBUS_I2C_S2            (IOBUS0_START + 14UL)
#define IOBUS_RESERVE15         (IOBUS0_START + 15UL)
#define IOBUS_REMOCON           (IOBUS0_START + 16UL)
#define IOBUS_RESERVE17         (IOBUS0_START + 17UL)
#define IOBUS_RESERVE18         (IOBUS0_START + 18UL)
#define IOBUS_RESERVE19         (IOBUS0_START + 19UL)
#define IOBUS_PRT               (IOBUS0_START + 20UL)
#define IOBUS_ADMA0             (IOBUS0_START + 21UL)
#define IOBUS_DAI0              (IOBUS0_START + 22UL)
#define IOBUS_SPDIF0            (IOBUS0_START + 23UL)
#define IOBUS_AUDIO0            (IOBUS0_START + 24UL)
#define IOBUS_ADMA3             (IOBUS0_START + 25UL)
#define IOBUS_DAI3              (IOBUS0_START + 26UL)
#define IOBUS_SPDIF3            (IOBUS0_START + 27UL)
#define IOBUS_AUDIO3            (IOBUS0_START + 28UL)
#define IOBUS_I2C_M0            (IOBUS0_START + 29UL)
#define IOBUS_I2C_M1            (IOBUS0_START + 30UL)
#define IOBUS_I2C_M2            (IOBUS0_START + 31UL)
#define IOBUS0_END              (IOBUS0_START + 31UL)


/* HCLKEN1 Register (0x16051004) */
/* HRSTEN1 Register (0x16051010) */
#define IOBUS1_START            (IOBUS0_END + 1UL)
#define IOBUS1_CLK_RST_EN       CKC_SWRST_CLKEN_ID(IOBUS1_START)
#define IOBUS_I2C_M3            IOBUS1_START
#define IOBUS_I2C_S0            (IOBUS1_START + 1UL)
#define IOBUS_I2C_S1            (IOBUS1_START + 2UL)
#define IOBUS_I2C0              (IOBUS1_START + 3UL)
#define IOBUS_I2C1              (IOBUS1_START + 4UL)
#define IOBUS1_RESERVE5         (IOBUS1_START + 5UL)
#define IOBUS1_RESERVE6         (IOBUS1_START + 6UL)
#define IOBUS1_RESERVE7         (IOBUS1_START + 7UL)
#define IOBUS1_RESERVE8         (IOBUS1_START + 8UL)
#define IOBUS1_RESERVE9         (IOBUS1_START + 9UL)
#define IOBUS1_RESERVE10        (IOBUS1_START + 10UL)
#define IOBUS1_RESERVE11        (IOBUS1_START + 11UL)
#define IOBUS1_RESERVE12        (IOBUS1_START + 12UL)
#define IOBUS1_RESERVE13        (IOBUS1_START + 13UL)
#define IOBUS1_RESERVE14        (IOBUS1_START + 14UL)
#define IOBUS1_RESERVE15        (IOBUS1_START + 15UL)
#define IOBUS1_RESERVE16        (IOBUS1_START + 16UL)
#define IOBUS_GPSB_2            (IOBUS1_START + 17UL)
#define IOBUS1_RESERVE18        (IOBUS1_START + 18UL)
#define IOBUS_GPSB0             (IOBUS1_START + 19UL)
#define IOBUS_GPSB1             (IOBUS1_START + 20UL)
#define IOBUS_GPSB2             (IOBUS1_START + 21UL)
#define IOBUS_GPSB3             (IOBUS1_START + 22UL)
#define IOBUS_GPSB4             (IOBUS1_START + 23UL)
#define IOBUS_GPSB5             (IOBUS1_START + 24UL)
#define IOBUS_GPSB              (IOBUS1_START + 25UL)
#define IOBUS1_RESERVE26        (IOBUS1_START + 26UL)
#define IOBUS_I2C_S3            (IOBUS1_START + 27UL)
#define IOBUS_I2C_M4            (IOBUS1_START + 28UL)
#define IOBUS_I2C_M5            (IOBUS1_START + 29UL)
#define IOBUS_I2C_M6            (IOBUS1_START + 30UL)
#define IOBUS_I2C_M7            (IOBUS1_START + 31UL)
#define IOBUS1_END              (IOBUS1_START + 31UL)


/* HCLKEN2 Register (0x16051008) */
/* HRSTEN2 Register (0x16051014) */
#define IOBUS2_START            (IOBUS1_END + 1UL)
#define IOBUS2_CLK_RST_EN       CKC_SWRST_CLKEN_ID(IOBUS2_START)
#define IOBUS_UART0             IOBUS2_START
#define IOBUS_UART1             (IOBUS2_START + 1UL)
#define IOBUS_UART2             (IOBUS2_START + 2UL)
#define IOBUS_UART3             (IOBUS2_START + 3UL)
#define IOBUS_UART4             (IOBUS2_START + 4UL)
#define IOBUS_UART5             (IOBUS2_START + 5UL)
#define IOBUS_UART6             (IOBUS2_START + 6UL)
#define IOBUS_UART7             (IOBUS2_START + 7UL)
#define IOBUS_UART8             (IOBUS2_START + 8UL)
#define IOBUS2_RESERVE9         (IOBUS2_START + 9UL)
#define IOBUS2_RESERVE10        (IOBUS2_START + 10UL)
#define IOBUS2_RESERVE11        (IOBUS2_START + 11UL)
#define IOBUS2_RESERVE12        (IOBUS2_START + 12UL)
#define IOBUS2_RESERVE13        (IOBUS2_START + 13UL)
#define IOBUS2_RESERVE14        (IOBUS2_START + 14UL)
#define IOBUS2_RESERVE15        (IOBUS2_START + 15UL)
#define IOBUS_UDMA0             (IOBUS2_START + 16UL)
#define IOBUS_UDMA1             (IOBUS2_START + 17UL)
#define IOBUS_UDMA2             (IOBUS2_START + 18UL)
#define IOBUS_UDMA3             (IOBUS2_START + 19UL)
#define IOBUS_UART_SMARTCARD0   (IOBUS2_START + 20UL)
#define IOBUS_UART_SMARTCARD1   (IOBUS2_START + 21UL)
#define IOBUS_UDMA4             (IOBUS2_START + 22UL)
#define IOBUS_UDMA5             (IOBUS2_START + 23UL)
#define IOBUS_UDMA6             (IOBUS2_START + 24UL)
#define IOBUS_UDMA7             (IOBUS2_START + 25UL)
#define IOBUS_UDMA8             (IOBUS2_START + 26UL)
#define IOBUS2_RESERVE27        (IOBUS2_START + 27UL)
#define IOBUS2_RESERVE28        (IOBUS2_START + 28UL)
#define IOBUS2_RESERVE29        (IOBUS2_START + 29UL)
#define IOBUS2_RESERVE30        (IOBUS2_START + 30UL)
#define IOBUS2_RESERVE31        (IOBUS2_START + 31UL)
#define IOBUS2_END              (IOBUS2_START + 31UL)


/* HCLKEN_STR Register (0x16494000) */
/* HRSTEN_STR Register (0x16494004) */
#define IOBUS3_START            (IOBUS2_END + 1UL)
#define IOBUS3_CLK_RST_EN       CKC_SWRST_CLKEN_ID(IOBUS3_START)
#define IOBUS_GDMA1             IOBUS3_START
#define IOBUS3_RESERVE1         (IOBUS3_START + 1UL)
#define IOBUS3_RESERVE2         (IOBUS3_START + 2UL)
#define IOBUS_SDMMC1            (IOBUS3_START + 3UL)
#define IOBUS_SDMMC2            (IOBUS3_START + 4UL)
#define IOBUS_SDMMC             (IOBUS3_START + 5UL)
#define IOBUS3_RESERVE6         (IOBUS3_START + 6UL)
#define IOBUS3_RESERVE7         (IOBUS3_START + 7UL)
#define IOBUS3_RESERVE8         (IOBUS3_START + 8UL)
#define IOBUS3_RESERVE9         (IOBUS3_START + 9UL)
#define IOBUS_RTC               (IOBUS3_START + 10UL)
#define IOBUS3_RESERVE11        (IOBUS3_START + 11UL)
#define IOBUS3_RESERVE12        (IOBUS3_START + 12UL)
#define IOBUS3_RESERVE13        (IOBUS3_START + 13UL)
#define IOBUS3_RESERVE14        (IOBUS3_START + 14UL)
#define IOBUS3_RESERVE15        (IOBUS3_START + 15UL)
#define IOBUS3_RESERVE16        (IOBUS3_START + 16UL)
#define IOBUS3_RESERVE17        (IOBUS3_START + 17UL)
#define IOBUS3_RESERVE18        (IOBUS3_START + 18UL)
#define IOBUS3_RESERVE19        (IOBUS3_START + 19UL)
#define IOBUS3_RESERVE20        (IOBUS3_START + 20UL)
#define IOBUS3_RESERVE21        (IOBUS3_START + 21UL)
#define IOBUS3_RESERVE22        (IOBUS3_START + 22UL)
#define IOBUS3_RESERVE23        (IOBUS3_START + 23UL)
#define IOBUS3_RESERVE24        (IOBUS3_START + 24UL)
#define IOBUS3_RESERVE25        (IOBUS3_START + 25UL)
#define IOBUS3_RESERVE26        (IOBUS3_START + 26UL)
#define IOBUS3_RESERVE27        (IOBUS3_START + 27UL)
#define IOBUS3_RESERVE28        (IOBUS3_START + 28UL)
#define IOBUS3_RESERVE29        (IOBUS3_START + 29UL)
#define IOBUS3_RESERVE30        (IOBUS3_START + 30UL)
#define IOBUS3_RESERVE31        (IOBUS3_START + 31UL)
#define IOBUS3_END              (IOBUS3_START + 31UL)

/* HCLKEN3 Register (0x16051050) */
#define IOBUS4_START            (IOBUS3_END + 1UL)
#define IOBUS4_CLK_RST_EN       CKC_SWRST_CLKEN_ID(IOBUS4_START)
#define IOBUS_ADMA1             IOBUS4_START
#define IOBUS_DAI1              (IOBUS4_START + 1UL)
#define IOBUS_SPDIF1            (IOBUS4_START + 2UL)
#define IOBUS_AUDIO1            (IOBUS4_START + 3UL)
#define IOBUS_ADMA2             (IOBUS4_START + 4UL)
#define IOBUS_DAI2              (IOBUS4_START + 5UL)
#define IOBUS_SPDIF2            (IOBUS4_START + 6UL)
#define IOBUS_AUDIO2            (IOBUS4_START + 7UL)
#define IOBUS_ADMA4             (IOBUS4_START + 8UL)
#define IOBUS_DAI4              (IOBUS4_START + 9UL)
#define IOBUS_SPDIF4            (IOBUS4_START + 10UL)
#define IOBUS_AUDIO4            (IOBUS4_START + 11UL)
#define IOBUS_ADMA5             (IOBUS4_START + 12UL)
#define IOBUS_DAI5              (IOBUS4_START + 13UL)
#define IOBUS_SPDIF5            (IOBUS4_START + 14UL)
#define IOBUS_AUDIO5            (IOBUS4_START + 15UL)
#define IOBUS_ADMA6             (IOBUS4_START + 16UL)
#define IOBUS_DAI6              (IOBUS4_START + 17UL)
#define IOBUS_SPDIF6            (IOBUS4_START + 18UL)
#define IOBUS_AUDIO6            (IOBUS4_START + 19UL)
#define IOBUS_ADMA7             (IOBUS4_START + 20UL)
#define IOBUS_DAI7              (IOBUS4_START + 21UL)
#define IOBUS_SPDIF7            (IOBUS4_START + 22UL)
#define IOBUS_AUDIO7            (IOBUS4_START + 23UL)
#define IOBUS4_RESERVE24        (IOBUS4_START + 24UL)
#define IOBUS4_RESERVE25        (IOBUS4_START + 25UL)
#define IOBUS4_RESERVE26        (IOBUS4_START + 26UL)
#define IOBUS4_RESERVE27        (IOBUS4_START + 27UL)
#define IOBUS4_RESERVE28        (IOBUS4_START + 28UL)
#define IOBUS4_RESERVE29        (IOBUS4_START + 29UL)
#define IOBUS4_RESERVE30        (IOBUS4_START + 30UL)
#define IOBUS4_RESERVE31        (IOBUS4_START + 31UL)
#define IOBUS4_END              (IOBUS4_START + 31UL)


/* PERICLKEN Register (0x16051018) */
#define IOPERI_START            (IOBUS4_END + 1UL)
#define IOPERI_CLK_EN       CKC_SWRST_CLKEN_ID(IOPERI_START)
#define IOPERI_RESERVE0          IOPERI_START
#define IOPERI_RESERVE1         (IOPERI_START + 1UL)
#define IOPERI_RESERVE2         (IOPERI_START + 2UL)
#define IOPERI_RESERVE3         (IOPERI_START + 3UL)
#define IOPERI_RESERVE4         (IOPERI_START + 4UL)
#define IOPERI_RESERVE5         (IOPERI_START + 5UL)
#define IOPERI_RESERVE6         (IOPERI_START + 6UL)
#define IOPERI_RESERVE7         (IOPERI_START + 7UL)
#define IOPERI_UART0            (IOPERI_START + 8UL)
#define IOPERI_UART1            (IOPERI_START + 9UL)
#define IOPERI_UART2            (IOPERI_START + 10UL)
#define IOPERI_UART3            (IOPERI_START + 11UL)
#define IOPERI_UART4            (IOPERI_START + 12UL)
#define IOPERI_UART5            (IOPERI_START + 13UL)
#define IOPERI_UART6            (IOPERI_START + 14UL)
#define IOPERI_UART7            (IOPERI_START + 15UL)
#define IOPERI_UART8            (IOPERI_START + 16UL)
#define IOPERI_RESERVE17        (IOPERI_START + 17UL)
#define IOPERI_RESERVE18        (IOPERI_START + 18UL)
#define IOPERI_RESERVE19        (IOPERI_START + 19UL)
#define IOPERI_RESERVE20        (IOPERI_START + 20UL)
#define IOPERI_RESERVE21        (IOPERI_START + 21UL)
#define IOPERI_RESERVE22        (IOPERI_START + 22UL)
#define IOPERI_RESERVE23        (IOPERI_START + 23UL)
#define IOPERI_I2C_M0           (IOPERI_START + 24UL)
#define IOPERI_I2C_M1           (IOPERI_START + 25UL)
#define IOPERI_I2C_M2           (IOPERI_START + 26UL)
#define IOPERI_I2C_M3           (IOPERI_START + 27UL)
#define IOPERI_I2C_M4           (IOPERI_START + 28UL)
#define IOPERI_I2C_M5           (IOPERI_START + 29UL)
#define IOPERI_I2C_M6           (IOPERI_START + 30UL)
#define IOPERI_I2C_M7           (IOPERI_START + 31UL)
#define IOPERI_END              (IOPERI_START + 31UL)


/* HCLKMASK Register (0x11DA0000) */
/* SWRESET  Register (0x11DA0004) */
#define HSIOBUS_START            (IOPERI_END + 1UL)
#define HSIOBUS_CLK_RST_EN       CKC_SWRST_CLKEN_ID(HSIOBUS_START)
#define HSIOBUS_USB30            HSIOBUS_START
#define HSIOBUS_RESERVE1         (HSIOBUS_START + 1UL)
#define HSIOBUS_GMAC             (HSIOBUS_START + 2UL)
#define HSIOBUS_RESERVE3         (HSIOBUS_START + 3UL)
#define HSIOBUS_RESERVE4         (HSIOBUS_START + 4UL)
#define HSIOBUS_RESERVE5         (HSIOBUS_START + 5UL)
#define HSIOBUS_USB20H           (HSIOBUS_START + 6UL)
#define HSIOBUS_RESERVE7         (HSIOBUS_START + 7UL)
#define HSIOBUS_RESERVE8         (HSIOBUS_START + 8UL)
#define HSIOBUS_RESERVE9         (HSIOBUS_START + 9UL)
#define HSIOBUS_RESERVE10        (HSIOBUS_START + 10UL)
#define HSIOBUS_RESERVE11        (HSIOBUS_START + 11UL)
#define HSIOBUS_RESERVE12        (HSIOBUS_START + 12UL)
#define HSIOBUS_RESERVE13        (HSIOBUS_START + 13UL)
#define HSIOBUS_RESERVE14        (HSIOBUS_START + 14UL)
#define HSIOBUS_RESERVE15        (HSIOBUS_START + 15UL)
#define HSIOBUS_RESERVE16        (HSIOBUS_START + 16UL)
#define HSIOBUS_RESERVE17        (HSIOBUS_START + 17UL)
#define HSIOBUS_CIPHER           (HSIOBUS_START + 18UL)
#define HSIOBUS_DWC_OTG          (HSIOBUS_START + 19UL)
#define HSIOBUS_RESERVE20        (HSIOBUS_START + 20UL)
#define HSIOBUS_SECURE_WRAP      (HSIOBUS_START + 21UL)
#define HSIOBUS_TRNG             (HSIOBUS_START + 22UL)
#define HSIOBUS_RESERVE23        (HSIOBUS_START + 23UL)
#define HSIOBUS_RESERVE24        (HSIOBUS_START + 24UL)
#define HSIOBUS_RESERVE25        (HSIOBUS_START + 25UL)
#define HSIOBUS_RESERVE26        (HSIOBUS_START + 26UL)
#define HSIOBUS_RESERVE27        (HSIOBUS_START + 27UL)
#define HSIOBUS_RESERVE28        (HSIOBUS_START + 28UL)
#define HSIOBUS_RESERVE29        (HSIOBUS_START + 29UL)
#define HSIOBUS_RESERVE30        (HSIOBUS_START + 30UL)
#define HSIOBUS_RESERVE31        (HSIOBUS_START + 31UL)
#define HSIOBUS_END              (HSIOBUS_START + 31UL)

/* DDI BUS CLKEN   Register (0x17400000) */
/* DDI BUS SWRESET Register (0x17400004) */
#define DDIBUS_START            (HSIOBUS_END + 1UL)
#define DDIBUS_CLK_RST_EN       CKC_SWRST_CLKEN_ID(DDIBUS_START)
#define DDIBUS_VIOC             DDIBUS_START
#define DDIBUS_HDMI             (DDIBUS_START + 1UL)
#define DDIBUS_MIPI             (DDIBUS_START + 2UL)
#define DDIBUS_LVDS             (DDIBUS_START + 3UL)
#define DDIBUS_RESERVE4         (DDIBUS_START + 4UL)
#define DDIBUS_RESERVE5         (DDIBUS_START + 5UL)
#define DDIBUS_RESERVE6         (DDIBUS_START + 6UL)
#define DDIBUS_RESERVE7         (DDIBUS_START + 7UL)
#define DDIBUS_RESERVE8         (DDIBUS_START + 8UL)
#define DDIBUS_RESERVE9         (DDIBUS_START + 9UL)
#define DDIBUS_RESERVE10        (DDIBUS_START + 10UL)
#define DDIBUS_RESERVE11        (DDIBUS_START + 11UL)
#define DDIBUS_RESERVE12        (DDIBUS_START + 12UL)
#define DDIBUS_RESERVE13        (DDIBUS_START + 13UL)
#define DDIBUS_RESERVE14        (DDIBUS_START + 14UL)
#define DDIBUS_RESERVE15        (DDIBUS_START + 15UL)
#define DDIBUS_RESERVE16        (DDIBUS_START + 16UL)
#define DDIBUS_RESERVE17        (DDIBUS_START + 17UL)
#define DDIBUS_RESERVE18        (DDIBUS_START + 18UL)
#define DDIBUS_RESERVE19        (DDIBUS_START + 19UL)
#define DDIBUS_RESERVE20        (DDIBUS_START + 20UL)
#define DDIBUS_RESERVE21        (DDIBUS_START + 21UL)
#define DDIBUS_RESERVE22        (DDIBUS_START + 22UL)
#define DDIBUS_RESERVE23        (DDIBUS_START + 23UL)
#define DDIBUS_RESERVE24        (DDIBUS_START + 24UL)
#define DDIBUS_RESERVE25        (DDIBUS_START + 25UL)
#define DDIBUS_RESERVE26        (DDIBUS_START + 26UL)
#define DDIBUS_RESERVE27        (DDIBUS_START + 27UL)
#define DDIBUS_RESERVE28        (DDIBUS_START + 28UL)
#define DDIBUS_RESERVE29        (DDIBUS_START + 29UL)
#define DDIBUS_RESERVE30        (DDIBUS_START + 30UL)
#define DDIBUS_RESERVE31        (DDIBUS_START + 31UL)
#define DDIBUS_END              (DDIBUS_START + 31UL)

/* HCLKMASK Register (0x11DA0000) */
/* SWRESET  Register (0x11DA0004) */
#define VIDEOBUS_START            (DDIBUS_END + 1UL)
#define VIDEOBUS_CLK_RST_EN       CKC_SWRST_CLKEN_ID(VIDEOBUS_START)
#define VIDEOBUS_JPEG             VIDEOBUS_START
#define VIDEOBUS_CODA_BUS         (VIDEOBUS_START + 1UL)
#define VIDEOBUS_CODA_CORE        (VIDEOBUS_START + 2UL)
#define VIDEOBUS_HEVC_BUS         (VIDEOBUS_START + 3UL)
#define VIDEOBUS_HEVC_CORE        (VIDEOBUS_START + 4UL)
#define VIDEOBUS_HEVC_ENCODER     (VIDEOBUS_START + 5UL)
#define VIDEOBUS_RESERVE6         (VIDEOBUS_START + 6UL)
#define VIDEOBUS_RESERVE7         (VIDEOBUS_START + 7UL)
#define VIDEOBUS_RESERVE8         (VIDEOBUS_START + 8UL)
#define VIDEOBUS_RESERVE9         (VIDEOBUS_START + 9UL)
#define VIDEOBUS_RESERVE10        (VIDEOBUS_START + 10UL)
#define VIDEOBUS_RESERVE11        (VIDEOBUS_START + 11UL)
#define VIDEOBUS_RESERVE12        (VIDEOBUS_START + 12UL)
#define VIDEOBUS_RESERVE13        (VIDEOBUS_START + 13UL)
#define VIDEOBUS_RESERVE14        (VIDEOBUS_START + 14UL)
#define VIDEOBUS_RESERVE15        (VIDEOBUS_START + 15UL)
#define VIDEOBUS_RESERVE16        (VIDEOBUS_START + 16UL)
#define VIDEOBUS_RESERVE17        (VIDEOBUS_START + 17UL)
#define VIDEOBUS_RESERVE18        (VIDEOBUS_START + 18UL)
#define VIDEOBUS_RESERVE19        (VIDEOBUS_START + 19UL)
#define VIDEOBUS_RESERVE20        (VIDEOBUS_START + 20UL)
#define VIDEOBUS_RESERVE21        (VIDEOBUS_START + 21UL)
#define VIDEOBUS_RESERVE22        (VIDEOBUS_START + 22UL)
#define VIDEOBUS_RESERVE23        (VIDEOBUS_START + 23UL)
#define VIDEOBUS_RESERVE24        (VIDEOBUS_START + 24UL)
#define VIDEOBUS_RESERVE25        (VIDEOBUS_START + 25UL)
#define VIDEOBUS_RESERVE26        (VIDEOBUS_START + 26UL)
#define VIDEOBUS_RESERVE27        (VIDEOBUS_START + 27UL)
#define VIDEOBUS_RESERVE28        (VIDEOBUS_START + 28UL)
#define VIDEOBUS_RESERVE29        (VIDEOBUS_START + 29UL)
#define VIDEOBUS_RESERVE30        (VIDEOBUS_START + 30UL)
#define VIDEOBUS_RESERVE31        (VIDEOBUS_START + 31UL)
#define VIDEOBUS_END              (VIDEOBUS_START + 31UL)

/* HCLKMASK Register (0x11DA0000) */
/* SWRESET  Register (0x11DA0004) */
#define CPUBUS_START            (VIDEOBUS_END + 1UL)
#define CPUBUS_CLK_RST_EN       CKC_SWRST_CLKEN_ID(CPUBUS_START)
#define CPUBUS_WDT0             CPUBUS_START
#define CPUBUS_WDT1             (CPUBUS_START + 1UL)
#define CPUBUS_WDT2             (CPUBUS_START + 2UL)
#define CPUBUS_WDT3             (CPUBUS_START + 3UL)
#define CPUBUS_WDT4             (CPUBUS_START + 4UL)
#define CPUBUS_RESERVE5         (CPUBUS_START + 5UL)
#define CPUBUS_CBUSCFG          (CPUBUS_START + 6UL)
#define CPUBUS_MB2DAP           (CPUBUS_START + 7UL)
#define CPUBUS_DAP              (CPUBUS_START + 8UL)
#define CPUBUS_DAPCFG           (CPUBUS_START + 9UL)
#define CPUBUS_DAP2MB           (CPUBUS_START + 10UL)
#define CPUBUS_MB2CB            (CPUBUS_START + 11UL)
#define CPUBUS_AHBMUX           (CPUBUS_START + 12UL)
#define CPUBUS_APBIF            (CPUBUS_START + 13UL)
#define CPUBUS_CA72H2H          (CPUBUS_START + 14UL)
#define CPUBUS_CA72             (CPUBUS_START + 15UL)
#define CPUBUS_CA53H2H          (CPUBUS_START + 16UL)
#define CPUBUS_CA53             (CPUBUS_START + 17UL)
#define CPUBUS_GIC0_H2X         (CPUBUS_START + 18UL)
#define CPUBUS_GIC0             (CPUBUS_START + 19UL)
#define CPUBUS_MBOX             (CPUBUS_START + 20UL)
#define CPUBUS_RESERVE21        (CPUBUS_START + 21UL)
#define CPUBUS_WDT5             (CPUBUS_START + 22UL)
#define CPUBUS_WDT6             (CPUBUS_START + 23UL)
#define CPUBUS_WDT7             (CPUBUS_START + 24UL)
#define CPUBUS_DAPNIC           (CPUBUS_START + 25UL)
#define CPUBUS_SJTAG            (CPUBUS_START + 26UL)
#define CPUBUS_GIC1_H2X         (CPUBUS_START + 27UL)
#define CPUBUS_GIC1             (CPUBUS_START + 28UL)
#define CPUBUS_MPPOR            (CPUBUS_START + 29UL)
#define CPUBUS_APPOR            (CPUBUS_START + 30UL)
#define CPUBUS_RESERVE31        (CPUBUS_START + 31UL)
#define CPUBUS_END              (CPUBUS_START + 31UL)



/* PLL source clock (Not support CLK_F_GET_SRC_CLK yet) */
#define PLL_SRC_XIN			0U

/* Source clock flags for CLK_F_GET_SRC_CLK */
/* SYSTEM BUS SEL */
#define SMU_CLKCTRL_SEL_PLL0            0U
#define SMU_CLKCTRL_SEL_PLL1            1U
#define SMU_CLKCTRL_SEL_PLL2            2U
#define SMU_CLKCTRL_SEL_PLL3            3U
#define SMU_CLKCTRL_SEL_PLL4            4U
#define SMU_CLKCTRL_SEL_XIN             5U
//#define SMU_CLKCTRL_SEL_EXTIN0          6U
#define SMU_CLKCTRL_SEL_PLL0DIV         7U
#define SMU_CLKCTRL_SEL_PLL1DIV         8U
#define SMU_CLKCTRL_SEL_PLL2DIV         9U
#define SMU_CLKCTRL_SEL_PLL3DIV         10U
#define SMU_CLKCTRL_SEL_PLL4DIV         11U
#define SMU_CLKCTRL_SEL_XINDIV          12U
//#define SMU_CLKCTRL_SEL_EXTIN1          13U
#define SMU_CLKCTRL_SEL_EXTIN2          14U
#define SMU_CLKCTRL_SEL_EXTIN3          15U

/* Peripheral SEL */
#define SMU_PCLKCTRL_SEL_PLL0           0U
#define SMU_PCLKCTRL_SEL_PLL1           1U
#define SMU_PCLKCTRL_SEL_PLL2           2U
#define SMU_PCLKCTRL_SEL_PLL3           3U
#define SMU_PCLKCTRL_SEL_PLL4           4U
#define SMU_PCLKCTRL_SEL_XIN            5U
#define SMU_PCLKCTRL_SEL_XTIN           6U

#define SMU_PCLKCTRL_SEL_PLL0DIV        10U
#define SMU_PCLKCTRL_SEL_PLL1DIV        11U
#define SMU_PCLKCTRL_SEL_PLL2DIV        12U
#define SMU_PCLKCTRL_SEL_PLL3DIV        13U
#define SMU_PCLKCTRL_SEL_PLL4DIV        14U

#define SMU_PCLKCTRL_SEL_PCI0PHY_CLKOUT 18U
#define SMU_PCLKCTRL_SEL_PCI1PHY_CLKOUT 19U

#define SMU_PCLKCTRL_SEL_DP_PLL         21U

#define SMU_PCLKCTRL_SEL_XINDIV         23U
#define SMU_PCLKCTRL_SEL_XTINDIV        24U
#define SMU_PCLKCTRL_SEL_EXTCLK0        25U
#define SMU_PCLKCTRL_SEL_EXTCLK1        26U

/* GPU BUS SEL */
#define GPU_CLKCTRL_SEL_XIN             0U
#define GPU_CLKCTRL_SEL_PLL             1U
#define GPU_CLKCTRL_SEL_PLLDIV          2U
#define GPU_CLKCTRL_SEL_EXTCLK          3U

/* MEMORY BUS SEL */
#define MEMORY_CLKCTRL_SEL_XIN          0U
#define MEMORY_CLKCTRL_SEL_PLL          1U
#define MEMORY_CLKCTRL_SEL_PLLDIV0      3U
#define MEMORY_CLKCTRL_SEL_PLLDIV1      4U
#define MEMORY_CLKCTRL_SEL_PLLDIV2      5U
#define MEMORY_CLKCTRL_SEL_PLLDIV3      6U
#define MEMORY_CLKCTRL_SEL_XTIN         7U
#define MEMORY_CLKCTRL_SEL_EXTCLK      15U

/* DP BUS SEL */
#define DP_CLKCTRL_SEL_XIN              0U
#define DP_CLKCTRL_SEL_PLL              1U
#define DP_CLKCTRL_SEL_PLLDIV           2U
#define DP_CLKCTRL_SEL_EXTCLK           3U

/* MIPI BUS SEL */
#define MIPI_CLKCTRL_SEL_XIN            0U
#define MIPI_CLKCTRL_SEL_PLL            1U
#define MIPI_CLKCTRL_SEL_PLLDIV         2U
#define MIPI_CLKCTRL_SEL_EXTCLK         3U

/* VIDEO BUS SEL */
#define VIDEO_CLKCTRL_SEL_XIN           0U
#define VIDEO_CLKCTRL_SEL_PLL0          1U
#define VIDEO_CLKCTRL_SEL_PLL1          2U
#define VIDEO_CLKCTRL_SEL_PLL0_DIV0     3U
#define VIDEO_CLKCTRL_SEL_PLL0_DIV1     4U
#define VIDEO_CLKCTRL_SEL_PLL1_DIV0     5U
#define VIDEO_CLKCTRL_SEL_PLL1_DIV1     6U
#define VIDEO_CLKCTRL_SEL_EXTCLK        7U

/* CPU BUS SEL */
#define CPU_CLKCTRL_SEL_XIN             0U
#define CPU_CLKCTRL_SEL_PLL             1U
#define CPU_CLKCTRL_SEL_PLLDIV          2U
#define CPU_CLKCTRL_SEL_EXTCLK          3U


#endif
