# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2019 Texas Instruments Incorporated - http://www.ti.com
#

# Modified by Telechips Inc. (date: 2020-05)

obj-$(CONFIG_UFS) += ufs-uclass.o
obj-$(CONFIG_UFS_CORE) += ufs.o
obj-$(CONFIG_CADENCE_UFS) += cdns-platform.o
obj-$(CONFIG_TI_J721E_UFS) += ti-j721e-ufs.o
obj-$(CONFIG_TCC_UFS) += tcc-ufs.o
obj-$(CONFIG_TCC_SC_UFS) += tcc_sc_ufs.o
obj-$(CONFIG_SUPPORT_UFS_RPMB) += rpmb.o
