/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * Copyright (C) Telechips Inc.
 */

#ifndef VIOC_CONFIG_H
#define VIOC_CONFIG_H

/*
 * register offset
 */
#define RAWSTATUS0_OFFSET (0x000U)
#define RAWSTATUS1_OFFSET (0x004U)
#define RAWSTATUS2_OFFSET (0x008U)
#define SYNCSTATUS0_OFFSET (0x010U)
#define SYNCSTATUS1_OFFSET (0x014U)
#define SYNCSTATUS2_OFFSET (0x018U)
#define VECTORID_OFFSET (0x028U)
#define CFG_PATH_MC_OFFSET (0x03CU)
#define CFG_MISC0_OFFSET (0x040U)
#define CFG_PATH_SC0_OFFSET (0x044U)
#define CFG_PATH_SC1_OFFSET (0x048U)
#define CFG_PATH_SC2_OFFSET (0x04CU)
#define CFG_PATH_SC3_OFFSET (0x050U)
#define CFG_PATH_VIQE0_OFFSET (0x054U)
#define CFG_MISC1_OFFSET (0x084U)
#define CFG_MISC2_OFFSET (0x088U)
#define CFG_FBC_DEC_SEL_OFFSET (0x0B0U)
#define CFG_DEV_SEL0_OFFSET (0x0B8U)
#define CFG_DEV_SEL1_OFFSET (0x0BCU)
#define ARID_OFFSET (0x0C0U)
#define AWID_OFFSET (0x0C4U)
#define PWR_AUTOPD_OFFSET (0x0C8U)
#define PWR_CLKCTRL_OFFSET (0x0CCU)
#define PWR_BLK_PWDN0_OFFSET (0x0D0U)
#define PWR_BLK_PWDN1_OFFSET (0x0D4U)
#define PWR_BLK_SWR0_OFFSET (0x0D8U)
#define PWR_BLK_SWR1_OFFSET (0x0DCU)
#define CFG_WMIX_PATH_SWR_OFFSET (0x0E8U)
#define IRQSELECT0_0_OFFSET (0x400U)
#define IRQSELECT0_1_OFFSET (0x404U)
#define IRQSELECT0_2_OFFSET (0x408U)
#define IRQMASKSET0_0_OFFSET (0x410U)
#define IRQMASKSET0_1_OFFSET (0x414U)
#define IRQMASKSET0_2_OFFSET (0x418U)
#define IRQMASKCLR0_0_OFFSET (0x420U)
#define IRQMASKCLR0_1_OFFSET (0x424U)
#define IRQMASKCLR0_2_OFFSET (0x428U)
#define IRQSELECT1_0_OFFSET (0x430U)
#define IRQSELECT1_1_OFFSET (0x434U)
#define IRQSELECT1_2_OFFSET (0x438U)
#define IRQMASKSET1_0_OFFSET (0x440U)
#define IRQMASKSET1_1_OFFSET (0x444U)
#define IRQMASKSET1_2_OFFSET (0x448U)
#define IRQMASKCLR1_0_OFFSET (0x450U)
#define IRQMASKCLR1_1_OFFSET (0x454U)
#define IRQMASKCLR1_2_OFFSET (0x458U)
#define IRQSELECT2_0_OFFSET (0x460U)
#define IRQSELECT2_1_OFFSET (0x464U)
#define IRQSELECT2_2_OFFSET (0x468U)
#define IRQMASKSET2_0_OFFSET (0x470U)
#define IRQMASKSET2_1_OFFSET (0x474U)
#define IRQMASKSET2_2_OFFSET (0x478U)
#define IRQMASKCLR2_0_OFFSET (0x480U)
#define IRQMASKCLR2_1_OFFSET (0x484U)
#define IRQMASKCLR2_2_OFFSET (0x488U)
#define IRQSELECT3_0_OFFSET (0x490U)
#define IRQSELECT3_1_OFFSET (0x494U)
#define IRQSELECT3_2_OFFSET (0x498U)
#define IRQMASKSET3_0_OFFSET (0x4A0U)
#define IRQMASKSET3_1_OFFSET (0x4A4U)
#define IRQMASKSET3_2_OFFSET (0x4A8U)
#define IRQMASKCLR3_0_OFFSET (0x4B0U)
#define IRQMASKCLR3_1_OFFSET (0x4B4U)
#define IRQMASKCLR3_2_OFFSET (0x4B8U)

/*
 * Interrupt Status 0 Registers
 * @Description: 0 - Normal, 1 - Interrupt
 */
#define RAWSTATUS0_FIFO1_SHIFT (29U)	// ASync. FIFO1 Interrupt Status
#define RAWSTATUS0_FIFO0_SHIFT (28U)	// ASync. FIFO0 Interrupt Status
#define RAWSTATUS0_MC0_SHIFT (24U)	// Map Conv0 interrupt Status
#define RAWSTATUS0_RD15_SHIFT (23U)	// RDMA15 interrupt Status
#define RAWSTATUS0_RD14_SHIFT (22U)	// RDMA14 interrupt Status
#define RAWSTATUS0_RD13_SHIFT (21U)	// RDMA13 interrupt Status
#define RAWSTATUS0_RD12_SHIFT (20U)	// RDMA12 interrupt Status
#define RAWSTATUS0_RD11_SHIFT (19U)	// RDMA11 interrupt Status
#define RAWSTATUS0_RD10_SHIFT (18U)	// RDMA10 interrupt Status
#define RAWSTATUS0_RD9_SHIFT (17U)	// RDMA09 interrupt Status
#define RAWSTATUS0_RD8_SHIFT (16U)	// RDMA08 interrupt Status
#define RAWSTATUS0_RD7_SHIFT (15U)	// RDMA07 interrupt Status
#define RAWSTATUS0_RD6_SHIFT (14U)	// RDMA06 interrupt Status
#define RAWSTATUS0_RD5_SHIFT (13U)	// RDMA05 interrupt Status
#define RAWSTATUS0_RD4_SHIFT (12U)	// RDMA04 interrupt Status
#define RAWSTATUS0_RD3_SHIFT (11U)	// RDMA03 interrupt Status
#define RAWSTATUS0_RD2_SHIFT (10U)	// RDMA02 interrupt Status
#define RAWSTATUS0_RD1_SHIFT (9U)	// RDMA01 interrupt Status
#define RAWSTATUS0_RD0_SHIFT (8U)	// RDMA00 interrupt Status
#define RAWSTATUS0_DEV4_SHIFT (4U)	// Display Controller 4 Interrupt Status
#define RAWSTATUS0_DEV3_SHIFT (3U)	// Display Controller 3 Interrupt Status
#define RAWSTATUS0_DEV2_SHIFT (2U) // Display Controller 2 interrupt Status
#define RAWSTATUS0_DEV1_SHIFT (1U) // Display Controller 1 interrupt Status
#define RAWSTATUS0_DEV0_SHIFT (0U) // Display Controller 0 interrupt Status

#define RAWSTATUS0_FIFO1_MASK ((u32)0x1U << RAWSTATUS0_FIFO1_SHIFT)
#define RAWSTATUS0_FIFO0_MASK ((u32)0x1U << RAWSTATUS0_FIFO0_SHIFT)
#define RAWSTATUS0_MC0_MASK ((u32)0x1U << RAWSTATUS0_MC0_SHIFT)
#define RAWSTATUS0_RD15_MASK ((u32)0x1U << RAWSTATUS0_RD15_SHIFT)
#define RAWSTATUS0_RD14_MASK ((u32)0x1U << RAWSTATUS0_RD14_SHIFT)
#define RAWSTATUS0_RD13_MASK ((u32)0x1U << RAWSTATUS0_RD13_SHIFT)
#define RAWSTATUS0_RD12_MASK ((u32)0x1U << RAWSTATUS0_RD12_SHIFT)
#define RAWSTATUS0_RD11_MASK ((u32)0x1U << RAWSTATUS0_RD11_SHIFT)
#define RAWSTATUS0_RD10_MASK ((u32)0x1U << RAWSTATUS0_RD10_SHIFT)
#define RAWSTATUS0_RD9_MASK ((u32)0x1U << RAWSTATUS0_RD9_SHIFT)
#define RAWSTATUS0_RD8_MASK ((u32)0x1U << RAWSTATUS0_RD8_SHIFT)
#define RAWSTATUS0_RD7_MASK ((u32)0x1U << RAWSTATUS0_RD7_SHIFT)
#define RAWSTATUS0_RD6_MASK ((u32)0x1U << RAWSTATUS0_RD6_SHIFT)
#define RAWSTATUS0_RD5_MASK ((u32)0x1U << RAWSTATUS0_RD5_SHIFT)
#define RAWSTATUS0_RD4_MASK ((u32)0x1U << RAWSTATUS0_RD4_SHIFT)
#define RAWSTATUS0_RD3_MASK ((u32)0x1U << RAWSTATUS0_RD3_SHIFT)
#define RAWSTATUS0_RD2_MASK ((u32)0x1U << RAWSTATUS0_RD2_SHIFT)
#define RAWSTATUS0_RD1_MASK ((u32)0x1U << RAWSTATUS0_RD1_SHIFT)
#define RAWSTATUS0_RD0_MASK ((u32)0x1U << RAWSTATUS0_RD0_SHIFT)
#define RAWSTATUS0_DEV4_MASK ((u32)0x1U << RAWSTATUS0_DEV4_SHIFT)
#define RAWSTATUS0_DEV3_MASK ((u32)0x1U << RAWSTATUS0_DEV3_SHIFT)
#define RAWSTATUS0_DEV2_MASK ((u32)0x1U << RAWSTATUS0_DEV2_SHIFT)
#define RAWSTATUS0_DEV1_MASK ((u32)0x1U << RAWSTATUS0_DEV1_SHIFT)
#define RAWSTATUS0_DEV0_MASK ((u32)0x1U << RAWSTATUS0_DEV0_SHIFT)

/*
 * Interrupt Status 1 Registers
 * @Description: 0 - Normal, 1 - Interrupt
 */
#define RAWSTATUS1_SC3_SHIFT (31U)	// Scaler3 Interrupt Status
#define RAWSTATUS1_SC2_SHIFT (30U)	// Scaler2 Interrupt Status
#define RAWSTATUS1_SC1_SHIFT (29U)	// Scaler1 Interrupt Status
#define RAWSTATUS1_SC0_SHIFT (28U)	// Scaler0 Interrupt Status
#define RAWSTATUS1_VIQE0_SHIFT (27U)	// VIQE0 Interrupt Status
#define RAWSTATUS1_WMIX3_SHIFT (19U)	// WMIX3 Interrupt Status
#define RAWSTATUS1_WMIX2_SHIFT (18U)	// WMIX2 Interrupt Status
#define RAWSTATUS1_WMIX1_SHIFT (17U)	// WMIX1 Interrupt Status
#define RAWSTATUS1_WMIX0_SHIFT (16U)	// WMIX0 Interrupt Status
#define RAWSTATUS1_TIMER_SHIFT (8U)		// TIMER Interrupt Status
#define RAWSTATUS1_WD5_SHIFT (5U)	// WDMA05 Interrupt Status
#define RAWSTATUS1_WD4_SHIFT (4U)	// WDMA04 Interrupt Status
#define RAWSTATUS1_WD3_SHIFT (3U)	// WDMA03 Interrupt Status
#define RAWSTATUS1_WD2_SHIFT (2U)	// WDMA02 Interrupt Status
#define RAWSTATUS1_WD1_SHIFT (1U)	// WDMA01 Interrupt Status
#define RAWSTATUS1_WD0_SHIFT (0U)	// WDMA00 Interrupt Status

#define RAWSTATUS1_SC3_MASK ((u32)0x1U << RAWSTATUS1_SC3_SHIFT)
#define RAWSTATUS1_SC2_MASK ((u32)0x1U << RAWSTATUS1_SC2_SHIFT)
#define RAWSTATUS1_SC1_MASK ((u32)0x1U << RAWSTATUS1_SC1_SHIFT)
#define RAWSTATUS1_SC0_MASK ((u32)0x1U << RAWSTATUS1_SC0_SHIFT)
#define RAWSTATUS1_VIQE0_MASK ((u32)0x1U << RAWSTATUS1_VIQE0_SHIFT)
#define RAWSTATUS1_WMIX3_MASK ((u32)0x1U << RAWSTATUS1_WMIX3_SHIFT)
#define RAWSTATUS1_WMIX2_MASK ((u32)0x1U << RAWSTATUS1_WMIX2_SHIFT)
#define RAWSTATUS1_WMIX1_MASK ((u32)0x1U << RAWSTATUS1_WMIX1_SHIFT)
#define RAWSTATUS1_WMIX0_MASK ((u32)0x1U << RAWSTATUS1_WMIX0_SHIFT)
#define RAWSTATUS1_TIMER_MASK ((u32)0x1U << RAWSTATUS1_TIMER_SHIFT)
#define RAWSTATUS1_WD5_MASK ((u32)0x1U << RAWSTATUS1_WD5_SHIFT)
#define RAWSTATUS1_WD4_MASK ((u32)0x1U << RAWSTATUS1_WD4_SHIFT)
#define RAWSTATUS1_WD3_MASK ((u32)0x1U << RAWSTATUS1_WD3_SHIFT)
#define RAWSTATUS1_WD2_MASK ((u32)0x1U << RAWSTATUS1_WD2_SHIFT)
#define RAWSTATUS1_WD1_MASK ((u32)0x1U << RAWSTATUS1_WD1_SHIFT)
#define RAWSTATUS1_WD0_MASK ((u32)0x1U << RAWSTATUS1_WD0_SHIFT)

/*
 * Interrupt Status 2 Register
 */
#define RAWSTATUS2_AFBC_SECURE_ID_ERR1_SHIFT (11U) // AFBC_DEC_SECURE_ID_ERR1 Interrupt Status
#define RAWSTATUS2_AFBC_SECURE_ID_ERR0_SHIFT (10U) // AFBC_DEC_SECURE_ID_ERR0 Interrupt Status
#define RAWSTATUS2_AFBC_DETILING_ERR1_SHIFT (9U) // AFBC_DEC_DETILING_ERR1 Interrupt Status
#define RAWSTATUS2_AFBC_DETILING_ERR0_SHIFT (8U) // AFBC_DEC_DETILING_ERR0 Interrupt Status
#define RAWSTATUS2_AFBC_DECODE_ERR1_SHIFT (7U) // AFBC_DEC_DECODE_ERR1 Interrupt Status
#define RAWSTATUS2_AFBC_DECODE_ERR0_SHIFT (6U) // AFBC_DEC_DECODE_ERR0 Interrupt Status
#define RAWSTATUS2_AFBC_CONFIG_SWAP1_SHIFT (5U) // AFBC_DEC_CONFIG_SWAP1 Interrupt Status
#define RAWSTATUS2_AFBC_CONFIG_SWAP0_SHIFT (4U) // AFBC_DEC_CONFIG_SWAP0 Interrupt Status
#define RAWSTATUS2_AFBC_AXI1_SHIFT (3U) // AFBC_DEC_AXI_ERROR1 Interrupt Status
#define RAWSTATUS2_AFBC_AXI0_SHIFT (2U) // AFBC_DEC_AXI_ERROR0 Interrupt Status
#define RAWSTATUS2_AFBC_DEC1_SHIFT (1U) // AFBC_DEC1 Interrupt Status
#define RAWSTATUS2_AFBC_DEC0_SHIFT (0U) // AFBC_DEC0 Interrupt Status

#define RAWSTATUS2_AFBC_SECURE_ID_ERR1_MASK ((u32)0x1U << RAWSTATUS2_AFBC_SECURE_ID_ERR1_SHIFT)
#define RAWSTATUS2_AFBC_SECURE_ID_ERR0_MASK ((u32)0x1U << RAWSTATUS2_AFBC_SECURE_ID_ERR0_SHIFT)
#define RAWSTATUS2_AFBC_DETILING_ERR1_MASK ((u32)0x1U << RAWSTATUS2_AFBC_DETILING_ERR1_SHIFT)
#define RAWSTATUS2_AFBC_DETILING_ERR0_MASK ((u32)0x1U << RAWSTATUS2_AFBC_DETILING_ERR0_SHIFT)
#define RAWSTATUS2_AFBC_DECODE_ERR1_MASK ((u32)0x1U << RAWSTATUS2_AFBC_DECODE_ERR1_SHIFT)
#define RAWSTATUS2_AFBC_DECODE_ERR0_MASK ((u32)0x1U << RAWSTATUS2_AFBC_DECODE_ERR0_SHIFT)
#define RAWSTATUS2_AFBC_CONFIG_SWAP1_MASK ((u32)0x1U << RAWSTATUS2_AFBC_CONFIG_SWAP1_SHIFT)
#define RAWSTATUS2_AFBC_CONFIG_SWAP0_MASK ((u32)0x1U << RAWSTATUS2_AFBC_CONFIG_SWAP0_SHIFT)
#define RAWSTATUS2_AFBC_AXI1_MASK ((u32)0x1U << RAWSTATUS2_AFBC_AXI1_SHIFT)
#define RAWSTATUS2_AFBC_AXI0_MASK ((u32)0x1U << RAWSTATUS2_AFBC_AXI0_SHIFT)
#define RAWSTATUS2_AFBC_DEC1_MASK ((u32)0x1U << RAWSTATUS2_AFBC_DEC1_SHIFT)
#define RAWSTATUS2_AFBC_DEC0_MASK ((u32)0x1U << RAWSTATUS2_AFBC_DEC0_SHIFT)

/*
 * Sync Interrupt Status 0 Registers
 * @Description: 0 - Normal, 1 - Interrupt
 */
#define SYNCSTATUS0_FIFO1_SHIFT (29U) // ASync. FIFO1 Sync Interrupt Status
#define SYNCSTATUS0_FIFO0_SHIFT (28U) // ASync. FIFO0 Sync Interrupt Status
#define SYNCSTATUS0_MC0_SHIFT (24U)	// Map Conv0 Sync Interrupt Status
#define SYNCSTATUS0_RD15_SHIFT (23U)	// RDMA15 Sync Interrupt Status
#define SYNCSTATUS0_RD14_SHIFT (22U)	// RDMA14 Sync Interrupt Status
#define SYNCSTATUS0_RD13_SHIFT (20U)	// RDMA13 Sync Interrupt Status
#define SYNCSTATUS0_RD12_SHIFT (20U)	// RDMA12 Sync Interrupt Status
#define SYNCSTATUS0_RD11_SHIFT (19U)	// RDMA11 Sync Interrupt Status
#define SYNCSTATUS0_RD10_SHIFT (18U)	// RDMA10 Sync Interrupt Status
#define SYNCSTATUS0_RD9_SHIFT (17U)	// RDMA09 Sync Interrupt Status
#define SYNCSTATUS0_RD8_SHIFT (16U)	// RDMA08 Sync Interrupt Status
#define SYNCSTATUS0_RD7_SHIFT (15U)	// RDMA07 Sync Interrupt Status
#define SYNCSTATUS0_RD6_SHIFT (14U)	// RDMA06 Sync Interrupt Status
#define SYNCSTATUS0_RD5_SHIFT (13U)	// RDMA05 Sync Interrupt Status
#define SYNCSTATUS0_RD4_SHIFT (12U)	// RDMA04 Sync Interrupt Status
#define SYNCSTATUS0_RD3_SHIFT (11U)	// RDMA03 Sync Interrupt Status
#define SYNCSTATUS0_RD2_SHIFT (10U)	// RDMA02 Sync Interrupt Status
#define SYNCSTATUS0_RD1_SHIFT (9U)	// RDMA01 Sync Interrupt Status
#define SYNCSTATUS0_RD0_SHIFT (8U)	// RDMA00 Sync Interrupt Status
#define SYNCSTATUS0_DEV4_SHIFT (4U) // Display Controller 4 Sync Interrupt Status
#define SYNCSTATUS0_DEV3_SHIFT (3U) // Display Controller 3 Sync Interrupt Status
#define SYNCSTATUS0_DEV2_SHIFT (2U) // Display Controller 2 Sync Interrupt Status
#define SYNCSTATUS0_DEV1_SHIFT (1U) // Display Controller 1 Sync Interrupt Status
#define SYNCSTATUS0_DEV0_SHIFT (0U) // Display Controller 0 Sync Interrupt Status

#define SYNCSTATUS0_FIFO1_MASK ((u32)0x1U << SYNCSTATUS0_FIFO1_SHIFT)
#define SYNCSTATUS0_FIFO0_MASK ((u32)0x1U << SYNCSTATUS0_FIFO0_SHIFT)
#define SYNCSTATUS0_MC0_MASK ((u32)0x1U <<	SYNCSTATUS0_MC0_SHIFT)
#define SYNCSTATUS0_RD15_MASK ((u32)0x1U <<	SYNCSTATUS0_RD15_SHIFT)
#define SYNCSTATUS0_RD14_MASK ((u32)0x1U <<	SYNCSTATUS0_RD14_SHIFT)
#define SYNCSTATUS0_RD13_MASK ((u32)0x1U <<	SYNCSTATUS0_RD13_SHIFT)
#define SYNCSTATUS0_RD12_MASK ((u32)0x1U <<	SYNCSTATUS0_RD12_SHIFT)
#define SYNCSTATUS0_RD11_MASK ((u32)0x1U <<	SYNCSTATUS0_RD11_SHIFT)
#define SYNCSTATUS0_RD10_MASK ((u32)0x1U <<	SYNCSTATUS0_RD10_SHIFT)
#define SYNCSTATUS0_RD9_MASK ((u32)0x1U <<	SYNCSTATUS0_RD9_SHIFT)
#define SYNCSTATUS0_RD8_MASK ((u32)0x1U <<	SYNCSTATUS0_RD8_SHIFT)
#define SYNCSTATUS0_RD7_MASK ((u32)0x1U <<	SYNCSTATUS0_RD7_SHIFT)
#define SYNCSTATUS0_RD6_MASK ((u32)0x1U <<	SYNCSTATUS0_RD6_SHIFT)
#define SYNCSTATUS0_RD5_MASK ((u32)0x1U <<	SYNCSTATUS0_RD5_SHIFT)
#define SYNCSTATUS0_RD4_MASK ((u32)0x1U <<	SYNCSTATUS0_RD4_SHIFT)
#define SYNCSTATUS0_RD3_MASK ((u32)0x1U <<	SYNCSTATUS0_RD3_SHIFT)
#define SYNCSTATUS0_RD2_MASK ((u32)0x1U <<	SYNCSTATUS0_RD2_SHIFT)
#define SYNCSTATUS0_RD1_MASK ((u32)0x1U <<	SYNCSTATUS0_RD1_SHIFT)
#define SYNCSTATUS0_RD0_MASK ((u32)0x1U <<	SYNCSTATUS0_RD0_SHIFT)
#define SYNCSTATUS0_DEV4_MASK ((u32)0x1U <<	SYNCSTATUS0_DEV4_SHIFT)
#define SYNCSTATUS0_DEV3_MASK ((u32)0x1U <<	SYNCSTATUS0_DEV3_SHIFT)
#define SYNCSTATUS0_DEV2_MASK ((u32)0x1U <<	SYNCSTATUS0_DEV2_SHIFT)
#define SYNCSTATUS0_DEV1_MASK ((u32)0x1U <<	SYNCSTATUS0_DEV1_SHIFT)
#define SYNCSTATUS0_DEV0_MASK ((u32)0x1U <<	SYNCSTATUS0_DEV0_SHIFT)

/*
 * Sync Interrupt Status 1 Registers
 * @Description: 0 - Normal, 1 - Interrupt
 */
#define SYNCSTATUS1_SC3_SHIFT (31U)	// Scaler3 Sync Interrupt Status
#define SYNCSTATUS1_SC2_SHIFT (30U)	// Scaler2 Sync Interrupt Status
#define SYNCSTATUS1_SC1_SHIFT (29U)	// Scaler1 Sync Interrupt Status
#define SYNCSTATUS1_SC0_SHIFT (28U)	// Scaler0 Sync Interrupt Status
#define SYNCSTATUS1_VIQE0_SHIFT (27U)	// VIQE0 Sync Interrupt Status
#define SYNCSTATUS1_WMIX3_SHIFT (19U)	// WMIX3 Sync Interrupt Status
#define SYNCSTATUS1_WMIX2_SHIFT (18U)	// WMIX2 Sync Interrupt Status
#define SYNCSTATUS1_WMIX1_SHIFT (17U)	// WMIX1 Sync Interrupt Status
#define SYNCSTATUS1_WMIX0_SHIFT (16U)	// WMIX0 Sync Interrupt Status
#define SYNCSTATUS1_TIMER_SHIFT (8U)	// TIMER Sync Interrupt Status
#define SYNCSTATUS1_WD5_SHIFT (5U)	// WDMA05 Sync Interrupt Status
#define SYNCSTATUS1_WD4_SHIFT (4U)	// WDMA04 Sync Interrupt Status
#define SYNCSTATUS1_WD3_SHIFT (3U)	// WDMA03 Sync Interrupt Status
#define SYNCSTATUS1_WD2_SHIFT (2U)	// WDMA02 Sync Interrupt Status
#define SYNCSTATUS1_WD1_SHIFT (1U)	// WDMA01 Sync Interrupt Status
#define SYNCSTATUS1_WD0_SHIFT (0U)	// WDMA00 Sync Interrupt Status

#define SYNCSTATUS1_SC3_MASK ((u32)0x1U << SYNCSTATUS1_SC3_SHIFT)
#define SYNCSTATUS1_SC2_MASK ((u32)0x1U << SYNCSTATUS1_SC2_SHIFT)
#define SYNCSTATUS1_SC1_MASK ((u32)0x1U << SYNCSTATUS1_SC1_SHIFT)
#define SYNCSTATUS1_SC0_MASK ((u32)0x1U << SYNCSTATUS1_SC0_SHIFT)
#define SYNCSTATUS1_VIQE0_MASK ((u32)0x1U << SYNCSTATUS1_VIQE0_SHIFT)
#define SYNCSTATUS1_WMIX3_MASK ((u32)0x1U << SYNCSTATUS1_WMIX3_SHIFT)
#define SYNCSTATUS1_WMIX2_MASK ((u32)0x1U << SYNCSTATUS1_WMIX2_SHIFT)
#define SYNCSTATUS1_WMIX1_MASK ((u32)0x1U << SYNCSTATUS1_WMIX1_SHIFT)
#define SYNCSTATUS1_WMIX0_MASK ((u32)0x1U << SYNCSTATUS1_WMIX0_SHIFT)
#define SYNCSTATUS1_TIMER_MASK ((u32)0x1U << SYNCSTATUS1_TIMER_SHIFT)
#define SYNCSTATUS1_WD5_MASK ((u32)0x1U << SYNCSTATUS1_WD5_SHIFT)
#define SYNCSTATUS1_WD4_MASK ((u32)0x1U << SYNCSTATUS1_WD4_SHIFT)
#define SYNCSTATUS1_WD3_MASK ((u32)0x1U << SYNCSTATUS1_WD3_SHIFT)
#define SYNCSTATUS1_WD2_MASK ((u32)0x1U << SYNCSTATUS1_WD2_SHIFT)
#define SYNCSTATUS1_WD1_MASK ((u32)0x1U << SYNCSTATUS1_WD1_SHIFT)
#define SYNCSTATUS1_WD0_MASK ((u32)0x1U << SYNCSTATUS1_WD0_SHIFT)

/*
 * Sync Interrupt Status 2 Register
 */
#define SYNCSTATUS2_AFBC_SECURE_ID_ERR1_SHIFT (11U) // AFBC_DEC_SECURE_ID_ERR1 Interrupt Status
#define SYNCSTATUS2_AFBC_SECURE_ID_ERR0_SHIFT (10U) // AFBC_DEC_SECURE_ID_ERR0 Interrupt Status
#define SYNCSTATUS2_AFBC_DETILING_ERR1_SHIFT (9U) // AFBC_DEC_DETILING_ERR1 Interrupt Status
#define SYNCSTATUS2_AFBC_DETILING_ERR0_SHIFT (8U) // AFBC_DEC_DETILING_ERR0 Interrupt Status
#define SYNCSTATUS2_AFBC_DECODE_ERR1_SHIFT (7U) // AFBC_DEC_DECODE_ERR1 Interrupt Status
#define SYNCSTATUS2_AFBC_DECODE_ERR0_SHIFT (6U) // AFBC_DEC_DECODE_ERR0 Interrupt Status
#define SYNCSTATUS2_AFBC_CONFIG_SWAP1_SHIFT (5U) // AFBC_DEC_CONFIG_SWAP1 Interrupt Status
#define SYNCSTATUS2_AFBC_CONFIG_SWAP0_SHIFT (4U) // AFBC_DEC_CONFIG_SWAP0 Interrupt Status
#define SYNCSTATUS2_AFBC_AXI1_SHIFT (3U) // AFBC_DEC_AXI_ERROR1 Interrupt Status
#define SYNCSTATUS2_AFBC_AXI0_SHIFT (2U) // AFBC_DEC_AXI_ERROR0 Interrupt Status
#define SYNCSTATUS2_AFBC_DEC1_SHIFT (1U) // AFBC_DEC1 Sync Interrupt Status
#define SYNCSTATUS2_AFBC_DEC0_SHIFT (0U) // AFBC_DEC0 Sync Interrupt Status

#define SYNCSTATUS2_AFBC_SECURE_ID_ERR1_MASK ((u32)0x1U << SYNCSTATUS2_AFBC_SECURE_ID_ERR1_SHIFT)
#define SYNCSTATUS2_AFBC_SECURE_ID_ERR0_MASK ((u32)0x1U << SYNCSTATUS2_AFBC_SECURE_ID_ERR0_SHIFT)
#define SYNCSTATUS2_AFBC_DETILING_ERR1_MASK ((u32)0x1U << SYNCSTATUS2_AFBC_DETILING_ERR1_SHIFT)
#define SYNCSTATUS2_AFBC_DETILING_ERR0_MASK ((u32)0x1U << SYNCSTATUS2_AFBC_DETILING_ERR0_SHIFT)
#define SYNCSTATUS2_AFBC_DECODE_ERR1_MASK ((u32)0x1U << SYNCSTATUS2_AFBC_DECODE_ERR1_SHIFT)
#define SYNCSTATUS2_AFBC_DECODE_ERR0_MASK ((u32)0x1U << SYNCSTATUS2_AFBC_DECODE_ERR0_SHIFT)
#define SYNCSTATUS2_AFBC_CONFIG_SWAP1_MASK ((u32)0x1U << SYNCSTATUS2_AFBC_CONFIG_SWAP1_SHIFT)
#define SYNCSTATUS2_AFBC_CONFIG_SWAP0_MASK ((u32)0x1U << SYNCSTATUS2_AFBC_CONFIG_SWAP0_SHIFT)
#define SYNCSTATUS2_AFBC_AXI1_MASK ((u32)0x1U << SYNCSTATUS2_AFBC_AXI1_SHIFT)
#define SYNCSTATUS2_AFBC_AXI0_MASK ((u32)0x1U << SYNCSTATUS2_AFBC_AXI0_SHIFT)
#define SYNCSTATUS2_AFBC_DEC1_MASK ((u32)0x1U << SYNCSTATUS2_AFBC_DEC1_SHIFT)
#define SYNCSTATUS2_AFBC_DEC0_MASK ((u32)0x1U << SYNCSTATUS2_AFBC_DEC0_SHIFT)

/*
 * Vector ID Registers
 */
#define VECTORID_IVALID3_SHIFT (31U)	// Invalid Interrupt
#define VECTORID_IVALID2_SHIFT (30U)	// Invalid Interrupt
#define VECTORID_IVALID1_SHIFT (29U)	// Invalid Interrupt
#define VECTORID_IVALID0_SHIFT (28U)	// Invalid Interrupt
#define	VECTORID_INDEX3_SHIFT (21U)	// Interrupt Index
#define	VECTORID_INDEX2_SHIFT (14U)	// Interrupt Index
#define	VECTORID_INDEX1_SHIFT (7U)		// Interrupt Index
#define	VECTORID_INDEX0_SHIFT (0U)		// Interrupt Index

#define VECTORID_IVALID3_MASK ((u32)0x1U << VECTORID_IVALID3_SHIFT)
#define VECTORID_IVALID2_MASK ((u32)0x1U << VECTORID_IVALID2_SHIFT)
#define VECTORID_IVALID1_MASK ((u32)0x1U << VECTORID_IVALID1_SHIFT)
#define VECTORID_IVALID0_MASK ((u32)0x1U << VECTORID_IVALID0_SHIFT)
#define	VECTORID_INDEX3_MASK ((u32)0x7FU << VECTORID_INDEX3_SHIFT)
#define	VECTORID_INDEX2_MASK ((u32)0x7FU << VECTORID_INDEX2_SHIFT)
#define	VECTORID_INDEX1_MASK ((u32)0x7FU << VECTORID_INDEX1_SHIFT)
#define	VECTORID_INDEX0_MASK ((u32)0x7FU << VECTORID_INDEX0_SHIFT)

/*
 * Map Conv Path Configuration Register
 */
#define CFG_PATH_MC_MC0_SEL_SHIFT (16U)
#define CFG_PATH_MC_RD13_SHIFT (6U)
#define CFG_PATH_MC_RD12_SHIFT (5U)
#define CFG_PATH_MC_RD11_SHIFT (4U)
#define CFG_PATH_MC_RD10_SHIFT (3U)
#define CFG_PATH_MC_RD09_SHIFT (2U)
#define CFG_PATH_MC_RD07_SHIFT (1U)
#define CFG_PATH_MC_RD03_SHIFT (0U)

#define CFG_PATH_MC_MC0_SEL_MASK ((u32)0x7U << CFG_PATH_MC_MC0_SEL_SHIFT)
#define CFG_PATH_MC_RD13_MASK ((u32)0x1U << CFG_PATH_MC_RD13_SHIFT)
#define CFG_PATH_MC_RD12_MASK ((u32)0x1U << CFG_PATH_MC_RD12_SHIFT)
#define CFG_PATH_MC_RD11_MASK ((u32)0x1U << CFG_PATH_MC_RD11_SHIFT)
#define CFG_PATH_MC_RD10_MASK ((u32)0x1U << CFG_PATH_MC_RD10_SHIFT)
#define CFG_PATH_MC_RD9_MASK ((u32)0x1U << CFG_PATH_MC_RD09_SHIFT)
#define CFG_PATH_MC_RD07_MASK ((u32)0x1U << CFG_PATH_MC_RD07_SHIFT)
#define CFG_PATH_MC_RD03_MASK ((u32)0x1U << CFG_PATH_MC_RD03_SHIFT)

/*
 * Miscellaneous0 Configuration Registers
 */
#define CFG_MISC0_L4_EVS_SEL_SHIFT (24U)
// Select VS signal for Display Device Output Port 4
#define CFG_MISC0_MIX30_SHIFT (22U)
// WMIX3 Path Control for 0��?th Input Channel
#define CFG_MISC0_MIX20_SHIFT (20U)
// WMIX2 Path Control for 0��?th Input Channel
#define CFG_MISC0_MIX13_SHIFT (19U)
// WMIX1 Path Control for 3��?rd Input Channel
#define CFG_MISC0_MIX10_SHIFT (18U)
// WMIX1 Path Control for 0��?th Input Channel
#define CFG_MISC0_MIX03_SHIFT (17U)
// WMIX0 Path Control for 3��?rd Input Channel
#define CFG_MISC0_MIX00_SHIFT (16U)
// WMIX0 Path Control for 0��?th Input Channel
#define CFG_MISC0_L3_EVS_SEL_SHIFT (12U)
// Select VS signal for Display Device Output Port 3
#define CFG_MISC0_L2_EVS_SEL_SHIFT (8U)
// Select VS signal for Display Device Output Port 2
#define CFG_MISC0_L1_EVS_SEL_SHIFT (4U)
// Select VS signal for Display Device Output Port 1
#define CFG_MISC0_L0_EVS_SEL_SHIFT (0U)
// Select VS signal for Display Device Output Port 0

#define CFG_MISC0_L4_EVS_SEL_MASK ((u32)0xFU <<  CFG_MISC0_L4_EVS_SEL_SHIFT)
#define CFG_MISC0_MIX30_MASK ((u32)0x1U <<  CFG_MISC0_MIX30_SHIFT)
#define CFG_MISC0_MIX20_MASK ((u32)0x1U <<  CFG_MISC0_MIX20_SHIFT)
#define CFG_MISC0_MIX13_MASK ((u32)0x1U <<  CFG_MISC0_MIX13_SHIFT)
#define CFG_MISC0_MIX10_MASK ((u32)0x1U <<  CFG_MISC0_MIX10_SHIFT)
#define CFG_MISC0_MIX03_MASK ((u32)0x1U <<  CFG_MISC0_MIX03_SHIFT)
#define CFG_MISC0_MIX00_MASK ((u32)0x1U <<  CFG_MISC0_MIX00_SHIFT)
#define CFG_MISC0_L3_EVS_SEL_MASK ((u32)0xFU <<  CFG_MISC0_L3_EVS_SEL_SHIFT)
#define CFG_MISC0_L2_EVS_SEL_MASK ((u32)0xFU <<  CFG_MISC0_L2_EVS_SEL_SHIFT)
#define CFG_MISC0_L1_EVS_SEL_MASK ((u32)0xFU <<  CFG_MISC0_L1_EVS_SEL_SHIFT)
#define CFG_MISC0_L0_EVS_SEL_MASK ((u32)0xFU <<  CFG_MISC0_L0_EVS_SEL_SHIFT)

/* Scaler / VIQE register fileds are all the same */
#define CFG_PATH_EN_SHIFT (31U)	// PATH Enable
#define CFG_PATH_ERR_SHIFT (18U)	// Device Error
#define CFG_PATH_STS_SHIFT (16U)	// Path Status
#define CFG_PATH_SEL_SHIFT (0U)	// Path Selection

#define CFG_PATH_EN_MASK ((u32)0x1U << CFG_PATH_EN_SHIFT)
#define CFG_PATH_ERR_MASK ((u32)0x1U << CFG_PATH_ERR_SHIFT)
#define CFG_PATH_STS_MASK ((u32)0x3U << CFG_PATH_STS_SHIFT)
#define CFG_PATH_SEL_MASK ((u32)0xFFU << CFG_PATH_SEL_SHIFT)

/*
 * Miscellaneous1 Configuration Registers
 */
#define CFG_MISC1_LCD1_SEL_SHIFT (28U)	// LCD1 PATH select
#define CFG_MISC1_LCD0_SEL_SHIFT (24U)	// LCD0 PATH select
#define CFG_MISC1_S_REQ_SHIFT (23U)	// Disable STOP Request
#define CFG_MISC1_AXIRD_M1_TR_SHIFT (14U)	// For Debug
#define CFG_MISC1_AXIRD_M0_TR_SHIFT (12U)	// For Debug
#define CFG_MISC1_AXIRD_SHIFT (8U)	// For Debug
#define CFG_MISC1_AXIWD_SHIFT (0U)	// For Debug

#define CFG_MISC1_LCD1_SEL_MASK ((u32)0x7U << CFG_MISC1_LCD1_SEL_SHIFT)
#define CFG_MISC1_LCD0_SEL_MASK ((u32)0x7U << CFG_MISC1_LCD0_SEL_SHIFT)
#define CFG_MISC1_S_REQ_MASK ((u32)0x1U << CFG_MISC1_S_REQ_SHIFT)
#define CFG_MISC1_AXIRD_M1_TR_MASK ((u32)0x3U << CFG_MISC1_AXIRD_M1_TR_SHIFT)
#define CFG_MISC1_AXIRD_M0_TR_MASK ((u32)0x3U << CFG_MISC1_AXIRD_M0_TR_SHIFT)
#define CFG_MISC1_AXIRD_MASK ((u32)0x1U << CFG_MISC1_AXIRD_SHIFT)
#define CFG_MISC1_AXIWD_MASK ((u32)0x1U << CFG_MISC1_AXIWD_SHIFT)

/*
 * Miscellaneous2 Configuration Registers
 */
#define CFG_MISC2_LCD4_SEL_SHIFT (8U)	// LCD4 PATH select
#define CFG_MISC2_LCD3_SEL_SHIFT (4U)	// LCD3 PATH select
#define CFG_MISC2_LCD2_SEL_SHIFT (0U)	// LCD2 PATH select

#define CFG_MISC2_LCD4_SEL_MASK ((u32)0x7U << CFG_MISC2_LCD4_SEL_SHIFT)
#define CFG_MISC2_LCD3_SEL_MASK ((u32)0x7U << CFG_MISC2_LCD3_SEL_SHIFT)
#define CFG_MISC2_LCD2_SEL_MASK ((u32)0x7U << CFG_MISC2_LCD2_SEL_SHIFT)

/*
 * AFBC_DEC Configuration Register
 */
#define CFG_AFBC_DEC_SEL_AXSM_SEL_SHIFT (12U)
// AFBC_DEC_AXSM Select
#define CFG_AFBC_DEC_SEL_AD_PATH_SEL01_SHIFT (5U)
// RDMA number to use AFBC_DEC01
#define CFG_AFBC_DEC_SEL_AD_PATH_SEL00_SHIFT (0U)
// RDMA number to use AFBC_DEC00

#define CFG_FBC_DEC_SEL_AXSM_SEL_MASK \
	((u32)0xFFFFFU << CFG_AFBC_DEC_SEL_AXSM_SEL_SHIFT)
#define CFG_FBC_DEC_SEL_AD_PATH_SEL01_MASK \
	((u32)0x1FU << CFG_AFBC_DEC_SEL_AD_PATH_SEL01_SHIFT)
#define CFG_FBC_DEC_SEL_AD_PATH_SEL00_MASK \
	((u32)0x1FU << CFG_AFBC_DEC_SEL_AD_PATH_SEL00_SHIFT)

/*
 * DEV Configuration 0 Registers
 */
#define CFG_DEV_SEL0_P2_EN_SHIFT (23U)	// DEV2 Path Enable
#define CFG_DEV_SEL0_DEV2_STAT_SHIFT (20U)	// DEV2 Path Status
#define CFG_DEV_SEL0_DEV2_PATH_SHIFT (16U)	// DEV2 Path Select
#define CFG_DEV_SEL0_P1_EN_SHIFT (15U)	// DEV1 Path Enable
#define CFG_DEV_SEL0_DEV1_STAT_SHIFT (12U)	// DEV1 Path Status
#define CFG_DEV_SEL0_DEV1_PATH_SHIFT (8U)		// DEV1 Path Select
#define CFG_DEV_SEL0_P0_EN_SHIFT (7U)		// DEV0 Path Enable
#define CFG_DEV_SEL0_DEV0_STAT_SHIFT (4U)	// DEV0 Path Status
#define CFG_DEV_SEL0_DEV0_PATH_SHIFT (0U)		// DEV0 Path Select

#define CFG_DEV_SEL0_P2_EN_MASK ((u32)0x1U << CFG_DEV_SEL0_P2_EN_SHIFT)
#define CFG_DEV_SEL0_DEV2_STAT_MASK ((u32)0x7U << CFG_DEV_SEL0_DEV2_STAT_SHIFT)
#define CFG_DEV_SEL0_DEV2_PATH_MASK ((u32)0x7U << CFG_DEV_SEL0_DEV2_PATH_SHIFT)
#define CFG_DEV_SEL0_P1_EN_MASK ((u32)0x1U << CFG_DEV_SEL0_P1_EN_SHIFT)
#define CFG_DEV_SEL0_DEV1_STAT_MASK ((u32)0x7U << CFG_DEV_SEL0_DEV1_STAT_SHIFT)
#define CFG_DEV_SEL0_DEV1_PATH_MASK ((u32)0x7U << CFG_DEV_SEL0_DEV1_PATH_SHIFT)
#define CFG_DEV_SEL0_P0_EN_MASK ((u32)0x1U << CFG_DEV_SEL0_P0_EN_SHIFT)
#define CFG_DEV_SEL0_DEV0_STAT_MASK ((u32)0x7U << CFG_DEV_SEL0_DEV0_STAT_SHIFT)
#define CFG_DEV_SEL0_DEV0_PATH_MASK ((u32)0x7U << CFG_DEV_SEL0_DEV0_PATH_SHIFT)

/*
 * DEV Configuration 1 Registers
 */
#define CFG_DEV_SEL1_P4_EN_SHIFT (15U)	// DEV4 Path Enable
#define CFG_DEV_SEL1_DEV4_STAT_SHIFT (12U)	// DEV4 Path Status
#define CFG_DEV_SEL1_DEV4_PATH_SHIFT (8U)		// DEV4 Path Select
#define CFG_DEV_SEL1_P3_EN_SHIFT (7U)		// DEV3 Path Enable
#define CFG_DEV_SEL1_DEV3_STAT_SHIFT (4U)	// DEV3 Path Status
#define CFG_DEV_SEL1_DEV3_PATH_SHIFT (0U)		// DEV3 Path Select

#define CFG_DEV_SEL1_P4_EN_MASK ((u32)0x1U << CFG_DEV_SEL1_P4_EN_SHIFT)
#define CFG_DEV_SEL1_DEV4_STAT_MASK ((u32)0x7U << CFG_DEV_SEL1_DEV4_STAT_SHIFT)
#define CFG_DEV_SEL1_DEV4_PATH_MASK ((u32)0x7U << CFG_DEV_SEL1_DEV4_PATH_SHIFT)
#define CFG_DEV_SEL1_P3_EN_MASK ((u32)0x1U << CFG_DEV_SEL1_P3_EN_SHIFT)
#define CFG_DEV_SEL1_DEV3_STAT_MASK ((u32)0x7U << CFG_DEV_SEL1_DEV3_STAT_SHIFT)
#define CFG_DEV_SEL1_DEV3_PATH_MASK ((u32)0x7U << CFG_DEV_SEL1_DEV3_PATH_SHIFT)

/*
 * ARID of DMA Registers
 */
#define ARID_ARID_SHIFT (0U)	// ARID of Master DMA

#define ARID_ARID_MASK ((u32)0xFFFFFFFU << ARID_ARID_SHIFT)

/*
 * AWID of DMA Registers
 */
#define AWID_AWID_SHIFT (0U)	// AWID of Master DMA

#define AWID_AWID_MASK ((u32)0x7FFFFFFFU << AWID_AWID_SHIFT)

/*
 * Power Auto Power Down Registers
 * @Description: 0 - Normal, 1 - Auto PWDN
 */
#define PWR_AUTOPD_MC_SHIFT (15U) // Map Conv Auto Power Down Mode
#define PWR_AUTOPD_DEVMX_SHIFT (14U) // Mixer for DISP Auto Power Down Mode
#define PWR_AUTOPD_VIQE_SHIFT (5U) // VIQE Auto Power Down Mode
#define PWR_AUTOPD_WDMA_SHIFT (3U) // WDMA Auto Power Down Mode
#define PWR_AUTOPD_MIX_SHIFT (2U) // WMIX Auto Power Down Mode
#define PWR_AUTOPD_SC_SHIFT (1U) // Scaler Auto Power Down Mode
#define PWR_AUTOPD_RDMA_SHIFT (0U) // RDMA Auto Power Down Mode

#define PWR_AUTOPD_MC_MASK ((u32)0x1U << PWR_AUTOPD_MC_SHIFT)
#define PWR_AUTOPD_DEVMX_MASK ((u32)0x1U << PWR_AUTOPD_DEVMX_SHIFT)
#define PWR_AUTOPD_VIQE_MASK ((u32)0x1U << PWR_AUTOPD_VIQE_SHIFT)
#define PWR_AUTOPD_WDMA_MASK ((u32)0x1U << PWR_AUTOPD_WDMA_SHIFT)
#define PWR_AUTOPD_MIX_MASK ((u32)0x1U << PWR_AUTOPD_MIX_SHIFT)
#define PWR_AUTOPD_SC_MASK ((u32)0x1U << PWR_AUTOPD_SC_SHIFT)
#define PWR_AUTOPD_RDMA_MASK ((u32)0x1U << PWR_AUTOPD_RDMA_SHIFT)

/*
 * Power Clock Control Registers
 * @Description: 0 - Disable, 1 - Enable
 */
#define PWR_CLKCTRL_PFDATA_SHIFT (16U)	// Clock Profile Data
#define PWR_CLKCTRL_PFDONE_SHIFT (15U)	// Clock Profile Done
#define PWR_CLKCTRL_PFEN_SHIFT (9U)	// Clock Profile Enable
#define PWR_CLKCTRL_EN_SHIFT (8U)	// Clock Control (Clock Gating) Enable
#define PWR_CLKCTRL_MIN_SHIFT (0U)	// Clock Disable Minimum size

#define PWR_CLKCTRL_PFDATA_MASK ((u32)0xFFFFU << PWR_CLKCTRL_PFDATA_SHIFT)
#define PWR_CLKCTRL_PFDONE_MASK ((u32)0x1U << PWR_CLKCTRL_PFDONE_SHIFT)
#define PWR_CLKCTRL_PFEN_MASK ((u32)0x1U << PWR_CLKCTRL_PFEN_SHIFT)
#define PWR_CLKCTRL_EN_MASK ((u32)0x1U << PWR_CLKCTRL_EN_SHIFT)
#define PWR_CLKCTRL_MIN_MASK ((u32)0xFU << PWR_CLKCTRL_MIN_SHIFT)

/*
 * Power Block Power Down 0 Registers
 * @Description: 0 - Normal, 1 - PWDN
 */
#define PWR_BLK_PWDN0_SC_SHIFT (28U)	// Scaler Block Power Dow
#define PWR_BLK_PWDN0_RDMA_SHIFT (0U)	// RDMA Power Down

#define PWR_BLK_PWDN0_SC_MASK ((u32)0xFU << PWR_BLK_PWDN0_SC_SHIFT)
#define PWR_BLK_PWDN0_RDMA_MASK ((u32)0xFFFFU << PWR_BLK_PWDN0_RDMA_SHIFT)

/*
 * Power Block Power Down 1 Registers
 * @Description: 0 - Normal, 1 - PWDN
 */
#define PWR_BLK_PWDN1_FIFO_SHIFT (31U)	// Frame FIFO Power Down
#define PWR_BLK_PWDN1_MC_SHIFT (26U)	// Map_Conv Power Down
#define PWR_BLK_PWDN1_DEV_SHIFT (20U)	// Display Device Power Down
#define PWR_BLK_PWDN1_VIQE0_SHIFT (16U)	// VIQE0 Power Down
#define PWR_BLK_PWDN1_WMIX_SHIFT (9U)	// WMIX Power Down
#define PWR_BLK_PWDN1_WDMA_SHIFT (0U)	// WDMA Power Down

#define PWR_BLK_PWDN1_FIFO_MASK ((u32)0x1U << PWR_BLK_PWDN1_FIFO_SHIFT)
#define PWR_BLK_PWDN1_MC_MASK ((u32)0x1U << PWR_BLK_PWDN1_MC_SHIFT)
#define PWR_BLK_PWDN1_DEV_MASK ((u32)0x1FU << PWR_BLK_PWDN1_DEV_SHIFT)
#define PWR_BLK_PWDN1_VIQE0_MASK ((u32)0x1U << PWR_BLK_PWDN1_VIQE0_SHIFT)
#define PWR_BLK_PWDN1_WMIX_MASK ((u32)0xFU << PWR_BLK_PWDN1_WMIX_SHIFT)
#define PWR_BLK_PWDN1_WDMA_MASK ((u32)0x3FU << PWR_BLK_PWDN1_WDMA_SHIFT)

/*
 * Power Block SWRESET 0 Registers
 * @Description: 0 - Normal, 1 - Reset
 */
#define PWR_BLK_SWR0_SC_SHIFT (28U)	// Scaler Block Reset
#define PWR_BLK_SWR0_RDMA_SHIFT (0U)	// RDMA Reset

#define PWR_BLK_SWR0_SC_MASK ((u32)0xFU << PWR_BLK_SWR0_SC_SHIFT)
#define PWR_BLK_SWR0_RDMA_MASK ((u32)0xFFFFU  << PWR_BLK_SWR0_RDMA_SHIFT)

/*
 * Power Block SWRESET 1 Registers
 * @Description: 0 - Normal, 1 - Reset
 */
#define PWR_BLK_SWR1_FIFO_SHIFT (31U)	// Frame FIFO Reset
#define PWR_BLK_SWR1_MC_SHIFT (26U)	// Map_Conv Reset
#define PWR_BLK_SWR1_DEV_SHIFT (20U)	// Display Device Reset
#define PWR_BLK_SWR1_VIQE0_SHIFT (16U)	// VIQE0 Reset
#define PWR_BLK_SWR1_WMIX_SHIFT (9U)	// WMIX Reset
#define PWR_BLK_SWR1_WDMA_SHIFT (0U)	// WDMA Reset

#define PWR_BLK_SWR1_FIFO_MASK ((u32)0x1U << PWR_BLK_SWR1_FIFO_SHIFT)
#define PWR_BLK_SWR1_MC_MASK ((u32)0x1U << PWR_BLK_SWR1_MC_SHIFT)
#define PWR_BLK_SWR1_DEV_MASK ((u32)0x1FU << PWR_BLK_SWR1_DEV_SHIFT)
#define PWR_BLK_SWR1_VIQE0_MASK ((u32)0x1U << PWR_BLK_SWR1_VIQE0_SHIFT)
#define PWR_BLK_SWR1_WMIX_MASK ((u32)0xFU << PWR_BLK_SWR1_WMIX_SHIFT)
#define PWR_BLK_SWR1_WDMA_MASK ((u32)0x3FU << PWR_BLK_SWR1_WDMA_SHIFT)

/*
 * WMIX PATH SWRESET Register
 * @Description: 0 - Normal, 1 - Mixing PATH reset
 */
#define WMIX_PATH_SWR_AD_SHITF (14U) // AFBC_DEC
#define WMIX_PATH_SWR_MIX30_SHIFT (6U)  // MIX30
#define WMIX_PATH_SWR_MIX20_SHIFT (4U)  // MIX20
#define WMIX_PATH_SWR_MIX13_SHIFT (3U)  // MIX13
#define WMIX_PATH_SWR_MIX10_SHIFT (2U)  // MIX10
#define WMIX_PATH_SWR_MIX03_SHIFT (1U)  // MIX03
#define WMIX_PATH_SWR_MIX00_SHIFT (0U)  // MIX00

#define WMIX_PATH_SWR_AD_MASK ((u32)0x3U << WMIX_PATH_SWR_AD_SHITF)
#define WMIX_PATH_SWR_MIX30_MASK ((u32)0x1U << WMIX_PATH_SWR_MIX30_SHIFT)
#define WMIX_PATH_SWR_MIX20_MASK ((u32)0x1U << WMIX_PATH_SWR_MIX20_SHIFT)
#define WMIX_PATH_SWR_MIX13_MASK ((u32)0x1U << WMIX_PATH_SWR_MIX13_SHIFT)
#define WMIX_PATH_SWR_MIX10_MASK ((u32)0x1U << WMIX_PATH_SWR_MIX10_SHIFT)
#define WMIX_PATH_SWR_MIX03_MASK ((u32)0x1U << WMIX_PATH_SWR_MIX03_SHIFT)
#define WMIX_PATH_SWR_MIX00_MASK ((u32)0x1U << WMIX_PATH_SWR_MIX00_SHIFT)

/*
 * Interrupt Select 0 Registers
 * @Description: 0 - Async Interrupt, 1 - Sync Interrupt
 */
#define IRQSELECT0_FIFO1_SHIFT (29U)	// ASync. FIFO1 Sync Interrupt Select
#define IRQSELECT0_FIFO0_SHIFT (28U)	// ASync. FIFO0 Sync Interrupt Select
#define IRQSELECT0_MC0_SHIFT (24U)	// Map Conv0 Sync Interrupt Select
#define IRQSELECT0_RD15_SHIFT (23U)	// RDMA15 Sync Interrupt Select
#define IRQSELECT0_RD14_SHIFT (22U)	// RDMA14 Sync Interrupt Select
#define IRQSELECT0_RD13_SHIFT (21U)	// RDMA13 Sync Interrupt Select
#define IRQSELECT0_RD12_SHIFT (20U)	// RDMA12 Sync Interrupt Select
#define IRQSELECT0_RD11_SHIFT (19U)	// RDMA11 Sync Interrupt Select
#define IRQSELECT0_RD10_SHIFT (18U)	// RDMA10 Sync Interrupt Select
#define IRQSELECT0_RD9_SHIFT (17U)	// RDMA09 Sync Interrupt Select
#define IRQSELECT0_RD8_SHIFT (16U)	// RDMA08 Sync Interrupt Select
#define IRQSELECT0_RD7_SHIFT (15U)	// RDMA07 Sync Interrupt Select
#define IRQSELECT0_RD6_SHIFT (14U)	// RDMA06 Sync Interrupt Select
#define IRQSELECT0_RD5_SHIFT (13U)	// RDMA05 Sync Interrupt Select
#define IRQSELECT0_RD4_SHIFT (12U)	// RDMA04 Sync Interrupt Select
#define IRQSELECT0_RD3_SHIFT (11U)	// RDMA03 Sync Interrupt Select
#define IRQSELECT0_RD2_SHIFT (10U)	// RDMA02 Sync Interrupt Select
#define IRQSELECT0_RD1_SHIFT (9U)	// RDMA01 Sync Interrupt Select
#define IRQSELECT0_RD0_SHIFT (8U)	// RDMA00 Sync Interrupt Select
#define IRQSELECT0_DEV4_SHIFT (4U) // Display Device 4 Sync Interrupt Select
#define IRQSELECT0_DEV3_SHIFT (3U) // Display Device 3 Sync Interrupt Select
#define IRQSELECT0_DEV2_SHIFT (2U) // Display Device 2 Sync Interrupt Select
#define IRQSELECT0_DEV1_SHIFT (1U) // Display Device 1 Sync Interrupt Select
#define IRQSELECT0_DEV0_SHIFT (0U) // Display Device 0 Sync Interrupt Select

#define IRQSELECT0_FIFO1_MASK ((u32)0x1U << IRQSELECT0_FIFO1_SHIFT)
#define IRQSELECT0_FIFO0_MASK ((u32)0x1U << IRQSELECT0_FIFO0_SHIFT)
#define IRQSELECT0_MC0_MASK ((u32)0x1U <<	IRQSELECT0_MC0_SHIFT)
#define IRQSELECT0_RD15_MASK ((u32)0x1U << IRQSELECT0_RD15_SHIFT)
#define IRQSELECT0_RD14_MASK ((u32)0x1U << IRQSELECT0_RD14_SHIFT)
#define IRQSELECT0_RD13_MASK ((u32)0x1U << IRQSELECT0_RD13_SHIFT)
#define IRQSELECT0_RD12_MASK ((u32)0x1U << IRQSELECT0_RD12_SHIFT)
#define IRQSELECT0_RD11_MASK ((u32)0x1U << IRQSELECT0_RD11_SHIFT)
#define IRQSELECT0_RD10_MASK ((u32)0x1U << IRQSELECT0_RD10_SHIFT)
#define IRQSELECT0_RD9_MASK ((u32)0x1U <<	IRQSELECT0_RD9_SHIFT)
#define IRQSELECT0_RD8_MASK ((u32)0x1U <<	IRQSELECT0_RD8_SHIFT)
#define IRQSELECT0_RD7_MASK ((u32)0x1U <<	IRQSELECT0_RD7_SHIFT)
#define IRQSELECT0_RD6_MASK ((u32)0x1U <<	IRQSELECT0_RD6_SHIFT)
#define IRQSELECT0_RD5_MASK ((u32)0x1U <<	IRQSELECT0_RD5_SHIFT)
#define IRQSELECT0_RD4_MASK ((u32)0x1U <<	IRQSELECT0_RD4_SHIFT)
#define IRQSELECT0_RD3_MASK ((u32)0x1U <<	IRQSELECT0_RD3_SHIFT)
#define IRQSELECT0_RD2_MASK ((u32)0x1U <<	IRQSELECT0_RD2_SHIFT)
#define IRQSELECT0_RD1_MASK ((u32)0x1U <<	IRQSELECT0_RD1_SHIFT)
#define IRQSELECT0_RD0_MASK ((u32)0x1U <<	IRQSELECT0_RD0_SHIFT)
#define IRQSELECT0_DEV4_MASK ((u32)0x1U << IRQSELECT0_DEV4_SHIFT)
#define IRQSELECT0_DEV3_MASK ((u32)0x1U << IRQSELECT0_DEV3_SHIFT)
#define IRQSELECT0_DEV2_MASK ((u32)0x1U << IRQSELECT0_DEV2_SHIFT)
#define IRQSELECT0_DEV1_MASK ((u32)0x1U << IRQSELECT0_DEV1_SHIFT)
#define IRQSELECT0_DEV0_MASK ((u32)0x1U << IRQSELECT0_DEV0_SHIFT)

/*
 * Interrupt Select 1 Registers
 * @Description: 0 - Normal, 1 - Interrupt
 */
#define IRQSELECT1_SC3_SHIFT (31U)	// Scaler3 Sync Interrupt Select
#define IRQSELECT1_SC2_SHIFT (30U)	// Scaler2 Sync Interrupt Select
#define IRQSELECT1_SC1_SHIFT (29U)	// Scaler1 Sync Interrupt Select
#define IRQSELECT1_SC0_SHIFT (28U)	// Scaler0 Sync Interrupt Select
#define IRQSELECT1_VIQE0_SHIFT (27U)	// VIQE0 Sync Interrupt Select
#define IRQSELECT1_WMIX3_SHIFT (19U)	// WMIX3 Sync Interrupt Select
#define IRQSELECT1_WMIX2_SHIFT (18U)	// WMIX2 Sync Interrupt Select
#define IRQSELECT1_WMIX1_SHIFT (17U)	// WMIX1 Sync Interrupt Select
#define IRQSELECT1_WMIX0_SHIFT (16U)	// WMIX0 Sync Interrupt Select
#define IRQSELECT1_TIMER_SHIFT (8U)	// TIMER Sync Interrupt Select
#define IRQSELECT1_WD5_SHIFT (5U)	// WDMA05 Sync Interrupt Select
#define IRQSELECT1_WD4_SHIFT (4U)	// WDMA04 Sync Interrupt Select
#define IRQSELECT1_WD3_SHIFT (3U)	// WDMA03 Sync Interrupt Select
#define IRQSELECT1_WD2_SHIFT (2U)	// WDMA02 Sync Interrupt Select
#define IRQSELECT1_WD1_SHIFT (1U)	// WDMA01 Sync Interrupt Select
#define IRQSELECT1_WD0_SHIFT (0U)	// WDMA00 Sync Interrupt Select

#define IRQSELECT1_SC3_MASK ((u32)0x1U << IRQSELECT1_SC3_SHIFT)
#define IRQSELECT1_SC2_MASK ((u32)0x1U << IRQSELECT1_SC2_SHIFT)
#define IRQSELECT1_SC1_MASK ((u32)0x1U << IRQSELECT1_SC1_SHIFT)
#define IRQSELECT1_SC0_MASK ((u32)0x1U << IRQSELECT1_SC0_SHIFT)
#define IRQSELECT1_VIQE0_MASK ((u32)0x1U << IRQSELECT1_VIQE0_SHIFT)
#define IRQSELECT1_WMIX3_MASK ((u32)0x1U << IRQSELECT1_WMIX3_SHIFT)
#define IRQSELECT1_WMIX2_MASK ((u32)0x1U << IRQSELECT1_WMIX2_SHIFT)
#define IRQSELECT1_WMIX1_MASK ((u32)0x1U << IRQSELECT1_WMIX1_SHIFT)
#define IRQSELECT1_WMIX0_MASK ((u32)0x1U << IRQSELECT1_WMIX0_SHIFT)
#define IRQSELECT1_TIMER_MASK ((u32)0x1U << IRQSELECT1_TIMER_SHIFT)
#define IRQSELECT1_WD5_MASK ((u32)0x1U << IRQSELECT1_WD5_SHIFT)
#define IRQSELECT1_WD4_MASK ((u32)0x1U << IRQSELECT1_WD4_SHIFT)
#define IRQSELECT1_WD3_MASK ((u32)0x1U << IRQSELECT1_WD3_SHIFT)
#define IRQSELECT1_WD2_MASK ((u32)0x1U << IRQSELECT1_WD2_SHIFT)
#define IRQSELECT1_WD1_MASK ((u32)0x1U << IRQSELECT1_WD1_SHIFT)
#define IRQSELECT1_WD0_MASK ((u32)0x1U << IRQSELECT1_WD0_SHIFT)

/*
 * Interrupt Select k_2 Register
 */

#define IRQSELECT2_AFBC_SECURE_ID_ERR1_SHIFT (11U) // AFBC_DEC_SECURE_ID_ERR1 Interrupt Select
#define IRQSELECT2_AFBC_SECURE_ID_ERR0_SHIFT (10U) // AFBC_DEC_SECURE_ID_ERR0 Interrupt Select
#define IRQSELECT2_AFBC_DETILING_ERR1_SHIFT (9U) // AFBC_DEC_DETILING_ERR1 Interrupt Select
#define IRQSELECT2_AFBC_DETILING_ERR0_SHIFT (8U) // AFBC_DEC_DETILING_ERR0 Interrupt Select
#define IRQSELECT2_AFBC_DECODE_ERR1_SHIFT (7U) // AFBC_DEC_DECODE_ERR1 Interrupt Select
#define IRQSELECT2_AFBC_DECODE_ERR0_SHIFT (6U) // AFBC_DEC_DECODE_ERR0 Interrupt Select
#define IRQSELECT2_AFBC_CONFIG_SWAP1_SHIFT (5U) // AFBC_DEC_CONFIG_SWAP1 Interrupt Select
#define IRQSELECT2_AFBC_CONFIG_SWAP0_SHIFT (4U) // AFBC_DEC_CONFIG_SWAP0 Interrupt Select
#define IRQSELECT2_AFBC_AXI1_SHIFT (3U) // AFBC_DEC_AXI_ERROR1 Interrupt Select
#define IRQSELECT2_AFBC_AXI0_SHIFT (2U) // AFBC_DEC_AXI_ERROR0 Interrupt Select
#define IRQSELECT2_AFBC_DEC1_SHIFT (1U) // AFBC_DEC1 Interrupt Select
#define IRQSELECT2_AFBC_DEC0_SHIFT (0U) // AFBC_DEC0 Interrupt Select

#define IRQSELECT2_AFBC_SECURE_ID_ERR1_MASK ((u32)0x1U << IRQSELECT2_AFBC_SECURE_ID_ERR1_SHIFT)
#define IRQSELECT2_AFBC_SECURE_ID_ERR0_MASK ((u32)0x1U << IRQSELECT2_AFBC_SECURE_ID_ERR0_SHIFT)
#define IRQSELECT2_AFBC_DETILING_ERR1_MASK ((u32)0x1U << IRQSELECT2_AFBC_DETILING_ERR1_SHIFT)
#define IRQSELECT2_AFBC_DETILING_ERR0_MASK ((u32)0x1U << IRQSELECT2_AFBC_DETILING_ERR0_SHIFT)
#define IRQSELECT2_AFBC_DECODE_ERR1_MASK ((u32)0x1U << IRQSELECT2_AFBC_DECODE_ERR1_SHIFT)
#define IRQSELECT2_AFBC_DECODE_ERR0_MASK ((u32)0x1U << IRQSELECT2_AFBC_DECODE_ERR0_SHIFT)
#define IRQSELECT2_AFBC_CONFIG_SWAP1_MASK ((u32)0x1U << IRQSELECT2_AFBC_CONFIG_SWAP1_SHIFT)
#define IRQSELECT2_AFBC_CONFIG_SWAP0_MASK ((u32)0x1U << IRQSELECT2_AFBC_CONFIG_SWAP0_SHIFT)
#define IRQSELECT2_AFBC_AXI1_MASK ((u32)0x1U << IRQSELECT2_AFBC_AXI1_SHIFT)
#define IRQSELECT2_AFBC_AXI0_MASK ((u32)0x1U << IRQSELECT2_AFBC_AXI0_SHIFT)
#define IRQSELECT2_AFBC_DEC1_MASK ((u32)0x1U << IRQSELECT2_AFBC_DEC1_SHIFT)
#define IRQSELECT2_AFBC_DEC0_MASK ((u32)0x1U << IRQSELECT2_AFBC_DEC0_SHIFT)

/*
 * Interrupt Mask Set 0 Registers
 * @Description: 0 - Enable, 1 - Disable
 */
#define IRQMASKSET0_FIFO1_SHIFT (29U)	// ASync. FIFO1 Interrupt Mask
#define IRQMASKSET0_FIFO0_SHIFT (28U)	// ASync. FIFO0 Interrupt Mask
#define IRQMASKSET0_MC0_SHIFT (24U)	// Map Conv0 Interrupt Mask
#define IRQMASKSET0_RD15_SHIFT (23U)	// RDMA15 Interrupt Mask
#define IRQMASKSET0_RD14_SHIFT (22U)	// RDMA14 Interrupt Mask
#define IRQMASKSET0_RD13_SHIFT (21U)	// RDMA13 Interrupt Mask
#define IRQMASKSET0_RD12_SHIFT (20U)	// RDMA12 Interrupt Mask
#define IRQMASKSET0_RD11_SHIFT (19U)	// RDMA11 Interrupt Mask
#define IRQMASKSET0_RD10_SHIFT (18U)	// RDMA10 Interrupt Mask
#define IRQMASKSET0_RD9_SHIFT (17U)	// RDMA09 Interrupt Mask
#define IRQMASKSET0_RD8_SHIFT (16U)	// RDMA08 Interrupt Mask
#define IRQMASKSET0_RD7_SHIFT (15U)	// RDMA07 Interrupt Mask
#define IRQMASKSET0_RD6_SHIFT (14U)	// RDMA06 Interrupt Mask
#define IRQMASKSET0_RD5_SHIFT (13U)	// RDMA05 Interrupt Mask
#define IRQMASKSET0_RD4_SHIFT (12U)	// RDMA04 Interrupt Mask
#define IRQMASKSET0_RD3_SHIFT (11U)	// RDMA03 Interrupt Mask
#define IRQMASKSET0_RD2_SHIFT (10U)	// RDMA02 Interrupt Mask
#define IRQMASKSET0_RD1_SHIFT (9U)	// RDMA01 Interrupt Mask
#define IRQMASKSET0_RD0_SHIFT (8U)	// RDMA00 Interrupt Mask
#define IRQMASKSET0_DEV4_SHIFT (4U)	// Display Device 4 Interrupt Mask
#define IRQMASKSET0_DEV3_SHIFT (3U)	// Display Device 3 Interrupt Mask
#define IRQMASKSET0_DEV2_SHIFT (2U)	// Display Device 2 Interrupt Mask
#define IRQMASKSET0_DEV1_SHIFT (1U)	// Display Device 1 Interrupt Mask
#define IRQMASKSET0_DEV0_SHIFT (0U)	// Display Device 0 Interrupt Mask

#define IRQMASKSET0_FIFO1_MASK ((u32)0x1U << IRQMASKSET0_FIFO1_SHIFT)
#define IRQMASKSET0_FIFO0_MASK ((u32)0x1U << IRQMASKSET0_FIFO0_SHIFT)
#define IRQMASKSET0_MC0_MASK ((u32)0x1U <<	IRQMASKSET0_MC0_SHIFT)
#define IRQMASKSET0_RD15_MASK ((u32)0x1U <<	IRQMASKSET0_RD15_SHIFT)
#define IRQMASKSET0_RD14_MASK ((u32)0x1U <<	IRQMASKSET0_RD14_SHIFT)
#define IRQMASKSET0_RD13_MASK ((u32)0x1U <<	IRQMASKSET0_RD13_SHIFT)
#define IRQMASKSET0_RD12_MASK ((u32)0x1U <<	IRQMASKSET0_RD12_SHIFT)
#define IRQMASKSET0_RD11_MASK ((u32)0x1U <<	IRQMASKSET0_RD11_SHIFT)
#define IRQMASKSET0_RD10_MASK ((u32)0x1U <<	IRQMASKSET0_RD10_SHIFT)
#define IRQMASKSET0_RD9_MASK ((u32)0x1U <<	IRQMASKSET0_RD9_SHIFT)
#define IRQMASKSET0_RD8_MASK ((u32)0x1U <<	IRQMASKSET0_RD8_SHIFT)
#define IRQMASKSET0_RD7_MASK ((u32)0x1U <<	IRQMASKSET0_RD7_SHIFT)
#define IRQMASKSET0_RD6_MASK ((u32)0x1U <<	IRQMASKSET0_RD6_SHIFT)
#define IRQMASKSET0_RD5_MASK ((u32)0x1U <<	IRQMASKSET0_RD5_SHIFT)
#define IRQMASKSET0_RD4_MASK ((u32)0x1U <<	IRQMASKSET0_RD4_SHIFT)
#define IRQMASKSET0_RD3_MASK ((u32)0x1U <<	IRQMASKSET0_RD3_SHIFT)
#define IRQMASKSET0_RD2_MASK ((u32)0x1U <<	IRQMASKSET0_RD2_SHIFT)
#define IRQMASKSET0_RD1_MASK ((u32)0x1U <<	IRQMASKSET0_RD1_SHIFT)
#define IRQMASKSET0_RD0_MASK ((u32)0x1U <<	IRQMASKSET0_RD0_SHIFT)
#define IRQMASKSET0_DEV4_MASK ((u32)0x1U <<	IRQMASKSET0_DEV4_SHIFT)
#define IRQMASKSET0_DEV3_MASK ((u32)0x1U <<	IRQMASKSET0_DEV3_SHIFT)
#define IRQMASKSET0_DEV2_MASK ((u32)0x1U <<	IRQMASKSET0_DEV2_SHIFT)
#define IRQMASKSET0_DEV1_MASK ((u32)0x1U <<	IRQMASKSET0_DEV1_SHIFT)
#define IRQMASKSET0_DEV0_MASK ((u32)0x1U <<	IRQMASKSET0_DEV0_SHIFT)

/*
 * Interrupt Mask Set 1 Registers
 * @Description: 0 - Normal, 1 - Interrupt
 */
#define IRQMASKSET1_SC3_SHIFT (31U) // Scaler3 Interrupt Mask
#define IRQMASKSET1_SC2_SHIFT (30U) // Scaler2 Interrupt Mask
#define IRQMASKSET1_SC1_SHIFT (29U) // Scaler1 Interrupt Mask
#define IRQMASKSET1_SC0_SHIFT (28U) // Scaler0 Interrupt Mask
#define IRQMASKSET1_VIQE0_SHIFT (27U) // VIQE0 Interrupt Mask
#define IRQMASKSET1_WMIX3_SHIFT (19U) // WMIX3 Interrupt Mask
#define IRQMASKSET1_WMIX2_SHIFT (18U) // WMIX2 Interrupt Mask
#define IRQMASKSET1_WMIX1_SHIFT (17U) // WMIX1 Interrupt Mask
#define IRQMASKSET1_WMIX0_SHIFT (16U) // WMIX0 Interrupt Mask
#define IRQMASKSET1_TIMER_SHIFT (8U) // TIMER Interrupt Mask
#define IRQMASKSET1_WD5_SHIFT (5U)  // WDMA05 Interrupt Mask
#define IRQMASKSET1_WD4_SHIFT (4U)  // WDMA04 Interrupt Mask
#define IRQMASKSET1_WD3_SHIFT (3U)  // WDMA03 Interrupt Mask
#define IRQMASKSET1_WD2_SHIFT (2U)  // WDMA02 Interrupt Mask
#define IRQMASKSET1_WD1_SHIFT (1U)  // WDMA01 Interrupt Mask
#define IRQMASKSET1_WD0_SHIFT (0U)  // WDMA00 Interrupt Mask

#define IRQMASKSET1_SC3_MASK ((u32)0x1U << IRQMASKSET1_SC3_SHIFT)
#define IRQMASKSET1_SC2_MASK ((u32)0x1U << IRQMASKSET1_SC2_SHIFT)
#define IRQMASKSET1_SC1_MASK ((u32)0x1U << IRQMASKSET1_SC1_SHIFT)
#define IRQMASKSET1_SC0_MASK ((u32)0x1U << IRQMASKSET1_SC0_SHIFT)
#define IRQMASKSET1_VIQE0_MASK ((u32)0x1U << IRQMASKSET1_VIQE0_SHIFT)
#define IRQMASKSET1_WMIX3_MASK ((u32)0x1U << IRQMASKSET1_WMIX3_SHIFT)
#define IRQMASKSET1_WMIX2_MASK ((u32)0x1U << IRQMASKSET1_WMIX2_SHIFT)
#define IRQMASKSET1_WMIX1_MASK ((u32)0x1U << IRQMASKSET1_WMIX1_SHIFT)
#define IRQMASKSET1_WMIX0_MASK ((u32)0x1U << IRQMASKSET1_WMIX0_SHIFT)
#define IRQMASKSET1_TIMER_MASK ((u32)0x1U << IRQMASKSET1_TIMER_SHIFT)
#define IRQMASKSET1_WD5_MASK ((u32)0x1U << IRQMASKSET1_WD5_SHIFT)
#define IRQMASKSET1_WD4_MASK ((u32)0x1U << IRQMASKSET1_WD4_SHIFT)
#define IRQMASKSET1_WD3_MASK ((u32)0x1U << IRQMASKSET1_WD3_SHIFT)
#define IRQMASKSET1_WD2_MASK ((u32)0x1U << IRQMASKSET1_WD2_SHIFT)
#define IRQMASKSET1_WD1_MASK ((u32)0x1U << IRQMASKSET1_WD1_SHIFT)
#define IRQMASKSET1_WD0_MASK ((u32)0x1U << IRQMASKSET1_WD0_SHIFT)

/*
 * Interrupt Mask Set k_2 Register
 */

#define IRQMASKSET2_AFBC_SECURE_ID_ERR1_SHIFT (11U) // AFBC_DEC_SECURE_ID_ERR1 Interrupt Mask
#define IRQMASKSET2_AFBC_SECURE_ID_ERR0_SHIFT (10U) // AFBC_DEC_SECURE_ID_ERR0 Interrupt Mask
#define IRQMASKSET2_AFBC_DETILING_ERR1_SHIFT (9U) // AFBC_DEC_DETILING_ERR1 Interrupt Mask
#define IRQMASKSET2_AFBC_DETILING_ERR0_SHIFT (8U) // AFBC_DEC_DETILING_ERR0 Interrupt Mask
#define IRQMASKSET2_AFBC_DECODE_ERR1_SHIFT  (7U) // AFBC_DEC_DECODE_ERR1 Interrupt Mask
#define IRQMASKSET2_AFBC_DECODE_ERR0_SHIFT  (6U) // AFBC_DEC_DECODE_ERR0 Interrupt Mask
#define IRQMASKSET2_AFBC_CONFIG_SWAP1_SHIFT (5U) // AFBC_DEC_CONFIG_SWAP1 Interrupt Mask
#define IRQMASKSET2_AFBC_CONFIG_SWAP0_SHIFT (4U) // AFBC_DEC_CONFIG_SWAP0 Interrupt Mask
#define IRQMASKSET2_AFBC_AXI1_SHIFT (3U) // AFBC_DEC_AXI_ERROR1 Interrupt Mask
#define IRQMASKSET2_AFBC_AXI0_SHIFT (2U) // AFBC_DEC_AXI_ERROR0 Interrupt Mask
#define IRQMASKSET2_AFBC_DEC1_SHIFT (1U) // AFBC_DEC1 Interrupt Mask
#define IRQMASKSET2_AFBC_DEC0_SHIFT (0U) // AFBC_DEC0 Interrupt Mask

#define IRQMASKSET2_AFBC_SECURE_ID_ERR1_MASK ((u32)0x1U << IRQMASKSET2_AFBC_SECURE_ID_ERR1_SHIFT)
#define IRQMASKSET2_AFBC_SECURE_ID_ERR0_MASK ((u32)0x1U << IRQMASKSET2_AFBC_SECURE_ID_ERR0_SHIFT)
#define IRQMASKSET2_AFBC_DETILING_ERR1_MASK ((u32)0x1U << IRQMASKSET2_AFBC_DETILING_ERR1_SHIFT)
#define IRQMASKSET2_AFBC_DETILING_ERR0_MASK ((u32)0x1U << IRQMASKSET2_AFBC_DETILING_ERR0_SHIFT)
#define IRQMASKSET2_AFBC_DECODE_ERR1_MASK ((u32)0x1U << IRQMASKSET2_AFBC_DECODE_ERR1_SHIFT)
#define IRQMASKSET2_AFBC_DECODE_ERR0_MASK ((u32)0x1U << IRQMASKSET2_AFBC_DECODE_ERR0_SHIFT)
#define IRQMASKSET2_AFBC_CONFIG_SWAP1_MASK ((u32)0x1U << IRQMASKSET2_AFBC_CONFIG_SWAP1_SHIFT)
#define IRQMASKSET2_AFBC_CONFIG_SWAP0_MASK ((u32)0x1U << IRQMASKSET2_AFBC_CONFIG_SWAP0_SHIFT)
#define IRQMASKSET2_AFBC_AXI1_MASK ((u32)0x1U << IRQMASKSET2_AFBC_AXI1_SHIFT)
#define IRQMASKSET2_AFBC_AXI0_MASK ((u32)0x1U << IRQMASKSET2_AFBC_AXI0_SHIFT)
#define IRQMASKSET2_AFBC_DEC1_MASK ((u32)0x1U << IRQMASKSET2_AFBC_DEC1_SHIFT)
#define IRQMASKSET2_AFBC_DEC0_MASK ((u32)0x1U << IRQMASKSET2_AFBC_DEC0_SHIFT)

/*
 * Interrupt Mask Clear 0 Registers
 * @Description: 0 - Normal, 1 - Clear
 */
#define IRQMASKCLR0_FIFO1_SHIFT (29U) // ASync. FIFO1 Interrupt Mask Clear
#define IRQMASKCLR0_FIFO0_SHIFT (28U) // ASync. FIFO0 Interrupt Mask Clear
#define IRQMASKCLR0_MC0_SHIFT (24U) // Map Conv0 Interrupt Mask Clear
#define IRQMASKCLR0_RD15_SHIFT (23U) // RDMA15 Interrupt Mask Clear
#define IRQMASKCLR0_RD14_SHIFT (22U) // RDMA14 Interrupt Mask Clear
#define IRQMASKCLR0_RD13_SHIFT (21U) // RDMA13 Interrupt Mask Clear
#define IRQMASKCLR0_RD12_SHIFT (20U) // RDMA12 Interrupt Mask Clear
#define IRQMASKCLR0_RD11_SHIFT (19U) // RDMA11 Interrupt Mask Clear
#define IRQMASKCLR0_RD10_SHIFT (18U) // RDMA10 Interrupt Mask Clear
#define IRQMASKCLR0_RD9_SHIFT (17U) // RDMA09 Interrupt Mask Clear
#define IRQMASKCLR0_RD8_SHIFT (16U) // RDMA08 Interrupt Mask Clear
#define IRQMASKCLR0_RD7_SHIFT (15U) // RDMA07 Interrupt Mask Clear
#define IRQMASKCLR0_RD6_SHIFT (14U) // RDMA06 Interrupt Mask Clear
#define IRQMASKCLR0_RD5_SHIFT (13U)	// RDMA05 Interrupt Mask Clear
#define IRQMASKCLR0_RD4_SHIFT (12U)	// RDMA04 Interrupt Mask Clear
#define IRQMASKCLR0_RD3_SHIFT (11U)	// RDMA03 Interrupt Mask Clear
#define IRQMASKCLR0_RD2_SHIFT (10U)	// RDMA02 Interrupt Mask Clear
#define IRQMASKCLR0_RD1_SHIFT (9U)	// RDMA01 Interrupt Mask Clear
#define IRQMASKCLR0_RD0_SHIFT (8U)	// RDMA00 Interrupt Mask Clear
#define IRQMASKCLR0_DEV4_SHIFT (4U)	// Display Device 4 Interrupt Mask Clear
#define IRQMASKCLR0_DEV3_SHIFT (3U)	// Display Device 3 Interrupt Mask Clear
#define IRQMASKCLR0_DEV2_SHIFT (2U)	// Display Device 2 Interrupt Mask Clear
#define IRQMASKCLR0_DEV1_SHIFT (1U)	// Display Device 1 Interrupt Mask Clear
#define IRQMASKCLR0_DEV0_SHIFT (0U)	// Display Device 0 Interrupt Mask Clear

#define IRQMASKCLR0_FIFO1_MASK ((u32)0x1U << IRQMASKCLR0_FIFO1_SHIFT)
#define IRQMASKCLR0_FIFO0_MASK ((u32)0x1U << IRQMASKCLR0_FIFO0_SHIFT)
#define IRQMASKCLR0_MC0_MASK ((u32)0x1U << IRQMASKCLR0_MC0_SHIFT)
#define IRQMASKCLR0_RD15_MASK ((u32)0x1U << IRQMASKCLR0_RD15_SHIFT)
#define IRQMASKCLR0_RD14_MASK ((u32)0x1U << IRQMASKCLR0_RD14_SHIFT)
#define IRQMASKCLR0_RD13_MASK ((u32)0x1U << IRQMASKCLR0_RD13_SHIFT)
#define IRQMASKCLR0_RD12_MASK ((u32)0x1U << IRQMASKCLR0_RD12_SHIFT)
#define IRQMASKCLR0_RD11_MASK ((u32)0x1U << IRQMASKCLR0_RD11_SHIFT)
#define IRQMASKCLR0_RD10_MASK ((u32)0x1U << IRQMASKCLR0_RD10_SHIFT)
#define IRQMASKCLR0_RD9_MASK ((u32)0x1U << IRQMASKCLR0_RD9_SHIFT)
#define IRQMASKCLR0_RD8_MASK ((u32)0x1U << IRQMASKCLR0_RD8_SHIFT)
#define IRQMASKCLR0_RD7_MASK ((u32)0x1U << IRQMASKCLR0_RD7_SHIFT)
#define IRQMASKCLR0_RD6_MASK ((u32)0x1U << IRQMASKCLR0_RD6_SHIFT)
#define IRQMASKCLR0_RD5_MASK ((u32)0x1U << IRQMASKCLR0_RD5_SHIFT)
#define IRQMASKCLR0_RD4_MASK ((u32)0x1U << IRQMASKCLR0_RD4_SHIFT)
#define IRQMASKCLR0_RD3_MASK ((u32)0x1U << IRQMASKCLR0_RD3_SHIFT)
#define IRQMASKCLR0_RD2_MASK ((u32)0x1U << IRQMASKCLR0_RD2_SHIFT)
#define IRQMASKCLR0_RD1_MASK ((u32)0x1U << IRQMASKCLR0_RD1_SHIFT)
#define IRQMASKCLR0_RD0_MASK ((u32)0x1U << IRQMASKCLR0_RD0_SHIFT)
#define IRQMASKCLR0_DEV4_MASK ((u32)0x1U << IRQMASKCLR0_DEV4_SHIFT)
#define IRQMASKCLR0_DEV3_MASK ((u32)0x1U << IRQMASKCLR0_DEV3_SHIFT)
#define IRQMASKCLR0_DEV2_MASK ((u32)0x1U << IRQMASKCLR0_DEV2_SHIFT)
#define IRQMASKCLR0_DEV1_MASK ((u32)0x1U << IRQMASKCLR0_DEV1_SHIFT)
#define IRQMASKCLR0_DEV0_MASK ((u32)0x1U << IRQMASKCLR0_DEV0_SHIFT)

/*
 * Interrupt Mask Clear Set 1 Registers
 * @Description: 0 - Normal, 1 - Interrupt
 */
#define IRQMASKCLR1_SC3_SHIFT (31U) // Scaler3 Interrupt Mask Clear
#define IRQMASKCLR1_SC2_SHIFT (30U) // Scaler2 Interrupt Mask Clear
#define IRQMASKCLR1_SC1_SHIFT (29U) // Scaler1 Interrupt Mask Clear
#define IRQMASKCLR1_SC0_SHIFT (28U) // Scaler0 Interrupt Mask Clear
#define IRQMASKCLR1_VIQE0_SHIFT (27U) // VIQE0 Interrupt Mask Clear
#define IRQMASKCLR1_WMIX3_SHIFT (19U) // WMIX3 Interrupt Mask Clear
#define IRQMASKCLR1_WMIX2_SHIFT (18U) // WMIX2 Interrupt Mask Clear
#define IRQMASKCLR1_WMIX1_SHIFT (17U) // WMIX1 Interrupt Mask Clear
#define IRQMASKCLR1_WMIX0_SHIFT (16U) // WMIX0 Interrupt Mask Clear
#define IRQMASKCLR1_TIMER_SHIFT (8U) // TIMER Interrupt Mask Clear
#define IRQMASKCLR1_WD5_SHIFT (5U)	 // WDMA05 Interrupt Mask Clear
#define IRQMASKCLR1_WD4_SHIFT (4U)	 // WDMA04 Interrupt Mask Clear
#define IRQMASKCLR1_WD3_SHIFT (3U)	 // WDMA03 Interrupt Mask Clear
#define IRQMASKCLR1_WD2_SHIFT (2U)	 // WDMA02 Interrupt Mask Clear
#define IRQMASKCLR1_WD1_SHIFT (1U)	 // WDMA01 Interrupt Mask Clear
#define IRQMASKCLR1_WD0_SHIFT (0U)	 // WDMA00 Interrupt Mask Clear

#define IRQMASKCLR1_SC3_MASK ((u32)0x1U << IRQMASKCLR1_SC3_SHIFT)
#define IRQMASKCLR1_SC2_MASK ((u32)0x1U << IRQMASKCLR1_SC2_SHIFT)
#define IRQMASKCLR1_SC1_MASK ((u32)0x1U << IRQMASKCLR1_SC1_SHIFT)
#define IRQMASKCLR1_SC0_MASK ((u32)0x1U << IRQMASKCLR1_SC0_SHIFT)
#define IRQMASKCLR1_VIQE0_MASK ((u32)0x1U << IRQMASKCLR1_VIQE0_SHIFT)
#define IRQMASKCLR1_WMIX3_MASK ((u32)0x1U << IRQMASKCLR1_WMIX3_SHIFT)
#define IRQMASKCLR1_WMIX2_MASK ((u32)0x1U << IRQMASKCLR1_WMIX2_SHIFT)
#define IRQMASKCLR1_WMIX1_MASK ((u32)0x1U << IRQMASKCLR1_WMIX1_SHIFT)
#define IRQMASKCLR1_WMIX0_MASK ((u32)0x1U << IRQMASKCLR1_WMIX0_SHIFT)
#define IRQMASKCLR1_TIMER_MASK ((u32)0x1U << IRQMASKCLR1_TIMER_SHIFT)
#define IRQMASKCLR1_WD5_MASK ((u32)0x1U << IRQMASKCLR1_WD5_SHIFT)
#define IRQMASKCLR1_WD4_MASK ((u32)0x1U << IRQMASKCLR1_WD4_SHIFT)
#define IRQMASKCLR1_WD3_MASK ((u32)0x1U << IRQMASKCLR1_WD3_SHIFT)
#define IRQMASKCLR1_WD2_MASK ((u32)0x1U << IRQMASKCLR1_WD2_SHIFT)
#define IRQMASKCLR1_WD1_MASK ((u32)0x1U << IRQMASKCLR1_WD1_SHIFT)
#define IRQMASKCLR1_WD0_MASK ((u32)0x1U << IRQMASKCLR1_WD0_SHIFT)

/*
 * Interrupt Mask Set k_2 Register
 */
#define IRQMASKSET2_AFBC_SECURE_ID_ERR1_SHIFT (11U) // AFBC_DEC_SECURE_ID_ERR1 Interrupt Mask Clear
#define IRQMASKSET2_AFBC_SECURE_ID_ERR0_SHIFT (10U) // AFBC_DEC_SECURE_ID_ERR0 Interrupt Mask Clear
#define IRQMASKSET2_AFBC_DETILING_ERR1_SHIFT (9U) // AFBC_DEC_DETILING_ERR1 Interrupt Mask Clear
#define IRQMASKSET2_AFBC_DETILING_ERR0_SHIFT (8U) // AFBC_DEC_DETILING_ERR0 Interrupt Mask Clear
#define IRQMASKSET2_AFBC_DECODE_ERR1_SHIFT  (7U) // AFBC_DEC_DECODE_ERR1 Interrupt Mask Clear
#define IRQMASKSET2_AFBC_DECODE_ERR0_SHIFT  (6U) // AFBC_DEC_DECODE_ERR0 Interrupt Mask Clear
#define IRQMASKSET2_AFBC_CONFIG_SWAP1_SHIFT (5U) // AFBC_DEC_CONFIG_SWAP1 Interrupt Mask Clear
#define IRQMASKSET2_AFBC_CONFIG_SWAP0_SHIFT (4U) // AFBC_DEC_CONFIG_SWAP0 Interrupt Mask Clear
#define IRQMASKSET2_AFBC_AXI1_SHIFT (3U) // AFBC_DEC_AXI_ERROR1 Interrupt Mask Clear
#define IRQMASKSET2_AFBC_AXI0_SHIFT (2U) // AFBC_DEC_AXI_ERROR0 Interrupt Mask Clear
#define IRQMASKSET2_AFBC_DEC1_SHIFT (1U) // AFBC_DEC1 Interrupt Mask Clear
#define IRQMASKSET2_AFBC_DEC0_SHIFT (0U) // AFBC_DEC0 Interrupt Mask Clear

#define IRQMASKSET2_AFBC_SECURE_ID_ERR1_MASK ((u32)0x1U << IRQMASKSET2_AFBC_SECURE_ID_ERR1_SHIFT)
#define IRQMASKSET2_AFBC_SECURE_ID_ERR0_MASK ((u32)0x1U << IRQMASKSET2_AFBC_SECURE_ID_ERR0_SHIFT)
#define IRQMASKSET2_AFBC_DETILING_ERR1_MASK ((u32)0x1U << IRQMASKSET2_AFBC_DETILING_ERR1_SHIFT)
#define IRQMASKSET2_AFBC_DETILING_ERR0_MASK ((u32)0x1U << IRQMASKSET2_AFBC_DETILING_ERR0_SHIFT)
#define IRQMASKSET2_AFBC_DECODE_ERR1_MASK ((u32)0x1U << IRQMASKSET2_AFBC_DECODE_ERR1_SHIFT)
#define IRQMASKSET2_AFBC_DECODE_ERR0_MASK ((u32)0x1U << IRQMASKSET2_AFBC_DECODE_ERR0_SHIFT)
#define IRQMASKSET2_AFBC_CONFIG_SWAP1_MASK ((u32)0x1U << IRQMASKSET2_AFBC_CONFIG_SWAP1_SHIFT)
#define IRQMASKSET2_AFBC_CONFIG_SWAP0_MASK ((u32)0x1U << IRQMASKSET2_AFBC_CONFIG_SWAP0_SHIFT)
#define IRQMASKSET2_AFBC_AXI1_MASK ((u32)0x1U << IRQMASKSET2_AFBC_AXI1_SHIFT)
#define IRQMASKSET2_AFBC_AXI0_MASK ((u32)0x1U << IRQMASKSET2_AFBC_AXI0_SHIFT)
#define IRQMASKSET2_AFBC_DEC1_MASK ((u32)0x1U << IRQMASKSET2_AFBC_DEC1_SHIFT)
#define IRQMASKSET2_AFBC_DEC0_MASK ((u32)0x1U << IRQMASKSET2_AFBC_DEC0_SHIFT)

#define VIOC_TYPE_SC0 (0U)
#define VIOC_TYPE_SC1 (1U)
#define VIOC_TYPE_SC2 (2U)
#define VIOC_TYPE_SC3 (3U)
#define VIOC_TYPE_VIQE0 (8U)

// plug in return value
#define VIOC_DEVICE_INVALID (-2)
#define VIOC_DEVICE_BUSY (-1)
#define VIOC_DEVICE_CONNECTED (0)

#define VIOC_PATH_DISCONNECTED (0U)
#define VIOC_PATH_CONNECTING (1U)
#define VIOC_PATH_CONNECTED (2U)
#define VIOC_PATH_DISCONNECTING (3U)

enum VIOC_CONFIG_WMIX_PATH {
	WMIX00 = 0,
	WMIX03,
	WMIX10,
	WMIX13,
	WMIX20,
	//WMIX23,
	WMIX30,
	//WMIX40,
	//WMIX50,
	//WMIX60,
	WMIX_MAX
};

enum VIOC_SWRESET_Component {
	VIOC_CONFIG_WMIXER = 0,
	VIOC_CONFIG_WDMA,
	VIOC_CONFIG_RDMA,
	VIOC_CONFIG_SCALER,
	VIOC_CONFIG_VIQE,
	//VIOC_CONFIG_DEINTS,
	//VIOC_CONFIG_VIN,
	VIOC_CONFIG_MC,
	VIOC_CONFIG_FCENC,
	VIOC_CONFIG_FCDEC,
	VIOC_CONFIG_FIFO,
};

enum VIOC_CONFIG_MC_PATH {
	MC_RDMA03 = 0,
	MC_RDMA07,
	MC_RDMA11,
	MC_RDMA13,
	MC_RDMA15,
	//MC_RDMA16,
	//MC_RDMA17,
	MC_RDMA_MAX,
};

enum VIOC_SWRESET_Mode {
	VIOC_CONFIG_CLEAR = 0,
	VIOC_CONFIG_RESET,
};

struct VIOC_PlugInOutCheck {
	unsigned int enable;
	unsigned int connect_statue;
	unsigned int connect_device;
};

struct VIOC_PATH_INFO_T {
	unsigned int mix;
	unsigned int rdma[4];
	unsigned int wmix;
	unsigned int disp;
	unsigned int wdma[2];
};

/* Interface APIs */
extern int VIOC_AUTOPWR_Enalbe(unsigned int component, unsigned int onoff);
extern int VIOC_CONFIG_Get_Path_Info(unsigned int wmix_id,
		struct VIOC_PATH_INFO_T *info);
extern int VIOC_CONFIG_ResetAll(void);
extern int VIOC_CONFIG_PlugIn(unsigned int component, unsigned int select);
extern int VIOC_CONFIG_PlugOut(unsigned int component);
extern int VIOC_CONFIG_WMIXPath(unsigned int component_num, unsigned int mode);
extern void VIOC_CONFIG_WMIXPathReset(unsigned int component_num, unsigned int resetmode);
extern void VIOC_CONFIG_SWReset(unsigned int component, unsigned int mode);
extern int VIOC_CONFIG_Device_PlugState(unsigned int component,
		struct VIOC_PlugInOutCheck *VIOC_PlugIn);
extern int VIOC_CONFIG_GetScaler_PluginToRDMA(unsigned int RdmaNum);
extern int VIOC_CONFIG_GetScaler_PluginToWDMA(unsigned int WdmaNum);
#if 0
extern int VIOC_CONFIG_GetViqeDeintls_PluginToRDMA(unsigned int RdmaNum);
extern int VIOC_CONFIG_GetRdma_PluginToComponent(unsigned int ComponentNum);
#endif

extern int VIOC_CONFIG_DMAPath_Select(unsigned int path);
extern int VIOC_CONFIG_DMAPath_Set(unsigned int path, unsigned int dma);
extern int VIOC_CONFIG_DMAPath_UnSet(int dma);
extern int VIOC_CONFIG_DMAPath_Support(void);

extern void VIOC_CONFIG_StopRequest(unsigned int en);

extern void VIOC_CONFIG_DMAPath_Iint(void);
extern int VIOC_CONFIG_MC_PlugIn(unsigned int nValue);
#if defined(CONFIG_VIOC_MAP_DECOMP)
extern int VIOC_CONFIG_MCPath(unsigned int component, unsigned int mc);
#endif
#if 0
extern void VIOC_CONFIG_SetLoopBack(unsigned int vin, unsigned int path);
#endif
extern void __iomem *VIOC_IREQConfig_GetAddress(void);

#endif
