# SPDX-License-Identifier: GPL-2.0-or-later
# #
# # Copyright (C) Telechips Inc.
obj-$(CONFIG_TCC803X) += tcc803x/
obj-$(CONFIG_TCC805X) += tcc805x/
obj-$(CONFIG_TCC897X) += tcc897x/
obj-$(CONFIG_TELECHIPS_LVDS_SERDES) += serdes/
