# SPDX-License-Identifier: GPL-2.0+

# Modified by Telechips Inc.

obj-y += core.o
obj-y += supplicant.o
obj-y += optee_fdt.o
obj-$(CONFIG_DM_I2C) += i2c.o
obj-$(CONFIG_SUPPORT_EMMC_RPMB) += rpmb.o
obj-$(CONFIG_SUPPORT_UFS_RPMB) += rpmb.o
