# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) Telechips Inc.

ccflags-y := \
	 -I$(srctree)/$(src) \
	 -I$(srctree)/$(src)/include

obj-y += \
	Dptx_api.o \
	Dptx_platform.o \
	Dptx_reg.o \
	Dptx_aux.o \
	Dptx_avgen.o \
	Dptx_core.o \
	Dptx_intr.o \
	Dptx_link.o \
	Dptx_edid.o \
	Dptx_extension.o \
	Dptx_hdcp.o \
	Dptx_drm_dp_addition.o
