# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) Telechips Inc.

obj-y	+= \
	vioc_config.o \
	vioc_ddicfg.o \
	vioc_disp.o \
	vioc_fifo.o \
	vioc_lut.o \
	vioc_rdma.o \
	vioc_scaler.o \
	vioc_wmix.o \
	vioc_wdma.o \
	vioc_intr.o \
	vioc_timer.o \
	vioc_dump.o
